In [2]:
from __future__ import annotations

import json
import hashlib
from pathlib import Path
from itertools import product

import numpy as np
import pandas as pd

from sklearn.base import clone, BaseEstimator, TransformerMixin
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.linear_model import Lasso, ElasticNet, Ridge, LassoLars
from sklearn.cross_decomposition import PLSRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    HistGradientBoostingRegressor,
)
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import GroupKFold, ParameterGrid, StratifiedKFold
from joblib import Parallel, delayed
import os
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.feature_selection import f_regression

# Optional XGBoost candidate.
# If xgboost is not installed in the current environment, the xgboost model
# will be removed from MODEL_TYPES below to avoid crashing the whole run.
try:
    from xgboost import XGBRegressor
    XGBOOST_AVAILABLE = True
except ImportError:
    XGBRegressor = None
    XGBOOST_AVAILABLE = False

In [3]:
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

In [4]:
# ==========================================
# Config
# ==========================================
DATA_ROOT = Path("../../DifferentCom_data_rebuild")
TP_DIR = DATA_ROOT / "tp_views"
BASE_DIR = DATA_ROOT / "base_patient_tables"

# ==========================================
# Experiment tag / output directory
# ==========================================
# Training version of paper-style single-omics:
#   1) uses TRAIN_IDS only
#   2) evaluates performance with outer CV OOF predictions
#   3) feature selection is performed inside each inner CV fold
#   4) f_regression / correlation univariate selection modes are supported
#   5) v11 uses targeted performance expansion with v9-compatible candidate-model pools
#   6) critical v9 routes are reproduced with the same candidate model sets, not single-model-only routes
#   7) final judgment must use OOF R², not train_r2 or final_full_train_r2
EXPERIMENT_TAG = "single_omics_train_paper_style_v11_rescue_expansion_v9compatible"

SAVE_DIR = DATA_ROOT / f"results_single_omics_train_only_{EXPERIMENT_TAG}"
SAVE_DIR.mkdir(parents=True, exist_ok=True)

TARGET_PATH = BASE_DIR / "target_by_patient.csv"

# A = proteomics, B = metabolomics, C = miRNA
COMBOS = ["A", "B", "C"]
TISSUES = ["csf", "ser"]
TIMEPOINTS = [24, 48, 72, 96, 120]

# Conservative model set for small-n single-omics.
# v11 keeps all model definitions available, but the actual run is
# controlled by the v9-compatible rescue expansion route table in the run cell.
MODEL_TYPES = [
    "ridge",
    "elasticnet",
    "pls",
    "svr_linear",
    "gbr",
    "xgboost",
]

# Keep the notebook runnable even when xgboost is not installed.
if not XGBOOST_AVAILABLE:
    print("[WARN] xgboost is not installed. Removing 'xgboost' from MODEL_TYPES.")
    MODEL_TYPES = [m for m in MODEL_TYPES if m != "xgboost"]


def get_candidate_models_for_single(tissue: str, combo: str, tp: int) -> list[str]:
    """
    v10 targeted OOF-focused routing based on the v9 single-omics summary.

    Main intent:
    - Keep ALL A/B/C combos and ALL 24/48/72/96/120h timepoints.
    - Use the v9 OOF winners as the primary route.
    - Keep a small number of backup models only where v9 showed useful signal.
    - Reduce noisy searches in weak B/C regions.
    """
    tissue = str(tissue).lower()
    combo = str(combo)
    tp = int(tp)

    if combo == "A":
        if tissue == "ser" and tp in [72, 96]:
            candidates = ["svr_linear", "ridge"]
        elif tissue == "csf" and tp == 72:
            candidates = ["svr_linear", "gbr", "ridge"]
        elif tissue == "csf" and tp == 96:
            candidates = ["ridge", "svr_linear"]
        else:
            candidates = ["ridge"]

    elif combo == "B":
        # B is kept mainly for complete A/B/C coverage.
        # v9 showed ridge as the only consistently useful B-family model.
        candidates = ["ridge"]

    elif combo == "C":
        if tissue == "ser" and tp == 24:
            # v9 overall best: ser C 24h + xgboost + f_regression_topk + top_k=40.
            candidates = ["xgboost", "ridge"]
        else:
            candidates = ["ridge"]

    else:
        candidates = ["ridge"]

    return [m for m in candidates if m in MODEL_TYPES]


def get_feature_selection_modes_for_single(tissue: str, combo: str, tp: int) -> list[str]:
    """
    v10 feature-selection routing.

    - A keeps both f_regression_topk and corr_topk because v9 showed both can win
      depending on tissue/TP, especially ser A 96h and csf A 72/96h.
    - ser C 24h keeps f_regression_topk as the primary XGBoost rescue route and
      corr_topk as a low-priority diagnostic route.
    - Other C routes use f_regression_topk primarily, with selected corr_topk checks
      in the explicit route table.
    - B remains f_regression_topk-only.
    """
    tissue = str(tissue).lower()
    combo = str(combo)
    tp = int(tp)

    if combo == "A":
        return ["f_regression_topk", "corr_topk"]

    if tissue == "ser" and combo == "C" and tp == 24:
        return ["f_regression_topk", "corr_topk"]

    return ["f_regression_topk"]


FEATURE_SELECTION_MODES_TO_RUN = [
    "f_regression_topk",
    "corr_topk",
]

# For ablation, change to ["omics_only", "light"].
CLINICAL_MODES_TO_RUN = ["light"]

# sparse filter: train 기준으로만 적용
MIN_OBS_FRAC = 0.50

# CV
N_SPLITS_OUTER = 5
N_SPLITS_INNER = 3
RANDOM_STATE = 42

# y-bin stratification for regression CV stability
USE_STRATIFIED_OUTER_CV = True
N_Y_BINS_FOR_OUTER_CV = 3
OUTER_CV_RANDOM_STATE = 42

# Model-selection stability penalty.
# best_score_for_selection = inner_oof_r2 - penalty * std(inner_fold_r2)
INNER_SELECTION_STD_PENALTY = 0.10

# ==========================================
# Leakage-free feature-wise weighting
# ==========================================
USE_FEATURE_WEIGHTING = True
FEATURE_WEIGHT_SCORE_MODE = "univariate_corr_soft_conservative"
FEATURE_WEIGHT_MIN = 1.0
FEATURE_WEIGHT_MAX = 1.20
FEATURE_WEIGHT_MIN_OBS = 8
FEATURE_WEIGHT_EXCLUDE_CLINICAL = True
FEATURE_WEIGHT_DEFAULT = 1.0

FEATURE_TRACE_DIR = SAVE_DIR / "feature_traces"
FEATURE_TRACE_DIR.mkdir(parents=True, exist_ok=True)

DETAIL_DIR = SAVE_DIR / "single_detail_outputs"
DETAIL_DIR.mkdir(parents=True, exist_ok=True)

print("SAVE_DIR:", SAVE_DIR.resolve())
print("DETAIL_DIR:", DETAIL_DIR.resolve())
print("EXPERIMENT_TAG:", EXPERIMENT_TAG)
print("MODEL_TYPES:", MODEL_TYPES)
print("MODEL_ROUTING_EXAMPLES:", {(t,c,tp): get_candidate_models_for_single(t,c,tp) for t in ["csf","ser"] for c in ["A","B","C"] for tp in [24,96]})
print("FEATURE_SELECTION_MODES_TO_RUN:", FEATURE_SELECTION_MODES_TO_RUN)
print("FEATURE_SELECTION_ROUTING_EXAMPLES:", {
    (t,c,tp): get_feature_selection_modes_for_single(t,c,tp)
    for t in ["csf","ser"] for c in ["A","B","C"] for tp in [24,72,120]
})
print("CLINICAL_MODES_TO_RUN:", CLINICAL_MODES_TO_RUN)
print("USE_FEATURE_WEIGHTING:", USE_FEATURE_WEIGHTING)
print("FEATURE_WEIGHT_SCORE_MODE:", FEATURE_WEIGHT_SCORE_MODE)
print("FEATURE_WEIGHT_RANGE:", (FEATURE_WEIGHT_MIN, FEATURE_WEIGHT_MAX))

SAVE_DIR: /data2/jinoh001/stable/research_SPI/DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible
DETAIL_DIR: /data2/jinoh001/stable/research_SPI/DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/single_detail_outputs
EXPERIMENT_TAG: single_omics_train_paper_style_v11_rescue_expansion_v9compatible
MODEL_TYPES: ['ridge', 'elasticnet', 'pls', 'svr_linear', 'gbr', 'xgboost']
MODEL_ROUTING_EXAMPLES: {('csf', 'A', 24): ['ridge'], ('csf', 'A', 96): ['ridge', 'svr_linear'], ('csf', 'B', 24): ['ridge'], ('csf', 'B', 96): ['ridge'], ('csf', 'C', 24): ['ridge'], ('csf', 'C', 96): ['ridge'], ('ser', 'A', 24): ['ridge'], ('ser', 'A', 96): ['svr_linear', 'ridge'], ('ser', 'B', 24): ['ridge'], ('ser', 'B', 96): ['ridge'], ('ser', 'C', 24): ['xgboost', 'ridge'], ('ser', 'C', 96): ['ridge']}
FEATURE_SELECTION_MODES_TO_RUN: ['f_regression_topk', 'corr_topk']
FEATURE_SELECTION_ROUTING_EXAMPLES: {('csf', 'A', 24): ['f_regression_topk', 'corr_topk'], ('csf', 'A', 72): ['f_regression_topk', 'corr_topk'], ('csf', 'A', 120): ['f_regression_topk', 'corr_topk'], ('csf', 'B', 24): ['f_regression_topk'], ('csf', 'B', 72): ['f_regression_topk'], ('csf', 'B', 120): ['f_regression_topk'], ('csf', 'C', 24): ['f_regression_topk'], ('csf', 'C', 72): ['f_regression_topk'], ('csf', 'C', 120): ['f_regression_topk'], ('ser', 'A', 24): ['f_regression_topk', 'corr_topk'], ('ser', 'A', 72): ['f_regression_topk', 'corr_topk'], ('ser', 'A', 120): ['f_regression_topk', 'corr_topk'], ('ser', 'B', 24): ['f_regression_topk'], ('ser', 'B', 72): ['f_regression_topk'], ('ser', 'B', 120): ['f_regression_topk'], ('ser', 'C', 24): ['f_regression_topk', 'corr_topk'], ('ser', 'C', 72): ['f_regression_topk'], ('ser', 'C', 120): ['f_regression_topk']}
CLINICAL_MODES_TO_RUN: ['light']
USE_FEATURE_WEIGHTING: True
FEATURE_WEIGHT_SCORE_MODE: univariate_corr_soft_conservative
FEATURE_WEIGHT_RANGE: (1.0, 1.2)

## v11 update: rescue expansion with v9-compatible candidate pools

This version is different from the previous v10 targeted-pruning notebook.

The previous targeted version reduced `candidate_models` to single-model routes. That made some routes look similar to v9, but they were not actually equivalent. For example, v9's `ser C 24h` rescue route used the candidate pool `xgboost + gbr + ridge`, while the targeted version used `xgboost` alone. That can change outer-fold model selection and OOF R².

Main changes:

- Keeps full coverage: `csf/ser × A/B/C × 24/48/72/96/120`.
- Restores v9-compatible candidate pools for critical routes.
- Expands only the high-potential areas around v9/v10 winners.
- Keeps B-family routes minimal because B is mainly for coverage.
- Uses OOF R² as the primary metric.

Critical rescue areas:

- `ser C 24h`: `xgboost + gbr + ridge`, `top_k = 10/20/30/40/50/60`, both `f_regression_topk` and `corr_topk`.
- `ser A 96h`: `svr_linear + ridge + elasticnet`, expanded top-k around 120.
- `ser A 72h`: `svr_linear + ridge + elasticnet`, expanded top-k around 120.
- `csf A 72h`: `svr_linear + ridge + gbr`, expanded top-k around 80.
- `csf A 96h`: `svr_linear + ridge + elasticnet`, expanded top-k around 40/80.
- `csf C 24/48/72/96/120`: includes `corr_topk` because v10 targeted found a strong `csf C 24h + corr_topk + top_k=20` signal.

In [5]:
# ==========================================
# Parallel config
# ==========================================
TOTAL_CPUS = os.cpu_count() or 1

# 실험 단위 병렬화 권장
# 32 CPU 기준이면 6~8 정도부터 시작하는 게 안전
N_JOBS_EXPERIMENT = 8

print("TOTAL_CPUS:", TOTAL_CPUS)
print("N_JOBS_EXPERIMENT:", N_JOBS_EXPERIMENT)

TOTAL_CPUS: 32
N_JOBS_EXPERIMENT: 8

In [6]:
def read_id_txt(path: str) -> list[str]:
    df = pd.read_csv(path)
    return df["Patient"].astype(str).tolist()


TRAIN_ID_PATH = "../../data/training_id.txt"

TRAIN_IDS = read_id_txt(TRAIN_ID_PATH)

print("n TRAIN_IDS:", len(TRAIN_IDS))

n TRAIN_IDS: 60

In [7]:
def load_target(path: Path) -> pd.Series:
    """
    patient-level target loader
    """
    y = pd.read_csv(path, index_col=0).iloc[:, 0]
    y.index = y.index.astype(str)
    y.name = "DeltaTMS"
    return y

In [8]:
# ==========================================
# Alignment helpers
# ==========================================
def align_xy(X: pd.DataFrame, y: pd.Series) -> tuple[pd.DataFrame, pd.Series]:
    """
    Keep only patients that exist in both X and y.
    """
    idx = X.index.intersection(y.index)
    X = X.loc[idx].copy()
    y = y.loc[idx].copy()
    return X, y

In [9]:
def filter_sparse_features_train_test(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
    min_obs_frac: float = 0.7,
    protected_keep_cols: list[str] | None = None,
):
    if protected_keep_cols is None:
        protected_keep_cols = []

    protected_keep_cols = [c for c in protected_keep_cols if c in X_train.columns]

    # 1) constant columns 제거 (train 기준)
    nunique = X_train.nunique(dropna=True)
    const_drop_cols = [
        c for c in X_train.columns
        if nunique.get(c, 0) <= 1 and c not in protected_keep_cols
    ]
    X_train_1 = X_train.drop(columns=const_drop_cols)
    X_valid_1 = X_valid.drop(columns=[c for c in const_drop_cols if c in X_valid.columns])

    # 2) missing ratio 기준 filtering (train 기준)
    obs_frac = X_train_1.notna().mean(axis=0)
    keep_cols = [
        c for c in X_train_1.columns
        if (obs_frac.get(c, 0.0) >= min_obs_frac) or (c in protected_keep_cols)
    ]

    X_train_f = X_train_1.loc[:, keep_cols].copy()
    X_valid_f = X_valid_1.reindex(columns=keep_cols).copy()

    return X_train_f, X_valid_f

In [10]:
def _median_impute_numeric_train_valid(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Fit median imputation on X_train only, then apply to X_train/X_valid.
    This helper is used only for univariate scoring, not for final model fitting.
    """
    X_tr = X_train.apply(pd.to_numeric, errors="coerce")
    X_va = X_valid.apply(pd.to_numeric, errors="coerce")

    med = X_tr.median(axis=0, skipna=True)
    med = med.fillna(0.0)

    return X_tr.fillna(med), X_va.fillna(med)


def compute_univariate_feature_scores(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    protected_keep_cols: list[str] | None = None,
    min_obs: int = FEATURE_WEIGHT_MIN_OBS,
) -> pd.DataFrame:
    """
    Compute train-only univariate scores.

    Available score columns:
    - abs_corr: absolute Pearson correlation with DeltaTMS
    - f_score / p_value: sklearn f_regression score and p-value
    - neg_log10_p: larger means smaller p-value
    - hybrid_rank_score: combines corr-rank and p-value-rank

    Important:
    - This function must be called only on the training side of the current split.
    - It should never see validation/test y.
    """
    protected_keep_cols = protected_keep_cols or []
    protected_set = set(protected_keep_cols)

    candidate_cols = [c for c in X_train.columns if c not in protected_set]
    rows = []

    if len(candidate_cols) == 0:
        return pd.DataFrame(columns=[
            "feature", "abs_corr", "f_score", "p_value", "neg_log10_p",
            "corr_rank_score", "p_rank_score", "hybrid_rank_score",
            "is_protected",
        ])

    X_cand = X_train.loc[:, candidate_cols].copy()
    X_imp, _ = _median_impute_numeric_train_valid(X_cand, X_cand)
    y_num = pd.to_numeric(y_train, errors="coerce")

    valid_y = y_num.notna() & np.isfinite(y_num)
    X_imp = X_imp.loc[valid_y]
    y_num = y_num.loc[valid_y]

    if len(y_num) >= 3 and y_num.nunique(dropna=True) > 1:
        try:
            f_vals, p_vals = f_regression(X_imp, y_num)
        except Exception:
            f_vals = np.zeros(len(candidate_cols), dtype=float)
            p_vals = np.ones(len(candidate_cols), dtype=float)
    else:
        f_vals = np.zeros(len(candidate_cols), dtype=float)
        p_vals = np.ones(len(candidate_cols), dtype=float)

    for j, col in enumerate(candidate_cols):
        abs_corr = _safe_abs_corr(X_train[col], y_train, min_obs=min_obs)
        f_score = float(f_vals[j]) if np.isfinite(f_vals[j]) else 0.0
        p_value = float(p_vals[j]) if np.isfinite(p_vals[j]) else 1.0
        p_value = max(p_value, 1e-300)
        rows.append({
            "feature": col,
            "abs_corr": float(abs_corr),
            "f_score": f_score,
            "p_value": p_value,
            "neg_log10_p": float(-np.log10(p_value)),
            "is_protected": False,
        })

    score_df = pd.DataFrame(rows)

    # rank scores: higher is better
    if len(score_df) > 0:
        score_df["corr_rank_score"] = score_df["abs_corr"].rank(method="average", pct=True)
        score_df["p_rank_score"] = score_df["neg_log10_p"].rank(method="average", pct=True)
        score_df["hybrid_rank_score"] = 0.5 * score_df["corr_rank_score"] + 0.5 * score_df["p_rank_score"]

    return score_df


def select_features_train_valid(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
    y_train: pd.Series,
    k: int | None,
    mode: str = "f_regression_topk",
    protected_keep_cols: list[str] | None = None,
    min_obs: int = FEATURE_WEIGHT_MIN_OBS,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, list[str]]:
    """
    Fold-safe feature selection.

    This replaces the old approach where target-aware top-k was applied once
    before inner CV. Here, feature selection is repeated inside each inner fold
    using only that fold's training data.

    Modes:
    - "none": keep all columns
    - "corr_topk": top-k by abs correlation with y_train
    - "f_regression_topk": top-k by univariate f_regression p-value
    - "hybrid_topk": top-k by combined corr/p-value rank
    """
    protected_keep_cols = protected_keep_cols or []
    protected_keep_cols = [c for c in protected_keep_cols if c in X_train.columns]

    if mode == "none" or k is None or k <= 0:
        selected_features = list(X_train.columns)
        score_df = pd.DataFrame({
            "feature": selected_features,
            "selected": True,
            "selection_mode": mode,
            "selection_score": np.nan,
            "is_protected": [c in protected_keep_cols for c in selected_features],
        })
        return (
            X_train.loc[:, selected_features].copy(),
            X_valid.reindex(columns=selected_features).copy(),
            score_df,
            selected_features,
        )

    score_df = compute_univariate_feature_scores(
        X_train=X_train,
        y_train=y_train,
        protected_keep_cols=protected_keep_cols,
        min_obs=min_obs,
    )

    if mode == "corr_topk":
        sort_col = "abs_corr"
    elif mode == "f_regression_topk":
        sort_col = "neg_log10_p"
    elif mode == "hybrid_topk":
        sort_col = "hybrid_rank_score"
    else:
        raise ValueError(f"Unknown feature_selection_mode: {mode}")

    candidate_cols = [c for c in X_train.columns if c not in set(protected_keep_cols)]
    k_for_candidates = max(0, int(k) - len(protected_keep_cols))

    if len(candidate_cols) == 0 or k_for_candidates == 0 or len(score_df) == 0:
        top_candidate_cols = []
    else:
        top_candidate_cols = (
            score_df.sort_values(sort_col, ascending=False)
                    .head(min(k_for_candidates, len(score_df)))["feature"]
                    .tolist()
        )

    selected_set = set(protected_keep_cols + top_candidate_cols)
    selected_features = [c for c in X_train.columns if c in selected_set]

    if len(selected_features) == 0:
        # Absolute fallback to avoid failed runs.
        selected_features = list(X_train.columns)

    out_score = score_df.copy()
    if len(out_score) > 0:
        out_score["selected"] = out_score["feature"].isin(selected_features)
        out_score["selection_mode"] = mode
        out_score["selection_score"] = out_score[sort_col]
        protected_rows = pd.DataFrame({
            "feature": protected_keep_cols,
            "abs_corr": np.nan,
            "f_score": np.nan,
            "p_value": np.nan,
            "neg_log10_p": np.nan,
            "corr_rank_score": np.nan,
            "p_rank_score": np.nan,
            "hybrid_rank_score": np.nan,
            "is_protected": True,
            "selected": True,
            "selection_mode": mode,
            "selection_score": np.nan,
        })
        out_score = pd.concat([protected_rows, out_score], ignore_index=True)

    return (
        X_train.loc[:, selected_features].copy(),
        X_valid.reindex(columns=selected_features).copy(),
        out_score,
        selected_features,
    )


def top_k_target_corr_filter(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
    y_train: pd.Series,
    k: int | None,
    protected_keep_cols: list[str] | None = None,
    min_obs: int = FEATURE_WEIGHT_MIN_OBS,
):
    """
    Backward-compatible wrapper.
    New code should use select_features_train_valid(..., mode="corr_topk").
    """
    X_tr, X_va, _, _ = select_features_train_valid(
        X_train=X_train,
        X_valid=X_valid,
        y_train=y_train,
        k=k,
        mode="corr_topk",
        protected_keep_cols=protected_keep_cols,
        min_obs=min_obs,
    )
    return X_tr, X_va

In [11]:
from sklearn.impute import KNNImputer


def make_preprocess(X: pd.DataFrame) -> ColumnTransformer:
    cat = [c for c in X.columns if c in ["Gender", "Level"]]
    num = [c for c in X.columns if c not in cat]

    preprocess = ColumnTransformer(
        transformers=[
            ("num", Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]), num),
            ("cat", Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("ohe", OneHotEncoder(handle_unknown="ignore")),
            ]), cat),
        ],
        remainder="drop",
        verbose_feature_names_out=False
    )

    try:
        preprocess.set_output(transform="pandas")
    except Exception:
        pass

    return preprocess


def make_model(model_type: str):
    """
    Model families are intentionally kept conservative because this dataset is small.
    Tree/boosting models use shallow settings through the parameter grid.
    """
    if model_type == "lasso":
        return Lasso(max_iter=50000, random_state=RANDOM_STATE, tol=1e-3)
    elif model_type == "elasticnet":
        return ElasticNet(max_iter=50000, random_state=RANDOM_STATE, tol=1e-3)
    elif model_type == "ridge":
        return Ridge()
    elif model_type == "lassolars":
        return LassoLars()
    elif model_type == "pls":
        return PLSRegression(scale=False)
    elif model_type == "svr_linear":
        return SVR(kernel="linear")
    elif model_type == "svr_rbf":
        return SVR(kernel="rbf")
    elif model_type == "knn":
        return KNeighborsRegressor()
    elif model_type == "rf":
        return RandomForestRegressor(random_state=RANDOM_STATE, n_jobs=1)
    elif model_type == "extratrees":
        return ExtraTreesRegressor(random_state=RANDOM_STATE, n_jobs=1)
    elif model_type == "gbr":
        return GradientBoostingRegressor(random_state=RANDOM_STATE)
    elif model_type == "xgboost":
        if not XGBOOST_AVAILABLE or XGBRegressor is None:
            raise ImportError("xgboost is not installed, so model_type='xgboost' cannot be used.")
        return XGBRegressor(
            objective="reg:squarederror",
            random_state=RANDOM_STATE,
            n_jobs=1,
            tree_method="hist",
            verbosity=0,
        )
    elif model_type == "histgbr":
        return HistGradientBoostingRegressor(random_state=RANDOM_STATE)
    else:
        raise ValueError(f"Unknown model_type: {model_type}")


def make_param_grid(model_type: str) -> dict:
    """
    Reduced hyperparameter grids for the training paper-style run.

    Purpose:
    - keep the full model family list
    - reduce alpha / major model grids enough to make the run practical
    - avoid the previous very long runtime from large nested CV grids
    """
    common_num_imputers = [SimpleImputer(strategy="median")]

    if model_type == "lasso":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__alpha": [0.1, 0.5],
        }

    elif model_type == "elasticnet":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__alpha": [0.05, 0.1, 0.5, 1.0],
            "model__l1_ratio": [0.1, 0.2, 0.5],
        }

    elif model_type == "ridge":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__alpha": [5.0, 10.0, 25.0, 50.0, 100.0],
        }

    elif model_type == "lassolars":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__alpha": [0.01, 0.1],
        }

    elif model_type == "pls":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_components": [2, 3],
        }

    elif model_type == "svr_linear":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__C": [0.03, 0.1, 0.3, 1.0],
            "model__epsilon": [0.1, 0.2],
        }

    elif model_type == "svr_rbf":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__C": [1.0],
            "model__epsilon": [0.1],
            "model__gamma": ["scale"],
        }

    elif model_type == "knn":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_neighbors": [3, 5],
            "model__weights": ["distance"],
        }

    elif model_type == "rf":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_estimators": [100],
            "model__max_depth": [2, 3],
            "model__min_samples_leaf": [2],
            "model__max_features": ["sqrt"],
        }

    elif model_type == "extratrees":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_estimators": [100],
            "model__max_depth": [2, 3],
            "model__min_samples_leaf": [2],
            "model__max_features": ["sqrt"],
        }

    elif model_type == "gbr":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_estimators": [30, 50],
            "model__learning_rate": [0.03, 0.05],
            "model__max_depth": [1],
            "model__min_samples_leaf": [3, 5],
            "model__subsample": [0.8],
        }

    elif model_type == "xgboost":
        # Conservative XGBoost grid for small-n/high-p single-omics data.
        # Goal: test regularized boosting without allowing train R2 to dominate model selection.
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_estimators": [50, 80],
            "model__max_depth": [1, 2],
            "model__learning_rate": [0.03],
            "model__subsample": [0.8],
            "model__colsample_bytree": [0.7, 0.9],
            "model__reg_alpha": [0.5, 1.0],
            "model__reg_lambda": [5.0, 10.0],
            "model__min_child_weight": [2, 4],
        }

    elif model_type == "histgbr":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__max_iter": [50],
            "model__learning_rate": [0.05],
            "model__max_leaf_nodes": [5],
            "model__l2_regularization": [0.1],
        }

    else:
        raise ValueError(f"Unknown model_type: {model_type}")

def adjust_param_grid_for_training_data(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    model_type: str,
) -> list[dict]:
    """
    Remove parameter settings that cannot work for the current train fold.
    Example: PLS n_components must be <= min(n_samples - 1, n_features).
    """
    grid = list(ParameterGrid(make_param_grid(model_type=model_type)))

    n_samples = int(X_train.shape[0])
    n_features = int(X_train.shape[1])

    valid_grid = []
    for params in grid:
        ok = True

        if model_type == "pls":
            n_comp = int(params.get("model__n_components", 1))
            if n_comp > max(1, min(n_samples - 1, n_features)):
                ok = False

        if model_type == "knn":
            n_neighbors = int(params.get("model__n_neighbors", 5))
            if n_neighbors >= n_samples:
                ok = False

        if ok:
            valid_grid.append(params)

    if len(valid_grid) == 0:
        # Fallback to a safe default for very small folds.
        if model_type == "pls":
            return [{
                "preprocess__num__imputer": SimpleImputer(strategy="median"),
                "model__n_components": 1,
            }]
        if model_type == "knn":
            return [{
                "preprocess__num__imputer": SimpleImputer(strategy="median"),
                "model__n_neighbors": max(1, min(3, n_samples - 1)),
                "model__weights": "distance",
            }]
        return grid

    return valid_grid


def make_pipeline(
    X: pd.DataFrame,
    model_type: str,
    feature_weight_map: dict[str, float] | None = None,
) -> Pipeline:
    preprocess = make_preprocess(X)
    model = make_model(model_type)

    steps = [
        ("preprocess", preprocess),
    ]

    if USE_FEATURE_WEIGHTING:
        steps.append((
            "feature_weight",
            FeatureWeightTransformer(
                feature_weight_map=feature_weight_map,
                default_weight=FEATURE_WEIGHT_DEFAULT,
                enabled=USE_FEATURE_WEIGHTING,
            ),
        ))

    steps.append(("model", model))

    return Pipeline(steps)


def predict_1d(model: Pipeline, X: pd.DataFrame) -> np.ndarray:
    """
    Some models, e.g. PLSRegression, return shape (n, 1).
    Standardize all predictions to 1D.
    """
    return np.ravel(model.predict(X))

In [12]:
def build_feature_path(feature_mode: str, tissue: str, combo: str, tp: int) -> Path:
    if feature_mode == "omics":
        return TP_DIR / f"x_omics_{tissue}_{combo}_{tp}.csv"
    elif feature_mode == "omicsdelta":
        return TP_DIR / f"x_omicsdelta_{tissue}_{combo}_{tp}.csv"
    else:
        raise ValueError(f"Unknown feature_mode: {feature_mode}")

def build_clinical_feature_path(tissue: str, combo: str, tp: int) -> Path:
    return TP_DIR / f"x_clinical_{tissue}_{combo}_{tp}.csv"


def load_feature_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    if "Patient" not in df.columns:
        raise ValueError(f"'Patient' not found in {path}")
    df = df.set_index("Patient")
    df.index = df.index.astype(str)
    return df

def dataframe_content_signature(df: pd.DataFrame) -> str:
    """
    Lightweight diagnostic hash used to check whether two TP feature matrices
    are accidentally identical. This is not used for modeling.
    """
    if df is None or len(df) == 0:
        return "EMPTY"
    tmp = df.copy()
    tmp = tmp.sort_index(axis=0).sort_index(axis=1)
    col_part = "|".join(map(str, tmp.columns))
    shape_part = f"{tmp.shape[0]}x{tmp.shape[1]}"
    # hash_pandas_object handles mixed dtypes after string fallback; keep it lightweight.
    try:
        values_hash = pd.util.hash_pandas_object(tmp.astype(str), index=True).values.tobytes()
    except Exception:
        values_hash = tmp.to_csv(index=True).encode("utf-8")
    return hashlib.md5((shape_part + "|" + col_part).encode("utf-8") + values_hash).hexdigest()

In [13]:
def get_clinical_columns() -> list[str]:
    return ["Age", "Gender", "Level"]


def get_hard_forbidden_proxy_columns() -> list[str]:
    return [
        "TMS_Base", "UEMS_Base", "LEMS_Base",
        "TMS_6mo", "UEMS_6mo", "LEMS_6mo",
        "AIS_6mo",
        "DeltaTMS", "DeltaUEMS", "DeltaLEMS",
    ]


def assert_no_forbidden_proxy_columns(
    X: pd.DataFrame,
    use_light_clinical: bool = False,
):
    hard_bad = [c for c in X.columns if c in get_hard_forbidden_proxy_columns()]
    if len(hard_bad) > 0:
        raise ValueError(f"Hard forbidden proxy/leakage columns found: {hard_bad}")

    all_clinical_like = [
        "Age", "Gender", "Level", "AIS", "AIS_Base", "AIS_Base_Numeric",
        "TMS_Base", "UEMS_Base", "LEMS_Base",
        "TMS_6mo", "UEMS_6mo", "LEMS_6mo", "AIS_6mo",
        "DeltaTMS", "DeltaUEMS", "DeltaLEMS",
    ]

    allowed = set(get_clinical_columns()) if use_light_clinical else set()
    soft_bad = [
        c for c in X.columns
        if (c in all_clinical_like and c not in allowed and c not in get_hard_forbidden_proxy_columns())
    ]

    if len(soft_bad) > 0:
        raise ValueError(f"Unexpected clinical columns found for this mode: {soft_bad}")

In [14]:
def load_light_clinical_block(
    tissue: str,
    combo: str,
    tp: int,
) -> pd.DataFrame:
    clin_path = build_clinical_feature_path(tissue=tissue, combo=combo, tp=tp)
    clin_df = load_feature_csv(clin_path)

    keep_cols = [c for c in get_clinical_columns() if c in clin_df.columns]
    clin_df = clin_df.loc[:, keep_cols].copy()

    missing_cols = [c for c in get_clinical_columns() if c not in clin_df.columns]
    if len(missing_cols) > 0:
        print(f"[WARN] missing light clinical columns in {clin_path.name}: {missing_cols}")

    if "Age" in clin_df.columns:
        clin_df["Age"] = pd.to_numeric(clin_df["Age"], errors="coerce")

    return clin_df


def merge_with_light_clinical(
    X_feat: pd.DataFrame,
    tissue: str,
    combo: str,
    tp: int,
) -> pd.DataFrame:
    clin_df = load_light_clinical_block(tissue=tissue, combo=combo, tp=tp)

    common_ids = X_feat.index.intersection(clin_df.index)
    X_feat2 = X_feat.loc[common_ids].copy()
    clin_df2 = clin_df.loc[common_ids].copy()

    X_merged = pd.concat([X_feat2, clin_df2], axis=1)

    dup_cols = X_merged.columns[X_merged.columns.duplicated()].tolist()
    if len(dup_cols) > 0:
        raise ValueError(f"Duplicate columns after light clinical merge: {dup_cols}")

    return X_merged

In [15]:
def encode_clinical_train_valid(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, list[str]]:
    """
    Clinical block은 train 기준으로만 encoding한다.
    반환:
      - encoded X_train
      - encoded X_valid
      - encoded clinical column names
    """
    base_clin_cols = [c for c in get_clinical_columns() if c in X_train.columns]
    if len(base_clin_cols) == 0:
        return X_train, X_valid, []

    tr_clin = X_train.loc[:, base_clin_cols].copy()
    va_clin = X_valid.loc[:, [c for c in base_clin_cols if c in X_valid.columns]].copy()

    tr_other = X_train.drop(columns=base_clin_cols, errors="ignore").copy()
    va_other = X_valid.drop(columns=base_clin_cols, errors="ignore").copy()

    if "Age" in tr_clin.columns:
        tr_clin["Age"] = pd.to_numeric(tr_clin["Age"], errors="coerce")
    if "Age" in va_clin.columns:
        va_clin["Age"] = pd.to_numeric(va_clin["Age"], errors="coerce")

    cat_cols = [c for c in ["Gender", "Level"] if c in tr_clin.columns]

    if len(cat_cols) > 0:
        tr_clin_enc = pd.get_dummies(
            tr_clin,
            columns=cat_cols,
            dummy_na=True,
            dtype=float,
        )
        va_clin_enc = pd.get_dummies(
            va_clin,
            columns=cat_cols,
            dummy_na=True,
            dtype=float,
        )
        va_clin_enc = va_clin_enc.reindex(columns=tr_clin_enc.columns, fill_value=0.0)
    else:
        tr_clin_enc = tr_clin.copy()
        va_clin_enc = va_clin.copy()

    tr_clin_enc = tr_clin_enc.apply(pd.to_numeric, errors="coerce")
    va_clin_enc = va_clin_enc.apply(pd.to_numeric, errors="coerce")

    encoded_clin_cols = tr_clin_enc.columns.tolist()

    X_train_out = pd.concat([tr_other, tr_clin_enc], axis=1)
    X_valid_out = pd.concat([va_other, va_clin_enc], axis=1)

    return X_train_out, X_valid_out, encoded_clin_cols

In [16]:
# # ==========================================
# # Inner CV tuning
# # ==========================================
# def fit_best_model(
#     X_train: pd.DataFrame,
#     y_train: pd.Series,
#     groups_train: np.ndarray,
#     model_type: str,
#     n_splits_inner: int = 3,
# ):
#     """
#     Tune hyperparameters only on the training fold.
#     """
#     pipe = make_pipeline(X_train, model_type=model_type)
#     param_grid = make_param_grid(model_type=model_type)

#     if model_type in ["lasso", "elasticnet"] and "select__k" in param_grid:
#         preprocess = make_preprocess(X_train)
#         X_train_tx = preprocess.fit_transform(X_train, y_train)
#         n_features_after_preprocess = X_train_tx.shape[1]

#         valid_k = sorted({
#             int(k)
#             for k in param_grid["select__k"]
#             if int(k) <= n_features_after_preprocess
#         })

#         if len(valid_k) == 0:
#             valid_k = [max(1, n_features_after_preprocess)]

#         param_grid["select__k"] = valid_k

#     inner_cv = GroupKFold(n_splits=n_splits_inner)

#     gs = GridSearchCV(
#         estimator=pipe,
#         param_grid=param_grid,
#         scoring="r2",
#         cv=inner_cv,
#         n_jobs=12,
#         refit=True,
#     )
#     gs.fit(X_train, y_train, groups=groups_train)

#     return gs.best_estimator_, gs.best_params_, gs.best_score_

In [17]:
class FeatureWeightTransformer(BaseEstimator, TransformerMixin):
    """
    Apply precomputed feature-wise weights after preprocessing/scaling.

    Why after preprocessing?
    - If weights are applied before StandardScaler, StandardScaler can cancel out most
      multiplicative effects.
    - Applying after preprocessing means the model sees the weighted feature matrix.

    Leakage rule:
    - feature_weight_map must be computed outside this transformer using train data only.
    - validation/test y is never used here.
    """
    def __init__(
        self,
        feature_weight_map: dict[str, float] | None = None,
        default_weight: float = 1.0,
        enabled: bool = True,
    ):
        self.feature_weight_map = feature_weight_map
        self.default_weight = default_weight
        self.enabled = enabled

    def fit(self, X, y=None):
        if not self.enabled or self.feature_weight_map is None:
            self.weights_ = np.ones(X.shape[1], dtype=float)
            self.feature_names_ = list(getattr(X, "columns", [f"x{i}" for i in range(X.shape[1])]))
            return self

        if hasattr(X, "columns"):
            self.feature_names_ = list(X.columns)
            weights = []
            for feat in self.feature_names_:
                feat_str = str(feat)

                # exact match for numeric/transformed numeric columns
                w = self.feature_weight_map.get(feat_str, None)

                # fallback for one-hot names such as Gender_M or Level_C
                if w is None:
                    base = feat_str.split("_")[0]
                    w = self.feature_weight_map.get(base, self.default_weight)

                weights.append(float(w))

            self.weights_ = np.asarray(weights, dtype=float)
        else:
            # fallback: if sklearn cannot output pandas, keep neutral weighting
            self.feature_names_ = [f"x{i}" for i in range(X.shape[1])]
            self.weights_ = np.ones(X.shape[1], dtype=float)

        return self

    def transform(self, X):
        if not self.enabled:
            return X

        if hasattr(X, "copy") and hasattr(X, "columns"):
            Xw = X.copy()
            for col, w in zip(Xw.columns, self.weights_):
                Xw[col] = Xw[col] * float(w)
            return Xw

        return X * self.weights_


def _safe_abs_corr(x: pd.Series, y: pd.Series, min_obs: int) -> float:
    x_num = pd.to_numeric(x, errors="coerce")
    y_num = pd.to_numeric(y, errors="coerce")
    mask = x_num.notna() & y_num.notna() & np.isfinite(x_num) & np.isfinite(y_num)

    if int(mask.sum()) < min_obs:
        return 0.0

    xv = x_num.loc[mask]
    yv = y_num.loc[mask]

    if xv.nunique(dropna=True) <= 1 or yv.nunique(dropna=True) <= 1:
        return 0.0

    corr = xv.corr(yv)
    if pd.isna(corr) or not np.isfinite(corr):
        return 0.0

    return float(abs(corr))


def compute_feature_weight_map_from_train(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    protected_keep_cols: list[str] | None = None,
    min_weight: float = FEATURE_WEIGHT_MIN,
    max_weight: float = FEATURE_WEIGHT_MAX,
    min_obs: int = FEATURE_WEIGHT_MIN_OBS,
) -> tuple[dict[str, float], pd.DataFrame]:
    """
    Compute feature weights using outer-train data only.

    Current score:
    - absolute Pearson correlation between feature and DeltaTMS within train data
    - clinical/protected columns are kept at weight 1.0 by default

    This is intentionally simple and conservative. It can be replaced later by
    selection-frequency or coefficient-stability scoring, but this version is safer
    as the first feature-weighting experiment.
    """
    protected_keep_cols = protected_keep_cols or []
    protected_set = set(protected_keep_cols)

    rows = []
    for col in X_train.columns:
        is_protected = col in protected_set

        if FEATURE_WEIGHT_EXCLUDE_CLINICAL and is_protected:
            score = 0.0
            weight = FEATURE_WEIGHT_DEFAULT
        else:
            score = _safe_abs_corr(X_train[col], y_train, min_obs=min_obs)
            weight = np.nan

        rows.append({
            "feature": col,
            "feature_score": float(score),
            "is_protected": bool(is_protected),
            "weight": weight,
        })

    score_df = pd.DataFrame(rows)

    eligible = score_df["weight"].isna()
    if eligible.any():
        s = score_df.loc[eligible, "feature_score"].astype(float)
        s_min = float(s.min())
        s_max = float(s.max())

        if np.isclose(s_min, s_max):
            scaled = pd.Series(0.0, index=s.index)
        else:
            scaled = (s - s_min) / (s_max - s_min)

        score_df.loc[eligible, "weight"] = min_weight + scaled * (max_weight - min_weight)

    score_df["weight"] = score_df["weight"].fillna(FEATURE_WEIGHT_DEFAULT).astype(float)
    score_df = score_df.sort_values(
        ["weight", "feature_score"],
        ascending=[False, False],
    ).reset_index(drop=True)

    weight_map = dict(zip(score_df["feature"].astype(str), score_df["weight"].astype(float)))

    return weight_map, score_df


def build_feature_weights(
    feature_score_df: pd.DataFrame,
    mode: str = "soft",
    top_k: int = 50,
    high_weight: float = 1.5,
    low_weight: float = 0.5,
    min_weight: float = 0.5,
    max_weight: float = 1.5,
):
    """
    Backward-compatible helper.
    Existing code may still call this function.
    """
    df = feature_score_df.copy()

    if len(df) == 0:
        return pd.DataFrame(columns=["feature", "weight"])

    if mode == "topk":
        df["weight"] = low_weight
        top_feats = df.head(top_k)["feature"].tolist()
        df.loc[df["feature"].isin(top_feats), "weight"] = high_weight

    elif mode == "soft":
        s = df["feature_score"].values.astype(float)
        s_min, s_max = s.min(), s.max()
        if np.isclose(s_min, s_max):
            scaled = np.ones_like(s)
        else:
            scaled = (s - s_min) / (s_max - s_min)
        df["weight"] = min_weight + scaled * (max_weight - min_weight)

    else:
        raise ValueError(f"Unknown weighting mode: {mode}")

    return df[["feature", "weight"]].copy()

In [18]:
def extract_final_feature_info(fitted_pipeline: Pipeline) -> pd.DataFrame:
    preprocess = fitted_pipeline.named_steps["preprocess"]
    feature_names = list(preprocess.get_feature_names_out())

    model = fitted_pipeline.named_steps["model"]

    coef = None
    if hasattr(model, "coef_"):
        coef = np.ravel(model.coef_)
    elif hasattr(model, "x_weights_"):
        # PLS does not expose coef_ in exactly the same way across sklearn versions.
        # x_weights_ is not identical to regression coefficients, but it is useful as a trace.
        coef = np.ravel(getattr(model, "x_weights_", np.array([])))

    if coef is not None and len(coef) == len(feature_names):
        coef_list = coef.tolist()
    else:
        coef_list = [np.nan] * len(feature_names)

    feature_df = pd.DataFrame({
        "feature": feature_names,
        "coef": coef_list,
        "abs_coef": np.abs(coef_list),
    })

    if USE_FEATURE_WEIGHTING and "feature_weight" in fitted_pipeline.named_steps:
        fw = fitted_pipeline.named_steps["feature_weight"]
        weight_by_processed = dict(zip(getattr(fw, "feature_names_", []), getattr(fw, "weights_", [])))
        feature_df["feature_weight"] = feature_df["feature"].map(weight_by_processed).fillna(FEATURE_WEIGHT_DEFAULT)
    else:
        feature_df["feature_weight"] = FEATURE_WEIGHT_DEFAULT

    feature_df = feature_df.sort_values(
        "abs_coef",
        ascending=False,
        na_position="last",
    ).reset_index(drop=True)

    return feature_df


def make_regression_strata(
    y: pd.Series,
    n_bins: int,
    n_splits: int,
) -> pd.Series:
    """
    Quantile-based strata for regression CV.
    """
    y_num = pd.to_numeric(y, errors="coerce")

    if y_num.notna().sum() < n_splits:
        return pd.Series(index=y.index, data=0).astype(int)

    max_bins = min(n_bins, int(y_num.nunique()))

    for bins in range(max_bins, 1, -1):
        try:
            y_bin = pd.qcut(
                y_num,
                q=bins,
                labels=False,
                duplicates="drop",
            )
            y_bin = pd.Series(y_bin, index=y.index)

            counts = y_bin.value_counts(dropna=True)

            if len(counts) >= 2 and counts.min() >= n_splits:
                return y_bin.fillna(-1).astype(int)

        except Exception:
            continue

    return pd.Series(index=y.index, data=0).astype(int)


def make_outer_cv_splits(
    X: pd.DataFrame,
    y: pd.Series,
    groups: np.ndarray,
    n_splits: int,
):
    """
    Outer CV split helper.
    """
    if USE_STRATIFIED_OUTER_CV and X.index.is_unique:
        y_bins = make_regression_strata(
            y=y,
            n_bins=N_Y_BINS_FOR_OUTER_CV,
            n_splits=n_splits,
        )

        if y_bins.nunique(dropna=True) >= 2:
            outer_cv = StratifiedKFold(
                n_splits=n_splits,
                shuffle=True,
                random_state=OUTER_CV_RANDOM_STATE,
            )
            return list(outer_cv.split(X, y_bins)), "StratifiedKFold_y_bins"

    outer_cv = GroupKFold(n_splits=n_splits)
    return list(outer_cv.split(X, y, groups=groups)), "GroupKFold_fallback"


def make_inner_cv_splits(
    X: pd.DataFrame,
    y: pd.Series,
    groups: np.ndarray,
    n_splits: int,
):
    """
    Inner CV split helper.

    목적:
    - model/alpha/top-k 선택이 특정 fold의 y 분포 때문에 흔들리는 것을 줄인다.
    - patient index가 unique이면 y-bin stratified split을 사용한다.
    - 실패하면 GroupKFold로 fallback한다.
    """
    if X.index.is_unique:
        y_bins = make_regression_strata(
            y=y,
            n_bins=N_Y_BINS_FOR_OUTER_CV,
            n_splits=n_splits,
        )

        if y_bins.nunique(dropna=True) >= 2:
            inner_cv = StratifiedKFold(
                n_splits=n_splits,
                shuffle=True,
                random_state=RANDOM_STATE,
            )
            return list(inner_cv.split(X, y_bins)), "StratifiedKFold_y_bins"

    inner_cv = GroupKFold(n_splits=n_splits)
    return list(inner_cv.split(X, y, groups=groups)), "GroupKFold_fallback"


def fit_best_model_only(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    groups_train: np.ndarray,
    candidate_models: list[str],
    n_splits_inner: int = 3,
    protected_keep_cols: list[str] | None = None,
    feature_selection_mode: str = "f_regression_topk",
    top_k_after_sparse: int | None = 100,
):
    """
    Select model/hyperparameters using train-side inner OOF R².

    Paper-style leakage rule:
    - In each inner fold, feature selection is fitted only on inner-train.
    - Inner-validation y is never used for feature selection or feature weighting.
    - Final feature selection is fitted only on the full predefined training set.
    - Holdout test y is never used until final evaluation.
    """
    protected_keep_cols = protected_keep_cols or []

    search_rows = []
    best_obj = None
    best_score = -np.inf

    inner_splits, inner_cv_type = make_inner_cv_splits(
        X=X_train,
        y=y_train,
        groups=groups_train,
        n_splits=n_splits_inner,
    )

    for model_type in candidate_models:
        grid = adjust_param_grid_for_training_data(
            X_train=X_train,
            y_train=y_train,
            model_type=model_type,
        )

        for params in grid:
            inner_oof = pd.Series(index=X_train.index, dtype=float)
            inner_fold_scores = []
            inner_n_features = []

            for inner_fold, (tr_idx, va_idx) in enumerate(inner_splits, start=1):
                X_tr_raw = X_train.iloc[tr_idx].copy()
                y_tr = y_train.iloc[tr_idx].copy()
                X_va_raw = X_train.iloc[va_idx].copy()
                y_va = y_train.iloc[va_idx].copy()

                X_tr, X_va, _, selected_features = select_features_train_valid(
                    X_train=X_tr_raw,
                    X_valid=X_va_raw,
                    y_train=y_tr,
                    k=top_k_after_sparse,
                    mode=feature_selection_mode,
                    protected_keep_cols=protected_keep_cols,
                )
                inner_n_features.append(len(selected_features))

                if USE_FEATURE_WEIGHTING:
                    inner_weight_map, _ = compute_feature_weight_map_from_train(
                        X_train=X_tr,
                        y_train=y_tr,
                        protected_keep_cols=[c for c in protected_keep_cols if c in X_tr.columns],
                    )
                else:
                    inner_weight_map = None

                pipe = make_pipeline(
                    X_tr,
                    model_type=model_type,
                    feature_weight_map=inner_weight_map,
                )
                pipe.set_params(**params)
                pipe.fit(X_tr, y_tr)

                pred = predict_1d(pipe, X_va)
                inner_oof.iloc[va_idx] = pred

                try:
                    inner_fold_scores.append(float(r2_score(y_va, pred)))
                except Exception:
                    inner_fold_scores.append(np.nan)

            valid_mask = inner_oof.notna()

            if valid_mask.sum() >= 2:
                inner_oof_r2 = float(
                    r2_score(
                        y_train.loc[valid_mask],
                        inner_oof.loc[valid_mask],
                    )
                )
                inner_oof_mae = float(
                    mean_absolute_error(
                        y_train.loc[valid_mask],
                        inner_oof.loc[valid_mask],
                    )
                )
            else:
                inner_oof_r2 = np.nan
                inner_oof_mae = np.nan

            inner_mean_fold_r2 = (
                float(np.nanmean(inner_fold_scores))
                if len(inner_fold_scores) > 0 and not np.all(pd.isna(inner_fold_scores))
                else np.nan
            )

            inner_std_fold_r2 = (
                float(np.nanstd(inner_fold_scores))
                if len(inner_fold_scores) > 0 and not np.all(pd.isna(inner_fold_scores))
                else np.nan
            )

            if pd.notna(inner_oof_r2):
                selection_score = float(inner_oof_r2)
                if pd.notna(inner_std_fold_r2):
                    selection_score -= INNER_SELECTION_STD_PENALTY * float(inner_std_fold_r2)
            else:
                selection_score = np.nan

            search_rows.append({
                "model_type": model_type,
                "params": json.dumps(params, default=str),
                "inner_mean_r2": inner_oof_r2,
                "inner_oof_r2": inner_oof_r2,
                "inner_oof_mae": inner_oof_mae,
                "inner_mean_fold_r2": inner_mean_fold_r2,
                "inner_std_fold_r2": inner_std_fold_r2,
                "selection_score_stability_penalized": selection_score,
                "inner_cv_type": inner_cv_type,
                "feature_selection_mode": feature_selection_mode,
                "top_k_after_sparse": top_k_after_sparse,
                "mean_inner_selected_features": (
                    float(np.mean(inner_n_features)) if len(inner_n_features) > 0 else np.nan
                ),
                "min_inner_selected_features": (
                    int(np.min(inner_n_features)) if len(inner_n_features) > 0 else np.nan
                ),
                "max_inner_selected_features": (
                    int(np.max(inner_n_features)) if len(inner_n_features) > 0 else np.nan
                ),
                "use_feature_weighting": USE_FEATURE_WEIGHTING,
                "feature_weight_min": FEATURE_WEIGHT_MIN if USE_FEATURE_WEIGHTING else np.nan,
                "feature_weight_max": FEATURE_WEIGHT_MAX if USE_FEATURE_WEIGHTING else np.nan,
            })

            if pd.notna(selection_score) and selection_score > best_score:
                best_score = selection_score
                best_obj = {
                    "model_type": model_type,
                    "params": params,
                }

    if best_obj is None:
        raise ValueError("No valid model/parameter combination found in fit_best_model_only")

    # Final train-only feature selection for the holdout test model.
    X_train_sel, _, final_selection_df, selected_features = select_features_train_valid(
        X_train=X_train,
        X_valid=X_train,
        y_train=y_train,
        k=top_k_after_sparse,
        mode=feature_selection_mode,
        protected_keep_cols=protected_keep_cols,
    )

    if USE_FEATURE_WEIGHTING:
        final_weight_map, final_weight_df = compute_feature_weight_map_from_train(
            X_train=X_train_sel,
            y_train=y_train,
            protected_keep_cols=[c for c in protected_keep_cols if c in X_train_sel.columns],
        )
    else:
        final_weight_map = None
        final_weight_df = pd.DataFrame(columns=["feature", "feature_score", "is_protected", "weight"])

    final_pipe = make_pipeline(
        X_train_sel,
        model_type=best_obj["model_type"],
        feature_weight_map=final_weight_map,
    )
    final_pipe.set_params(**best_obj["params"])
    final_pipe.fit(X_train_sel, y_train)

    search_df = pd.DataFrame(search_rows)
    if len(search_df) > 0:
        search_df = search_df.sort_values(
            "selection_score_stability_penalized",
            ascending=False,
            na_position="last",
        ).reset_index(drop=True)

    return {
        "best_model_type": best_obj["model_type"],
        "best_params": best_obj["params"],
        "best_score": best_score,
        "search_df": search_df,
        "fitted_pipeline": final_pipe,
        "feature_weight_df": final_weight_df,
        "feature_selection_df": final_selection_df,
        "selected_features": selected_features,
    }


def get_inner_oof_predictions_model_only(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    groups_train: np.ndarray,
    candidate_models: list[str],
    n_splits_inner: int = 3,
    protected_keep_cols: list[str] | None = None,
    feature_selection_mode: str = "f_regression_topk",
    top_k_after_sparse: int | None = 100,
):
    """
    Diagnostic train-inner OOF predictions using the same paper-style fold-safe selection.
    """
    inner_splits, inner_cv_type = make_inner_cv_splits(
        X=X_train,
        y=y_train,
        groups=groups_train,
        n_splits=n_splits_inner,
    )

    oof = pd.Series(index=X_train.index, dtype=float)

    for tr_idx, va_idx in inner_splits:
        X_tr = X_train.iloc[tr_idx].copy()
        y_tr = y_train.iloc[tr_idx].copy()
        X_va = X_train.iloc[va_idx].copy()

        fit_result = fit_best_model_only(
            X_train=X_tr,
            y_train=y_tr,
            groups_train=groups_train[tr_idx],
            candidate_models=candidate_models,
            n_splits_inner=n_splits_inner,
            protected_keep_cols=protected_keep_cols,
            feature_selection_mode=feature_selection_mode,
            top_k_after_sparse=top_k_after_sparse,
        )

        selected_features = fit_result["selected_features"]
        X_va_sel = X_va.reindex(columns=selected_features).copy()

        best_pipe = fit_result["fitted_pipeline"]
        pred_va = predict_1d(best_pipe, X_va_sel)

        oof.iloc[va_idx] = pred_va

    return oof

In [19]:
def generate_weight_grid(n_models: int, step: float = 0.1):
    """
    Generate nonnegative weight tuples that sum to 1.
    Example:
      n_models=2, step=0.5 -> [(0.0,1.0),(0.5,0.5),(1.0,0.0)]
    """
    if n_models < 1:
        raise ValueError("n_models must be >= 1")
    if step <= 0 or step > 1:
        raise ValueError("step must be in (0, 1]")

    step_int = int(round(1 / step))
    if not np.isclose(step_int * step, 1.0):
        raise ValueError("step must divide 1.0 exactly, e.g. 0.5, 0.25, 0.2, 0.1")

    grids = []

    def backtrack(prefix, remaining, depth):
        if depth == n_models - 1:
            grids.append(tuple(prefix + [remaining / step_int]))
            return
        for v in range(remaining + 1):
            backtrack(prefix + [v / step_int], remaining - v, depth + 1)

    backtrack([], step_int, 0)
    return grids

In [20]:
def encode_clinical_train_valid(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, list[str]]:
    """
    Clinical을 항상 fold 내부에서 encoding한다.
    반환:
      - encoded X_train
      - encoded X_valid
      - encoded clinical column names
    """
    base_clin_cols = [c for c in get_clinical_columns() if c in X_train.columns]
    if len(base_clin_cols) == 0:
        return X_train, X_valid, []

    tr_clin = X_train.loc[:, base_clin_cols].copy()
    va_clin = X_valid.loc[:, [c for c in base_clin_cols if c in X_valid.columns]].copy()

    tr_other = X_train.drop(columns=base_clin_cols, errors="ignore").copy()
    va_other = X_valid.drop(columns=base_clin_cols, errors="ignore").copy()

    if "Age" in tr_clin.columns:
        tr_clin["Age"] = pd.to_numeric(tr_clin["Age"], errors="coerce")
    if "Age" in va_clin.columns:
        va_clin["Age"] = pd.to_numeric(va_clin["Age"], errors="coerce")

    cat_cols = [c for c in ["Gender", "Level"] if c in tr_clin.columns]

    if len(cat_cols) > 0:
        tr_clin_enc = pd.get_dummies(
            tr_clin,
            columns=cat_cols,
            dummy_na=True,
            dtype=float,
        )
        va_clin_enc = pd.get_dummies(
            va_clin,
            columns=cat_cols,
            dummy_na=True,
            dtype=float,
        )
        va_clin_enc = va_clin_enc.reindex(columns=tr_clin_enc.columns, fill_value=0.0)
    else:
        tr_clin_enc = tr_clin.copy()
        va_clin_enc = va_clin.copy()

    tr_clin_enc = tr_clin_enc.apply(pd.to_numeric, errors="coerce")
    va_clin_enc = va_clin_enc.apply(pd.to_numeric, errors="coerce")

    encoded_clin_cols = tr_clin_enc.columns.tolist()

    X_train_out = pd.concat([tr_other, tr_clin_enc], axis=1)
    X_valid_out = pd.concat([va_other, va_clin_enc], axis=1)

    return X_train_out, X_valid_out, encoded_clin_cols

In [21]:
def run_single_omics_train_oof_cv(
    X: pd.DataFrame,
    y: pd.Series,
    tissue: str,
    combo: str,
    tp: int,
    train_ids: list[str],
    candidate_models: list[str],
    feature_mode: str,
    clinical_mode: str = "light",
    feature_selection_mode: str = "f_regression_topk",
    min_obs_frac: float = MIN_OBS_FRAC,
    top_k_after_sparse: int | None = 100,
):
    """
    TRAIN-ONLY paper-style single-omics evaluation.

    Main metric:
    - outer-CV OOF R² computed only on TRAIN_IDS

    Leakage control:
    - outer-valid y is never used for sparse filtering, feature selection, feature weighting, or tuning
    - inner feature selection is fitted only on inner-train folds
    - all OOF predictions are generated from models that did not train on that patient
    """
    train_ids_in = [pid for pid in train_ids if pid in X.index]
    X_all = X.loc[train_ids_in].copy()
    y_all_train = y.loc[train_ids_in].copy()

    print("\n[TRAIN-ONLY OOF CV CHECK]")
    print("clinical_mode:", clinical_mode)
    print("feature_selection_mode:", feature_selection_mode)
    print("top_k_after_sparse:", top_k_after_sparse)
    print("X_all shape:", X_all.shape)
    print("y_all_train shape:", y_all_train.shape)
    print("n unique train ids:", X_all.index.nunique())

    delta_cols = [c for c in X_all.columns if "_d" in str(c)]
    clin_cols_present = [c for c in get_clinical_columns() if c in X_all.columns]
    print("delta cols count:", len(delta_cols))
    print("clinical cols present:", clin_cols_present)

    if len(X_all) < N_SPLITS_OUTER:
        raise ValueError("not enough training samples for outer CV")

    outer_splits, outer_cv_type = make_outer_cv_splits(
        X=X_all,
        y=y_all_train,
        groups=X_all.index.to_numpy(),
        n_splits=N_SPLITS_OUTER,
    )

    print("outer_cv_type:", outer_cv_type)
    print("n_outer_folds:", len(outer_splits))

    oof_pred = pd.Series(index=X_all.index, dtype=float)
    fold_metric_rows = []
    oof_rows = []
    search_dfs = []
    feature_dfs = []
    feature_weight_dfs = []
    feature_selection_dfs = []

    protected_base_cols = get_clinical_columns() if clinical_mode == "light" else []

    for outer_fold, (tr_idx, va_idx) in enumerate(outer_splits, start=1):
        X_tr_raw = X_all.iloc[tr_idx].copy()
        y_tr = y_all_train.iloc[tr_idx].copy()
        X_va_raw = X_all.iloc[va_idx].copy()
        y_va = y_all_train.iloc[va_idx].copy()

        print(f"\n[OUTER FOLD {outer_fold}]")
        print("raw train shape:", X_tr_raw.shape, "| valid shape:", X_va_raw.shape)

        X_tr_f, X_va_f = filter_sparse_features_train_test(
            X_train=X_tr_raw,
            X_valid=X_va_raw,
            min_obs_frac=min_obs_frac,
            protected_keep_cols=protected_base_cols,
        )

        n_before_sparse = X_tr_raw.shape[1]
        n_after_sparse = X_tr_f.shape[1]

        if X_tr_f.shape[1] == 0:
            raise ValueError(f"outer_fold={outer_fold}: no features left after sparse filtering")

        if clinical_mode == "light":
            X_tr_f, X_va_f, encoded_clin_cols = encode_clinical_train_valid(
                X_train=X_tr_f,
                X_valid=X_va_f,
            )
            protected_keep_cols = encoded_clin_cols
        else:
            encoded_clin_cols = []
            protected_keep_cols = []

        non_numeric_cols = X_tr_f.select_dtypes(exclude=[np.number, "bool"]).columns.tolist()
        if len(non_numeric_cols) > 0:
            raise TypeError(f"outer_fold={outer_fold}: non-numeric columns remain: {non_numeric_cols[:20]}")

        fit_result = fit_best_model_only(
            X_train=X_tr_f,
            y_train=y_tr,
            groups_train=X_tr_f.index.to_numpy(),
            candidate_models=candidate_models,
            n_splits_inner=N_SPLITS_INNER,
            protected_keep_cols=protected_keep_cols,
            feature_selection_mode=feature_selection_mode,
            top_k_after_sparse=top_k_after_sparse,
        )

        selected_features = fit_result["selected_features"]
        X_tr_model = X_tr_f.loc[:, selected_features].copy()
        X_va_model = X_va_f.reindex(columns=selected_features).copy()

        best_pipe = fit_result["fitted_pipeline"]

        pred_tr = predict_1d(best_pipe, X_tr_model)
        pred_va = predict_1d(best_pipe, X_va_model)

        oof_pred.iloc[va_idx] = pred_va

        train_r2 = float(r2_score(y_tr, pred_tr)) if len(y_tr) >= 2 else np.nan
        valid_r2 = float(r2_score(y_va, pred_va)) if len(y_va) >= 2 else np.nan
        train_mae = float(mean_absolute_error(y_tr, pred_tr))
        valid_mae = float(mean_absolute_error(y_va, pred_va))

        print(
            f"fold={outer_fold} | best={fit_result['best_model_type']} | "
            f"valid_r2={valid_r2:.4f} | train_r2={train_r2:.4f} | "
            f"n_features={len(selected_features)}"
        )

        fold_metric_rows.append({
            "outer_fold": outer_fold,
            "outer_cv_type": outer_cv_type,
            "clinical_mode": clinical_mode,
            "feature_selection_mode": feature_selection_mode,
            "tissue": tissue,
            "combo": combo,
            "tp": tp,
            "best_model_type": fit_result["best_model_type"],
            "best_params": json.dumps(fit_result["best_params"], default=str),
            "best_inner_oof_r2": fit_result["best_score"],
            "train_r2": train_r2,
            "valid_r2": valid_r2,
            "train_mae": train_mae,
            "valid_mae": valid_mae,
            "n_train": len(y_tr),
            "n_valid": len(y_va),
            "n_features_before_sparse": n_before_sparse,
            "n_features_after_sparse": n_after_sparse,
            "n_features_after_selection": len(selected_features),
            "top_k_after_sparse": top_k_after_sparse,
        })

        fold_pred_df = pd.DataFrame({
            "Patient": X_va_model.index.astype(str),
            "outer_fold": outer_fold,
            "y_true": y_va.values,
            "y_pred_oof": pred_va,
            "clinical_mode": clinical_mode,
            "feature_selection_mode": feature_selection_mode,
            "tissue": tissue,
            "combo": combo,
            "tp": tp,
            "best_model_type": fit_result["best_model_type"],
            "top_k_after_sparse": top_k_after_sparse,
        })
        oof_rows.append(fold_pred_df)

        search_df = fit_result["search_df"].copy()
        search_df["outer_fold"] = outer_fold
        search_df["clinical_mode"] = clinical_mode
        search_df["feature_selection_mode_outer"] = feature_selection_mode
        search_df["tissue"] = tissue
        search_df["combo"] = combo
        search_df["tp"] = tp
        search_dfs.append(search_df)

        feature_info_df = extract_final_feature_info(best_pipe).copy()
        feature_info_df["outer_fold"] = outer_fold
        feature_info_df["clinical_mode"] = clinical_mode
        feature_info_df["feature_selection_mode"] = feature_selection_mode
        feature_info_df["tissue"] = tissue
        feature_info_df["combo"] = combo
        feature_info_df["tp"] = tp
        feature_dfs.append(feature_info_df)

        fw_df = fit_result.get("feature_weight_df", pd.DataFrame()).copy()
        if isinstance(fw_df, pd.DataFrame) and len(fw_df) > 0:
            fw_df["outer_fold"] = outer_fold
            fw_df["clinical_mode"] = clinical_mode
            fw_df["feature_selection_mode"] = feature_selection_mode
            fw_df["tissue"] = tissue
            fw_df["combo"] = combo
            fw_df["tp"] = tp
            feature_weight_dfs.append(fw_df)

        fs_df = fit_result.get("feature_selection_df", pd.DataFrame()).copy()
        if isinstance(fs_df, pd.DataFrame) and len(fs_df) > 0:
            fs_df["outer_fold"] = outer_fold
            fs_df["clinical_mode"] = clinical_mode
            fs_df["feature_selection_mode"] = feature_selection_mode
            fs_df["tissue"] = tissue
            fs_df["combo"] = combo
            fs_df["tp"] = tp
            feature_selection_dfs.append(fs_df)

    valid_mask = oof_pred.notna()
    if valid_mask.sum() >= 2:
        oof_r2 = float(r2_score(y_all_train.loc[valid_mask], oof_pred.loc[valid_mask]))
        oof_mae = float(mean_absolute_error(y_all_train.loc[valid_mask], oof_pred.loc[valid_mask]))
    else:
        oof_r2 = np.nan
        oof_mae = np.nan

    fold_metrics_df = pd.DataFrame(fold_metric_rows)
    oof_pred_df = pd.concat(oof_rows, ignore_index=True) if len(oof_rows) > 0 else pd.DataFrame()
    search_all_df = pd.concat(search_dfs, ignore_index=True) if len(search_dfs) > 0 else pd.DataFrame()
    feature_all_df = pd.concat(feature_dfs, ignore_index=True) if len(feature_dfs) > 0 else pd.DataFrame()
    feature_weight_all_df = pd.concat(feature_weight_dfs, ignore_index=True) if len(feature_weight_dfs) > 0 else pd.DataFrame()
    feature_selection_all_df = pd.concat(feature_selection_dfs, ignore_index=True) if len(feature_selection_dfs) > 0 else pd.DataFrame()

    mean_valid_r2 = float(np.nanmean(fold_metrics_df["valid_r2"])) if len(fold_metrics_df) else np.nan
    std_valid_r2 = float(np.nanstd(fold_metrics_df["valid_r2"])) if len(fold_metrics_df) else np.nan
    mean_train_r2 = float(np.nanmean(fold_metrics_df["train_r2"])) if len(fold_metrics_df) else np.nan
    mean_valid_mae = float(np.nanmean(fold_metrics_df["valid_mae"])) if len(fold_metrics_df) else np.nan
    mean_train_mae = float(np.nanmean(fold_metrics_df["train_mae"])) if len(fold_metrics_df) else np.nan

    # Fit one final model on the full TRAIN_IDS set for tracing/deployment.
    # This model is not used to compute OOF R².
    X_full_f, _ = filter_sparse_features_train_test(
        X_train=X_all,
        X_valid=X_all,
        min_obs_frac=min_obs_frac,
        protected_keep_cols=protected_base_cols,
    )

    if clinical_mode == "light":
        X_full_f, _, encoded_clin_cols_full = encode_clinical_train_valid(
            X_train=X_full_f,
            X_valid=X_full_f,
        )
        protected_keep_cols_full = encoded_clin_cols_full
    else:
        protected_keep_cols_full = []

    final_fit_result = fit_best_model_only(
        X_train=X_full_f,
        y_train=y_all_train,
        groups_train=X_full_f.index.to_numpy(),
        candidate_models=candidate_models,
        n_splits_inner=N_SPLITS_INNER,
        protected_keep_cols=protected_keep_cols_full,
        feature_selection_mode=feature_selection_mode,
        top_k_after_sparse=top_k_after_sparse,
    )

    final_selected = final_fit_result["selected_features"]
    X_full_model = X_full_f.loc[:, final_selected].copy()
    final_pipe = final_fit_result["fitted_pipeline"]
    final_train_pred = predict_1d(final_pipe, X_full_model)

    final_train_r2 = float(r2_score(y_all_train, final_train_pred)) if len(y_all_train) >= 2 else np.nan
    final_train_mae = float(mean_absolute_error(y_all_train, final_train_pred))

    final_train_pred_df = pd.DataFrame({
        "Patient": X_full_model.index.astype(str),
        "y_true": y_all_train.values,
        "y_pred_final_train_model": final_train_pred,
        "clinical_mode": clinical_mode,
        "feature_selection_mode": feature_selection_mode,
        "tissue": tissue,
        "combo": combo,
        "tp": tp,
        "best_model_type": final_fit_result["best_model_type"],
        "top_k_after_sparse": top_k_after_sparse,
    })

    final_feature_df = extract_final_feature_info(final_pipe).copy()

    metrics = {
        "selection_basis": "outer_cv_oof_r2_train_only_fold_safe_feature_selection",
        "outer_cv_type": outer_cv_type,
        "n_outer_folds": len(outer_splits),
        "n_train": len(X_all),
        "n_features_input": X.shape[1],
        "n_delta_features_input": len(delta_cols),
        "n_clinical_input": len(clin_cols_present),
        "oof_r2": oof_r2,
        "oof_mae": oof_mae,
        "mean_valid_r2": mean_valid_r2,
        "std_valid_r2": std_valid_r2,
        "mean_train_r2": mean_train_r2,
        "mean_valid_mae": mean_valid_mae,
        "mean_train_mae": mean_train_mae,
        "generalization_gap_mean_train_minus_valid": mean_train_r2 - mean_valid_r2,
        "final_full_train_best_model_type": final_fit_result["best_model_type"],
        "final_full_train_best_score_inner_oof_r2": final_fit_result["best_score"],
        "final_full_train_r2": final_train_r2,
        "final_full_train_mae": final_train_mae,
        "n_features_final_full_train": len(final_selected),
        "top_k_after_sparse": top_k_after_sparse,
    }

    return {
        "metrics": metrics,
        "fold_metrics_df": fold_metrics_df,
        "oof_pred_df": oof_pred_df,
        "search_df": search_all_df,
        "feature_df": feature_all_df,
        "feature_weight_df": feature_weight_all_df,
        "feature_selection_df": feature_selection_all_df,
        "final_train_pred_df": final_train_pred_df,
        "final_feature_df": final_feature_df,
    }

In [22]:
def run_one_single_omics_train_experiment(
    tissue: str,
    combo: str,
    tp: int,
    y_all: pd.Series,
    feature_mode: str,
    candidate_models: list[str],
    clinical_mode: str = "light",
    feature_selection_mode: str = "f_regression_topk",
    top_k_after_sparse_override: int | None = 100,
):
    feature_path = build_feature_path(
        feature_mode=feature_mode,
        tissue=tissue,
        combo=combo,
        tp=tp,
    )

    if not feature_path.exists():
        print("missing:", feature_path)
        return None

    print(
        f"\n[RUN-TRAIN-OOF] feature_mode={feature_mode}, "
        f"clinical_mode={clinical_mode}, selection={feature_selection_mode}, "
        f"tissue={tissue}, combo={combo}, tp={tp}"
    )
    print("feature_path:", feature_path)

    X = load_feature_csv(feature_path)
    raw_feature_signature = dataframe_content_signature(X)
    raw_feature_columns_hash = hashlib.md5("|".join(map(str, sorted(X.columns))).encode("utf-8")).hexdigest()
    X, y = align_xy(X, y_all)

    print("\n[EXPERIMENT START]")
    print("feature_mode:", feature_mode)
    print("clinical_mode:", clinical_mode)
    print("feature_selection_mode:", feature_selection_mode)
    print("tissue:", tissue, "| combo:", combo, "| tp:", tp)
    print("X shape before clinical:", X.shape)
    print("y shape:", y.shape)

    delta_cols = [c for c in X.columns if "_d" in str(c)]
    print("n_delta_features:", len(delta_cols))
    print("delta examples:", delta_cols[:10])

    if clinical_mode == "light":
        X = merge_with_light_clinical(
            X_feat=X,
            tissue=tissue,
            combo=combo,
            tp=tp,
        )
        assert_no_forbidden_proxy_columns(X, use_light_clinical=True)
    elif clinical_mode == "omics_only":
        assert_no_forbidden_proxy_columns(X, use_light_clinical=False)
    else:
        raise ValueError(f"Unknown clinical_mode: {clinical_mode}")

    delta_cols = [c for c in X.columns if "_d" in str(c)]
    clinical_cols_present = [c for c in get_clinical_columns() if c in X.columns]
    train_ids_in = [pid for pid in TRAIN_IDS if pid in X.index]

    base_skip = {
        "status": "skipped",
        "experiment_tag": EXPERIMENT_TAG,
        "use_feature_weighting": USE_FEATURE_WEIGHTING,
        "feature_weight_score_mode": FEATURE_WEIGHT_SCORE_MODE if USE_FEATURE_WEIGHTING else "none",
        "feature_weight_min": FEATURE_WEIGHT_MIN if USE_FEATURE_WEIGHTING else np.nan,
        "feature_weight_max": FEATURE_WEIGHT_MAX if USE_FEATURE_WEIGHTING else np.nan,
        "feature_mode": feature_mode,
        "clinical_mode": clinical_mode,
        "feature_selection_mode": feature_selection_mode,
        "tissue": tissue,
        "combo": combo,
        "tp": tp,
        "reason": None,
        "n_train_available": len(train_ids_in),
        "oof_r2": np.nan,
        "oof_mae": np.nan,
        "mean_valid_r2": np.nan,
        "std_valid_r2": np.nan,
        "mean_train_r2": np.nan,
        "mean_valid_mae": np.nan,
        "mean_train_mae": np.nan,
        "generalization_gap_mean_train_minus_valid": np.nan,
        "final_full_train_best_model_type": None,
        "final_full_train_best_score_inner_oof_r2": np.nan,
        "final_full_train_r2": np.nan,
        "final_full_train_mae": np.nan,
        "n_features_input": X.shape[1],
        "raw_feature_signature": raw_feature_signature,
        "raw_feature_columns_hash": raw_feature_columns_hash,
        "feature_path": str(feature_path),
        "n_delta_features_input": len(delta_cols),
        "n_clinical_input": len(clinical_cols_present),
        "n_features_final_full_train": np.nan,
        "top_k_after_sparse": top_k_after_sparse_override,
        "selection_basis": "not_run",
    }

    if len(train_ids_in) < N_SPLITS_OUTER:
        print("skip: not enough training patients after TRAIN_IDS filter")
        out = base_skip.copy()
        out["reason"] = "not enough training patients after TRAIN_IDS filter"
        return out

    top_k_after_sparse = top_k_after_sparse_override if top_k_after_sparse_override is not None else 100

    result = run_single_omics_train_oof_cv(
        X=X,
        y=y,
        tissue=tissue,
        combo=combo,
        tp=tp,
        train_ids=TRAIN_IDS,
        candidate_models=candidate_models,
        feature_mode=feature_mode,
        clinical_mode=clinical_mode,
        feature_selection_mode=feature_selection_mode,
        min_obs_frac=MIN_OBS_FRAC,
        top_k_after_sparse=top_k_after_sparse,
    )

    prefix = f"{feature_mode}_{clinical_mode}_{feature_selection_mode}_{tissue}_{combo}_tp{tp}_topk{top_k_after_sparse}"

    metrics = result["metrics"].copy()
    metrics.update({
        "status": "ok",
        "experiment_tag": EXPERIMENT_TAG,
        "use_feature_weighting": USE_FEATURE_WEIGHTING,
        "feature_weight_score_mode": FEATURE_WEIGHT_SCORE_MODE if USE_FEATURE_WEIGHTING else "none",
        "feature_weight_min": FEATURE_WEIGHT_MIN if USE_FEATURE_WEIGHTING else np.nan,
        "feature_weight_max": FEATURE_WEIGHT_MAX if USE_FEATURE_WEIGHTING else np.nan,
        "feature_mode": feature_mode,
        "clinical_mode": clinical_mode,
        "feature_selection_mode": feature_selection_mode,
        "tissue": tissue,
        "combo": combo,
        "tp": tp,
        "reason": None,
        "raw_feature_signature": raw_feature_signature,
        "raw_feature_columns_hash": raw_feature_columns_hash,
        "feature_path": str(feature_path),
    })

    pd.DataFrame([metrics]).to_csv(
        DETAIL_DIR / f"{prefix}_train_summary.csv",
        index=False
    )
    result["fold_metrics_df"].to_csv(
        DETAIL_DIR / f"{prefix}_train_fold_metrics.csv",
        index=False
    )
    result["oof_pred_df"].to_csv(
        DETAIL_DIR / f"{prefix}_train_oof_predictions.csv",
        index=False
    )
    result["search_df"].to_csv(
        DETAIL_DIR / f"{prefix}_train_search_results.csv",
        index=False
    )
    result["feature_df"].to_csv(
        DETAIL_DIR / f"{prefix}_train_outer_fold_features.csv",
        index=False
    )
    result["final_train_pred_df"].to_csv(
        DETAIL_DIR / f"{prefix}_final_full_train_predictions.csv",
        index=False
    )
    result["final_feature_df"].to_csv(
        DETAIL_DIR / f"{prefix}_final_full_train_features.csv",
        index=False
    )

    if isinstance(result.get("feature_weight_df", None), pd.DataFrame) and len(result["feature_weight_df"]) > 0:
        result["feature_weight_df"].to_csv(
            DETAIL_DIR / f"{prefix}_train_feature_weights.csv",
            index=False
        )

    if isinstance(result.get("feature_selection_df", None), pd.DataFrame) and len(result["feature_selection_df"]) > 0:
        result["feature_selection_df"].to_csv(
            DETAIL_DIR / f"{prefix}_train_feature_selection_scores.csv",
            index=False
        )

    return metrics

In [23]:
# ==========================================
# Sanity check before running Experiment B
# ==========================================
y_all = load_target(TARGET_PATH)

for tissue, combo, tp in product(TISSUES, COMBOS, TIMEPOINTS):
    feature_path = build_feature_path(feature_mode="omics", tissue=tissue, combo=combo, tp=tp)
    if not feature_path.exists():
        print("missing:", feature_path.name)
        continue

    X = load_feature_csv(feature_path)
    X, y = align_xy(X, y_all)
    
    

    delta_cols = [c for c in X.columns if "_d" in str(c)]
    print(
        f"{feature_path.name}: shape={X.shape}, delta_cols={len(delta_cols)}"
    )

    if len(delta_cols) > 0:
        print("  delta examples:", delta_cols[:10])

x_omics_csf_A_24.csv: shape=(103, 438), delta_cols=0
x_omics_csf_A_48.csv: shape=(103, 438), delta_cols=0
x_omics_csf_A_72.csv: shape=(103, 438), delta_cols=0
x_omics_csf_A_96.csv: shape=(103, 438), delta_cols=0
x_omics_csf_A_120.csv: shape=(103, 438), delta_cols=0
x_omics_csf_B_24.csv: shape=(83, 749), delta_cols=0
x_omics_csf_B_48.csv: shape=(83, 749), delta_cols=0
x_omics_csf_B_72.csv: shape=(83, 749), delta_cols=0
x_omics_csf_B_96.csv: shape=(83, 749), delta_cols=0
x_omics_csf_B_120.csv: shape=(83, 749), delta_cols=0
x_omics_csf_C_24.csv: shape=(39, 312), delta_cols=0
x_omics_csf_C_48.csv: shape=(39, 312), delta_cols=0
x_omics_csf_C_72.csv: shape=(39, 312), delta_cols=0
x_omics_csf_C_96.csv: shape=(39, 312), delta_cols=0
x_omics_csf_C_120.csv: shape=(39, 312), delta_cols=0
x_omics_ser_A_24.csv: shape=(108, 438), delta_cols=0
x_omics_ser_A_48.csv: shape=(108, 438), delta_cols=0
x_omics_ser_A_72.csv: shape=(108, 438), delta_cols=0
x_omics_ser_A_96.csv: shape=(108, 438), delta_cols=0
x_omics_ser_A_120.csv: shape=(108, 438), delta_cols=0
x_omics_ser_B_24.csv: shape=(108, 749), delta_cols=0
x_omics_ser_B_48.csv: shape=(108, 749), delta_cols=0
x_omics_ser_B_72.csv: shape=(108, 749), delta_cols=0
x_omics_ser_B_96.csv: shape=(108, 749), delta_cols=0
x_omics_ser_B_120.csv: shape=(108, 749), delta_cols=0
x_omics_ser_C_24.csv: shape=(38, 312), delta_cols=0
x_omics_ser_C_48.csv: shape=(38, 312), delta_cols=0
x_omics_ser_C_72.csv: shape=(38, 312), delta_cols=0
x_omics_ser_C_96.csv: shape=(38, 312), delta_cols=0
x_omics_ser_C_120.csv: shape=(38, 312), delta_cols=0

In [24]:
y_all = load_target(TARGET_PATH)

# Paper-style single-omics TRAIN-ONLY run.
# This produces outer-CV OOF results on TRAIN_IDS only.
# v11 rescue-expansion route table:
# - Keep all A/B/C combos and all 24/48/72/96/120h timepoints.
# - Restore v9-compatible candidate-model pools for critical routes.
# - Expand only high-potential route neighborhoods from v9/v10 OOF results.
# - The main comparable metric to the paper is OOF R², not train_r2/final_full_train_r2.
FEATURE_MODE_TO_RUN = "omics"


def _add_route(rows, *, tissue, combo, tp, top_k, feature_selection_mode, candidate_models, priority, reason):
    """Append one route while keeping candidate_models filtered to available model families."""
    candidate_models = [m for m in candidate_models if m in MODEL_TYPES]
    if len(candidate_models) == 0:
        return
    rows.append({
        "feature_mode": FEATURE_MODE_TO_RUN,
        "clinical_mode": "light",
        "feature_selection_mode": feature_selection_mode,
        "combo": combo,
        "top_k": int(top_k),
        "tissue": tissue,
        "tp": int(tp),
        "candidate_models": candidate_models,
        "priority": priority,
        "reason": reason,
    })


def _candidate_pool_v9_compatible(tissue: str, combo: str, tp: int) -> list[str]:
    """
    Important: this intentionally restores the v9-style candidate pools.
    The previous targeted version used many single-model routes, which made
    the critical v9 routes non-equivalent.
    """
    tissue = str(tissue).lower()
    combo = str(combo)
    tp = int(tp)

    if combo == "A":
        if tissue == "ser" and tp in [72, 96]:
            return ["svr_linear", "ridge", "elasticnet"]
        if tissue == "csf" and tp == 72:
            return ["svr_linear", "ridge", "gbr"]
        if tissue == "csf" and tp == 96:
            return ["svr_linear", "ridge", "elasticnet"]
        return ["ridge"]

    if combo == "B":
        if tissue == "ser" and tp in [96, 120]:
            return ["ridge", "elasticnet"]
        if tissue == "csf" and tp in [48, 72, 96]:
            return ["ridge", "elasticnet"]
        return ["ridge"]

    if combo == "C":
        if tissue == "ser" and tp == 24:
            return ["xgboost", "gbr", "ridge"]
        if tissue == "csf" and tp == 120:
            return ["ridge", "elasticnet", "pls"]
        return ["ridge"]

    return ["ridge"]


# Build explicit v11 rescue-expansion route table.
V11_ROUTE_ROWS = []

# -------------------------------
# A-family: strong/important single-omics signal.
# Start from v9 coverage and add targeted top-k expansion around strong regions.
# -------------------------------
A_BASE_TOPK = [40, 80, 120]
A_EXTRA_TOPK = {
    ("ser", 72): [100, 140],
    ("ser", 96): [100, 140, 160],
    ("csf", 72): [60, 100],
    ("csf", 96): [30, 60, 100],
}

for tissue in ["csf", "ser"]:
    for tp in [24, 48, 72, 96, 120]:
        pool = _candidate_pool_v9_compatible(tissue, "A", tp)
        topks = sorted(set(A_BASE_TOPK + A_EXTRA_TOPK.get((tissue, tp), [])))
        for top_k in topks:
            for fs in ["f_regression_topk", "corr_topk"]:
                is_critical = (tissue == "ser" and tp == 96 and top_k in [120, 140])
                is_high = (tissue == "ser" and tp in [72, 96]) or (tissue == "csf" and tp in [72, 96])
                _add_route(
                    V11_ROUTE_ROWS,
                    tissue=tissue,
                    combo="A",
                    tp=tp,
                    top_k=top_k,
                    feature_selection_mode=fs,
                    candidate_models=pool,
                    priority="critical" if is_critical else ("high" if is_high else "normal"),
                    reason="v11 A rescue-expansion: v9-compatible model pool + expanded top_k around strong A routes",
                )

# -------------------------------
# B-family: keep minimal coverage. B was weak, so do not spend the budget here.
# Use v9-compatible pools where B previously allowed elasticnet.
# -------------------------------
B_SELECTED = {
    ("csf", 24): ("f_regression_topk", 40),
    ("csf", 48): ("f_regression_topk", 40),
    ("csf", 72): ("f_regression_topk", 40),
    ("csf", 96): ("f_regression_topk", 40),
    ("csf", 120): ("f_regression_topk", 40),
    ("ser", 24): ("f_regression_topk", 40),
    ("ser", 48): ("f_regression_topk", 80),
    ("ser", 72): ("f_regression_topk", 40),
    ("ser", 96): ("f_regression_topk", 80),
    ("ser", 120): ("f_regression_topk", 40),
}
for (tissue, tp), (fs, top_k) in B_SELECTED.items():
    _add_route(
        V11_ROUTE_ROWS,
        tissue=tissue,
        combo="B",
        tp=tp,
        top_k=top_k,
        feature_selection_mode=fs,
        candidate_models=_candidate_pool_v9_compatible(tissue, "B", tp),
        priority="low" if (tissue, tp) in [("csf", 24), ("csf", 120), ("ser", 24), ("ser", 72)] else "normal",
        reason="v11 B minimal coverage: v9-compatible pool but no broad expansion",
    )

# -------------------------------
# C-family: rescue ser C 24h and expand csf C around new v10 targeted signal.
# -------------------------------
# ser C 24h: critical. Restore v9 candidate pool xgboost+gbr+ridge and expand top_k.
for top_k in [10, 20, 30, 40, 50, 60]:
    for fs in ["f_regression_topk", "corr_topk"]:
        _add_route(
            V11_ROUTE_ROWS,
            tissue="ser",
            combo="C",
            tp=24,
            top_k=top_k,
            feature_selection_mode=fs,
            candidate_models=_candidate_pool_v9_compatible("ser", "C", 24),
            priority="critical" if (fs == "f_regression_topk" and top_k in [30, 40, 50]) else "high",
            reason="v11 ser C 24h rescue: restore v9 candidate pool xgboost+gbr+ridge and expand top_k",
        )

# ser C non-24h: stable ridge route with small top_k neighborhood.
for tp in [48, 72, 96, 120]:
    for top_k in [5, 10, 15, 20]:
        _add_route(
            V11_ROUTE_ROWS,
            tissue="ser",
            combo="C",
            tp=tp,
            top_k=top_k,
            feature_selection_mode="f_regression_topk",
            candidate_models=_candidate_pool_v9_compatible("ser", "C", tp),
            priority="normal" if top_k == 10 else "low",
            reason="v11 ser C non-24h: ridge-focused top_k neighborhood around v9 stable top10 route",
        )

# csf C: include corr_topk because v10 targeted found csf C 24h corr_topk top20 as a strong route.
for tp in [24, 48, 72, 96, 120]:
    for top_k in [15, 20, 30]:
        for fs in ["f_regression_topk", "corr_topk"]:
            _add_route(
                V11_ROUTE_ROWS,
                tissue="csf",
                combo="C",
                tp=tp,
                top_k=top_k,
                feature_selection_mode=fs,
                candidate_models=_candidate_pool_v9_compatible("csf", "C", tp),
                priority="high" if (tp in [24, 120] and top_k == 20) else "normal",
                reason="v11 csf C expansion: include corr_topk and top_k neighborhood around 20",
            )

# Deduplicate defensively.
_seen = set()
_deduped = []
for row in V11_ROUTE_ROWS:
    key = (
        row["feature_mode"], row["clinical_mode"], row["feature_selection_mode"],
        row["combo"], row["top_k"], row["tissue"], row["tp"], tuple(row["candidate_models"]),
    )
    if key not in _seen:
        _seen.add(key)
        _deduped.append(row)
V11_ROUTE_ROWS = _deduped

jobs = V11_ROUTE_ROWS
print("n_jobs_to_run:", len(jobs))
job_manifest_df = pd.DataFrame(jobs)

# Coverage check: should be 30 = 2 tissues * 3 combos * 5 TPs.
coverage_df = (
    job_manifest_df[["tissue", "combo", "tp"]]
    .drop_duplicates()
    .sort_values(["tissue", "combo", "tp"])
    .reset_index(drop=True)
)
print("coverage rows:", len(coverage_df), "| expected:", len(TISSUES) * len(COMBOS) * len(TIMEPOINTS))
missing_coverage = []
for tissue in TISSUES:
    for combo in COMBOS:
        for tp in TIMEPOINTS:
            mask = (
                (coverage_df["tissue"] == tissue)
                & (coverage_df["combo"] == combo)
                & (coverage_df["tp"] == tp)
            )
            if not mask.any():
                missing_coverage.append((tissue, combo, tp))
print("missing coverage:", missing_coverage)
if len(missing_coverage) > 0:
    raise ValueError(f"Missing required tissue/combo/TP coverage: {missing_coverage}")

display(job_manifest_df.head(20))
print("candidate model counts:")
display(job_manifest_df["candidate_models"].astype(str).value_counts().reset_index(name="n_jobs"))
print("route priority counts:")
display(job_manifest_df["priority"].value_counts().reset_index(name="n_jobs"))
print("route counts by tissue/combo/priority:")
display(job_manifest_df.groupby(["tissue", "combo", "priority"]).size().reset_index(name="n_routes"))

job_manifest_path = SAVE_DIR / f"job_manifest_{EXPERIMENT_TAG}.csv"
coverage_check_path = SAVE_DIR / f"coverage_check_{EXPERIMENT_TAG}.csv"
route_summary_path = SAVE_DIR / f"route_summary_{EXPERIMENT_TAG}.csv"

job_manifest_df.to_csv(job_manifest_path, index=False)
coverage_df.to_csv(coverage_check_path, index=False)
job_manifest_df.groupby(["tissue", "combo", "priority"]).size().reset_index(name="n_routes").to_csv(route_summary_path, index=False)

print("saved job manifest:", job_manifest_path)
print("saved coverage check:", coverage_check_path)
print("saved route summary:", route_summary_path)

print("feature-selection routing counts:")
display(job_manifest_df["feature_selection_mode"].value_counts().reset_index(name="n_jobs"))

def run_one_single_omics_train_experiment_safe(job: dict, y_all: pd.Series):
    feature_mode = job["feature_mode"]
    clinical_mode = job["clinical_mode"]
    feature_selection_mode = job["feature_selection_mode"]
    tissue = job["tissue"]
    combo = job["combo"]
    tp = job["tp"]
    top_k = job["top_k"]
    candidate_models = job.get("candidate_models", MODEL_TYPES)

    try:
        result = run_one_single_omics_train_experiment(
            tissue=tissue,
            combo=combo,
            tp=tp,
            y_all=y_all,
            feature_mode=feature_mode,
            candidate_models=candidate_models,
            clinical_mode=clinical_mode,
            feature_selection_mode=feature_selection_mode,
            top_k_after_sparse_override=top_k,
        )
        if isinstance(result, dict):
            result["route_priority"] = job.get("priority")
            result["route_reason"] = job.get("reason")
        return result

    except Exception as e:
        print(
            f"[ERROR] feature_mode={feature_mode}, clinical={clinical_mode}, "
            f"selection={feature_selection_mode}, tissue={tissue}, "
            f"combo={combo}, tp={tp}, top_k={top_k} :: {e}"
        )
        return {
            "status": "failed",
            "experiment_tag": EXPERIMENT_TAG,
            "use_feature_weighting": USE_FEATURE_WEIGHTING,
            "feature_weight_score_mode": FEATURE_WEIGHT_SCORE_MODE if USE_FEATURE_WEIGHTING else "none",
            "feature_weight_min": FEATURE_WEIGHT_MIN if USE_FEATURE_WEIGHTING else np.nan,
            "feature_weight_max": FEATURE_WEIGHT_MAX if USE_FEATURE_WEIGHTING else np.nan,
            "feature_mode": feature_mode,
            "clinical_mode": clinical_mode,
            "feature_selection_mode": feature_selection_mode,
            "tissue": tissue,
            "combo": combo,
            "tp": tp,
            "reason": str(e),
            "route_priority": job.get("priority"),
            "route_reason": job.get("reason"),
            "n_train": np.nan,
            "oof_r2": np.nan,
            "oof_mae": np.nan,
            "mean_valid_r2": np.nan,
            "std_valid_r2": np.nan,
            "mean_train_r2": np.nan,
            "mean_valid_mae": np.nan,
            "mean_train_mae": np.nan,
            "generalization_gap_mean_train_minus_valid": np.nan,
            "final_full_train_best_model_type": None,
            "final_full_train_best_score_inner_oof_r2": np.nan,
            "final_full_train_r2": np.nan,
            "final_full_train_mae": np.nan,
            "n_features_input": np.nan,
            "raw_feature_signature": None,
            "raw_feature_columns_hash": None,
            "feature_path": str(build_feature_path(feature_mode, tissue, combo, tp)),
            "n_delta_features_input": np.nan,
            "n_clinical_input": np.nan,
            "n_features_final_full_train": np.nan,
            "top_k_after_sparse": top_k,
            "candidate_models": ",".join(candidate_models),
            "selection_basis": "outer_cv_oof_r2_train_only_fold_safe_feature_selection",
        }


rows = Parallel(
    n_jobs=N_JOBS_EXPERIMENT,
    backend="loky",
    verbose=10,
)(
    delayed(run_one_single_omics_train_experiment_safe)(job, y_all)
    for job in jobs
)

summary_df = pd.DataFrame(rows)

sort_cols = [
    "oof_r2", "mean_valid_r2", "mean_train_r2", "oof_mae",
    "final_full_train_best_score_inner_oof_r2",
]
for c in sort_cols:
    if c not in summary_df.columns:
        summary_df[c] = np.nan

if len(summary_df) > 0:
    summary_df = summary_df.sort_values(
        by=["status", "oof_r2", "mean_valid_r2"],
        ascending=[True, False, False],
        na_position="last",
    ).reset_index(drop=True)

out_path = SAVE_DIR / f"{FEATURE_MODE_TO_RUN}_paper_style_train_summary_{EXPERIMENT_TAG}.csv"
summary_df.to_csv(out_path, index=False)

print("saved:", out_path)

# Grouped summaries for OOF-R² analysis.
ok_df = summary_df[summary_df["status"].eq("ok")].copy()


def save_grouped_summary(df: pd.DataFrame, group_cols: list[str], name: str):
    if len(df) == 0:
        return None
    grouped = (
        df.groupby(group_cols, dropna=False)
          .agg(
              n=("oof_r2", "size"),
              mean_oof_r2=("oof_r2", "mean"),
              median_oof_r2=("oof_r2", "median"),
              best_oof_r2=("oof_r2", "max"),
              mean_valid_r2=("mean_valid_r2", "mean"),
              mean_train_r2=("mean_train_r2", "mean"),
              mean_gap=("generalization_gap_mean_train_minus_valid", "mean"),
          )
          .reset_index()
          .sort_values(["mean_oof_r2", "best_oof_r2"], ascending=False)
    )
    path = SAVE_DIR / f"{name}_{EXPERIMENT_TAG}.csv"
    grouped.to_csv(path, index=False)
    print("saved grouped summary:", path)
    return grouped


grouped_by_tissue = save_grouped_summary(ok_df, ["tissue"], "grouped_by_tissue")
grouped_by_tissue_combo = save_grouped_summary(ok_df, ["tissue", "combo"], "grouped_by_tissue_combo")
grouped_by_tissue_combo_tp = save_grouped_summary(ok_df, ["tissue", "combo", "tp"], "grouped_by_tissue_combo_tp")
grouped_by_tissue_combo_model = save_grouped_summary(ok_df, ["tissue", "combo", "final_full_train_best_model_type"], "grouped_by_tissue_combo_model")
grouped_by_tissue_combo_tp_model = save_grouped_summary(ok_df, ["tissue", "combo", "tp", "final_full_train_best_model_type"], "grouped_by_tissue_combo_tp_model")
grouped_by_tissue_combo_tp_selection = save_grouped_summary(ok_df, ["tissue", "combo", "tp", "feature_selection_mode"], "grouped_by_tissue_combo_tp_selection")

# Paper-style best row per tissue + combo + TP.
# This is the main table for comparing single-omics results by TP rather than using one global mean.
if len(ok_df) > 0:
    best_by_tissue_combo_tp = (
        ok_df.sort_values(["tissue", "combo", "tp", "oof_r2", "mean_valid_r2"], ascending=[True, True, True, False, False])
             .groupby(["tissue", "combo", "tp"], as_index=False)
             .first()
             .sort_values(["tissue", "combo", "tp"])
    )
    best_path = SAVE_DIR / f"paper_style_best_by_tissue_combo_tp_{EXPERIMENT_TAG}.csv"
    best_by_tissue_combo_tp.to_csv(best_path, index=False)
    print("saved paper-style best by tissue+combo+tp:", best_path)

    best_by_tissue_tp = (
        ok_df.sort_values(["tissue", "tp", "oof_r2", "mean_valid_r2"], ascending=[True, True, False, False])
             .groupby(["tissue", "tp"], as_index=False)
             .first()
             .sort_values(["tissue", "tp"])
    )
    best_tp_path = SAVE_DIR / f"paper_style_best_by_tissue_tp_{EXPERIMENT_TAG}.csv"
    best_by_tissue_tp.to_csv(best_tp_path, index=False)
    print("saved paper-style best by tissue+tp:", best_tp_path)

# Diagnostic: identify feature matrices that are identical across different TPs.
if "raw_feature_signature" in ok_df.columns:
    duplicate_feature_matrix_check = (
        ok_df.groupby(["tissue", "combo", "raw_feature_signature"], dropna=False)
             .agg(
                 n_rows=("oof_r2", "size"),
                 timepoints=("tp", lambda s: ",".join(map(str, sorted(set(s))))),
                 n_unique_tp=("tp", lambda s: len(set(s))),
                 feature_path_examples=("feature_path", lambda s: " | ".join(map(str, list(s)[:3]))),
             )
             .reset_index()
             .query("n_unique_tp > 1")
             .sort_values(["tissue", "combo", "n_unique_tp"], ascending=[True, True, False])
    )
    dup_path = SAVE_DIR / f"duplicate_feature_matrix_check_{EXPERIMENT_TAG}.csv"
    duplicate_feature_matrix_check.to_csv(dup_path, index=False)
    print("saved duplicate feature-matrix diagnostic:", dup_path)
    display(duplicate_feature_matrix_check.head(20))

print("\nTop 30 by TRAIN OOF R²:")
display_cols = [
    "status", "clinical_mode", "feature_selection_mode", "tissue", "combo", "tp",
    "top_k_after_sparse", "final_full_train_best_model_type",
    "oof_r2", "oof_mae", "mean_valid_r2", "std_valid_r2",
    "mean_train_r2", "generalization_gap_mean_train_minus_valid",
    "final_full_train_best_score_inner_oof_r2",
    "n_features_final_full_train",
]
optional_cols = ["route_priority", "route_reason"]
display_cols_existing = [c for c in display_cols + optional_cols if c in summary_df.columns]
display(summary_df[display_cols_existing].head(30))

print("\nBest by clinical/selection/tissue/combo/tp:")
best_by_group = (
    summary_df[summary_df["status"].eq("ok")]
    .sort_values("oof_r2", ascending=False)
    .groupby(["clinical_mode", "feature_selection_mode", "tissue", "combo", "tp"], as_index=False)
    .first()
)
display(best_by_group[[c for c in display_cols_existing if c in best_by_group.columns]].head(50))

n_jobs_to_run: 148
coverage rows: 30 | expected: 30
missing coverage: []

,feature_mode,clinical_mode,feature_selection_mode,combo,top_k,tissue,tp,candidate_models,priority,reason
0,omics,light,f_regression_topk,A,40,csf,24,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
1,omics,light,corr_topk,A,40,csf,24,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
2,omics,light,f_regression_topk,A,80,csf,24,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
3,omics,light,corr_topk,A,80,csf,24,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
4,omics,light,f_regression_topk,A,120,csf,24,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
5,omics,light,corr_topk,A,120,csf,24,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
6,omics,light,f_regression_topk,A,40,csf,48,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
7,omics,light,corr_topk,A,40,csf,48,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
8,omics,light,f_regression_topk,A,80,csf,48,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
9,omics,light,corr_topk,A,80,csf,48,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
10,omics,light,f_regression_topk,A,120,csf,48,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
11,omics,light,corr_topk,A,120,csf,48,[ridge],normal,v11 A rescue-expansion: v9-compatible model po...
12,omics,light,f_regression_topk,A,40,csf,72,"[svr_linear, ridge, gbr]",high,v11 A rescue-expansion: v9-compatible model po...
13,omics,light,corr_topk,A,40,csf,72,"[svr_linear, ridge, gbr]",high,v11 A rescue-expansion: v9-compatible model po...
14,omics,light,f_regression_topk,A,60,csf,72,"[svr_linear, ridge, gbr]",high,v11 A rescue-expansion: v9-compatible model po...
15,omics,light,corr_topk,A,60,csf,72,"[svr_linear, ridge, gbr]",high,v11 A rescue-expansion: v9-compatible model po...
16,omics,light,f_regression_topk,A,80,csf,72,"[svr_linear, ridge, gbr]",high,v11 A rescue-expansion: v9-compatible model po...
17,omics,light,corr_topk,A,80,csf,72,"[svr_linear, ridge, gbr]",high,v11 A rescue-expansion: v9-compatible model po...
18,omics,light,f_regression_topk,A,100,csf,72,"[svr_linear, ridge, gbr]",high,v11 A rescue-expansion: v9-compatible model po...
19,omics,light,corr_topk,A,100,csf,72,"[svr_linear, ridge, gbr]",high,v11 A rescue-expansion: v9-compatible model po...

candidate model counts:

                        candidate_models  n_jobs
0                              ['ridge']      81
1  ['svr_linear', 'ridge', 'elasticnet']      34
2            ['xgboost', 'gbr', 'ridge']      12
3         ['svr_linear', 'ridge', 'gbr']      10
4         ['ridge', 'elasticnet', 'pls']       6
5                ['ridge', 'elasticnet']       5

route priority counts:

   priority  n_jobs
0    normal      72
1      high      53
2       low      16
3  critical       7

route counts by tissue/combo/priority:

   tissue combo  priority  n_routes
0     csf     A      high        22
1     csf     A    normal        18
2     csf     B       low         2
3     csf     B    normal         3
4     csf     C      high         4
5     csf     C    normal        26
6     ser     A  critical         4
7     ser     A      high        18
8     ser     A    normal        18
9     ser     B       low         2
10    ser     B    normal         3
11    ser     C  critical         3
12    ser     C      high         9
13    ser     C       low        12
14    ser     C    normal         4

saved job manifest: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/job_manifest_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
saved coverage check: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/coverage_check_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
saved route summary: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/route_summary_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
feature-selection routing counts:

  feature_selection_mode  n_jobs
0      f_regression_topk      87
1              corr_topk      61

[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_24.csv

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_24.csv

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_24.csv

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_24.csv

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_24.csv

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_48.csv

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_24.csv

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 24
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 24
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 24
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 24
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 24
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 48
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 24
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features:
[OUTER FOLD 1]
 0raw train shape:
 delta examples:(44, 441)  []| valid shape:
 (11, 441)

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 48
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.2627 | train_r2=0.5359 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0053 | train_r2=0.3678 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0132 | train_r2=0.3721 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.2584 | train_r2=0.5346 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0260 | train_r2=0.4817 | n_features=80

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0670 | train_r2=0.4747 | n_features=80

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.0567 | train_r2=0.5316 | n_features=120

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.0622 | train_r2=0.5370 | n_features=120

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.7685 | train_r2=0.7622 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.4385 | train_r2=0.4678 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.7616 | train_r2=0.7642 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.5969 | train_r2=0.4777 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.4607 | train_r2=0.5411 | n_features=80

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.4132 | train_r2=0.5334 | n_features=80

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.4031 | train_r2=0.5729 | n_features=120

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.3567 | train_r2=0.5701 | n_features=120

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.3072 | train_r2=0.5407 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.1015 | train_r2=0.5810 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.2764 | train_r2=0.3964 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.1529 | train_r2=0.3970 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.1569 | train_r2=0.4735 | n_features=80

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.1765 | train_r2=0.4609 | n_features=80

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.2049 | train_r2=0.5302 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.2193 | train_r2=0.5241 | n_features=120

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=-0.0274 | train_r2=0.5028 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.1364 | train_r2=0.5319 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.1778 | train_r2=0.5234 | n_features=120

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=-0.0086 | train_r2=0.4912 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.0862 | train_r2=0.6204 | n_features=80

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.1309 | train_r2=0.6249 | n_features=80

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.4415 | train_r2=0.5424 | n_features=40
fold=5 | best=ridge | valid_r2=0.4485 | train_r2=0.5681 | n_features=40
fold=5 | best=ridge | valid_r2=0.2657 | train_r2=0.3367 | n_features=40
fold=5 | best=ridge | valid_r2=0.2718 | train_r2=0.3964 | n_features=40
fold=4 | best=ridge | valid_r2=0.1333 | train_r2=0.6929 | n_features=120

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.1544 | train_r2=0.6931 | n_features=120

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 48
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.3138 | train_r2=0.4886 | n_features=80
fold=5 | best=ridge | valid_r2=0.2649 | train_r2=0.4997 | n_features=80

[Parallel(n_jobs=8)]: Done   2 tasks      | elapsed:   52.6s

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 48
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 48
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 48
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.3352 | train_r2=0.5503 | n_features=120
fold=5 | best=ridge | valid_r2=0.3262 | train_r2=0.5447 | n_features=120
fold=1 | best=ridge | valid_r2=0.2990 | train_r2=0.6289 | n_features=80

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.2785 | train_r2=0.6280 | n_features=80

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.2539 | train_r2=0.6804 | n_features=120

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.2748 | train_r2=0.6764 | n_features=120

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 60
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv
fold=2 | best=ridge | valid_r2=-0.7477 | train_r2=0.8232 | n_features=80

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 60
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.9185 | train_r2=0.8945 | n_features=80

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.6804 | train_r2=0.8628 | n_features=120

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.7535 | train_r2=0.9231 | n_features=120

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.2779 | train_r2=0.6355 | n_features=80

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.2769 | train_r2=0.6473 | n_features=80

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.3088 | train_r2=0.6857 | n_features=120

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.3574 | train_r2=0.6820 | n_features=120

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.1421 | train_r2=0.5966 | n_features=80

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.1780 | train_r2=0.6055 | n_features=80

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.1850 | train_r2=0.5779 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.1361 | train_r2=0.5768 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.1790 | train_r2=0.6479 | n_features=120

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.2450 | train_r2=0.6530 | n_features=120

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.3338 | train_r2=0.6381 | n_features=80
fold=5 | best=ridge | valid_r2=0.3484 | train_r2=0.6466 | n_features=80
fold=1 | best=gbr | valid_r2=0.0404 | train_r2=0.5043 | n_features=60

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=0.1561 | train_r2=0.6155 | n_features=60

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.3723 | train_r2=0.6826 | n_features=120

[Parallel(n_jobs=8)]: Done   9 tasks      | elapsed:  1.8min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.3827 | train_r2=0.6800 | n_features=120

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 100
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 100
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=svr_linear | valid_r2=-0.1477 | train_r2=0.5362 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.2099 | train_r2=0.7552 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.2168 | train_r2=0.7920 | n_features=60

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.1884 | train_r2=0.6502 | n_features=60

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=gbr | valid_r2=0.0400 | train_r2=0.5046 | n_features=80

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.1122 | train_r2=0.6242 | n_features=80

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=-0.3006 | train_r2=0.4829 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=-0.2803 | train_r2=0.4827 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=0.1551 | train_r2=0.6854 | n_features=100

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=0.0449 | train_r2=0.5026 | n_features=100

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.1702 | train_r2=0.5593 | n_features=60

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.2020 | train_r2=0.5697 | n_features=60

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.2643 | train_r2=0.8140 | n_features=80

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.3146 | train_r2=0.6728 | n_features=80

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.3012 | train_r2=0.5920 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.2790 | train_r2=0.6193 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.4665 | train_r2=0.8382 | n_features=100

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.3198 | train_r2=0.6934 | n_features=100

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.2927 | train_r2=0.5575 | n_features=60

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=svr_linear | valid_r2=0.5243 | train_r2=0.6295 | n_features=60

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=gbr | valid_r2=0.3385 | train_r2=0.3518 | n_features=40
fold=3 | best=ridge | valid_r2=-0.1370 | train_r2=0.5736 | n_features=80

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=gbr | valid_r2=0.3408 | train_r2=0.3535 | n_features=40
fold=3 | best=ridge | valid_r2=-0.2249 | train_r2=0.5906 | n_features=80

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.2007 | train_r2=0.6052 | n_features=100

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=gbr | valid_r2=0.3471 | train_r2=0.3492 | n_features=60
fold=3 | best=ridge | valid_r2=-0.3898 | train_r2=0.6100 | n_features=100

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=gbr | valid_r2=0.3412 | train_r2=0.3453 | n_features=60

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=svr_linear | valid_r2=0.4021 | train_r2=0.6840 | n_features=80

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=svr_linear | valid_r2=0.4410 | train_r2=0.6761 | n_features=80

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=svr_linear | valid_r2=0.4531 | train_r2=0.7106 | n_features=100

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)

[Parallel(n_jobs=8)]: Done  16 tasks      | elapsed:  4.6min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 30
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=svr_linear | valid_r2=0.3938 | train_r2=0.7365 | n_features=100

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=gbr | valid_r2=0.3477 | train_r2=0.3450 | n_features=80
fold=1 | best=svr_linear | valid_r2=0.0095 | train_r2=0.5179 | n_features=120

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=0.1651 | train_r2=0.7174 | n_features=120

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=gbr | valid_r2=0.3548 | train_r2=0.3422 | n_features=80
fold=1 | best=ridge | valid_r2=0.1851 | train_r2=0.5228 | n_features=30

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=gbr | valid_r2=0.3477 | train_r2=0.3450 | n_features=100
fold=1 | best=ridge | valid_r2=0.1897 | train_r2=0.5285 | n_features=30

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=gbr | valid_r2=0.3548 | train_r2=0.3422 | n_features=100

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.3332 | train_r2=0.7105 | n_features=120

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.3096 | train_r2=0.7143 | n_features=120

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=0.1479 | train_r2=0.5452 | n_features=30

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=0.1721 | train_r2=0.6018 | n_features=30

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 60
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 60
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.1046 | train_r2=0.5406 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.0939 | train_r2=0.5381 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.2830 | train_r2=0.5256 | n_features=30

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.4060 | train_r2=0.6372 | n_features=120

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.4041 | train_r2=0.6397 | n_features=120

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.3227 | train_r2=0.5265 | n_features=30

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.0652 | train_r2=0.5736 | n_features=60

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=0.0634 | train_r2=0.5753 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.0309 | train_r2=0.5803 | n_features=60

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=0.0951 | train_r2=0.5763 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.3083 | train_r2=0.4603 | n_features=30

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.2815 | train_r2=0.4681 | n_features=30

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=svr_linear | valid_r2=0.3419 | train_r2=0.7580 | n_features=120

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=svr_linear | valid_r2=0.3461 | train_r2=0.7596 | n_features=120

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.0021 | train_r2=0.6049 | n_features=60

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=-0.6948 | train_r2=0.4335 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=svr_linear | valid_r2=0.0603 | train_r2=0.4556 | n_features=60

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.6385 | train_r2=0.4518 | n_features=30
fold=3 | best=svr_linear | valid_r2=-0.6561 | train_r2=0.4575 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.6234 | train_r2=0.4612 | n_features=30
fold=5 | best=gbr | valid_r2=0.3436 | train_r2=0.3423 | n_features=120
fold=5 | best=gbr | valid_r2=0.3512 | train_r2=0.3420 | n_features=120
fold=3 | best=svr_linear | valid_r2=-0.6707 | train_r2=0.4734 | n_features=60

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.2645 | train_r2=0.4734 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.2790 | train_r2=0.4773 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=-0.6863 | train_r2=0.4692 | n_features=60

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 100
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.5432 | train_r2=0.5102 | n_features=40
fold=4 | best=ridge | valid_r2=0.2697 | train_r2=0.4961 | n_features=60

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 100
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.5432 | train_r2=0.5102 | n_features=40
fold=1 | best=svr_linear | valid_r2=-0.0146 | train_r2=0.4663 | n_features=80

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.3085 | train_r2=0.5008 | n_features=60

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=-0.0135 | train_r2=0.4653 | n_features=80

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)

[Parallel(n_jobs=8)]: Done  25 tasks      | elapsed:  8.9min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.4804 | train_r2=0.5322 | n_features=60
fold=1 | best=svr_linear | valid_r2=-0.0454 | train_r2=0.4789 | n_features=100

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=-0.0526 | train_r2=0.4685 | n_features=100

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.4699 | train_r2=0.5330 | n_features=60
fold=2 | best=svr_linear | valid_r2=-0.1727 | train_r2=0.7247 | n_features=80

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=svr_linear | valid_r2=-0.1079 | train_r2=0.7021 | n_features=80

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 120
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=-0.0484 | train_r2=0.5269 | n_features=120

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.1675 | train_r2=0.3679 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=svr_linear | valid_r2=-0.2964 | train_r2=0.7802 | n_features=100

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.1899 | train_r2=0.5031 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 120
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=svr_linear | valid_r2=-0.5296 | train_r2=0.7873 | n_features=100

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=-0.0382 | train_r2=0.5212 | n_features=120
fold=3 | best=ridge | valid_r2=-0.1885 | train_r2=0.3743 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=-0.5174 | train_r2=0.4784 | n_features=80

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.1675 | train_r2=0.3679 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.1237 | train_r2=0.5138 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.3002 | train_r2=0.5582 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0638 | train_r2=0.3876 | n_features=40
fold=3 | best=ridge | valid_r2=-0.1893 | train_r2=0.3742 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=-0.4886 | train_r2=0.4734 | n_features=80

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 120
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.1298 | train_r2=0.4467 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.2289 | train_r2=0.4303 | n_features=80

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0608 | train_r2=0.3878 | n_features=40
fold=2 | best=ridge | valid_r2=-0.1580 | train_r2=0.5244 | n_features=80

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=svr_linear | valid_r2=-0.6081 | train_r2=0.8106 | n_features=120

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 120
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=-0.4381 | train_r2=0.4912 | n_features=100

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.1368 | train_r2=0.4081 | n_features=80

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.2307 | train_r2=0.4296 | n_features=80

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=-0.4616 | train_r2=0.4878 | n_features=100

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.3101 | train_r2=0.5314 | n_features=80

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=-0.0233 | train_r2=0.6004 | n_features=80

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=svr_linear | valid_r2=-0.6243 | train_r2=0.7989 | n_features=120

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.1513 | train_r2=0.5241 | n_features=80

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0474 | train_r2=0.4507 | n_features=80
fold=3 | best=ridge | valid_r2=-0.2007 | train_r2=0.4101 | n_features=80

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 120
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.3277 | train_r2=0.5393 | n_features=80

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=-0.0233 | train_r2=0.6004 | n_features=80

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=0.2069 | train_r2=0.4532 | n_features=120

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0619 | train_r2=0.4505 | n_features=80
fold=2 | best=ridge | valid_r2=-0.1001 | train_r2=0.5324 | n_features=120

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 120
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_all shape: (55, 441)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=-0.5188 | train_r2=0.5141 | n_features=120

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.3513 | train_r2=0.5868 | n_features=100

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.0782 | train_r2=0.4548 | n_features=120

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.4633 | train_r2=0.5709 | n_features=80
fold=1 | best=ridge | valid_r2=0.2111 | train_r2=0.4531 | n_features=120

[OUTER FOLD 2]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.3627 | train_r2=0.5874 | n_features=100

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=-0.0063 | train_r2=0.5409 | n_features=120

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.0967 | train_r2=0.5329 | n_features=120

[OUTER FOLD 3]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=-0.4827 | train_r2=0.4989 | n_features=120

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0677 | train_r2=0.4679 | n_features=120
fold=3 | best=ridge | valid_r2=-0.1013 | train_r2=0.4539 | n_features=120

[OUTER FOLD 4]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.4792 | train_r2=0.5826 | n_features=80

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 24
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=-0.0079 | train_r2=0.5409 | n_features=120

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0932 | train_r2=0.4299 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.0699 | train_r2=0.4696 | n_features=120
fold=2 | best=ridge | valid_r2=0.2442 | train_r2=0.4614 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)

[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed: 12.0min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 24
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.0948 | train_r2=0.4748 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.3488 | train_r2=0.6159 | n_features=120

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.4622 | train_r2=0.6153 | n_features=100

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 24
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=ridge | valid_r2=-0.0935 | train_r2=0.4249 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=-0.0381 | train_r2=0.4684 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.4581 | train_r2=0.6222 | n_features=100
fold=1 | best=ridge | valid_r2=-0.0533 | train_r2=0.5026 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.2689 | train_r2=0.4618 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.1456 | train_r2=0.5120 | n_features=40
fold=2 | best=ridge | valid_r2=0.2080 | train_r2=0.5297 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.1409 | train_r2=0.4756 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 24
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=0.3112 | train_r2=0.6282 | n_features=120

[OUTER FOLD 5]
raw train shape: (44, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 24
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=-0.0156 | train_r2=0.4888 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=-0.0246 | train_r2=0.5370 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0434 | train_r2=0.4910 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=ridge | valid_r2=-0.0541 | train_r2=0.5712 | n_features=120

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.1245 | train_r2=0.5093 | n_features=40
fold=4 | best=ridge | valid_r2=-0.3314 | train_r2=0.5449 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=0.2159 | train_r2=0.5429 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 24
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.1546 | train_r2=0.5877 | n_features=120

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.0200 | train_r2=0.5780 | n_features=80
fold=3 | best=ridge | valid_r2=0.0360 | train_r2=0.5407 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0312 | train_r2=0.5724 | n_features=120

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=-0.0570 | train_r2=0.5785 | n_features=120

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=-0.2513 | train_r2=0.5419 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 48
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 48
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.4687 | train_r2=0.6440 | n_features=120
fold=1 | best=ridge | valid_r2=-0.0737 | train_r2=0.5944 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.0967 | train_r2=0.5880 | n_features=120

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=ridge | valid_r2=-0.1084 | train_r2=0.6045 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.0230 | train_r2=0.5803 | n_features=80
fold=4 | best=ridge | valid_r2=-0.2728 | train_r2=0.5746 | n_features=120

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 48
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=-0.3291 | train_r2=0.6780 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=-0.1405 | train_r2=0.5980 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 48
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=-0.0661 | train_r2=0.5830 | n_features=120

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0054 | train_r2=0.6270 | n_features=120
fold=3 | best=ridge | valid_r2=0.3129 | train_r2=0.4334 | n_features=40
fold=1 | best=ridge | valid_r2=-0.0997 | train_r2=0.6696 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.3139 | train_r2=0.4410 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0634 | train_r2=0.6520 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.4477 | train_r2=0.6497 | n_features=120
fold=4 | best=ridge | valid_r2=-0.2663 | train_r2=0.5726 | n_features=120

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=-0.0103 | train_r2=0.4965 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=-0.0303 | train_r2=0.5040 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 48
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=-0.0343 | train_r2=0.5619 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.0027 | train_r2=0.6043 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.4077 | train_r2=0.4443 | n_features=40
fold=5 | best=ridge | valid_r2=0.4272 | train_r2=0.4482 | n_features=40
fold=5 | best=ridge | valid_r2=-0.0079 | train_r2=0.6226 | n_features=120
fold=3 | best=ridge | valid_r2=0.3130 | train_r2=0.5627 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0583 | train_r2=0.7265 | n_features=120

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.3130 | train_r2=0.5627 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 48
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)

[Parallel(n_jobs=8)]: Done  45 tasks      | elapsed: 13.4min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=-0.2390 | train_r2=0.5708 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=-0.2390 | train_r2=0.5708 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.0433 | train_r2=0.6828 | n_features=120

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=ridge | valid_r2=-0.0647 | train_r2=0.7278 | n_features=120

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.1950 | train_r2=0.6216 | n_features=80
fold=5 | best=ridge | valid_r2=0.1950 | train_r2=0.6216 | n_features=80

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.2343 | train_r2=0.6545 | n_features=120

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.0329 | train_r2=0.6769 | n_features=120

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 100
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=0.0786 | train_r2=0.6615 | n_features=120

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.2343 | train_r2=0.6545 | n_features=120

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=-0.3829 | train_r2=0.7717 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.3819 | train_r2=0.7517 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.1195 | train_r2=0.7099 | n_features=120

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 100
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=0.0750 | train_r2=0.6613 | n_features=120

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.1305 | train_r2=0.7054 | n_features=120
fold=1 | best=svr_linear | valid_r2=-0.2846 | train_r2=0.7030 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.2592 | train_r2=0.6842 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=-0.1093 | train_r2=0.6896 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.2658 | train_r2=0.7361 | n_features=100

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=-0.0212 | train_r2=0.5970 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.2549 | train_r2=0.7402 | n_features=100

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.0503 | train_r2=0.6571 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.2201 | train_r2=0.7663 | n_features=120

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.4851 | train_r2=0.5194 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.4851 | train_r2=0.5194 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=0.0503 | train_r2=0.6571 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.2232 | train_r2=0.7636 | n_features=120

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.0923 | train_r2=0.6891 | n_features=100

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.0943 | train_r2=0.6891 | n_features=100

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=0.1623 | train_r2=0.6837 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=0.5552 | train_r2=0.7297 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.1353 | train_r2=0.6936 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=0.1299 | train_r2=0.7123 | n_features=120

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=svr_linear | valid_r2=0.5354 | train_r2=0.7265 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=0.4954 | train_r2=0.7405 | n_features=100

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=0.1288 | train_r2=0.7124 | n_features=120

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.3015 | train_r2=0.5470 | n_features=40
fold=5 | best=ridge | valid_r2=0.2995 | train_r2=0.5626 | n_features=40
fold=3 | best=svr_linear | valid_r2=0.4948 | train_r2=0.7425 | n_features=100

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.2812 | train_r2=0.6686 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.2812 | train_r2=0.6686 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=0.5125 | train_r2=0.7746 | n_features=120

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.3475 | train_r2=0.6971 | n_features=100

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 140
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 140
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=svr_linear | valid_r2=0.5011 | train_r2=0.7702 | n_features=120

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=svr_linear | valid_r2=0.2922 | train_r2=0.7341 | n_features=80
fold=4 | best=ridge | valid_r2=0.3067 | train_r2=0.6947 | n_features=100

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=svr_linear | valid_r2=0.2531 | train_r2=0.7317 | n_features=80
fold=5 | best=svr_linear | valid_r2=0.1997 | train_r2=0.8089 | n_features=100
fold=4 | best=elasticnet | valid_r2=0.3401 | train_r2=0.8243 | n_features=120

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=-0.1914 | train_r2=0.7660 | n_features=140

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.1914 | train_r2=0.7660 | n_features=140

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=elasticnet | valid_r2=0.3325 | train_r2=0.8246 | n_features=120

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=svr_linear | valid_r2=0.1895 | train_r2=0.7960 | n_features=100

[Parallel(n_jobs=8)]: Done  56 tasks      | elapsed: 17.2min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.2532 | train_r2=0.7570 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=svr_linear | valid_r2=0.2413 | train_r2=0.8385 | n_features=120
fold=2 | best=ridge | valid_r2=0.1154 | train_r2=0.7202 | n_features=140

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.2330 | train_r2=0.7575 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.1373 | train_r2=0.7231 | n_features=140

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=svr_linear | valid_r2=0.2487 | train_r2=0.8419 | n_features=120

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.2453 | train_r2=0.5200 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.1932 | train_r2=0.8577 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.2498 | train_r2=0.5891 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 100
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.1853 | train_r2=0.8577 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.6354 | train_r2=0.4541 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=svr_linear | valid_r2=0.4307 | train_r2=0.7997 | n_features=140

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 100
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.4731 | train_r2=0.7193 | n_features=140

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=0.1040 | train_r2=0.6586 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.6386 | train_r2=0.4539 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.4151 | train_r2=0.4832 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=-0.0660 | train_r2=0.8917 | n_features=100

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=0.1249 | train_r2=0.6594 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.0658 | train_r2=0.8919 | n_features=100

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=0.4151 | train_r2=0.4832 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=elasticnet | valid_r2=0.2865 | train_r2=0.8367 | n_features=140

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.7161 | train_r2=0.6179 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=elasticnet | valid_r2=0.3093 | train_r2=0.8340 | n_features=140

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0922 | train_r2=0.5319 | n_features=40
fold=2 | best=svr_linear | valid_r2=0.3916 | train_r2=0.5080 | n_features=100

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.7070 | train_r2=0.6064 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0922 | train_r2=0.5319 | n_features=40
fold=2 | best=svr_linear | valid_r2=0.3832 | train_r2=0.5104 | n_features=100

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=0.4635 | train_r2=0.6024 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=svr_linear | valid_r2=0.1939 | train_r2=0.8459 | n_features=140
fold=5 | best=svr_linear | valid_r2=0.1999 | train_r2=0.8455 | n_features=140

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=0.4610 | train_r2=0.5981 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.6933 | train_r2=0.6416 | n_features=100

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0314 | train_r2=0.6359 | n_features=80
fold=3 | best=ridge | valid_r2=0.6929 | train_r2=0.6407 | n_features=100

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0832 | train_r2=0.8804 | n_features=120

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 140
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 140
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=svr_linear | valid_r2=0.1172 | train_r2=0.5229 | n_features=80
fold=1 | best=ridge | valid_r2=-0.0813 | train_r2=0.8802 | n_features=120

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=svr_linear | valid_r2=0.3836 | train_r2=0.4361 | n_features=100

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 160
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=svr_linear | valid_r2=0.3717 | train_r2=0.4447 | n_features=100

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=svr_linear | valid_r2=0.4170 | train_r2=0.5121 | n_features=120

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 160
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.1774 | train_r2=0.7641 | n_features=140

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=svr_linear | valid_r2=-0.1656 | train_r2=0.7631 | n_features=140

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=svr_linear | valid_r2=0.4428 | train_r2=0.5175 | n_features=120

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.0378 | train_r2=0.6959 | n_features=100
fold=5 | best=ridge | valid_r2=0.0378 | train_r2=0.6959 | n_features=100
fold=1 | best=svr_linear | valid_r2=-0.1733 | train_r2=0.7670 | n_features=149

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.6945 | train_r2=0.6603 | n_features=120

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=svr_linear | valid_r2=-0.1733 | train_r2=0.7670 | n_features=149

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_120.csv
fold=2 | best=svr_linear | valid_r2=0.4249 | train_r2=0.5143 | n_features=140

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 120
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.6950 | train_r2=0.6587 | n_features=120

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=svr_linear | valid_r2=0.4242 | train_r2=0.5154 | n_features=140

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=ridge | valid_r2=-0.1575 | train_r2=0.6394 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_120.csv
fold=2 | best=ridge | valid_r2=-0.1802 | train_r2=0.4970 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 120
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.3341 | train_r2=0.4287 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.1575 | train_r2=0.6394 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=svr_linear | valid_r2=0.4178 | train_r2=0.5200 | n_features=149

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=-0.1802 | train_r2=0.4970 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=0.2979 | train_r2=0.4039 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=svr_linear | valid_r2=0.3549 | train_r2=0.4653 | n_features=120

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.3234 | train_r2=0.4532 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0043 | train_r2=0.4427 | n_features=40
fold=4 | best=ridge | valid_r2=0.2979 | train_r2=0.4039 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[Parallel(n_jobs=8)]: Done  69 tasks      | elapsed: 22.5min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 120
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.0043 | train_r2=0.4427 | n_features=40
fold=1 | best=ridge | valid_r2=-0.1093 | train_r2=0.6119 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=0.4922 | train_r2=0.6445 | n_features=120

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.6764 | train_r2=0.6774 | n_features=140

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=svr_linear | valid_r2=0.4178 | train_r2=0.5200 | n_features=149

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_120.csv
fold=3 | best=ridge | valid_r2=0.6924 | train_r2=0.6757 | n_features=140

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 120
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=2 | best=ridge | valid_r2=-0.2319 | train_r2=0.5897 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=ridge | valid_r2=-0.1093 | train_r2=0.6119 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.1450 | train_r2=0.5648 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.2173 | train_r2=0.5897 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=ridge | valid_r2=0.2798 | train_r2=0.5308 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.6891 | train_r2=0.6842 | n_features=150

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=svr_linear | valid_r2=-0.0283 | train_r2=0.7851 | n_features=120
fold=3 | best=ridge | valid_r2=0.1462 | train_r2=0.5583 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=0.0400 | train_r2=0.5667 | n_features=80
fold=4 | best=ridge | valid_r2=0.2857 | train_r2=0.5275 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 120
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=5 | best=ridge | valid_r2=0.0400 | train_r2=0.5667 | n_features=80
fold=5 | best=ridge | valid_r2=-0.0163 | train_r2=0.7143 | n_features=120
fold=4 | best=svr_linear | valid_r2=0.3720 | train_r2=0.4857 | n_features=140

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=1 | best=ridge | valid_r2=-0.0983 | train_r2=0.6421 | n_features=120

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 120
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_all shape: (58, 441)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=svr_linear | valid_r2=0.3635 | train_r2=0.4896 | n_features=140

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.6891 | train_r2=0.6842 | n_features=150

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=2 | best=ridge | valid_r2=-0.2772 | train_r2=0.6217 | n_features=120

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=1 | best=ridge | valid_r2=-0.1139 | train_r2=0.6435 | n_features=120

[OUTER FOLD 2]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=3 | best=ridge | valid_r2=0.0760 | train_r2=0.5976 | n_features=120

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=B, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_B_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: B | tp: 24
X shape before clinical: (83, 749)
y shape: (83,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (55, 752)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=2 | best=ridge | valid_r2=-0.2734 | train_r2=0.6214 | n_features=120

[OUTER FOLD 3]
raw train shape: (46, 441) | valid shape: (12, 441)
fold=4 | best=svr_linear | valid_r2=0.3833 | train_r2=0.4932 | n_features=148

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=4 | best=ridge | valid_r2=0.3256 | train_r2=0.5706 | n_features=120

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=3 | best=ridge | valid_r2=0.0735 | train_r2=0.5979 | n_features=120

[OUTER FOLD 4]
raw train shape: (47, 441) | valid shape: (11, 441)
fold=5 | best=ridge | valid_r2=-0.0243 | train_r2=0.6191 | n_features=120

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=B, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_B_48.csv
fold=4 | best=ridge | valid_r2=0.3079 | train_r2=0.5732 | n_features=120

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: B | tp: 48
X shape before clinical: (83, 749)
y shape: (83,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (55, 752)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=1 | best=ridge | valid_r2=-0.0800 | train_r2=0.5444 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 752) | valid shape: (11, 752)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=B, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_B_72.csv
fold=5 | best=ridge | valid_r2=-0.0227 | train_r2=0.7281 | n_features=140

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: B | tp: 72
X shape before clinical: (83, 749)
y shape: (83,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (55, 752)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=5 | best=ridge | valid_r2=-0.0243 | train_r2=0.6191 | n_features=120
fold=5 | best=ridge | valid_r2=-0.0227 | train_r2=0.7281 | n_features=140
fold=4 | best=svr_linear | valid_r2=0.3833 | train_r2=0.4932 | n_features=148

[OUTER FOLD 5]
raw train shape: (47, 441) | valid shape: (11, 441)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=B, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_B_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: B | tp: 96
X shape before clinical: (83, 749)
y shape: (83,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (55, 752)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=2 | best=ridge | valid_r2=-0.4583 | train_r2=0.6102 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=5 | best=ridge | valid_r2=-0.0275 | train_r2=0.7331 | n_features=149
fold=3 | best=ridge | valid_r2=-0.1784 | train_r2=0.5277 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 752) | valid shape: (11, 752)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=B, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_B_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: B | tp: 120
X shape before clinical: (83, 749)
y shape: (83,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (55, 752)
y_all_train shape: (55,)
n unique train ids: 55
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=4 | best=ridge | valid_r2=0.2304 | train_r2=0.5923 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 752) | valid shape: (11, 752)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=B, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_B_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: B | tp: 24
X shape before clinical: (108, 749)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (58, 752)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 752) | valid shape: (12, 752)
fold=1 | best=ridge | valid_r2=0.2417 | train_r2=0.5815 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=5 | best=ridge | valid_r2=-0.0275 | train_r2=0.7331 | n_features=149
fold=1 | best=ridge | valid_r2=-0.3906 | train_r2=0.5457 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 752) | valid shape: (12, 752)
fold=1 | best=ridge | valid_r2=-0.1908 | train_r2=0.4510 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=1 | best=ridge | valid_r2=0.1486 | train_r2=0.4684 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=5 | best=ridge | valid_r2=0.2199 | train_r2=0.5119 | n_features=40

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=B, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_B_48.csv
fold=2 | best=ridge | valid_r2=-0.3457 | train_r2=0.5143 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 752) | valid shape: (12, 752)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: B | tp: 48
X shape before clinical: (108, 749)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (58, 752)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 752) | valid shape: (12, 752)
fold=1 | best=ridge | valid_r2=0.0500 | train_r2=0.5310 | n_features=40

[OUTER FOLD 2]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=2 | best=ridge | valid_r2=-0.0772 | train_r2=0.4227 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=3 | best=ridge | valid_r2=-0.1316 | train_r2=0.4955 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 752) | valid shape: (11, 752)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=B, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_B_72.csv
fold=1 | best=ridge | valid_r2=-0.2204 | train_r2=0.6934 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 752) | valid shape: (12, 752)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: B | tp: 72
X shape before clinical: (108, 749)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (58, 752)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 752) | valid shape: (12, 752)
fold=4 | best=ridge | valid_r2=0.0026 | train_r2=0.5112 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 752) | valid shape: (11, 752)
fold=3 | best=ridge | valid_r2=-0.8214 | train_r2=0.4015 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=1 | best=ridge | valid_r2=-0.1849 | train_r2=0.6620 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 752) | valid shape: (12, 752)
fold=2 | best=ridge | valid_r2=0.2685 | train_r2=0.8704 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 752) | valid shape: (12, 752)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=B, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_B_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: B | tp: 96
X shape before clinical: (108, 749)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 80
X_all shape: (58, 752)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 752) | valid shape: (12, 752)
fold=5 | best=ridge | valid_r2=0.0329 | train_r2=0.5620 | n_features=40
fold=2 | best=ridge | valid_r2=-0.0173 | train_r2=0.4688 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 752) | valid shape: (12, 752)
fold=3 | best=ridge | valid_r2=0.1878 | train_r2=0.6995 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 752) | valid shape: (11, 752)
fold=4 | best=ridge | valid_r2=0.0298 | train_r2=0.5133 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=2 | best=ridge | valid_r2=-0.1578 | train_r2=0.5778 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 752) | valid shape: (11, 752)

[Parallel(n_jobs=8)]: Done  82 tasks      | elapsed: 26.0min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=B, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_B_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: B | tp: 120
X shape before clinical: (108, 749)
y shape: (108,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (58, 752)
y_all_train shape: (58,)
n unique train ids: 58
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (46, 752) | valid shape: (12, 752)
fold=3 | best=ridge | valid_r2=-0.1255 | train_r2=0.5487 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 752) | valid shape: (11, 752)
fold=4 | best=ridge | valid_r2=0.1383 | train_r2=0.8516 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 752) | valid shape: (11, 752)
fold=2 | best=ridge | valid_r2=0.0055 | train_r2=0.4948 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=4 | best=ridge | valid_r2=0.0840 | train_r2=0.5219 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 752) | valid shape: (11, 752)
fold=5 | best=ridge | valid_r2=-0.0751 | train_r2=0.4527 | n_features=40
fold=2 | best=elasticnet | valid_r2=-0.0377 | train_r2=0.7174 | n_features=40

[OUTER FOLD 3]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=5 | best=ridge | valid_r2=0.3382 | train_r2=0.7440 | n_features=80
fold=5 | best=ridge | valid_r2=0.3155 | train_r2=0.4949 | n_features=40
fold=1 | best=elasticnet | valid_r2=-0.1418 | train_r2=0.9303 | n_features=80

[OUTER FOLD 2]
raw train shape: (46, 752) | valid shape: (12, 752)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 10
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 10
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.1771 | train_r2=0.6698 | n_features=40

[OUTER FOLD 2]
raw train shape: (46, 752) | valid shape: (12, 752)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 20
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-0.6726 | train_r2=0.5460 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=3 | best=ridge | valid_r2=-0.6572 | train_r2=0.5085 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=2 | best=ridge | valid_r2=0.1392 | train_r2=0.5234 | n_features=40

[OUTER FOLD 3]
raw train shape: (46, 752) | valid shape: (12, 752)
fold=2 | best=ridge | valid_r2=-0.0267 | train_r2=0.7075 | n_features=80

[OUTER FOLD 3]
raw train shape: (46, 752) | valid shape: (12, 752)
fold=3 | best=ridge | valid_r2=-0.4020 | train_r2=0.4979 | n_features=40

[OUTER FOLD 4]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=3 | best=ridge | valid_r2=0.3375 | train_r2=0.5270 | n_features=40

[OUTER FOLD 4]
raw train shape: (47, 752) | valid shape: (11, 752)
fold=3 | best=ridge | valid_r2=0.2718 | train_r2=0.6841 | n_features=80

[OUTER FOLD 4]
raw train shape: (47, 752) | valid shape: (11, 752)
fold=4 | best=ridge | valid_r2=0.3376 | train_r2=0.5171 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=4 | best=ridge | valid_r2=0.1308 | train_r2=0.5300 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=4 | best=ridge | valid_r2=0.1417 | train_r2=0.4826 | n_features=40

[OUTER FOLD 5]
raw train shape: (47, 752) | valid shape: (11, 752)
fold=4 | best=ridge | valid_r2=0.2594 | train_r2=0.5096 | n_features=40

[OUTER FOLD 5]
raw train shape: (44, 752) | valid shape: (11, 752)
fold=4 | best=ridge | valid_r2=0.3394 | train_r2=0.6932 | n_features=80

[OUTER FOLD 5]
raw train shape: (47, 752) | valid shape: (11, 752)
fold=5 | best=ridge | valid_r2=0.3720 | train_r2=0.5266 | n_features=40
fold=5 | best=ridge | valid_r2=0.3669 | train_r2=0.5577 | n_features=40
fold=5 | best=ridge | valid_r2=0.4124 | train_r2=0.4578 | n_features=40
fold=1 | best=gbr | valid_r2=-0.1467 | train_r2=0.3598 | n_features=14

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.2239 | train_r2=0.6185 | n_features=80
fold=1 | best=ridge | valid_r2=-0.2880 | train_r2=0.7536 | n_features=20

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.4337 | train_r2=0.5118 | n_features=40
fold=1 | best=gbr | valid_r2=-0.1467 | train_r2=0.3598 | n_features=14

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 20
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 30
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=0.5750 | train_r2=0.4222 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=xgboost | valid_r2=-0.1159 | train_r2=0.5461 | n_features=20

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=gbr | valid_r2=-0.1621 | train_r2=0.6846 | n_features=20

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=0.5750 | train_r2=0.4222 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=gbr | valid_r2=0.1475 | train_r2=0.8937 | n_features=30

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=gbr | valid_r2=0.1520 | train_r2=0.8934 | n_features=30

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.4400 | train_r2=0.9777 | n_features=40

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=gbr | valid_r2=0.1443 | train_r2=0.8926 | n_features=40

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2957 | train_r2=0.5640 | n_features=20

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=-0.1286 | train_r2=0.6213 | n_features=20

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=-0.1064 | train_r2=0.6586 | n_features=30

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=-0.0907 | train_r2=0.6546 | n_features=30

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=0.0464 | train_r2=0.7898 | n_features=40

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=-0.0698 | train_r2=0.8826 | n_features=40

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.4766 | train_r2=0.9125 | n_features=20

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.3433 | train_r2=0.4860 | n_features=20

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=gbr | valid_r2=0.3049 | train_r2=0.5675 | n_features=30

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=xgboost | valid_r2=0.2156 | train_r2=0.4881 | n_features=30

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=xgboost | valid_r2=0.1477 | train_r2=0.4799 | n_features=40

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=xgboost | valid_r2=0.2232 | train_r2=0.4319 | n_features=40

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.2359 | train_r2=0.3854 | n_features=14
fold=5 | best=xgboost | valid_r2=-0.0802 | train_r2=0.7254 | n_features=20
fold=5 | best=ridge | valid_r2=-0.2359 | train_r2=0.3854 | n_features=14
fold=4 | best=ridge | valid_r2=0.4766 | train_r2=0.9125 | n_features=20

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=gbr | valid_r2=0.2061 | train_r2=0.6891 | n_features=30

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=gbr | valid_r2=0.2858 | train_r2=0.6881 | n_features=30

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=gbr | valid_r2=0.3543 | train_r2=0.6885 | n_features=40

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=gbr | valid_r2=0.1494 | train_r2=0.6877 | n_features=40

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 50
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 50
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 60
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=xgboost | valid_r2=0.0754 | train_r2=0.7034 | n_features=20
fold=5 | best=xgboost | valid_r2=-0.0643 | train_r2=0.7311 | n_features=30
fold=5 | best=xgboost | valid_r2=-0.0749 | train_r2=0.7322 | n_features=30
fold=5 | best=xgboost | valid_r2=-0.0176 | train_r2=0.7306 | n_features=40
fold=5 | best=xgboost | valid_r2=-0.0986 | train_r2=0.7264 | n_features=40
fold=1 | best=gbr | valid_r2=0.1435 | train_r2=0.7627 | n_features=50

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 60
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=gbr | valid_r2=0.1115 | train_r2=0.8938 | n_features=50

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=gbr | valid_r2=0.1618 | train_r2=0.7667 | n_features=60

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 48
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 5
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 48
X shape before clinical: (38, 312)
y shape: (38,)

[Parallel(n_jobs=8)]: Done  97 tasks      | elapsed: 47.3min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 48
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 15
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.2359 | train_r2=0.3854 | n_features=14

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 48
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 20
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.2359 | train_r2=0.3854 | n_features=14
fold=1 | best=ridge | valid_r2=0.0576 | train_r2=0.6028 | n_features=15

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 72
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 5
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.0781 | train_r2=0.5934 | n_features=20

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 72
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 10
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=-0.1627 | train_r2=0.8910 | n_features=50

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.3953 | train_r2=0.1853 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0484 | train_r2=0.4883 | n_features=14

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2774 | train_r2=0.4220 | n_features=20

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0484 | train_r2=0.4883 | n_features=14

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.3953 | train_r2=0.1853 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.1046 | train_r2=0.4645 | n_features=20

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.3953 | train_r2=0.1853 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=-0.3022 | train_r2=0.4963 | n_features=20

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=gbr | valid_r2=0.1224 | train_r2=0.8962 | n_features=60

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.0783 | train_r2=0.4445 | n_features=15
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=-0.0883 | train_r2=0.8891 | n_features=50

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.0264 | train_r2=0.5068 | n_features=20
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 72
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 15
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.2359 | train_r2=0.3854 | n_features=14

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 72
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 20
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.2359 | train_r2=0.3854 | n_features=14
fold=1 | best=ridge | valid_r2=-0.3828 | train_r2=0.6420 | n_features=15

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 96
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 5
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=-0.0527 | train_r2=0.8909 | n_features=60

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.7937 | train_r2=0.8595 | n_features=20

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.3953 | train_r2=0.1853 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 96
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 10
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0484 | train_r2=0.4883 | n_features=14

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2141 | train_r2=0.3835 | n_features=20

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0484 | train_r2=0.4883 | n_features=14

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.3953 | train_r2=0.1853 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.1692 | train_r2=0.4063 | n_features=20

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.3953 | train_r2=0.1853 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.0047 | train_r2=0.4628 | n_features=20

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.1940 | train_r2=0.3636 | n_features=15
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.1302 | train_r2=0.5708 | n_features=20

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 96
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 15
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.2359 | train_r2=0.3854 | n_features=14

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 96
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 20
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0477 | train_r2=0.4664 | n_features=15

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 120
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 5
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.0712 | train_r2=0.5636 | n_features=20

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.2359 | train_r2=0.3854 | n_features=14
fold=2 | best=ridge | valid_r2=0.3953 | train_r2=0.1853 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0484 | train_r2=0.4883 | n_features=14

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.5139 | train_r2=0.3261 | n_features=20

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 120
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 10
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.3953 | train_r2=0.1853 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-0.1331 | train_r2=0.3641 | n_features=20

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0484 | train_r2=0.4883 | n_features=14

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.1699 | train_r2=0.4070 | n_features=20

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.3953 | train_r2=0.1853 | n_features=16

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.1424 | train_r2=0.4309 | n_features=15
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=xgboost | valid_r2=0.0651 | train_r2=0.4808 | n_features=50

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.3643 | train_r2=0.4164 | n_features=20
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 120
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 15
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.2359 | train_r2=0.3854 | n_features=14

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 120
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 20
X_all shape: (25, 315)
y_all_train shape: (25,)
n unique train ids: 25
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.0379 | train_r2=0.6546 | n_features=15

[OUTER FOLD 2]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 24
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light

[Parallel(n_jobs=8)]: Done 112 tasks      | elapsed: 51.1min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 24
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 15
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=3 | best=xgboost | valid_r2=0.1156 | train_r2=0.4745 | n_features=50

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=gbr | valid_r2=-0.0094 | train_r2=0.8890 | n_features=60

[OUTER FOLD 3]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2449 | train_r2=0.3572 | n_features=16

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2090 | train_r2=0.3554 | n_features=16

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.1291 | train_r2=0.3205 | n_features=20

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.0868 | train_r2=0.8018 | n_features=15

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.2842 | train_r2=0.2493 | n_features=15

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-2.1187 | train_r2=0.6193 | n_features=16

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2090 | train_r2=0.3554 | n_features=16

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.0632 | train_r2=0.4194 | n_features=20

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=3 | best=xgboost | valid_r2=0.2199 | train_r2=0.4789 | n_features=60

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.4194 | train_r2=0.4136 | n_features=15
fold=4 | best=ridge | valid_r2=-1.6526 | train_r2=0.8130 | n_features=15

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-2.1187 | train_r2=0.6193 | n_features=16

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=-0.3025 | train_r2=0.4349 | n_features=20
fold=5 | best=ridge | valid_r2=0.2230 | train_r2=0.3132 | n_features=15

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 24
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 20
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=4 | best=ridge | valid_r2=-1.6526 | train_r2=0.8130 | n_features=15

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 24
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 20
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_24.csv
fold=1 | best=ridge | valid_r2=0.0238 | train_r2=0.5929 | n_features=20

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 24
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=5 | best=ridge | valid_r2=0.2230 | train_r2=0.3132 | n_features=15
fold=1 | best=ridge | valid_r2=-0.0422 | train_r2=0.5497 | n_features=20

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.1365 | train_r2=0.7087 | n_features=20

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.0114 | train_r2=0.7153 | n_features=30

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 24
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 30
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=2 | best=ridge | valid_r2=0.2868 | train_r2=0.5936 | n_features=20

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2348 | train_r2=0.6672 | n_features=20

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.0979 | train_r2=0.7218 | n_features=30

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0368 | train_r2=0.8946 | n_features=30

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.4409 | train_r2=0.7419 | n_features=20

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.1536 | train_r2=0.8872 | n_features=20

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-0.1679 | train_r2=0.8220 | n_features=30

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.1723 | train_r2=0.7025 | n_features=30

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.5506 | train_r2=0.9054 | n_features=20

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.1388 | train_r2=0.6029 | n_features=20
fold=4 | best=ridge | valid_r2=0.7319 | train_r2=0.9687 | n_features=30

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.0184 | train_r2=0.6986 | n_features=30

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.3448 | train_r2=0.5800 | n_features=20

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 48
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 15
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=5 | best=ridge | valid_r2=0.1446 | train_r2=0.7279 | n_features=30
fold=4 | best=ridge | valid_r2=0.6221 | train_r2=0.9753 | n_features=30

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 48
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 15
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=1 | best=ridge | valid_r2=0.0276 | train_r2=0.6573 | n_features=15

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0276 | train_r2=0.6573 | n_features=15

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 48
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 20
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=5 | best=ridge | valid_r2=0.3543 | train_r2=0.7153 | n_features=30
fold=2 | best=ridge | valid_r2=0.2090 | train_r2=0.3554 | n_features=16

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2090 | train_r2=0.3554 | n_features=16

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0177 | train_r2=0.5694 | n_features=20

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-2.1187 | train_r2=0.6193 | n_features=16

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=gbr | valid_r2=0.2970 | train_r2=0.6922 | n_features=50

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 48
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 20
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=3 | best=ridge | valid_r2=-2.1187 | train_r2=0.6193 | n_features=16

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=-0.0587 | train_r2=0.5005 | n_features=20

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=-1.6526 | train_r2=0.8130 | n_features=15

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0412 | train_r2=0.5227 | n_features=20

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=-1.6526 | train_r2=0.8130 | n_features=15

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-0.0240 | train_r2=0.4692 | n_features=20

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.3328 | train_r2=0.2581 | n_features=15
fold=2 | best=ridge | valid_r2=-0.0587 | train_r2=0.5005 | n_features=20

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.2768 | train_r2=0.1930 | n_features=15
fold=4 | best=ridge | valid_r2=-0.2946 | train_r2=0.5335 | n_features=20

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-0.2450 | train_r2=0.4367 | n_features=20

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 48
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 48
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 30
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=5 | best=ridge | valid_r2=0.4328 | train_r2=0.4584 | n_features=20
fold=4 | best=ridge | valid_r2=-0.4151 | train_r2=0.4968 | n_features=20

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.0244 | train_r2=0.7230 | n_features=30

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=gbr | valid_r2=0.2970 | train_r2=0.6922 | n_features=50

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=0.0676 | train_r2=0.6916 | n_features=30

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 72
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 15
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=2 | best=ridge | valid_r2=-0.2289 | train_r2=0.6399 | n_features=30

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.3156 | train_r2=0.3834 | n_features=20
fold=3 | best=xgboost | valid_r2=0.1528 | train_r2=0.4839 | n_features=60

[OUTER FOLD 4]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.0344 | train_r2=0.6181 | n_features=15

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=-0.1052 | train_r2=0.6564 | n_features=30

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.2054 | train_r2=0.9020 | n_features=30

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 72
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 15
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=2 | best=ridge | valid_r2=0.2090 | train_r2=0.3554 | n_features=16

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.4600 | train_r2=0.9269 | n_features=30

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.0137 | train_r2=0.6048 | n_features=15

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=-0.1446 | train_r2=0.6620 | n_features=30

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-2.1187 | train_r2=0.6193 | n_features=16

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.0221 | train_r2=0.6633 | n_features=30

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2090 | train_r2=0.3554 | n_features=16

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=gbr | valid_r2=0.1171 | train_r2=0.5608 | n_features=60

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=-1.6526 | train_r2=0.8130 | n_features=15

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.4954 | train_r2=0.6316 | n_features=30

[Parallel(n_jobs=8)]: Done 129 tasks      | elapsed: 55.6min

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 96
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 15
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=4 | best=ridge | valid_r2=0.3008 | train_r2=0.5545 | n_features=30

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 96
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 15
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=1 | best=ridge | valid_r2=-0.0250 | train_r2=0.6650 | n_features=15

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 96
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 20
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=5 | best=ridge | valid_r2=0.1123 | train_r2=0.5238 | n_features=30
fold=1 | best=ridge | valid_r2=0.0296 | train_r2=0.5048 | n_features=15

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2090 | train_r2=0.3554 | n_features=16

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.1204 | train_r2=0.6684 | n_features=20

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2090 | train_r2=0.3554 | n_features=16

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 96
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 20
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=3 | best=ridge | valid_r2=-2.1187 | train_r2=0.6193 | n_features=16

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2525 | train_r2=0.3512 | n_features=20

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-2.1187 | train_r2=0.6193 | n_features=16

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=-1.6526 | train_r2=0.8130 | n_features=15

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.0957 | train_r2=0.6575 | n_features=20

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=0.0564 | train_r2=0.5944 | n_features=20

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=-1.6526 | train_r2=0.8130 | n_features=15

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.1442 | train_r2=0.3165 | n_features=20

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.2665 | train_r2=0.2256 | n_features=15
fold=4 | best=ridge | valid_r2=-1.0720 | train_r2=0.8980 | n_features=20

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=xgboost | valid_r2=-0.0111 | train_r2=0.7324 | n_features=50
fold=5 | best=ridge | valid_r2=0.2813 | train_r2=0.1774 | n_features=15
fold=3 | best=ridge | valid_r2=-0.8261 | train_r2=0.5405 | n_features=20

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 96
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=5 | best=ridge | valid_r2=0.4030 | train_r2=0.3407 | n_features=20

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 96
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 30
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=4 | best=ridge | valid_r2=-1.1485 | train_r2=0.8987 | n_features=20

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 120
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 15
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=1 | best=ridge | valid_r2=-0.1204 | train_r2=0.8315 | n_features=30

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=ridge | valid_r2=-0.1571 | train_r2=0.8287 | n_features=30

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.3820 | train_r2=0.3145 | n_features=20
fold=2 | best=ridge | valid_r2=0.0741 | train_r2=0.4027 | n_features=30

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2597 | train_r2=0.4036 | n_features=30

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 120
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 15
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=3 | best=ridge | valid_r2=0.1852 | train_r2=0.6336 | n_features=30

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-0.1688 | train_r2=0.6446 | n_features=30

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=-0.6746 | train_r2=0.8480 | n_features=30

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=-0.6581 | train_r2=0.8625 | n_features=30

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=elasticnet | valid_r2=-0.0462 | train_r2=0.6155 | n_features=15

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=xgboost | valid_r2=-0.0022 | train_r2=0.7366 | n_features=50
fold=5 | best=ridge | valid_r2=0.3211 | train_r2=0.4244 | n_features=30
fold=5 | best=ridge | valid_r2=0.3689 | train_r2=0.3839 | n_features=30
fold=4 | best=gbr | valid_r2=0.2478 | train_r2=0.5617 | n_features=60

[OUTER FOLD 5]
raw train shape: (20, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_120.csv
fold=1 | best=elasticnet | valid_r2=-0.0840 | train_r2=0.6576 | n_features=15

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 120
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 20
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 120
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 20
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=2 | best=ridge | valid_r2=0.2090 | train_r2=0.3554 | n_features=16

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2090 | train_r2=0.3554 | n_features=16

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=pls | valid_r2=-0.0456 | train_r2=0.9059 | n_features=20

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=pls | valid_r2=-0.0661 | train_r2=0.8946 | n_features=20

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=elasticnet | valid_r2=-1.8975 | train_r2=0.6111 | n_features=16

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=xgboost | valid_r2=-0.0226 | train_r2=0.7403 | n_features=60
fold=3 | best=elasticnet | valid_r2=-1.8975 | train_r2=0.6111 | n_features=16

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2375 | train_r2=0.3733 | n_features=20

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=pls | valid_r2=-3.0774 | train_r2=0.8539 | n_features=15

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.1321 | train_r2=0.3799 | n_features=20

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=pls | valid_r2=-3.0774 | train_r2=0.8539 | n_features=15

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-0.3530 | train_r2=0.5947 | n_features=20

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.2172 | train_r2=0.1999 | n_features=15
fold=3 | best=ridge | valid_r2=-0.8797 | train_r2=0.5247 | n_features=20

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.2469 | train_r2=0.1749 | n_features=15
fold=4 | best=elasticnet | valid_r2=-0.1624 | train_r2=0.7825 | n_features=20

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=elasticnet | valid_r2=-0.1125 | train_r2=0.7849 | n_features=20

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 120
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)

[RUN-TRAIN-OOF] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 120
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []

[TRAIN-ONLY OOF CV CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 30
X_all shape: (26, 315)
y_all_train shape: (26,)
n unique train ids: 26
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
outer_cv_type: StratifiedKFold_y_bins
n_outer_folds: 5

[OUTER FOLD 1]
raw train shape: (20, 315) | valid shape: (6, 315)
fold=5 | best=ridge | valid_r2=0.2627 | train_r2=0.3293 | n_features=20
fold=5 | best=ridge | valid_r2=0.2994 | train_r2=0.3035 | n_features=20
fold=1 | best=ridge | valid_r2=-0.0645 | train_r2=0.7089 | n_features=30

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=1 | best=pls | valid_r2=-0.0664 | train_r2=0.9168 | n_features=30

[OUTER FOLD 2]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2237 | train_r2=0.4768 | n_features=30

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=2 | best=ridge | valid_r2=0.2352 | train_r2=0.4660 | n_features=30

[OUTER FOLD 3]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=3 | best=ridge | valid_r2=-0.5489 | train_r2=0.5573 | n_features=30

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=xgboost | valid_r2=-0.0186 | train_r2=0.7347 | n_features=60
fold=3 | best=ridge | valid_r2=0.0062 | train_r2=0.6486 | n_features=30

[OUTER FOLD 4]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=elasticnet | valid_r2=-0.4177 | train_r2=0.8074 | n_features=30

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=4 | best=ridge | valid_r2=0.2502 | train_r2=0.5004 | n_features=30

[OUTER FOLD 5]
raw train shape: (21, 315) | valid shape: (5, 315)
fold=5 | best=ridge | valid_r2=0.4316 | train_r2=0.4043 | n_features=30
fold=5 | best=ridge | valid_r2=0.3668 | train_r2=0.3835 | n_features=30
saved: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/omics_paper_style_train_summary_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
saved grouped summary: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/grouped_by_tissue_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
saved grouped summary: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/grouped_by_tissue_combo_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
saved grouped summary: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/grouped_by_tissue_combo_tp_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
saved grouped summary: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/grouped_by_tissue_combo_model_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
saved grouped summary: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/grouped_by_tissue_combo_tp_model_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
saved grouped summary: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/grouped_by_tissue_combo_tp_selection_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
saved paper-style best by tissue+combo+tp: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/paper_style_best_by_tissue_combo_tp_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
saved paper-style best by tissue+tp: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/paper_style_best_by_tissue_tp_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv

[Parallel(n_jobs=8)]: Done 148 out of 148 | elapsed: 62.8min finished

Empty DataFrame
Columns: [tissue, combo, raw_feature_signature, n_rows, timepoints, n_unique_tp, feature_path_examples]
Index: []

Top 30 by TRAIN OOF R²:

,status,clinical_mode,feature_selection_mode,tissue,combo,tp,top_k_after_sparse,final_full_train_best_model_type,oof_r2,oof_mae,mean_valid_r2,std_valid_r2,mean_train_r2,generalization_gap_mean_train_minus_valid,final_full_train_best_score_inner_oof_r2,n_features_final_full_train,route_priority,route_reason
0,ok,light,f_regression_topk,ser,C,24,40,xgboost,0.271758,15.176796,0.194197,0.176020,0.733303,0.539106,0.176393,40,critical,v11 ser C 24h rescue: restore v9 candidate poo...
1,ok,light,corr_topk,csf,C,24,30,ridge,0.261029,14.235372,0.240782,0.225431,0.797261,0.556479,0.159739,30,normal,v11 csf C expansion: include corr_topk and top...
2,ok,light,corr_topk,csf,C,24,20,ridge,0.253265,13.439060,0.316194,0.200290,0.674126,0.357932,0.276462,20,high,v11 csf C expansion: include corr_topk and top...
3,ok,light,corr_topk,ser,A,96,120,svr_linear,0.242782,13.388230,0.306499,0.302850,0.683036,0.376537,0.161328,120,critical,v11 A rescue-expansion: v9-compatible model po...
4,ok,light,f_regression_topk,csf,A,96,30,ridge,0.236085,13.732454,0.199354,0.296724,0.501134,0.301780,0.212344,30,high,v11 A rescue-expansion: v9-compatible model po...
5,ok,light,f_regression_topk,ser,A,96,100,svr_linear,0.234564,13.494215,0.288056,0.272773,0.634685,0.346629,0.176559,100,high,v11 A rescue-expansion: v9-compatible model po...
6,ok,light,corr_topk,ser,A,96,100,svr_linear,0.231528,13.546047,0.283952,0.271167,0.636724,0.352771,0.178925,100,high,v11 A rescue-expansion: v9-compatible model po...
7,ok,light,corr_topk,csf,A,96,30,ridge,0.226360,13.697032,0.188781,0.303123,0.517226,0.328445,0.203671,30,high,v11 A rescue-expansion: v9-compatible model po...
8,ok,light,f_regression_topk,ser,A,96,120,svr_linear,0.217384,13.474596,0.270970,0.290776,0.660641,0.389671,0.170774,120,critical,v11 A rescue-expansion: v9-compatible model po...
9,ok,light,corr_topk,csf,C,48,30,ridge,0.201590,14.601400,0.186037,0.241039,0.696185,0.510148,0.167297,30,normal,v11 csf C expansion: include corr_topk and top...
10,ok,light,corr_topk,csf,A,72,60,gbr,0.195500,14.211108,0.126244,0.287160,0.562045,0.435801,0.113992,60,high,v11 A rescue-expansion: v9-compatible model po...
11,ok,light,corr_topk,ser,A,96,140,svr_linear,0.194071,13.616950,0.258349,0.311671,0.634389,0.376040,0.155597,140,critical,v11 A rescue-expansion: v9-compatible model po...
12,ok,light,f_regression_topk,ser,A,96,160,svr_linear,0.191596,13.602036,0.257905,0.314539,0.639495,0.381590,0.162002,150,high,v11 A rescue-expansion: v9-compatible model po...
13,ok,light,corr_topk,ser,A,96,160,svr_linear,0.191596,13.602036,0.257905,0.314539,0.639495,0.381590,0.162002,150,high,v11 A rescue-expansion: v9-compatible model po...
14,ok,light,f_regression_topk,ser,A,96,140,svr_linear,0.188765,13.706629,0.254641,0.311197,0.633928,0.379288,0.157654,140,critical,v11 A rescue-expansion: v9-compatible model po...
15,ok,light,f_regression_topk,csf,C,24,30,ridge,0.185944,14.740801,0.159013,0.305969,0.791110,0.632097,-0.028393,30,normal,v11 csf C expansion: include corr_topk and top...
16,ok,light,f_regression_topk,ser,C,48,15,ridge,0.183097,15.716588,0.180746,0.169184,0.367828,0.187082,0.178553,16,low,v11 ser C non-24h: ridge-focused top_k neighbo...
17,ok,light,corr_topk,csf,C,120,30,ridge,0.181183,14.333944,0.158403,0.162130,0.583065,0.424662,0.096037,30,normal,v11 csf C expansion: include corr_topk and top...
18,ok,light,corr_topk,ser,A,96,80,svr_linear,0.176934,14.016840,0.244973,0.308547,0.648902,0.403928,0.182110,80,high,v11 A rescue-expansion: v9-compatible model po...
19,ok,light,f_regression_topk,ser,C,96,15,ridge,0.170303,15.374032,0.165948,0.190721,0.337825,0.171877,0.178553,16,low,v11 ser C non-24h: ridge-focused top_k neighbo...
20,ok,light,corr_topk,ser,A,96,40,ridge,0.161063,14.840301,0.232529,0.294946,0.563120,0.330592,0.192018,40,high,v11 A rescue-expansion: v9-compatible model po...
21,ok,light,f_regression_topk,ser,C,48,5,ridge,0.157075,15.686889,0.147370,0.222005,0.333103,0.185734,0.178553,16,low,v11 ser C non-24h: ridge-focused top_k neighbo...
22,ok,light,f_regression_topk,ser,C,48,10,ridge,0.157075,15.686889,0.147370,0.222005,0.333103,0.185734,0.178553,16,normal,v11 ser C non-24h: ridge-focused top_k neighbo...
23,ok,light,f_regression_topk,ser,C,72,5,ridge,0.157075,15.686889,0.147370,0.222005,0.333103,0.185734,0.178553,16,low,v11 ser C non-24h: ridge-focused top_k neighbo...
24,ok,light,f_regression_topk,ser,C,72,10,ridge,0.157075,15.686889,0.147370,0.222005,0.333103,0.185734,0.178553,16,normal,v11 ser C non-24h: ridge-focused top_k neighbo...
25,ok,light,f_regression_topk,ser,C,96,5,ridge,0.157075,15.686889,0.147370,0.222005,0.333103,0.185734,0.178553,16,low,v11 ser C non-24h: ridge-focused top_k neighbo...
26,ok,light,f_regression_topk,ser,C,96,10,ridge,0.157075,15.686889,0.147370,0.222005,0.333103,0.185734,0.178553,16,normal,v11 ser C non-24h: ridge-focused top_k neighbo...
27,ok,light,f_regression_topk,ser,C,120,5,ridge,0.157075,15.686889,0.147370,0.222005,0.333103,0.185734,0.178553,16,low,v11 ser C non-24h: ridge-focused top_k neighbo...
28,ok,light,f_regression_topk,ser,C,120,10,ridge,0.157075,15.686889,0.147370,0.222005,0.333103,0.185734,0.178553,16,normal,v11 ser C non-24h: ridge-focused top_k neighbo...
29,ok,light,f_regression_topk,ser,A,96,80,svr_linear,0.156211,14.264497,0.224338,0.324055,0.674499,0.450161,0.187898,80,high,v11 A rescue-expansion: v9-compatible model po...

Best by clinical/selection/tissue/combo/tp:

,status,clinical_mode,feature_selection_mode,tissue,combo,tp,top_k_after_sparse,final_full_train_best_model_type,oof_r2,oof_mae,mean_valid_r2,std_valid_r2,mean_train_r2,generalization_gap_mean_train_minus_valid,final_full_train_best_score_inner_oof_r2,n_features_final_full_train,route_priority,route_reason
0,ok,light,corr_topk,csf,A,24,120,ridge,0.059446,15.369274,0.068281,0.253235,0.574360,0.506079,-0.007916,120,normal,v11 A rescue-expansion: v9-compatible model po...
1,ok,light,corr_topk,csf,A,48,40,ridge,0.016371,15.672716,-0.003948,0.418752,0.595960,0.599908,0.008625,40,normal,v11 A rescue-expansion: v9-compatible model po...
2,ok,light,corr_topk,csf,A,72,60,gbr,0.195500,14.211108,0.126244,0.287160,0.562045,0.435801,0.113992,60,high,v11 A rescue-expansion: v9-compatible model po...
3,ok,light,corr_topk,csf,A,96,30,ridge,0.226360,13.697032,0.188781,0.303123,0.517226,0.328445,0.203671,30,high,v11 A rescue-expansion: v9-compatible model po...
4,ok,light,corr_topk,csf,A,120,120,ridge,0.028866,15.770312,0.015004,0.116635,0.490056,0.475052,0.044072,120,normal,v11 A rescue-expansion: v9-compatible model po...
5,ok,light,corr_topk,csf,C,24,30,ridge,0.261029,14.235372,0.240782,0.225431,0.797261,0.556479,0.159739,30,normal,v11 csf C expansion: include corr_topk and top...
6,ok,light,corr_topk,csf,C,48,30,ridge,0.201590,14.601400,0.186037,0.241039,0.696185,0.510148,0.167297,30,normal,v11 csf C expansion: include corr_topk and top...
7,ok,light,corr_topk,csf,C,72,30,ridge,0.090519,15.485917,0.067422,0.145476,0.684612,0.617191,-0.066097,30,normal,v11 csf C expansion: include corr_topk and top...
8,ok,light,corr_topk,csf,C,96,30,ridge,0.014829,15.663919,-0.071074,0.364555,0.624650,0.695724,0.095775,30,normal,v11 csf C expansion: include corr_topk and top...
9,ok,light,corr_topk,csf,C,120,30,ridge,0.181183,14.333944,0.158403,0.162130,0.583065,0.424662,0.096037,30,normal,v11 csf C expansion: include corr_topk and top...
10,ok,light,corr_topk,ser,A,24,40,ridge,0.073299,16.318682,0.085032,0.126879,0.472096,0.387064,-0.068471,40,normal,v11 A rescue-expansion: v9-compatible model po...
11,ok,light,corr_topk,ser,A,48,40,ridge,0.082142,15.571042,0.092378,0.232703,0.519129,0.426751,0.045957,40,normal,v11 A rescue-expansion: v9-compatible model po...
12,ok,light,corr_topk,ser,A,72,120,svr_linear,0.138242,14.762171,0.197571,0.242775,0.782533,0.584963,0.103099,120,high,v11 A rescue-expansion: v9-compatible model po...
13,ok,light,corr_topk,ser,A,96,120,svr_linear,0.242782,13.388230,0.306499,0.302850,0.683036,0.376537,0.161328,120,critical,v11 A rescue-expansion: v9-compatible model po...
14,ok,light,corr_topk,ser,A,120,40,ridge,0.023038,16.764476,0.057579,0.216366,0.487246,0.429668,0.088317,40,normal,v11 A rescue-expansion: v9-compatible model po...
15,ok,light,corr_topk,ser,C,24,30,xgboost,0.137132,15.579252,0.101614,0.154439,0.707129,0.605515,0.177675,30,high,v11 ser C 24h rescue: restore v9 candidate poo...
16,ok,light,f_regression_topk,csf,A,24,120,ridge,0.069795,15.335052,0.072770,0.230849,0.573675,0.500904,0.006060,120,normal,v11 A rescue-expansion: v9-compatible model po...
17,ok,light,f_regression_topk,csf,A,48,40,ridge,0.012076,15.781390,-0.033328,0.443915,0.582268,0.615595,-0.002548,40,normal,v11 A rescue-expansion: v9-compatible model po...
18,ok,light,f_regression_topk,csf,A,72,40,gbr,0.128291,14.392514,0.075298,0.254300,0.508171,0.432874,0.149833,40,high,v11 A rescue-expansion: v9-compatible model po...
19,ok,light,f_regression_topk,csf,A,96,30,ridge,0.236085,13.732454,0.199354,0.296724,0.501134,0.301780,0.212344,30,high,v11 A rescue-expansion: v9-compatible model po...
20,ok,light,f_regression_topk,csf,A,120,40,ridge,0.031232,15.855359,-0.004695,0.154198,0.429323,0.434018,0.063665,40,normal,v11 A rescue-expansion: v9-compatible model po...
21,ok,light,f_regression_topk,csf,B,24,40,ridge,-0.015607,16.474072,-0.053293,0.259014,0.557295,0.610588,-0.216260,40,low,v11 B minimal coverage: v9-compatible pool but...
22,ok,light,f_regression_topk,csf,B,48,40,ridge,0.110969,14.898098,0.023137,0.395376,0.556011,0.532874,0.062792,40,normal,v11 B minimal coverage: v9-compatible pool but...
23,ok,light,f_regression_topk,csf,B,72,40,ridge,0.066373,15.469060,0.008004,0.358023,0.491887,0.483883,-0.100720,40,normal,v11 B minimal coverage: v9-compatible pool but...
24,ok,light,f_regression_topk,csf,B,96,40,ridge,0.109713,15.318968,0.060688,0.283737,0.553529,0.492842,0.062972,40,normal,v11 B minimal coverage: v9-compatible pool but...
25,ok,light,f_regression_topk,csf,B,120,40,ridge,-0.151021,17.396986,-0.226955,0.305312,0.448236,0.675190,-0.290665,40,low,v11 B minimal coverage: v9-compatible pool but...
26,ok,light,f_regression_topk,csf,C,24,30,ridge,0.185944,14.740801,0.159013,0.305969,0.791110,0.632097,-0.028393,30,normal,v11 csf C expansion: include corr_topk and top...
27,ok,light,f_regression_topk,csf,C,48,30,ridge,0.117648,15.028840,0.060554,0.261978,0.711715,0.651161,0.161967,30,normal,v11 csf C expansion: include corr_topk and top...
28,ok,light,f_regression_topk,csf,C,72,30,ridge,0.075139,15.902995,-0.023831,0.177896,0.746048,0.769879,0.008317,30,normal,v11 csf C expansion: include corr_topk and top...
29,ok,light,f_regression_topk,csf,C,96,30,ridge,0.003195,16.184878,-0.042917,0.347333,0.628037,0.670954,0.117709,30,normal,v11 csf C expansion: include corr_topk and top...
30,ok,light,f_regression_topk,csf,C,120,20,ridge,0.088311,15.739595,-0.012170,0.235679,0.597156,0.609326,0.052364,20,high,v11 csf C expansion: include corr_topk and top...
31,ok,light,f_regression_topk,ser,A,24,40,ridge,0.062171,16.474085,0.070649,0.122471,0.469302,0.398654,-0.081068,40,normal,v11 A rescue-expansion: v9-compatible model po...
32,ok,light,f_regression_topk,ser,A,48,40,ridge,0.058741,15.973093,0.061497,0.267986,0.529330,0.467834,0.045627,40,normal,v11 A rescue-expansion: v9-compatible model po...
33,ok,light,f_regression_topk,ser,A,72,120,svr_linear,0.140991,14.705040,0.200750,0.245112,0.783185,0.582436,0.109696,120,high,v11 A rescue-expansion: v9-compatible model po...
34,ok,light,f_regression_topk,ser,A,96,100,svr_linear,0.234564,13.494215,0.288056,0.272773,0.634685,0.346629,0.176559,100,high,v11 A rescue-expansion: v9-compatible model po...
35,ok,light,f_regression_topk,ser,A,120,40,ridge,0.024884,16.701177,0.059715,0.219017,0.482346,0.422632,0.076778,40,normal,v11 A rescue-expansion: v9-compatible model po...
36,ok,light,f_regression_topk,ser,B,24,40,ridge,-0.192389,18.843997,-0.166480,0.174280,0.525745,0.692224,-0.149274,40,low,v11 B minimal coverage: v9-compatible pool but...
37,ok,light,f_regression_topk,ser,B,48,80,ridge,0.101422,15.836199,0.142470,0.193881,0.771779,0.629308,0.009948,80,normal,v11 B minimal coverage: v9-compatible pool but...
38,ok,light,f_regression_topk,ser,B,72,40,ridge,-0.003109,16.371021,0.014344,0.176514,0.539233,0.524889,-0.124605,40,low,v11 B minimal coverage: v9-compatible pool but...
39,ok,light,f_regression_topk,ser,B,96,80,ridge,0.093472,15.997928,0.133329,0.185026,0.726705,0.593377,0.106833,80,normal,v11 B minimal coverage: v9-compatible pool but...
40,ok,light,f_regression_topk,ser,B,120,40,ridge,0.125283,15.438100,0.162649,0.195343,0.545873,0.383224,0.103158,40,normal,v11 B minimal coverage: v9-compatible pool but...
41,ok,light,f_regression_topk,ser,C,24,40,xgboost,0.271758,15.176796,0.194197,0.176020,0.733303,0.539106,0.176393,40,critical,v11 ser C 24h rescue: restore v9 candidate poo...
42,ok,light,f_regression_topk,ser,C,48,15,ridge,0.183097,15.716588,0.180746,0.169184,0.367828,0.187082,0.178553,16,low,v11 ser C non-24h: ridge-focused top_k neighbo...
43,ok,light,f_regression_topk,ser,C,72,5,ridge,0.157075,15.686889,0.147370,0.222005,0.333103,0.185734,0.178553,16,low,v11 ser C non-24h: ridge-focused top_k neighbo...
44,ok,light,f_regression_topk,ser,C,96,15,ridge,0.170303,15.374032,0.165948,0.190721,0.337825,0.171877,0.178553,16,low,v11 ser C non-24h: ridge-focused top_k neighbo...
45,ok,light,f_regression_topk,ser,C,120,5,ridge,0.157075,15.686889,0.147370,0.222005,0.333103,0.185734,0.178553,16,low,v11 ser C non-24h: ridge-focused top_k neighbo...

In [25]:
print("SAVE_DIR:", SAVE_DIR.resolve())
print("DETAIL_DIR:", DETAIL_DIR.resolve())
print("FEATURE_TRACE_DIR:", FEATURE_TRACE_DIR.resolve())

SAVE_DIR: /data2/jinoh001/stable/research_SPI/DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible
DETAIL_DIR: /data2/jinoh001/stable/research_SPI/DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/single_detail_outputs
FEATURE_TRACE_DIR: /data2/jinoh001/stable/research_SPI/DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/feature_traces