In [2]:
from __future__ import annotations

import json
import hashlib
from pathlib import Path
from itertools import product

import numpy as np
import pandas as pd

from sklearn.base import clone, BaseEstimator, TransformerMixin
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.linear_model import Lasso, ElasticNet, Ridge, LassoLars
from sklearn.cross_decomposition import PLSRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    HistGradientBoostingRegressor,
)
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import GroupKFold, ParameterGrid, StratifiedKFold
from joblib import Parallel, delayed
import os
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.feature_selection import f_regression

# Optional XGBoost candidate.
# If xgboost is not installed in the current environment, the xgboost model
# will be removed from MODEL_TYPES below to avoid crashing the whole run.
try:
    from xgboost import XGBRegressor
    XGBOOST_AVAILABLE = True
except ImportError:
    XGBRegressor = None
    XGBOOST_AVAILABLE = False

In [3]:
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

In [4]:
# ==========================================
# Config
# ==========================================
DATA_ROOT = Path("../../DifferentCom_data_rebuild")
TP_DIR = DATA_ROOT / "tp_views"
BASE_DIR = DATA_ROOT / "base_patient_tables"

# ==========================================
# Experiment tags / output directories
# ==========================================
# IMPORTANT:
# - TRAIN_EXPERIMENT_TAG must match the completed training-only OOF/CV notebook.
# - TEST_EXPERIMENT_TAG is only for this held-out test run.
# - The holdout test set is NOT used to choose model/configs.
TRAIN_EXPERIMENT_TAG = "single_omics_train_paper_style_v11_rescue_expansion_v9compatible"
TEST_EXPERIMENT_TAG = "single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible"

# Compatibility alias for older helper functions in this notebook.
EXPERIMENT_TAG = TEST_EXPERIMENT_TAG

TRAIN_SAVE_DIR = DATA_ROOT / f"results_single_omics_train_only_{TRAIN_EXPERIMENT_TAG}"
TRAIN_SUMMARY_PATH = TRAIN_SAVE_DIR / f"omics_paper_style_train_summary_{TRAIN_EXPERIMENT_TAG}.csv"

SAVE_DIR = DATA_ROOT / "testResult" / f"results_single_omics_test_{TEST_EXPERIMENT_TAG}"
SAVE_DIR.mkdir(parents=True, exist_ok=True)

TARGET_PATH = BASE_DIR / "target_by_patient.csv"

# A = proteomics, B = metabolomics, C = miRNA
COMBOS = ["A", "B", "C"]
TISSUES = ["csf", "ser"]
TIMEPOINTS = [24, 48, 72, 96, 120]

# Must match the training v11 available model families.
# The final held-out test cell still restricts each job to the model selected by training OOF/CV.
MODEL_TYPES = [
    "ridge",
    "elasticnet",
    "pls",
    "svr_linear",
    "gbr",
    "xgboost",
]

# Keep the notebook runnable even when xgboost is not installed.
if not XGBOOST_AVAILABLE:
    print("[WARN] xgboost is not installed. Removing 'xgboost' from MODEL_TYPES.")
    MODEL_TYPES = [m for m in MODEL_TYPES if m != "xgboost"]

# Feature-selection modes available in v11 training.
FEATURE_SELECTION_MODES_TO_RUN = [
    "f_regression_topk",
    "corr_topk",
]

# v11 training used light clinical mode only.
CLINICAL_MODES_TO_RUN = ["light"]

# sparse filter: train 기준으로만 적용
MIN_OBS_FRAC = 0.50

# CV used inside train-only model fitting on TRAIN_IDS.
N_SPLITS_OUTER = 5
N_SPLITS_INNER = 3
RANDOM_STATE = 42

# y-bin stratification for regression CV stability
USE_STRATIFIED_OUTER_CV = True
N_Y_BINS_FOR_OUTER_CV = 3
OUTER_CV_RANDOM_STATE = 42

# Must match training v11 model-selection penalty.
INNER_SELECTION_STD_PENALTY = 0.10

# ==========================================
# Held-out test config selection policy
# ==========================================
# Safe final-test default:
#   Choose configs using TRAINING OOF/CV only, then evaluate those pre-selected configs once on TEST_IDS.
#
# Recommended final EF/LF comparison:
#   "best_per_tissue_tp"         -> 2 tissues x 5 TPs = up to 10 rows.
#
# Recommended diagnostic after unstable holdout results:
#   "top_n_per_tissue_tp"        -> top N training-OOF configs per tissue+TP.
#                                   This checks whether the OOF-best config is unstable on holdout.
#                                   Do NOT use holdout test R² to choose the final config.
#
# Other optional diagnostics:
#   "best_per_tissue_combo_tp"   -> 2 tissues x 3 combos x 5 TPs = up to 30 rows.
#   "top_k_per_tissue_combo_tp"  -> top K per tissue/combo/tp from training summary.
#   "all_train_ok"              -> diagnostic only; do not use to select final best by test R².
TEST_CONFIG_SELECTION_MODE = "top_n_per_tissue_tp"
TOP_N_PER_TISSUE_TP = 5
TOP_K_PER_TISSUE_COMBO_TP = 3

# Training-CV selection ranking columns.
# test_r2 must NEVER be used here.
TRAIN_SELECTION_SORT_COLUMNS = [
    "oof_r2",
    "mean_valid_r2",
    "final_full_train_best_score_inner_oof_r2",
    "oof_mae",
]

# ==========================================
# Leakage-free feature-wise weighting
# ==========================================
# Note:
# - feature weighting is computed only after fold-safe feature selection.
# - inner CV: inner-train only
# - final test: predefined train only
USE_FEATURE_WEIGHTING = True
FEATURE_WEIGHT_SCORE_MODE = "univariate_corr_soft_conservative"
FEATURE_WEIGHT_MIN = 1.0
FEATURE_WEIGHT_MAX = 1.20
FEATURE_WEIGHT_MIN_OBS = 8
FEATURE_WEIGHT_EXCLUDE_CLINICAL = True
FEATURE_WEIGHT_DEFAULT = 1.0

FEATURE_TRACE_DIR = SAVE_DIR / "feature_traces"
FEATURE_TRACE_DIR.mkdir(parents=True, exist_ok=True)

DETAIL_DIR = SAVE_DIR / "single_detail_outputs"
DETAIL_DIR.mkdir(parents=True, exist_ok=True)

print("TRAIN_SUMMARY_PATH:", TRAIN_SUMMARY_PATH.resolve())
print("SAVE_DIR:", SAVE_DIR.resolve())
print("DETAIL_DIR:", DETAIL_DIR.resolve())
print("TRAIN_EXPERIMENT_TAG:", TRAIN_EXPERIMENT_TAG)
print("TEST_EXPERIMENT_TAG:", TEST_EXPERIMENT_TAG)
print("TEST_CONFIG_SELECTION_MODE:", TEST_CONFIG_SELECTION_MODE)
print("MODEL_TYPES available:", MODEL_TYPES)
print("FEATURE_SELECTION_MODES_TO_RUN:", FEATURE_SELECTION_MODES_TO_RUN)
print("CLINICAL_MODES_TO_RUN:", CLINICAL_MODES_TO_RUN)
print("USE_FEATURE_WEIGHTING:", USE_FEATURE_WEIGHTING)
print("FEATURE_WEIGHT_SCORE_MODE:", FEATURE_WEIGHT_SCORE_MODE)
print("FEATURE_WEIGHT_RANGE:", (FEATURE_WEIGHT_MIN, FEATURE_WEIGHT_MAX))

TRAIN_SUMMARY_PATH: /data2/jinoh001/stable/research_SPI/DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/omics_paper_style_train_summary_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
SAVE_DIR: /data2/jinoh001/stable/research_SPI/DifferentCom_data_rebuild/testResult/results_single_omics_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible
DETAIL_DIR: /data2/jinoh001/stable/research_SPI/DifferentCom_data_rebuild/testResult/results_single_omics_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible/single_detail_outputs
TRAIN_EXPERIMENT_TAG: single_omics_train_paper_style_v11_rescue_expansion_v9compatible
TEST_EXPERIMENT_TAG: single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible
TEST_CONFIG_SELECTION_MODE: top_n_per_tissue_tp
MODEL_TYPES available: ['ridge', 'elasticnet', 'pls', 'svr_linear', 'gbr', 'xgboost']
FEATURE_SELECTION_MODES_TO_RUN: ['f_regression_topk', 'corr_topk']
CLINICAL_MODES_TO_RUN: ['light']
USE_FEATURE_WEIGHTING: True
FEATURE_WEIGHT_SCORE_MODE: univariate_corr_soft_conservative
FEATURE_WEIGHT_RANGE: (1.0, 1.2)

In [5]:
# ==========================================
# Parallel config
# ==========================================
TOTAL_CPUS = os.cpu_count() or 1

# 실험 단위 병렬화 권장
# 32 CPU 기준이면 6~8 정도부터 시작하는 게 안전
N_JOBS_EXPERIMENT = 8

print("TOTAL_CPUS:", TOTAL_CPUS)
print("N_JOBS_EXPERIMENT:", N_JOBS_EXPERIMENT)

TOTAL_CPUS: 32
N_JOBS_EXPERIMENT: 8

In [6]:
def read_id_txt(path: str) -> list[str]:
    """Read a one-column patient-id file.

    Expected format:
        Patient
        <id1>
        <id2>
        ...

    The function keeps IDs as strings so they match feature-table indexes.
    """
    df = pd.read_csv(path)
    if "Patient" not in df.columns:
        raise ValueError(f"{path} must contain a 'Patient' column. Found: {df.columns.tolist()}")
    ids = df["Patient"].dropna().astype(str).tolist()
    # keep order while removing duplicates
    return list(dict.fromkeys(ids))


TRAIN_ID_PATH = "../../data/training_id.txt"
TEST_ID_PATH = "../../data/testing_id.txt"

TRAIN_IDS = read_id_txt(TRAIN_ID_PATH)
TEST_IDS = read_id_txt(TEST_ID_PATH)

overlap_ids = sorted(set(TRAIN_IDS).intersection(TEST_IDS))

print("n TRAIN_IDS:", len(TRAIN_IDS))
print("n TEST_IDS :", len(TEST_IDS))
print("n overlap  :", len(overlap_ids))
print("overlap examples:", overlap_ids[:10])

if len(TEST_IDS) == 0:
    raise ValueError("TEST_IDS is empty. Check TEST_ID_PATH.")
if len(overlap_ids) > 0:
    raise ValueError("TRAIN_IDS and TEST_IDS overlap. This would leak holdout-test data.")

n TRAIN_IDS: 60
n TEST_IDS : 30
n overlap  : 0
overlap examples: []

In [7]:
def load_target(path: Path) -> pd.Series:
    """
    patient-level target loader
    """
    y = pd.read_csv(path, index_col=0).iloc[:, 0]
    y.index = y.index.astype(str)
    y.name = "DeltaTMS"
    return y

In [8]:
# ==========================================
# Alignment helpers
# ==========================================
def align_xy(X: pd.DataFrame, y: pd.Series) -> tuple[pd.DataFrame, pd.Series]:
    """
    Keep only patients that exist in both X and y.
    """
    idx = X.index.intersection(y.index)
    X = X.loc[idx].copy()
    y = y.loc[idx].copy()
    return X, y

In [9]:
def filter_sparse_features_train_test(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
    min_obs_frac: float = 0.7,
    protected_keep_cols: list[str] | None = None,
):
    if protected_keep_cols is None:
        protected_keep_cols = []

    protected_keep_cols = [c for c in protected_keep_cols if c in X_train.columns]

    # 1) constant columns 제거 (train 기준)
    nunique = X_train.nunique(dropna=True)
    const_drop_cols = [
        c for c in X_train.columns
        if nunique.get(c, 0) <= 1 and c not in protected_keep_cols
    ]
    X_train_1 = X_train.drop(columns=const_drop_cols)
    X_valid_1 = X_valid.drop(columns=[c for c in const_drop_cols if c in X_valid.columns])

    # 2) missing ratio 기준 filtering (train 기준)
    obs_frac = X_train_1.notna().mean(axis=0)
    keep_cols = [
        c for c in X_train_1.columns
        if (obs_frac.get(c, 0.0) >= min_obs_frac) or (c in protected_keep_cols)
    ]

    X_train_f = X_train_1.loc[:, keep_cols].copy()
    X_valid_f = X_valid_1.reindex(columns=keep_cols).copy()

    return X_train_f, X_valid_f

In [10]:
def _median_impute_numeric_train_valid(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Fit median imputation on X_train only, then apply to X_train/X_valid.
    This helper is used only for univariate scoring, not for final model fitting.
    """
    X_tr = X_train.apply(pd.to_numeric, errors="coerce")
    X_va = X_valid.apply(pd.to_numeric, errors="coerce")

    med = X_tr.median(axis=0, skipna=True)
    med = med.fillna(0.0)

    return X_tr.fillna(med), X_va.fillna(med)


def compute_univariate_feature_scores(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    protected_keep_cols: list[str] | None = None,
    min_obs: int = FEATURE_WEIGHT_MIN_OBS,
) -> pd.DataFrame:
    """
    Compute train-only univariate scores.

    Available score columns:
    - abs_corr: absolute Pearson correlation with DeltaTMS
    - f_score / p_value: sklearn f_regression score and p-value
    - neg_log10_p: larger means smaller p-value
    - hybrid_rank_score: combines corr-rank and p-value-rank

    Important:
    - This function must be called only on the training side of the current split.
    - It should never see validation/test y.
    """
    protected_keep_cols = protected_keep_cols or []
    protected_set = set(protected_keep_cols)

    candidate_cols = [c for c in X_train.columns if c not in protected_set]
    rows = []

    if len(candidate_cols) == 0:
        return pd.DataFrame(columns=[
            "feature", "abs_corr", "f_score", "p_value", "neg_log10_p",
            "corr_rank_score", "p_rank_score", "hybrid_rank_score",
            "is_protected",
        ])

    X_cand = X_train.loc[:, candidate_cols].copy()
    X_imp, _ = _median_impute_numeric_train_valid(X_cand, X_cand)
    y_num = pd.to_numeric(y_train, errors="coerce")

    valid_y = y_num.notna() & np.isfinite(y_num)
    X_imp = X_imp.loc[valid_y]
    y_num = y_num.loc[valid_y]

    if len(y_num) >= 3 and y_num.nunique(dropna=True) > 1:
        try:
            f_vals, p_vals = f_regression(X_imp, y_num)
        except Exception:
            f_vals = np.zeros(len(candidate_cols), dtype=float)
            p_vals = np.ones(len(candidate_cols), dtype=float)
    else:
        f_vals = np.zeros(len(candidate_cols), dtype=float)
        p_vals = np.ones(len(candidate_cols), dtype=float)

    for j, col in enumerate(candidate_cols):
        abs_corr = _safe_abs_corr(X_train[col], y_train, min_obs=min_obs)
        f_score = float(f_vals[j]) if np.isfinite(f_vals[j]) else 0.0
        p_value = float(p_vals[j]) if np.isfinite(p_vals[j]) else 1.0
        p_value = max(p_value, 1e-300)
        rows.append({
            "feature": col,
            "abs_corr": float(abs_corr),
            "f_score": f_score,
            "p_value": p_value,
            "neg_log10_p": float(-np.log10(p_value)),
            "is_protected": False,
        })

    score_df = pd.DataFrame(rows)

    # rank scores: higher is better
    if len(score_df) > 0:
        score_df["corr_rank_score"] = score_df["abs_corr"].rank(method="average", pct=True)
        score_df["p_rank_score"] = score_df["neg_log10_p"].rank(method="average", pct=True)
        score_df["hybrid_rank_score"] = 0.5 * score_df["corr_rank_score"] + 0.5 * score_df["p_rank_score"]

    return score_df


def select_features_train_valid(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
    y_train: pd.Series,
    k: int | None,
    mode: str = "f_regression_topk",
    protected_keep_cols: list[str] | None = None,
    min_obs: int = FEATURE_WEIGHT_MIN_OBS,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, list[str]]:
    """
    Fold-safe feature selection.

    This replaces the old approach where target-aware top-k was applied once
    before inner CV. Here, feature selection is repeated inside each inner fold
    using only that fold's training data.

    Modes:
    - "none": keep all columns
    - "corr_topk": top-k by abs correlation with y_train
    - "f_regression_topk": top-k by univariate f_regression p-value
    - "hybrid_topk": top-k by combined corr/p-value rank
    """
    protected_keep_cols = protected_keep_cols or []
    protected_keep_cols = [c for c in protected_keep_cols if c in X_train.columns]

    if mode == "none" or k is None or k <= 0:
        selected_features = list(X_train.columns)
        score_df = pd.DataFrame({
            "feature": selected_features,
            "selected": True,
            "selection_mode": mode,
            "selection_score": np.nan,
            "is_protected": [c in protected_keep_cols for c in selected_features],
        })
        return (
            X_train.loc[:, selected_features].copy(),
            X_valid.reindex(columns=selected_features).copy(),
            score_df,
            selected_features,
        )

    score_df = compute_univariate_feature_scores(
        X_train=X_train,
        y_train=y_train,
        protected_keep_cols=protected_keep_cols,
        min_obs=min_obs,
    )

    if mode == "corr_topk":
        sort_col = "abs_corr"
    elif mode == "f_regression_topk":
        sort_col = "neg_log10_p"
    elif mode == "hybrid_topk":
        sort_col = "hybrid_rank_score"
    else:
        raise ValueError(f"Unknown feature_selection_mode: {mode}")

    candidate_cols = [c for c in X_train.columns if c not in set(protected_keep_cols)]
    k_for_candidates = max(0, int(k) - len(protected_keep_cols))

    if len(candidate_cols) == 0 or k_for_candidates == 0 or len(score_df) == 0:
        top_candidate_cols = []
    else:
        top_candidate_cols = (
            score_df.sort_values(sort_col, ascending=False)
                    .head(min(k_for_candidates, len(score_df)))["feature"]
                    .tolist()
        )

    selected_set = set(protected_keep_cols + top_candidate_cols)
    selected_features = [c for c in X_train.columns if c in selected_set]

    if len(selected_features) == 0:
        # Absolute fallback to avoid failed runs.
        selected_features = list(X_train.columns)

    out_score = score_df.copy()
    if len(out_score) > 0:
        out_score["selected"] = out_score["feature"].isin(selected_features)
        out_score["selection_mode"] = mode
        out_score["selection_score"] = out_score[sort_col]
        protected_rows = pd.DataFrame({
            "feature": protected_keep_cols,
            "abs_corr": np.nan,
            "f_score": np.nan,
            "p_value": np.nan,
            "neg_log10_p": np.nan,
            "corr_rank_score": np.nan,
            "p_rank_score": np.nan,
            "hybrid_rank_score": np.nan,
            "is_protected": True,
            "selected": True,
            "selection_mode": mode,
            "selection_score": np.nan,
        })
        out_score = pd.concat([protected_rows, out_score], ignore_index=True)

    return (
        X_train.loc[:, selected_features].copy(),
        X_valid.reindex(columns=selected_features).copy(),
        out_score,
        selected_features,
    )


def top_k_target_corr_filter(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
    y_train: pd.Series,
    k: int | None,
    protected_keep_cols: list[str] | None = None,
    min_obs: int = FEATURE_WEIGHT_MIN_OBS,
):
    """
    Backward-compatible wrapper.
    New code should use select_features_train_valid(..., mode="corr_topk").
    """
    X_tr, X_va, _, _ = select_features_train_valid(
        X_train=X_train,
        X_valid=X_valid,
        y_train=y_train,
        k=k,
        mode="corr_topk",
        protected_keep_cols=protected_keep_cols,
        min_obs=min_obs,
    )
    return X_tr, X_va

In [11]:
from sklearn.impute import KNNImputer


def make_preprocess(X: pd.DataFrame) -> ColumnTransformer:
    cat = [c for c in X.columns if c in ["Gender", "Level"]]
    num = [c for c in X.columns if c not in cat]

    preprocess = ColumnTransformer(
        transformers=[
            ("num", Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]), num),
            ("cat", Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("ohe", OneHotEncoder(handle_unknown="ignore")),
            ]), cat),
        ],
        remainder="drop",
        verbose_feature_names_out=False
    )

    try:
        preprocess.set_output(transform="pandas")
    except Exception:
        pass

    return preprocess


def make_model(model_type: str):
    """
    Model families are intentionally kept conservative because this dataset is small.
    Tree/boosting models use shallow settings through the parameter grid.
    """
    if model_type == "lasso":
        return Lasso(max_iter=50000, random_state=RANDOM_STATE, tol=1e-3)
    elif model_type == "elasticnet":
        return ElasticNet(max_iter=50000, random_state=RANDOM_STATE, tol=1e-3)
    elif model_type == "ridge":
        return Ridge()
    elif model_type == "lassolars":
        return LassoLars()
    elif model_type == "pls":
        return PLSRegression(scale=False)
    elif model_type == "svr_linear":
        return SVR(kernel="linear")
    elif model_type == "svr_rbf":
        return SVR(kernel="rbf")
    elif model_type == "knn":
        return KNeighborsRegressor()
    elif model_type == "rf":
        return RandomForestRegressor(random_state=RANDOM_STATE, n_jobs=1)
    elif model_type == "extratrees":
        return ExtraTreesRegressor(random_state=RANDOM_STATE, n_jobs=1)
    elif model_type == "gbr":
        return GradientBoostingRegressor(random_state=RANDOM_STATE)
    elif model_type == "xgboost":
        if not XGBOOST_AVAILABLE or XGBRegressor is None:
            raise ImportError("xgboost is not installed, so model_type='xgboost' cannot be used.")
        return XGBRegressor(
            objective="reg:squarederror",
            random_state=RANDOM_STATE,
            n_jobs=1,
            tree_method="hist",
            verbosity=0,
        )
    elif model_type == "histgbr":
        return HistGradientBoostingRegressor(random_state=RANDOM_STATE)
    else:
        raise ValueError(f"Unknown model_type: {model_type}")


def make_param_grid(model_type: str) -> dict:
    """
    Reduced hyperparameter grids for the training paper-style run.

    Purpose:
    - keep the full model family list
    - reduce alpha / major model grids enough to make the run practical
    - avoid the previous very long runtime from large nested CV grids
    """
    common_num_imputers = [SimpleImputer(strategy="median")]

    if model_type == "lasso":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__alpha": [0.1, 0.5],
        }

    elif model_type == "elasticnet":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__alpha": [0.05, 0.1, 0.5, 1.0],
            "model__l1_ratio": [0.1, 0.2, 0.5],
        }

    elif model_type == "ridge":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__alpha": [5.0, 10.0, 25.0, 50.0, 100.0],
        }

    elif model_type == "lassolars":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__alpha": [0.01, 0.1],
        }

    elif model_type == "pls":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_components": [2, 3],
        }

    elif model_type == "svr_linear":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__C": [0.03, 0.1, 0.3, 1.0],
            "model__epsilon": [0.1, 0.2],
        }

    elif model_type == "svr_rbf":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__C": [1.0],
            "model__epsilon": [0.1],
            "model__gamma": ["scale"],
        }

    elif model_type == "knn":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_neighbors": [3, 5],
            "model__weights": ["distance"],
        }

    elif model_type == "rf":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_estimators": [100],
            "model__max_depth": [2, 3],
            "model__min_samples_leaf": [2],
            "model__max_features": ["sqrt"],
        }

    elif model_type == "extratrees":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_estimators": [100],
            "model__max_depth": [2, 3],
            "model__min_samples_leaf": [2],
            "model__max_features": ["sqrt"],
        }

    elif model_type == "gbr":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_estimators": [30, 50],
            "model__learning_rate": [0.03, 0.05],
            "model__max_depth": [1],
            "model__min_samples_leaf": [3, 5],
            "model__subsample": [0.8],
        }

    elif model_type == "xgboost":
        # Conservative XGBoost grid for small-n/high-p single-omics data.
        # Goal: test regularized boosting without allowing train R2 to dominate model selection.
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__n_estimators": [50, 80],
            "model__max_depth": [1, 2],
            "model__learning_rate": [0.03],
            "model__subsample": [0.8],
            "model__colsample_bytree": [0.7, 0.9],
            "model__reg_alpha": [0.5, 1.0],
            "model__reg_lambda": [5.0, 10.0],
            "model__min_child_weight": [2, 4],
        }

    elif model_type == "histgbr":
        return {
            "preprocess__num__imputer": common_num_imputers,
            "model__max_iter": [50],
            "model__learning_rate": [0.05],
            "model__max_leaf_nodes": [5],
            "model__l2_regularization": [0.1],
        }

    else:
        raise ValueError(f"Unknown model_type: {model_type}")

def adjust_param_grid_for_training_data(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    model_type: str,
) -> list[dict]:
    """
    Remove parameter settings that cannot work for the current train fold.
    Example: PLS n_components must be <= min(n_samples - 1, n_features).
    """
    grid = list(ParameterGrid(make_param_grid(model_type=model_type)))

    n_samples = int(X_train.shape[0])
    n_features = int(X_train.shape[1])

    valid_grid = []
    for params in grid:
        ok = True

        if model_type == "pls":
            n_comp = int(params.get("model__n_components", 1))
            if n_comp > max(1, min(n_samples - 1, n_features)):
                ok = False

        if model_type == "knn":
            n_neighbors = int(params.get("model__n_neighbors", 5))
            if n_neighbors >= n_samples:
                ok = False

        if ok:
            valid_grid.append(params)

    if len(valid_grid) == 0:
        # Fallback to a safe default for very small folds.
        if model_type == "pls":
            return [{
                "preprocess__num__imputer": SimpleImputer(strategy="median"),
                "model__n_components": 1,
            }]
        if model_type == "knn":
            return [{
                "preprocess__num__imputer": SimpleImputer(strategy="median"),
                "model__n_neighbors": max(1, min(3, n_samples - 1)),
                "model__weights": "distance",
            }]
        return grid

    return valid_grid


def make_pipeline(
    X: pd.DataFrame,
    model_type: str,
    feature_weight_map: dict[str, float] | None = None,
) -> Pipeline:
    preprocess = make_preprocess(X)
    model = make_model(model_type)

    steps = [
        ("preprocess", preprocess),
    ]

    if USE_FEATURE_WEIGHTING:
        steps.append((
            "feature_weight",
            FeatureWeightTransformer(
                feature_weight_map=feature_weight_map,
                default_weight=FEATURE_WEIGHT_DEFAULT,
                enabled=USE_FEATURE_WEIGHTING,
            ),
        ))

    steps.append(("model", model))

    return Pipeline(steps)


def predict_1d(model: Pipeline, X: pd.DataFrame) -> np.ndarray:
    """
    Some models, e.g. PLSRegression, return shape (n, 1).
    Standardize all predictions to 1D.
    """
    return np.ravel(model.predict(X))

In [12]:
def build_feature_path(feature_mode: str, tissue: str, combo: str, tp: int) -> Path:
    if feature_mode == "omics":
        return TP_DIR / f"x_omics_{tissue}_{combo}_{tp}.csv"
    elif feature_mode == "omicsdelta":
        return TP_DIR / f"x_omicsdelta_{tissue}_{combo}_{tp}.csv"
    else:
        raise ValueError(f"Unknown feature_mode: {feature_mode}")

def build_clinical_feature_path(tissue: str, combo: str, tp: int) -> Path:
    return TP_DIR / f"x_clinical_{tissue}_{combo}_{tp}.csv"


def load_feature_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    if "Patient" not in df.columns:
        raise ValueError(f"'Patient' not found in {path}")
    df = df.set_index("Patient")
    df.index = df.index.astype(str)
    return df

def dataframe_content_signature(df: pd.DataFrame) -> str:
    """
    Lightweight diagnostic hash used to check whether two TP feature matrices
    are accidentally identical. This is not used for modeling.
    """
    if df is None or len(df) == 0:
        return "EMPTY"
    tmp = df.copy()
    tmp = tmp.sort_index(axis=0).sort_index(axis=1)
    col_part = "|".join(map(str, tmp.columns))
    shape_part = f"{tmp.shape[0]}x{tmp.shape[1]}"
    # hash_pandas_object handles mixed dtypes after string fallback; keep it lightweight.
    try:
        values_hash = pd.util.hash_pandas_object(tmp.astype(str), index=True).values.tobytes()
    except Exception:
        values_hash = tmp.to_csv(index=True).encode("utf-8")
    return hashlib.md5((shape_part + "|" + col_part).encode("utf-8") + values_hash).hexdigest()

In [13]:
def get_clinical_columns() -> list[str]:
    return ["Age", "Gender", "Level"]


def get_hard_forbidden_proxy_columns() -> list[str]:
    return [
        "TMS_Base", "UEMS_Base", "LEMS_Base",
        "TMS_6mo", "UEMS_6mo", "LEMS_6mo",
        "AIS_6mo",
        "DeltaTMS", "DeltaUEMS", "DeltaLEMS",
    ]


def assert_no_forbidden_proxy_columns(
    X: pd.DataFrame,
    use_light_clinical: bool = False,
):
    hard_bad = [c for c in X.columns if c in get_hard_forbidden_proxy_columns()]
    if len(hard_bad) > 0:
        raise ValueError(f"Hard forbidden proxy/leakage columns found: {hard_bad}")

    all_clinical_like = [
        "Age", "Gender", "Level", "AIS", "AIS_Base", "AIS_Base_Numeric",
        "TMS_Base", "UEMS_Base", "LEMS_Base",
        "TMS_6mo", "UEMS_6mo", "LEMS_6mo", "AIS_6mo",
        "DeltaTMS", "DeltaUEMS", "DeltaLEMS",
    ]

    allowed = set(get_clinical_columns()) if use_light_clinical else set()
    soft_bad = [
        c for c in X.columns
        if (c in all_clinical_like and c not in allowed and c not in get_hard_forbidden_proxy_columns())
    ]

    if len(soft_bad) > 0:
        raise ValueError(f"Unexpected clinical columns found for this mode: {soft_bad}")

In [14]:
def load_light_clinical_block(
    tissue: str,
    combo: str,
    tp: int,
) -> pd.DataFrame:
    clin_path = build_clinical_feature_path(tissue=tissue, combo=combo, tp=tp)
    clin_df = load_feature_csv(clin_path)

    keep_cols = [c for c in get_clinical_columns() if c in clin_df.columns]
    clin_df = clin_df.loc[:, keep_cols].copy()

    missing_cols = [c for c in get_clinical_columns() if c not in clin_df.columns]
    if len(missing_cols) > 0:
        print(f"[WARN] missing light clinical columns in {clin_path.name}: {missing_cols}")

    if "Age" in clin_df.columns:
        clin_df["Age"] = pd.to_numeric(clin_df["Age"], errors="coerce")

    return clin_df


def merge_with_light_clinical(
    X_feat: pd.DataFrame,
    tissue: str,
    combo: str,
    tp: int,
) -> pd.DataFrame:
    clin_df = load_light_clinical_block(tissue=tissue, combo=combo, tp=tp)

    common_ids = X_feat.index.intersection(clin_df.index)
    X_feat2 = X_feat.loc[common_ids].copy()
    clin_df2 = clin_df.loc[common_ids].copy()

    X_merged = pd.concat([X_feat2, clin_df2], axis=1)

    dup_cols = X_merged.columns[X_merged.columns.duplicated()].tolist()
    if len(dup_cols) > 0:
        raise ValueError(f"Duplicate columns after light clinical merge: {dup_cols}")

    return X_merged

In [15]:
def encode_clinical_train_valid(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, list[str]]:
    """
    Clinical block은 train 기준으로만 encoding한다.
    반환:
      - encoded X_train
      - encoded X_valid
      - encoded clinical column names
    """
    base_clin_cols = [c for c in get_clinical_columns() if c in X_train.columns]
    if len(base_clin_cols) == 0:
        return X_train, X_valid, []

    tr_clin = X_train.loc[:, base_clin_cols].copy()
    va_clin = X_valid.loc[:, [c for c in base_clin_cols if c in X_valid.columns]].copy()

    tr_other = X_train.drop(columns=base_clin_cols, errors="ignore").copy()
    va_other = X_valid.drop(columns=base_clin_cols, errors="ignore").copy()

    if "Age" in tr_clin.columns:
        tr_clin["Age"] = pd.to_numeric(tr_clin["Age"], errors="coerce")
    if "Age" in va_clin.columns:
        va_clin["Age"] = pd.to_numeric(va_clin["Age"], errors="coerce")

    cat_cols = [c for c in ["Gender", "Level"] if c in tr_clin.columns]

    if len(cat_cols) > 0:
        tr_clin_enc = pd.get_dummies(
            tr_clin,
            columns=cat_cols,
            dummy_na=True,
            dtype=float,
        )
        va_clin_enc = pd.get_dummies(
            va_clin,
            columns=cat_cols,
            dummy_na=True,
            dtype=float,
        )
        va_clin_enc = va_clin_enc.reindex(columns=tr_clin_enc.columns, fill_value=0.0)
    else:
        tr_clin_enc = tr_clin.copy()
        va_clin_enc = va_clin.copy()

    tr_clin_enc = tr_clin_enc.apply(pd.to_numeric, errors="coerce")
    va_clin_enc = va_clin_enc.apply(pd.to_numeric, errors="coerce")

    encoded_clin_cols = tr_clin_enc.columns.tolist()

    X_train_out = pd.concat([tr_other, tr_clin_enc], axis=1)
    X_valid_out = pd.concat([va_other, va_clin_enc], axis=1)

    return X_train_out, X_valid_out, encoded_clin_cols

In [16]:
# # ==========================================
# # Inner CV tuning
# # ==========================================
# def fit_best_model(
#     X_train: pd.DataFrame,
#     y_train: pd.Series,
#     groups_train: np.ndarray,
#     model_type: str,
#     n_splits_inner: int = 3,
# ):
#     """
#     Tune hyperparameters only on the training fold.
#     """
#     pipe = make_pipeline(X_train, model_type=model_type)
#     param_grid = make_param_grid(model_type=model_type)

#     if model_type in ["lasso", "elasticnet"] and "select__k" in param_grid:
#         preprocess = make_preprocess(X_train)
#         X_train_tx = preprocess.fit_transform(X_train, y_train)
#         n_features_after_preprocess = X_train_tx.shape[1]

#         valid_k = sorted({
#             int(k)
#             for k in param_grid["select__k"]
#             if int(k) <= n_features_after_preprocess
#         })

#         if len(valid_k) == 0:
#             valid_k = [max(1, n_features_after_preprocess)]

#         param_grid["select__k"] = valid_k

#     inner_cv = GroupKFold(n_splits=n_splits_inner)

#     gs = GridSearchCV(
#         estimator=pipe,
#         param_grid=param_grid,
#         scoring="r2",
#         cv=inner_cv,
#         n_jobs=12,
#         refit=True,
#     )
#     gs.fit(X_train, y_train, groups=groups_train)

#     return gs.best_estimator_, gs.best_params_, gs.best_score_

In [17]:
class FeatureWeightTransformer(BaseEstimator, TransformerMixin):
    """
    Apply precomputed feature-wise weights after preprocessing/scaling.

    Why after preprocessing?
    - If weights are applied before StandardScaler, StandardScaler can cancel out most
      multiplicative effects.
    - Applying after preprocessing means the model sees the weighted feature matrix.

    Leakage rule:
    - feature_weight_map must be computed outside this transformer using train data only.
    - validation/test y is never used here.
    """
    def __init__(
        self,
        feature_weight_map: dict[str, float] | None = None,
        default_weight: float = 1.0,
        enabled: bool = True,
    ):
        self.feature_weight_map = feature_weight_map
        self.default_weight = default_weight
        self.enabled = enabled

    def fit(self, X, y=None):
        if not self.enabled or self.feature_weight_map is None:
            self.weights_ = np.ones(X.shape[1], dtype=float)
            self.feature_names_ = list(getattr(X, "columns", [f"x{i}" for i in range(X.shape[1])]))
            return self

        if hasattr(X, "columns"):
            self.feature_names_ = list(X.columns)
            weights = []
            for feat in self.feature_names_:
                feat_str = str(feat)

                # exact match for numeric/transformed numeric columns
                w = self.feature_weight_map.get(feat_str, None)

                # fallback for one-hot names such as Gender_M or Level_C
                if w is None:
                    base = feat_str.split("_")[0]
                    w = self.feature_weight_map.get(base, self.default_weight)

                weights.append(float(w))

            self.weights_ = np.asarray(weights, dtype=float)
        else:
            # fallback: if sklearn cannot output pandas, keep neutral weighting
            self.feature_names_ = [f"x{i}" for i in range(X.shape[1])]
            self.weights_ = np.ones(X.shape[1], dtype=float)

        return self

    def transform(self, X):
        if not self.enabled:
            return X

        if hasattr(X, "copy") and hasattr(X, "columns"):
            Xw = X.copy()
            for col, w in zip(Xw.columns, self.weights_):
                Xw[col] = Xw[col] * float(w)
            return Xw

        return X * self.weights_


def _safe_abs_corr(x: pd.Series, y: pd.Series, min_obs: int) -> float:
    x_num = pd.to_numeric(x, errors="coerce")
    y_num = pd.to_numeric(y, errors="coerce")
    mask = x_num.notna() & y_num.notna() & np.isfinite(x_num) & np.isfinite(y_num)

    if int(mask.sum()) < min_obs:
        return 0.0

    xv = x_num.loc[mask]
    yv = y_num.loc[mask]

    if xv.nunique(dropna=True) <= 1 or yv.nunique(dropna=True) <= 1:
        return 0.0

    corr = xv.corr(yv)
    if pd.isna(corr) or not np.isfinite(corr):
        return 0.0

    return float(abs(corr))


def compute_feature_weight_map_from_train(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    protected_keep_cols: list[str] | None = None,
    min_weight: float = FEATURE_WEIGHT_MIN,
    max_weight: float = FEATURE_WEIGHT_MAX,
    min_obs: int = FEATURE_WEIGHT_MIN_OBS,
) -> tuple[dict[str, float], pd.DataFrame]:
    """
    Compute feature weights using outer-train data only.

    Current score:
    - absolute Pearson correlation between feature and DeltaTMS within train data
    - clinical/protected columns are kept at weight 1.0 by default

    This is intentionally simple and conservative. It can be replaced later by
    selection-frequency or coefficient-stability scoring, but this version is safer
    as the first feature-weighting experiment.
    """
    protected_keep_cols = protected_keep_cols or []
    protected_set = set(protected_keep_cols)

    rows = []
    for col in X_train.columns:
        is_protected = col in protected_set

        if FEATURE_WEIGHT_EXCLUDE_CLINICAL and is_protected:
            score = 0.0
            weight = FEATURE_WEIGHT_DEFAULT
        else:
            score = _safe_abs_corr(X_train[col], y_train, min_obs=min_obs)
            weight = np.nan

        rows.append({
            "feature": col,
            "feature_score": float(score),
            "is_protected": bool(is_protected),
            "weight": weight,
        })

    score_df = pd.DataFrame(rows)

    eligible = score_df["weight"].isna()
    if eligible.any():
        s = score_df.loc[eligible, "feature_score"].astype(float)
        s_min = float(s.min())
        s_max = float(s.max())

        if np.isclose(s_min, s_max):
            scaled = pd.Series(0.0, index=s.index)
        else:
            scaled = (s - s_min) / (s_max - s_min)

        score_df.loc[eligible, "weight"] = min_weight + scaled * (max_weight - min_weight)

    score_df["weight"] = score_df["weight"].fillna(FEATURE_WEIGHT_DEFAULT).astype(float)
    score_df = score_df.sort_values(
        ["weight", "feature_score"],
        ascending=[False, False],
    ).reset_index(drop=True)

    weight_map = dict(zip(score_df["feature"].astype(str), score_df["weight"].astype(float)))

    return weight_map, score_df


def build_feature_weights(
    feature_score_df: pd.DataFrame,
    mode: str = "soft",
    top_k: int = 50,
    high_weight: float = 1.5,
    low_weight: float = 0.5,
    min_weight: float = 0.5,
    max_weight: float = 1.5,
):
    """
    Backward-compatible helper.
    Existing code may still call this function.
    """
    df = feature_score_df.copy()

    if len(df) == 0:
        return pd.DataFrame(columns=["feature", "weight"])

    if mode == "topk":
        df["weight"] = low_weight
        top_feats = df.head(top_k)["feature"].tolist()
        df.loc[df["feature"].isin(top_feats), "weight"] = high_weight

    elif mode == "soft":
        s = df["feature_score"].values.astype(float)
        s_min, s_max = s.min(), s.max()
        if np.isclose(s_min, s_max):
            scaled = np.ones_like(s)
        else:
            scaled = (s - s_min) / (s_max - s_min)
        df["weight"] = min_weight + scaled * (max_weight - min_weight)

    else:
        raise ValueError(f"Unknown weighting mode: {mode}")

    return df[["feature", "weight"]].copy()

In [18]:
def extract_final_feature_info(fitted_pipeline: Pipeline) -> pd.DataFrame:
    preprocess = fitted_pipeline.named_steps["preprocess"]
    feature_names = list(preprocess.get_feature_names_out())

    model = fitted_pipeline.named_steps["model"]

    coef = None
    if hasattr(model, "coef_"):
        coef = np.ravel(model.coef_)
    elif hasattr(model, "x_weights_"):
        # PLS does not expose coef_ in exactly the same way across sklearn versions.
        # x_weights_ is not identical to regression coefficients, but it is useful as a trace.
        coef = np.ravel(getattr(model, "x_weights_", np.array([])))

    if coef is not None and len(coef) == len(feature_names):
        coef_list = coef.tolist()
    else:
        coef_list = [np.nan] * len(feature_names)

    feature_df = pd.DataFrame({
        "feature": feature_names,
        "coef": coef_list,
        "abs_coef": np.abs(coef_list),
    })

    if USE_FEATURE_WEIGHTING and "feature_weight" in fitted_pipeline.named_steps:
        fw = fitted_pipeline.named_steps["feature_weight"]
        weight_by_processed = dict(zip(getattr(fw, "feature_names_", []), getattr(fw, "weights_", [])))
        feature_df["feature_weight"] = feature_df["feature"].map(weight_by_processed).fillna(FEATURE_WEIGHT_DEFAULT)
    else:
        feature_df["feature_weight"] = FEATURE_WEIGHT_DEFAULT

    feature_df = feature_df.sort_values(
        "abs_coef",
        ascending=False,
        na_position="last",
    ).reset_index(drop=True)

    return feature_df


def make_regression_strata(
    y: pd.Series,
    n_bins: int,
    n_splits: int,
) -> pd.Series:
    """
    Quantile-based strata for regression CV.
    """
    y_num = pd.to_numeric(y, errors="coerce")

    if y_num.notna().sum() < n_splits:
        return pd.Series(index=y.index, data=0).astype(int)

    max_bins = min(n_bins, int(y_num.nunique()))

    for bins in range(max_bins, 1, -1):
        try:
            y_bin = pd.qcut(
                y_num,
                q=bins,
                labels=False,
                duplicates="drop",
            )
            y_bin = pd.Series(y_bin, index=y.index)

            counts = y_bin.value_counts(dropna=True)

            if len(counts) >= 2 and counts.min() >= n_splits:
                return y_bin.fillna(-1).astype(int)

        except Exception:
            continue

    return pd.Series(index=y.index, data=0).astype(int)


def make_outer_cv_splits(
    X: pd.DataFrame,
    y: pd.Series,
    groups: np.ndarray,
    n_splits: int,
):
    """
    Outer CV split helper.
    """
    if USE_STRATIFIED_OUTER_CV and X.index.is_unique:
        y_bins = make_regression_strata(
            y=y,
            n_bins=N_Y_BINS_FOR_OUTER_CV,
            n_splits=n_splits,
        )

        if y_bins.nunique(dropna=True) >= 2:
            outer_cv = StratifiedKFold(
                n_splits=n_splits,
                shuffle=True,
                random_state=OUTER_CV_RANDOM_STATE,
            )
            return list(outer_cv.split(X, y_bins)), "StratifiedKFold_y_bins"

    outer_cv = GroupKFold(n_splits=n_splits)
    return list(outer_cv.split(X, y, groups=groups)), "GroupKFold_fallback"


def make_inner_cv_splits(
    X: pd.DataFrame,
    y: pd.Series,
    groups: np.ndarray,
    n_splits: int,
):
    """
    Inner CV split helper.

    목적:
    - model/alpha/top-k 선택이 특정 fold의 y 분포 때문에 흔들리는 것을 줄인다.
    - patient index가 unique이면 y-bin stratified split을 사용한다.
    - 실패하면 GroupKFold로 fallback한다.
    """
    if X.index.is_unique:
        y_bins = make_regression_strata(
            y=y,
            n_bins=N_Y_BINS_FOR_OUTER_CV,
            n_splits=n_splits,
        )

        if y_bins.nunique(dropna=True) >= 2:
            inner_cv = StratifiedKFold(
                n_splits=n_splits,
                shuffle=True,
                random_state=RANDOM_STATE,
            )
            return list(inner_cv.split(X, y_bins)), "StratifiedKFold_y_bins"

    inner_cv = GroupKFold(n_splits=n_splits)
    return list(inner_cv.split(X, y, groups=groups)), "GroupKFold_fallback"


def fit_best_model_only(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    groups_train: np.ndarray,
    candidate_models: list[str],
    n_splits_inner: int = 3,
    protected_keep_cols: list[str] | None = None,
    feature_selection_mode: str = "f_regression_topk",
    top_k_after_sparse: int | None = 100,
):
    """
    Select model/hyperparameters using train-side inner OOF R².

    Paper-style leakage rule:
    - In each inner fold, feature selection is fitted only on inner-train.
    - Inner-validation y is never used for feature selection or feature weighting.
    - Final feature selection is fitted only on the full predefined training set.
    - Holdout test y is never used until final evaluation.
    """
    protected_keep_cols = protected_keep_cols or []

    search_rows = []
    best_obj = None
    best_score = -np.inf

    inner_splits, inner_cv_type = make_inner_cv_splits(
        X=X_train,
        y=y_train,
        groups=groups_train,
        n_splits=n_splits_inner,
    )

    for model_type in candidate_models:
        grid = adjust_param_grid_for_training_data(
            X_train=X_train,
            y_train=y_train,
            model_type=model_type,
        )

        for params in grid:
            inner_oof = pd.Series(index=X_train.index, dtype=float)
            inner_fold_scores = []
            inner_n_features = []

            for inner_fold, (tr_idx, va_idx) in enumerate(inner_splits, start=1):
                X_tr_raw = X_train.iloc[tr_idx].copy()
                y_tr = y_train.iloc[tr_idx].copy()
                X_va_raw = X_train.iloc[va_idx].copy()
                y_va = y_train.iloc[va_idx].copy()

                X_tr, X_va, _, selected_features = select_features_train_valid(
                    X_train=X_tr_raw,
                    X_valid=X_va_raw,
                    y_train=y_tr,
                    k=top_k_after_sparse,
                    mode=feature_selection_mode,
                    protected_keep_cols=protected_keep_cols,
                )
                inner_n_features.append(len(selected_features))

                if USE_FEATURE_WEIGHTING:
                    inner_weight_map, _ = compute_feature_weight_map_from_train(
                        X_train=X_tr,
                        y_train=y_tr,
                        protected_keep_cols=[c for c in protected_keep_cols if c in X_tr.columns],
                    )
                else:
                    inner_weight_map = None

                pipe = make_pipeline(
                    X_tr,
                    model_type=model_type,
                    feature_weight_map=inner_weight_map,
                )
                pipe.set_params(**params)
                pipe.fit(X_tr, y_tr)

                pred = predict_1d(pipe, X_va)
                inner_oof.iloc[va_idx] = pred

                try:
                    inner_fold_scores.append(float(r2_score(y_va, pred)))
                except Exception:
                    inner_fold_scores.append(np.nan)

            valid_mask = inner_oof.notna()

            if valid_mask.sum() >= 2:
                inner_oof_r2 = float(
                    r2_score(
                        y_train.loc[valid_mask],
                        inner_oof.loc[valid_mask],
                    )
                )
                inner_oof_mae = float(
                    mean_absolute_error(
                        y_train.loc[valid_mask],
                        inner_oof.loc[valid_mask],
                    )
                )
            else:
                inner_oof_r2 = np.nan
                inner_oof_mae = np.nan

            inner_mean_fold_r2 = (
                float(np.nanmean(inner_fold_scores))
                if len(inner_fold_scores) > 0 and not np.all(pd.isna(inner_fold_scores))
                else np.nan
            )

            inner_std_fold_r2 = (
                float(np.nanstd(inner_fold_scores))
                if len(inner_fold_scores) > 0 and not np.all(pd.isna(inner_fold_scores))
                else np.nan
            )

            if pd.notna(inner_oof_r2):
                selection_score = float(inner_oof_r2)
                if pd.notna(inner_std_fold_r2):
                    selection_score -= INNER_SELECTION_STD_PENALTY * float(inner_std_fold_r2)
            else:
                selection_score = np.nan

            search_rows.append({
                "model_type": model_type,
                "params": json.dumps(params, default=str),
                "inner_mean_r2": inner_oof_r2,
                "inner_oof_r2": inner_oof_r2,
                "inner_oof_mae": inner_oof_mae,
                "inner_mean_fold_r2": inner_mean_fold_r2,
                "inner_std_fold_r2": inner_std_fold_r2,
                "selection_score_stability_penalized": selection_score,
                "inner_cv_type": inner_cv_type,
                "feature_selection_mode": feature_selection_mode,
                "top_k_after_sparse": top_k_after_sparse,
                "mean_inner_selected_features": (
                    float(np.mean(inner_n_features)) if len(inner_n_features) > 0 else np.nan
                ),
                "min_inner_selected_features": (
                    int(np.min(inner_n_features)) if len(inner_n_features) > 0 else np.nan
                ),
                "max_inner_selected_features": (
                    int(np.max(inner_n_features)) if len(inner_n_features) > 0 else np.nan
                ),
                "use_feature_weighting": USE_FEATURE_WEIGHTING,
                "feature_weight_min": FEATURE_WEIGHT_MIN if USE_FEATURE_WEIGHTING else np.nan,
                "feature_weight_max": FEATURE_WEIGHT_MAX if USE_FEATURE_WEIGHTING else np.nan,
            })

            if pd.notna(selection_score) and selection_score > best_score:
                best_score = selection_score
                best_obj = {
                    "model_type": model_type,
                    "params": params,
                }

    if best_obj is None:
        raise ValueError("No valid model/parameter combination found in fit_best_model_only")

    # Final train-only feature selection for the holdout test model.
    X_train_sel, _, final_selection_df, selected_features = select_features_train_valid(
        X_train=X_train,
        X_valid=X_train,
        y_train=y_train,
        k=top_k_after_sparse,
        mode=feature_selection_mode,
        protected_keep_cols=protected_keep_cols,
    )

    if USE_FEATURE_WEIGHTING:
        final_weight_map, final_weight_df = compute_feature_weight_map_from_train(
            X_train=X_train_sel,
            y_train=y_train,
            protected_keep_cols=[c for c in protected_keep_cols if c in X_train_sel.columns],
        )
    else:
        final_weight_map = None
        final_weight_df = pd.DataFrame(columns=["feature", "feature_score", "is_protected", "weight"])

    final_pipe = make_pipeline(
        X_train_sel,
        model_type=best_obj["model_type"],
        feature_weight_map=final_weight_map,
    )
    final_pipe.set_params(**best_obj["params"])
    final_pipe.fit(X_train_sel, y_train)

    search_df = pd.DataFrame(search_rows)
    if len(search_df) > 0:
        search_df = search_df.sort_values(
            "selection_score_stability_penalized",
            ascending=False,
            na_position="last",
        ).reset_index(drop=True)

    return {
        "best_model_type": best_obj["model_type"],
        "best_params": best_obj["params"],
        "best_score": best_score,
        "search_df": search_df,
        "fitted_pipeline": final_pipe,
        "feature_weight_df": final_weight_df,
        "feature_selection_df": final_selection_df,
        "selected_features": selected_features,
    }


def get_inner_oof_predictions_model_only(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    groups_train: np.ndarray,
    candidate_models: list[str],
    n_splits_inner: int = 3,
    protected_keep_cols: list[str] | None = None,
    feature_selection_mode: str = "f_regression_topk",
    top_k_after_sparse: int | None = 100,
):
    """
    Diagnostic train-inner OOF predictions using the same paper-style fold-safe selection.
    """
    inner_splits, inner_cv_type = make_inner_cv_splits(
        X=X_train,
        y=y_train,
        groups=groups_train,
        n_splits=n_splits_inner,
    )

    oof = pd.Series(index=X_train.index, dtype=float)

    for tr_idx, va_idx in inner_splits:
        X_tr = X_train.iloc[tr_idx].copy()
        y_tr = y_train.iloc[tr_idx].copy()
        X_va = X_train.iloc[va_idx].copy()

        fit_result = fit_best_model_only(
            X_train=X_tr,
            y_train=y_tr,
            groups_train=groups_train[tr_idx],
            candidate_models=candidate_models,
            n_splits_inner=n_splits_inner,
            protected_keep_cols=protected_keep_cols,
            feature_selection_mode=feature_selection_mode,
            top_k_after_sparse=top_k_after_sparse,
        )

        selected_features = fit_result["selected_features"]
        X_va_sel = X_va.reindex(columns=selected_features).copy()

        best_pipe = fit_result["fitted_pipeline"]
        pred_va = predict_1d(best_pipe, X_va_sel)

        oof.iloc[va_idx] = pred_va

    return oof

In [19]:
def generate_weight_grid(n_models: int, step: float = 0.1):
    """
    Generate nonnegative weight tuples that sum to 1.
    Example:
      n_models=2, step=0.5 -> [(0.0,1.0),(0.5,0.5),(1.0,0.0)]
    """
    if n_models < 1:
        raise ValueError("n_models must be >= 1")
    if step <= 0 or step > 1:
        raise ValueError("step must be in (0, 1]")

    step_int = int(round(1 / step))
    if not np.isclose(step_int * step, 1.0):
        raise ValueError("step must divide 1.0 exactly, e.g. 0.5, 0.25, 0.2, 0.1")

    grids = []

    def backtrack(prefix, remaining, depth):
        if depth == n_models - 1:
            grids.append(tuple(prefix + [remaining / step_int]))
            return
        for v in range(remaining + 1):
            backtrack(prefix + [v / step_int], remaining - v, depth + 1)

    backtrack([], step_int, 0)
    return grids

In [20]:
def encode_clinical_train_valid(
    X_train: pd.DataFrame,
    X_valid: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, list[str]]:
    """
    Clinical을 항상 fold 내부에서 encoding한다.
    반환:
      - encoded X_train
      - encoded X_valid
      - encoded clinical column names
    """
    base_clin_cols = [c for c in get_clinical_columns() if c in X_train.columns]
    if len(base_clin_cols) == 0:
        return X_train, X_valid, []

    tr_clin = X_train.loc[:, base_clin_cols].copy()
    va_clin = X_valid.loc[:, [c for c in base_clin_cols if c in X_valid.columns]].copy()

    tr_other = X_train.drop(columns=base_clin_cols, errors="ignore").copy()
    va_other = X_valid.drop(columns=base_clin_cols, errors="ignore").copy()

    if "Age" in tr_clin.columns:
        tr_clin["Age"] = pd.to_numeric(tr_clin["Age"], errors="coerce")
    if "Age" in va_clin.columns:
        va_clin["Age"] = pd.to_numeric(va_clin["Age"], errors="coerce")

    cat_cols = [c for c in ["Gender", "Level"] if c in tr_clin.columns]

    if len(cat_cols) > 0:
        tr_clin_enc = pd.get_dummies(
            tr_clin,
            columns=cat_cols,
            dummy_na=True,
            dtype=float,
        )
        va_clin_enc = pd.get_dummies(
            va_clin,
            columns=cat_cols,
            dummy_na=True,
            dtype=float,
        )
        va_clin_enc = va_clin_enc.reindex(columns=tr_clin_enc.columns, fill_value=0.0)
    else:
        tr_clin_enc = tr_clin.copy()
        va_clin_enc = va_clin.copy()

    tr_clin_enc = tr_clin_enc.apply(pd.to_numeric, errors="coerce")
    va_clin_enc = va_clin_enc.apply(pd.to_numeric, errors="coerce")

    encoded_clin_cols = tr_clin_enc.columns.tolist()

    X_train_out = pd.concat([tr_other, tr_clin_enc], axis=1)
    X_valid_out = pd.concat([va_other, va_clin_enc], axis=1)

    return X_train_out, X_valid_out, encoded_clin_cols

In [21]:
def run_single_omics_final_train_test(
    X: pd.DataFrame,
    y: pd.Series,
    tissue: str,
    combo: str,
    tp: int,
    train_ids: list[str],
    test_ids: list[str],
    candidate_models: list[str],
    feature_mode: str,
    clinical_mode: str = "light",
    feature_selection_mode: str = "f_regression_topk",
    min_obs_frac: float = MIN_OBS_FRAC,
    top_k_after_sparse: int | None = 100,
):
    train_ids_in = [pid for pid in train_ids if pid in X.index]
    test_ids_in = [pid for pid in test_ids if pid in X.index]

    X_train = X.loc[train_ids_in].copy()
    y_train = y.loc[train_ids_in].copy()
    X_test = X.loc[test_ids_in].copy()
    y_test = y.loc[test_ids_in].copy()

    print("\n[TRAIN / TEST SPLIT CHECK]")
    print("clinical_mode:", clinical_mode)
    print("feature_selection_mode:", feature_selection_mode)
    print("top_k_after_sparse:", top_k_after_sparse)
    print("X_train shape:", X_train.shape)
    print("X_test  shape:", X_test.shape)
    print("y_train shape:", y_train.shape)
    print("y_test  shape:", y_test.shape)

    train_ids_set = set(X_train.index.astype(str))
    test_ids_set = set(X_test.index.astype(str))
    overlap_ids = sorted(train_ids_set.intersection(test_ids_set))

    print("train unique ids:", len(train_ids_set))
    print("test unique ids :", len(test_ids_set))
    print("overlap ids count:", len(overlap_ids))
    print("overlap ids example:", overlap_ids[:10])

    delta_cols = [c for c in X_train.columns if "_d" in str(c)]
    print("  delta cols count:", len(delta_cols))
    print("  delta examples:", delta_cols[:10])

    clin_cols_present = [c for c in get_clinical_columns() if c in X_train.columns]
    print("  clinical cols present:", clin_cols_present)

    if len(X_train) < N_SPLITS_INNER:
        raise ValueError("not enough training samples for inner CV")
    if len(X_test) == 0:
        raise ValueError("no holdout test samples available")

    protected_keep_cols = get_clinical_columns() if clinical_mode == "light" else []

    X_train_f, X_test_f = filter_sparse_features_train_test(
        X_train=X_train,
        X_valid=X_test,
        min_obs_frac=min_obs_frac,
        protected_keep_cols=protected_keep_cols,
    )

    print("\n[AFTER SPARSE FILTER]")
    print("X_train_f shape:", X_train_f.shape)
    print("X_test_f  shape:", X_test_f.shape)

    removed_cols = [c for c in X_train.columns if c not in X_train_f.columns]
    print("n_removed_by_sparse:", len(removed_cols))
    print("removed example:", removed_cols[:20])

    remaining_clin = [c for c in get_clinical_columns() if c in X_train_f.columns]
    print("clinical remaining after sparse:", remaining_clin)

    n_before_sparse = X_train.shape[1]
    n_after_sparse = X_train_f.shape[1]

    if X_train_f.shape[1] == 0:
        raise ValueError("no features left after sparse filtering")

    if clinical_mode == "light":
        X_train_f, X_test_f, encoded_clin_cols = encode_clinical_train_valid(
            X_train=X_train_f,
            X_valid=X_test_f,
        )
        protected_keep_cols = encoded_clin_cols
    else:
        encoded_clin_cols = []
        protected_keep_cols = []

    print("\n[AFTER CLINICAL ENCODING]")
    print("X_train_f shape:", X_train_f.shape)
    print("X_test_f  shape:", X_test_f.shape)
    print("encoded clinical cols:", encoded_clin_cols[:20])
    print("n_encoded_clinical_cols:", len(encoded_clin_cols))

    non_numeric_cols = X_train_f.select_dtypes(exclude=[np.number, "bool"]).columns.tolist()
    print("non_numeric_cols_after_encoding:", non_numeric_cols[:20])
    print("n_non_numeric_after_encoding:", len(non_numeric_cols))    

    if len(non_numeric_cols) > 0:
        raise TypeError(f"Non-numeric columns remain after encoding: {non_numeric_cols[:20]}")

    # IMPORTANT:
    # Do NOT apply target-aware top-k here.
    # Feature selection is now performed inside fit_best_model_only for each inner fold.
    # This prevents inner-CV leakage and follows the paper-style CV rule.
    n_after_pre_selection = X_train_f.shape[1]

    print("\n[BEFORE FOLD-SAFE SELECTION]")
    print("X_train_f shape:", X_train_f.shape)
    print("X_test_f  shape:", X_test_f.shape)
    print("candidate feature examples:", X_train_f.columns[:30].tolist())

    pd.DataFrame({
        "feature": X_train_f.columns,
        "has_delta": ["_d" in str(c) for c in X_train_f.columns],
        "is_clinical": [c in protected_keep_cols for c in X_train_f.columns],
    }).to_csv(
        FEATURE_TRACE_DIR / f"{feature_mode}_{clinical_mode}_{feature_selection_mode}_{tissue}_{combo}_{tp}_before_fold_safe_selection.csv",
        index=False,
    )

    fit_result = fit_best_model_only(
        X_train=X_train_f,
        y_train=y_train,
        groups_train=X_train_f.index.to_numpy(),
        candidate_models=candidate_models,
        n_splits_inner=N_SPLITS_INNER,
        protected_keep_cols=protected_keep_cols,
        feature_selection_mode=feature_selection_mode,
        top_k_after_sparse=top_k_after_sparse,
    )

    selected_features = fit_result["selected_features"]
    X_train_model = X_train_f.loc[:, selected_features].copy()
    X_test_model = X_test_f.reindex(columns=selected_features).copy()

    print("\n[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]")
    print("selected n_features:", len(selected_features))
    print("selected feature examples:", selected_features[:30])

    best_pipe = fit_result["fitted_pipeline"]

    pred_train = predict_1d(best_pipe, X_train_model)
    pred_test = predict_1d(best_pipe, X_test_model)

    train_r2 = r2_score(y_train, pred_train)
    train_mae = mean_absolute_error(y_train, pred_train)

    test_r2 = r2_score(y_test, pred_test)
    test_mae = mean_absolute_error(y_test, pred_test)

    pred_df = pd.DataFrame({
        "Patient": X_test_model.index,
        "y_true": y_test.values,
        "y_pred": pred_test,
        "clinical_mode": clinical_mode,
        "feature_selection_mode": feature_selection_mode,
        "tissue": tissue,
        "combo": combo,
        "tp": tp,
        "best_model_type": fit_result["best_model_type"],
        "top_k_after_sparse": top_k_after_sparse,
    })

    train_pred_df = pd.DataFrame({
        "Patient": X_train_model.index,
        "y_true": y_train.values,
        "y_pred": pred_train,
        "clinical_mode": clinical_mode,
        "feature_selection_mode": feature_selection_mode,
        "tissue": tissue,
        "combo": combo,
        "tp": tp,
        "best_model_type": fit_result["best_model_type"],
        "top_k_after_sparse": top_k_after_sparse,
    })

    print("\n[FINAL PREDICTION CHECK]")
    print("best_model_type:", fit_result["best_model_type"])
    print("best_params:", fit_result["best_params"])
    print("best_score_inner_oof_r2:", fit_result["best_score"])

    print("train_r2:", train_r2)
    print("train_mae:", train_mae)
    print("test_r2 :", test_r2)
    print("test_mae:", test_mae)

    print("pred_train summary:")
    print("  mean:", float(np.mean(pred_train)))
    print("  std :", float(np.std(pred_train)))
    print("  min :", float(np.min(pred_train)))
    print("  max :", float(np.max(pred_train)))

    print("pred_test summary:")
    print("  mean:", float(np.mean(pred_test)))
    print("  std :", float(np.std(pred_test)))
    print("  min :", float(np.min(pred_test)))
    print("  max :", float(np.max(pred_test)))

    print("y_test summary:")
    print("  mean:", float(np.mean(y_test)))
    print("  std :", float(np.std(y_test)))
    print("  min :", float(np.min(y_test)))
    print("  max :", float(np.max(y_test)))

    feature_info_df = extract_final_feature_info(best_pipe).copy()
    feature_weight_df = fit_result.get("feature_weight_df", pd.DataFrame()).copy()
    feature_selection_df = fit_result.get("feature_selection_df", pd.DataFrame()).copy()

    for trace_df in [feature_weight_df, feature_selection_df]:
        if isinstance(trace_df, pd.DataFrame) and len(trace_df) > 0:
            trace_df["feature_mode"] = feature_mode
            trace_df["clinical_mode"] = clinical_mode
            trace_df["feature_selection_mode"] = feature_selection_mode
            trace_df["tissue"] = tissue
            trace_df["combo"] = combo
            trace_df["tp"] = tp
            trace_df["experiment_tag"] = EXPERIMENT_TAG

    metrics = {
        "experiment_tag": EXPERIMENT_TAG,
        "use_feature_weighting": USE_FEATURE_WEIGHTING,
        "feature_weight_score_mode": FEATURE_WEIGHT_SCORE_MODE if USE_FEATURE_WEIGHTING else "none",
        "feature_weight_min": FEATURE_WEIGHT_MIN if USE_FEATURE_WEIGHTING else np.nan,
        "feature_weight_max": FEATURE_WEIGHT_MAX if USE_FEATURE_WEIGHTING else np.nan,
        "mean_feature_weight": (
            float(feature_weight_df["weight"].mean())
            if len(feature_weight_df) > 0 and "weight" in feature_weight_df.columns
            else FEATURE_WEIGHT_DEFAULT
        ),
        "max_feature_weight": (
            float(feature_weight_df["weight"].max())
            if len(feature_weight_df) > 0 and "weight" in feature_weight_df.columns
            else FEATURE_WEIGHT_DEFAULT
        ),
        "n_weighted_features": (
            int((feature_weight_df["weight"] > FEATURE_WEIGHT_DEFAULT).sum())
            if len(feature_weight_df) > 0 and "weight" in feature_weight_df.columns
            else 0
        ),
        "feature_mode": feature_mode,
        "clinical_mode": clinical_mode,
        "feature_selection_mode": feature_selection_mode,
        "tissue": tissue,
        "combo": combo,
        "tp": tp,
        "best_model_type": fit_result["best_model_type"],
        "best_score_inner_cv_r2": float(fit_result.get("best_score", np.nan)),
        "selection_basis": "training_matched_inner_oof_r2_with_fold_safe_feature_selection_not_test_r2",
        "n_train": len(X_train_model),
        "n_test": len(X_test_model),
        "n_features_before_sparse": n_before_sparse,
        "n_features_after_sparse": n_after_sparse,
        "n_features_before_fold_safe_selection": n_after_pre_selection,
        "n_features_after_selection": len(selected_features),
        "n_features_after_topk": len(selected_features),
        "top_k_after_sparse": top_k_after_sparse,
        "train_r2": train_r2,
        "train_mae": train_mae,
        "test_r2": test_r2,
        "test_mae": test_mae,
    }

    return {
        "metrics": metrics,
        "search_df": fit_result["search_df"],
        "train_pred_df": train_pred_df,
        "test_pred_df": pred_df,
        "feature_df": feature_info_df,
        "feature_weight_df": feature_weight_df,
        "feature_selection_df": feature_selection_df,
        "best_model_type": fit_result["best_model_type"],
        "best_params": fit_result["best_params"],
        "selected_features": selected_features,
    }

In [22]:
def run_one_single_omics_experiment(
    tissue: str,
    combo: str,
    tp: int,
    y_all: pd.Series,
    feature_mode: str,
    candidate_models: list[str],
    clinical_mode: str = "light",
    feature_selection_mode: str = "f_regression_topk",
    top_k_after_sparse_override: int | None = 100,
):
    feature_path = build_feature_path(
        feature_mode=feature_mode,
        tissue=tissue,
        combo=combo,
        tp=tp,
    )

    if not feature_path.exists():
        print("missing:", feature_path)
        return None

    print(
        f"\n[RUN-FINAL-TEST] feature_mode={feature_mode}, "
        f"clinical_mode={clinical_mode}, selection={feature_selection_mode}, "
        f"tissue={tissue}, combo={combo}, tp={tp}"
    )
    print("feature_path:", feature_path)

    X = load_feature_csv(feature_path)
    X, y = align_xy(X, y_all)

    print("\n[EXPERIMENT START]")
    print("feature_mode:", feature_mode)
    print("clinical_mode:", clinical_mode)
    print("feature_selection_mode:", feature_selection_mode)
    print("tissue:", tissue, "| combo:", combo, "| tp:", tp)
    print("X shape before clinical:", X.shape)
    print("y shape:", y.shape)

    delta_cols = [c for c in X.columns if "_d" in str(c)]
    print("n_delta_features:", len(delta_cols))
    print("delta examples:", delta_cols[:10])

    print("y summary:")
    print("  mean:", float(y.mean()))
    print("  std :", float(y.std()))
    print("  min :", float(y.min()))
    print("  max :", float(y.max()))

    if clinical_mode == "light":
        X = merge_with_light_clinical(
            X_feat=X,
            tissue=tissue,
            combo=combo,
            tp=tp,
        )
        assert_no_forbidden_proxy_columns(X, use_light_clinical=True)
    elif clinical_mode == "omics_only":
        assert_no_forbidden_proxy_columns(X, use_light_clinical=False)
    else:
        raise ValueError(f"Unknown clinical_mode: {clinical_mode}")

    delta_cols = [c for c in X.columns if "_d" in str(c)]
    clinical_cols_present = [c for c in get_clinical_columns() if c in X.columns]

    print("X shape after clinical mode:", X.shape)
    print("delta cols count:", len(delta_cols))
    print("clinical cols present:", clinical_cols_present)

    train_ids_in = [pid for pid in TRAIN_IDS if pid in X.index]
    test_ids_in = [pid for pid in TEST_IDS if pid in X.index]

    base_skip = {
        "status": "skipped",
        "experiment_tag": EXPERIMENT_TAG,
        "use_feature_weighting": USE_FEATURE_WEIGHTING,
        "feature_weight_score_mode": FEATURE_WEIGHT_SCORE_MODE if USE_FEATURE_WEIGHTING else "none",
        "feature_weight_min": FEATURE_WEIGHT_MIN if USE_FEATURE_WEIGHTING else np.nan,
        "feature_weight_max": FEATURE_WEIGHT_MAX if USE_FEATURE_WEIGHTING else np.nan,
        "mean_feature_weight": np.nan,
        "max_feature_weight": np.nan,
        "n_weighted_features": np.nan,
        "feature_mode": feature_mode,
        "clinical_mode": clinical_mode,
        "feature_selection_mode": feature_selection_mode,
        "tissue": tissue,
        "combo": combo,
        "tp": tp,
        "best_model_type": None,
        "n_train_available": len(train_ids_in),
        "n_test_available": len(test_ids_in),
        "test_r2": np.nan,
        "test_mae": np.nan,
        "train_r2": np.nan,
        "train_mae": np.nan,
        "n_features_input": X.shape[1],
        "n_delta_features_input": len(delta_cols),
        "n_clinical_input": len(clinical_cols_present),
        "top_k_after_sparse": top_k_after_sparse_override,
        "selection_basis": "not_run",
    }

    if len(train_ids_in) < N_SPLITS_INNER:
        print("skip: not enough training patients after TRAIN_IDS filter")
        out = base_skip.copy()
        out["reason"] = "not enough training patients after TRAIN_IDS filter"
        return out

    if len(test_ids_in) == 0:
        print("skip: no test patients after TEST_IDS filter")
        out = base_skip.copy()
        out["reason"] = "no test patients after TEST_IDS filter"
        return out

    top_k_after_sparse = top_k_after_sparse_override if top_k_after_sparse_override is not None else 100

    result = run_single_omics_final_train_test(
        X=X,
        y=y,
        tissue=tissue,
        combo=combo,
        tp=tp,
        train_ids=TRAIN_IDS,
        test_ids=TEST_IDS,
        candidate_models=candidate_models,
        feature_mode=feature_mode,
        clinical_mode=clinical_mode,
        feature_selection_mode=feature_selection_mode,
        min_obs_frac=MIN_OBS_FRAC,
        top_k_after_sparse=top_k_after_sparse,
    )

    prefix = f"{feature_mode}_{clinical_mode}_{feature_selection_mode}_{tissue}_{combo}_{tp}_topk{top_k_after_sparse}"

    pd.DataFrame([result["metrics"]]).to_csv(
        SAVE_DIR / f"{prefix}_final_test_summary.csv",
        index=False
    )
    result["search_df"].to_csv(
        SAVE_DIR / f"{prefix}_final_test_search_results.csv",
        index=False
    )
    result["train_pred_df"].to_csv(
        SAVE_DIR / f"{prefix}_final_train_predictions.csv",
        index=False
    )
    result["test_pred_df"].to_csv(
        SAVE_DIR / f"{prefix}_final_test_predictions.csv",
        index=False
    )
    result["feature_df"].to_csv(
        SAVE_DIR / f"{prefix}_final_selected_features.csv",
        index=False
    )
    if isinstance(result.get("feature_weight_df", None), pd.DataFrame) and len(result["feature_weight_df"]) > 0:
        result["feature_weight_df"].to_csv(
            SAVE_DIR / f"{prefix}_final_feature_weights.csv",
            index=False
        )
    if isinstance(result.get("feature_selection_df", None), pd.DataFrame) and len(result["feature_selection_df"]) > 0:
        result["feature_selection_df"].to_csv(
            SAVE_DIR / f"{prefix}_final_feature_selection_scores.csv",
            index=False
        )

    return {
        "status": "ok",
        "experiment_tag": EXPERIMENT_TAG,
        "use_feature_weighting": USE_FEATURE_WEIGHTING,
        "feature_weight_score_mode": FEATURE_WEIGHT_SCORE_MODE if USE_FEATURE_WEIGHTING else "none",
        "feature_weight_min": FEATURE_WEIGHT_MIN if USE_FEATURE_WEIGHTING else np.nan,
        "feature_weight_max": FEATURE_WEIGHT_MAX if USE_FEATURE_WEIGHTING else np.nan,
        "mean_feature_weight": result["metrics"].get("mean_feature_weight", np.nan),
        "max_feature_weight": result["metrics"].get("max_feature_weight", np.nan),
        "n_weighted_features": result["metrics"].get("n_weighted_features", np.nan),
        "feature_mode": feature_mode,
        "clinical_mode": clinical_mode,
        "feature_selection_mode": feature_selection_mode,
        "tissue": tissue,
        "combo": combo,
        "tp": tp,
        "reason": None,
        "best_model_type": result["best_model_type"],
        "n_train": result["metrics"]["n_train"],
        "n_test": result["metrics"]["n_test"],
        "train_r2": result["metrics"]["train_r2"],
        "train_mae": result["metrics"]["train_mae"],
        "test_r2": result["metrics"]["test_r2"],
        "test_mae": result["metrics"]["test_mae"],
        "best_score_inner_cv_r2": result["metrics"]["best_score_inner_cv_r2"],
        "selection_basis": result["metrics"].get("selection_basis", "training_matched_inner_oof_r2_with_fold_safe_feature_selection_not_test_r2"),
        "n_features_input": X.shape[1],
        "n_delta_features_input": len(delta_cols),
        "n_clinical_input": len(clinical_cols_present),
        "n_features_after_selection": result["metrics"].get("n_features_after_selection", np.nan),
        "top_k_after_sparse": top_k_after_sparse,
    }

In [23]:
# ==========================================
# Sanity check before running Experiment B
# ==========================================
y_all = load_target(TARGET_PATH)

for tissue, combo, tp in product(TISSUES, COMBOS, TIMEPOINTS):
    feature_path = build_feature_path(feature_mode="omics", tissue=tissue, combo=combo, tp=tp)
    if not feature_path.exists():
        print("missing:", feature_path.name)
        continue

    X = load_feature_csv(feature_path)
    X, y = align_xy(X, y_all)
    
    

    delta_cols = [c for c in X.columns if "_d" in str(c)]
    print(
        f"{feature_path.name}: shape={X.shape}, delta_cols={len(delta_cols)}"
    )

    if len(delta_cols) > 0:
        print("  delta examples:", delta_cols[:10])

x_omics_csf_A_24.csv: shape=(103, 438), delta_cols=0
x_omics_csf_A_48.csv: shape=(103, 438), delta_cols=0
x_omics_csf_A_72.csv: shape=(103, 438), delta_cols=0
x_omics_csf_A_96.csv: shape=(103, 438), delta_cols=0
x_omics_csf_A_120.csv: shape=(103, 438), delta_cols=0
x_omics_csf_B_24.csv: shape=(83, 749), delta_cols=0
x_omics_csf_B_48.csv: shape=(83, 749), delta_cols=0
x_omics_csf_B_72.csv: shape=(83, 749), delta_cols=0
x_omics_csf_B_96.csv: shape=(83, 749), delta_cols=0
x_omics_csf_B_120.csv: shape=(83, 749), delta_cols=0
x_omics_csf_C_24.csv: shape=(39, 312), delta_cols=0
x_omics_csf_C_48.csv: shape=(39, 312), delta_cols=0
x_omics_csf_C_72.csv: shape=(39, 312), delta_cols=0
x_omics_csf_C_96.csv: shape=(39, 312), delta_cols=0
x_omics_csf_C_120.csv: shape=(39, 312), delta_cols=0
x_omics_ser_A_24.csv: shape=(108, 438), delta_cols=0
x_omics_ser_A_48.csv: shape=(108, 438), delta_cols=0
x_omics_ser_A_72.csv: shape=(108, 438), delta_cols=0
x_omics_ser_A_96.csv: shape=(108, 438), delta_cols=0
x_omics_ser_A_120.csv: shape=(108, 438), delta_cols=0
x_omics_ser_B_24.csv: shape=(108, 749), delta_cols=0
x_omics_ser_B_48.csv: shape=(108, 749), delta_cols=0
x_omics_ser_B_72.csv: shape=(108, 749), delta_cols=0
x_omics_ser_B_96.csv: shape=(108, 749), delta_cols=0
x_omics_ser_B_120.csv: shape=(108, 749), delta_cols=0
x_omics_ser_C_24.csv: shape=(38, 312), delta_cols=0
x_omics_ser_C_48.csv: shape=(38, 312), delta_cols=0
x_omics_ser_C_72.csv: shape=(38, 312), delta_cols=0
x_omics_ser_C_96.csv: shape=(38, 312), delta_cols=0
x_omics_ser_C_120.csv: shape=(38, 312), delta_cols=0

In [24]:
y_all = load_target(TARGET_PATH)

FEATURE_MODE_TO_RUN = "omics"

# ==========================================
# Select held-out test configs from TRAINING summary only
# ==========================================
def _first_existing_col(df: pd.DataFrame, candidates: list[str]) -> str | None:
    for c in candidates:
        if c in df.columns:
            return c
    return None


def load_and_select_single_test_configs(
    train_summary_path: Path,
    selection_mode: str = "top_n_per_tissue_tp",
    top_n_per_tissue_tp: int = 5,
    top_k_per_tissue_combo_tp: int = 3,
) -> pd.DataFrame:
    """Select holdout-test configs using training OOF/CV only.

    Important:
    - This function never uses holdout-test metrics for selection.
    - top_n_per_tissue_tp is a sensitivity-analysis mode. It evaluates several
      training-selected candidates per tissue+TP to see whether OOF-best is unstable.
    - Any test-best table saved later is descriptive only and must not be used as
      the final model-selection criterion.
    """
    if not train_summary_path.exists():
        raise FileNotFoundError(
            f"Training summary not found: {train_summary_path}\n"
            "Run the single-omics training notebook first, or update TRAIN_SUMMARY_PATH."
        )

    train_summary = pd.read_csv(train_summary_path)
    print("loaded training summary:", train_summary_path)
    print("training summary shape:", train_summary.shape)

    if "status" in train_summary.columns:
        train_summary = train_summary[train_summary["status"].astype(str).str.lower().eq("ok")].copy()
        print("training ok rows:", len(train_summary))

    required = ["tissue", "combo", "tp", "clinical_mode", "feature_selection_mode", "top_k_after_sparse"]
    missing = [c for c in required if c not in train_summary.columns]
    if missing:
        raise ValueError(f"Training summary is missing required columns: {missing}")

    model_col = _first_existing_col(
        train_summary,
        ["final_full_train_best_model_type", "best_model_type", "model_type"],
    )
    if model_col is None:
        raise ValueError(
            "Training summary must contain one of: "
            "final_full_train_best_model_type, best_model_type, model_type"
        )

    train_summary = train_summary.copy()
    train_summary["selected_model_type_from_training"] = train_summary[model_col].astype(str)

    numeric_cols = [
        "oof_r2", "mean_valid_r2", "std_valid_r2", "mean_train_r2", "oof_mae",
        "final_full_train_best_score_inner_oof_r2", "final_full_train_r2", "final_full_train_mae",
        "top_k_after_sparse",
    ]
    for c in numeric_cols:
        if c in train_summary.columns:
            train_summary[c] = pd.to_numeric(train_summary[c], errors="coerce")

    if "single_selection_score" not in train_summary.columns:
        train_summary["single_selection_score"] = train_summary.get("oof_r2", np.nan)

    sort_by = []
    ascending = []
    for c in TRAIN_SELECTION_SORT_COLUMNS:
        if c in train_summary.columns:
            sort_by.append(c)
            ascending.append(True if c.endswith("mae") else False)

    if len(sort_by) == 0:
        raise ValueError("No usable training-CV ranking columns found in training summary.")

    ranked = train_summary.sort_values(
        by=sort_by,
        ascending=ascending,
        na_position="last",
    ).reset_index(drop=True)

    # Add training-only ranks. These ranks are computed BEFORE any holdout-test evaluation.
    ranked["training_rank_global"] = np.arange(1, len(ranked) + 1)
    ranked["training_rank_within_tissue_tp"] = (
        ranked.groupby(["tissue", "tp"]).cumcount() + 1
    )
    ranked["training_rank_within_tissue_combo_tp"] = (
        ranked.groupby(["tissue", "combo", "tp"]).cumcount() + 1
    )

    if selection_mode == "best_per_tissue_tp":
        selected = ranked[ranked["training_rank_within_tissue_tp"].eq(1)].copy()
    elif selection_mode == "top_n_per_tissue_tp":
        selected = ranked[ranked["training_rank_within_tissue_tp"].le(int(top_n_per_tissue_tp))].copy()
    elif selection_mode == "best_per_tissue_combo_tp":
        selected = ranked[ranked["training_rank_within_tissue_combo_tp"].eq(1)].copy()
    elif selection_mode == "top_k_per_tissue_combo_tp":
        selected = ranked[ranked["training_rank_within_tissue_combo_tp"].le(int(top_k_per_tissue_combo_tp))].copy()
    elif selection_mode == "all_train_ok":
        selected = ranked.copy()
    else:
        raise ValueError(f"Unknown TEST_CONFIG_SELECTION_MODE: {selection_mode}")

    selected = selected.reset_index(drop=True)
    selected["test_selection_basis"] = (
        "selected_before_holdout_test_using_training_only_oof_cv_"
        + selection_mode
    )
    selected["training_model_col_used"] = model_col
    selected["train_experiment_tag"] = TRAIN_EXPERIMENT_TAG
    selected["test_experiment_tag"] = TEST_EXPERIMENT_TAG
    selected["holdout_test_usage_note"] = (
        "Holdout test is evaluation only. Do not choose the final model by test_r2. "
        "For final reporting, use training_rank_within_tissue_tp == 1 unless explicitly doing sensitivity analysis."
    )

    return selected


selected_configs = load_and_select_single_test_configs(
    TRAIN_SUMMARY_PATH,
    selection_mode=TEST_CONFIG_SELECTION_MODE,
    top_n_per_tissue_tp=TOP_N_PER_TISSUE_TP,
    top_k_per_tissue_combo_tp=TOP_K_PER_TISSUE_COMBO_TP,
)

selected_configs_path = SAVE_DIR / f"single_omics_selected_configs_used_for_test_{TEST_EXPERIMENT_TAG}.csv"
selected_configs.to_csv(selected_configs_path, index=False)
print("selected configs saved:", selected_configs_path)
print("n_selected_configs:", len(selected_configs))
print("selection mode:", TEST_CONFIG_SELECTION_MODE)
if TEST_CONFIG_SELECTION_MODE == "top_n_per_tissue_tp":
    print("TOP_N_PER_TISSUE_TP:", TOP_N_PER_TISSUE_TP)

# Quick coverage of selected candidates.
coverage_selected = (
    selected_configs.groupby(["tissue", "tp"], as_index=False)
    .size()
    .rename(columns={"size": "n_selected_training_candidates"})
)
coverage_selected_path = SAVE_DIR / f"single_omics_selected_config_coverage_{TEST_EXPERIMENT_TAG}.csv"
coverage_selected.to_csv(coverage_selected_path, index=False)
print("selected coverage saved:", coverage_selected_path)

display_cols_selected = [
    "tissue", "tp", "training_rank_within_tissue_tp", "combo",
    "clinical_mode", "feature_selection_mode", "top_k_after_sparse",
    "selected_model_type_from_training", "oof_r2", "mean_valid_r2", "std_valid_r2",
    "mean_train_r2", "oof_mae", "test_selection_basis",
]
display(selected_configs[[c for c in display_cols_selected if c in selected_configs.columns]].head(120))


# ==========================================
# Build jobs from selected training configs
# ==========================================
jobs = []
for _, row in selected_configs.iterrows():
    selected_model = str(row["selected_model_type_from_training"])
    if selected_model not in MODEL_TYPES:
        print(f"[WARN] selected model {selected_model} not in MODEL_TYPES; still passing it directly.")

    jobs.append({
        "feature_mode": FEATURE_MODE_TO_RUN,
        "clinical_mode": str(row["clinical_mode"]),
        "feature_selection_mode": str(row["feature_selection_mode"]),
        "combo": str(row["combo"]),
        "top_k": int(row["top_k_after_sparse"]),
        "tissue": str(row["tissue"]),
        "tp": int(row["tp"]),
        "selected_model_type_from_training": selected_model,
        "train_oof_r2": row.get("oof_r2", np.nan),
        "train_mean_valid_r2": row.get("mean_valid_r2", np.nan),
        "train_std_valid_r2": row.get("std_valid_r2", np.nan),
        "train_mean_train_r2": row.get("mean_train_r2", np.nan),
        "train_oof_mae": row.get("oof_mae", np.nan),
        "training_rank_global": row.get("training_rank_global", np.nan),
        "training_rank_within_tissue_tp": row.get("training_rank_within_tissue_tp", np.nan),
        "training_rank_within_tissue_combo_tp": row.get("training_rank_within_tissue_combo_tp", np.nan),
        "test_selection_basis": row.get("test_selection_basis", "training_only_oof_cv"),
        "holdout_test_usage_note": row.get("holdout_test_usage_note", "evaluation_only"),
    })

print("n_jobs_to_run:", len(jobs))
display(pd.DataFrame(jobs).head(120))


def run_one_single_omics_experiment_safe(job: dict, y_all: pd.Series):
    feature_mode = job["feature_mode"]
    clinical_mode = job["clinical_mode"]
    feature_selection_mode = job["feature_selection_mode"]
    tissue = job["tissue"]
    combo = job["combo"]
    tp = job["tp"]
    top_k = job["top_k"]
    selected_model = job["selected_model_type_from_training"]

    try:
        # Important:
        # Only the model family selected by training-only OOF/CV is allowed here.
        # The test set is not used for model-family selection.
        result = run_one_single_omics_experiment(
            tissue=tissue,
            combo=combo,
            tp=tp,
            y_all=y_all,
            feature_mode=feature_mode,
            candidate_models=[selected_model],
            clinical_mode=clinical_mode,
            feature_selection_mode=feature_selection_mode,
            top_k_after_sparse_override=top_k,
        )
        if result is None:
            raise ValueError("run_one_single_omics_experiment returned None")

        for k in [
            "selected_model_type_from_training",
            "train_oof_r2",
            "train_mean_valid_r2",
            "train_std_valid_r2",
            "train_mean_train_r2",
            "train_oof_mae",
            "training_rank_global",
            "training_rank_within_tissue_tp",
            "training_rank_within_tissue_combo_tp",
            "test_selection_basis",
            "holdout_test_usage_note",
        ]:
            result[k] = job.get(k, np.nan)
        result["train_experiment_tag"] = TRAIN_EXPERIMENT_TAG
        result["test_experiment_tag"] = TEST_EXPERIMENT_TAG
        result["selection_is_training_rank1_within_tissue_tp"] = (
            pd.notna(job.get("training_rank_within_tissue_tp", np.nan))
            and int(job.get("training_rank_within_tissue_tp")) == 1
        )
        return result

    except Exception as e:
        print(
            f"[ERROR] feature_mode={feature_mode}, clinical={clinical_mode}, "
            f"selection={feature_selection_mode}, tissue={tissue}, combo={combo}, "
            f"tp={tp}, top_k={top_k}, selected_model={selected_model} :: {e}"
        )
        return {
            "status": "failed",
            "experiment_tag": EXPERIMENT_TAG,
            "train_experiment_tag": TRAIN_EXPERIMENT_TAG,
            "test_experiment_tag": TEST_EXPERIMENT_TAG,
            "use_feature_weighting": USE_FEATURE_WEIGHTING,
            "feature_weight_score_mode": FEATURE_WEIGHT_SCORE_MODE if USE_FEATURE_WEIGHTING else "none",
            "feature_weight_min": FEATURE_WEIGHT_MIN if USE_FEATURE_WEIGHTING else np.nan,
            "feature_weight_max": FEATURE_WEIGHT_MAX if USE_FEATURE_WEIGHTING else np.nan,
            "mean_feature_weight": np.nan,
            "max_feature_weight": np.nan,
            "n_weighted_features": np.nan,
            "feature_mode": feature_mode,
            "clinical_mode": clinical_mode,
            "feature_selection_mode": feature_selection_mode,
            "tissue": tissue,
            "combo": combo,
            "tp": tp,
            "reason": str(e),
            "best_model_type": selected_model,
            "selected_model_type_from_training": selected_model,
            "n_train": np.nan,
            "n_test": np.nan,
            "train_r2": np.nan,
            "train_mae": np.nan,
            "test_r2": np.nan,
            "test_mae": np.nan,
            "best_score_inner_cv_r2": np.nan,
            "selection_basis": "training_summary_selected_config_then_holdout_test_once",
            "test_selection_basis": job.get("test_selection_basis", "training_only_oof_cv"),
            "holdout_test_usage_note": job.get("holdout_test_usage_note", "evaluation_only"),
            "train_oof_r2": job.get("train_oof_r2", np.nan),
            "train_mean_valid_r2": job.get("train_mean_valid_r2", np.nan),
            "train_std_valid_r2": job.get("train_std_valid_r2", np.nan),
            "train_mean_train_r2": job.get("train_mean_train_r2", np.nan),
            "train_oof_mae": job.get("train_oof_mae", np.nan),
            "training_rank_global": job.get("training_rank_global", np.nan),
            "training_rank_within_tissue_tp": job.get("training_rank_within_tissue_tp", np.nan),
            "training_rank_within_tissue_combo_tp": job.get("training_rank_within_tissue_combo_tp", np.nan),
            "selection_is_training_rank1_within_tissue_tp": False,
            "n_features_input": np.nan,
            "n_delta_features_input": np.nan,
            "n_clinical_input": np.nan,
            "n_features_after_selection": np.nan,
            "top_k_after_sparse": top_k,
        }


rows = Parallel(
    n_jobs=N_JOBS_EXPERIMENT,
    backend="loky",
    verbose=10,
)(
    delayed(run_one_single_omics_experiment_safe)(job, y_all)
    for job in jobs
)

summary_df = pd.DataFrame(rows)

# Ensure key columns exist.
for c in [
    "test_r2", "test_mae", "train_r2", "train_mae",
    "best_score_inner_cv_r2", "train_oof_r2", "train_mean_valid_r2",
    "train_std_valid_r2", "train_mean_train_r2", "train_oof_mae",
    "training_rank_global", "training_rank_within_tissue_tp", "training_rank_within_tissue_combo_tp",
]:
    if c not in summary_df.columns:
        summary_df[c] = np.nan
    summary_df[c] = pd.to_numeric(summary_df[c], errors="coerce")

if "selection_is_training_rank1_within_tissue_tp" not in summary_df.columns:
    summary_df["selection_is_training_rank1_within_tissue_tp"] = False

if len(summary_df) > 0:
    summary_df = summary_df.sort_values(
        by=["status", "tissue", "tp", "training_rank_within_tissue_tp", "combo"],
        ascending=[True, True, True, True, True],
        na_position="last",
    ).reset_index(drop=True)

out_path = SAVE_DIR / f"{FEATURE_MODE_TO_RUN}_holdout_test_summary_{TEST_EXPERIMENT_TAG}.csv"
summary_df.to_csv(out_path, index=False)
print("saved:", out_path)

ok_df = summary_df[summary_df["status"].astype(str).str.lower().eq("ok")].copy()

if len(ok_df) > 0:
    # 1) Leakage-safe final table: training OOF rank-1 per tissue+TP only.
    rank1_df = ok_df[ok_df["training_rank_within_tissue_tp"].eq(1)].copy()
    rank1_df = rank1_df.sort_values(["tissue", "tp"]).reset_index(drop=True)
    rank1_path = SAVE_DIR / f"single_omics_test_training_rank1_by_tissue_tp_for_ef_lf_compare_{TEST_EXPERIMENT_TAG}.csv"
    rank1_df.to_csv(rank1_path, index=False)
    print("saved leakage-safe rank1 final compare table:", rank1_path)

    # 2) Descriptive only: test-best among inspected top-N candidates.
    best_by_test_tissue_tp = (
        ok_df.sort_values("test_r2", ascending=False, na_position="last")
        .groupby(["tissue", "tp"], as_index=False)
        .first()
        .sort_values(["tissue", "tp"])
        .reset_index(drop=True)
    )
    best_by_test_path = SAVE_DIR / f"single_omics_test_descriptive_best_by_test_r2_within_topN_tissue_tp_{TEST_EXPERIMENT_TAG}.csv"
    best_by_test_tissue_tp.to_csv(best_by_test_path, index=False)
    print("saved descriptive test-best table:", best_by_test_path)

    # 3) Descriptive only: test-best per tissue/combo/TP among inspected candidates.
    best_by_test_tissue_combo_tp = (
        ok_df.sort_values("test_r2", ascending=False, na_position="last")
        .groupby(["tissue", "combo", "tp"], as_index=False)
        .first()
        .sort_values(["tissue", "combo", "tp"])
        .reset_index(drop=True)
    )
    best_combo_path = SAVE_DIR / f"single_omics_test_descriptive_best_by_test_r2_within_topN_tissue_combo_tp_{TEST_EXPERIMENT_TAG}.csv"
    best_by_test_tissue_combo_tp.to_csv(best_combo_path, index=False)
    print("saved descriptive test-best combo table:", best_combo_path)

    # 4) Sensitivity summary per tissue+TP.
    sens_rows = []
    for (tissue, tp), g in ok_df.groupby(["tissue", "tp"]):
        g_sorted_train = g.sort_values("training_rank_within_tissue_tp", ascending=True)
        g_sorted_test = g.sort_values("test_r2", ascending=False, na_position="last")
        train_rank1 = g_sorted_train.iloc[0]
        test_best = g_sorted_test.iloc[0]
        sens_rows.append({
            "tissue": tissue,
            "tp": tp,
            "n_tested_topN_candidates": len(g),
            "train_rank1_combo": train_rank1.get("combo"),
            "train_rank1_model": train_rank1.get("selected_model_type_from_training"),
            "train_rank1_fs": train_rank1.get("feature_selection_mode"),
            "train_rank1_top_k": train_rank1.get("top_k_after_sparse"),
            "train_rank1_oof_r2": train_rank1.get("train_oof_r2"),
            "train_rank1_test_r2": train_rank1.get("test_r2"),
            "descriptive_test_best_combo": test_best.get("combo"),
            "descriptive_test_best_model": test_best.get("selected_model_type_from_training"),
            "descriptive_test_best_fs": test_best.get("feature_selection_mode"),
            "descriptive_test_best_top_k": test_best.get("top_k_after_sparse"),
            "descriptive_test_best_training_rank": test_best.get("training_rank_within_tissue_tp"),
            "descriptive_test_best_train_oof_r2": test_best.get("train_oof_r2"),
            "descriptive_test_best_test_r2": test_best.get("test_r2"),
            "test_r2_median_among_topN": g["test_r2"].median(),
            "test_r2_mean_among_topN": g["test_r2"].mean(),
            "test_r2_std_among_topN": g["test_r2"].std(ddof=1) if len(g) > 1 else np.nan,
            "n_positive_test_r2_among_topN": int((g["test_r2"] > 0).sum()),
            "n_negative_test_r2_among_topN": int((g["test_r2"] < 0).sum()),
            "note": "test_best columns are descriptive only; final model must be selected by training OOF/CV, not holdout test R2",
        })
    sensitivity_df = pd.DataFrame(sens_rows).sort_values(["tissue", "tp"]).reset_index(drop=True)
    sensitivity_path = SAVE_DIR / f"single_omics_test_topN_sensitivity_by_tissue_tp_{TEST_EXPERIMENT_TAG}.csv"
    sensitivity_df.to_csv(sensitivity_path, index=False)
    print("saved top-N sensitivity summary:", sensitivity_path)

    # 5) Backward-compatible file name, but make content leakage-safe rank1 by default.
    compare_cols = [
        "status", "tissue", "tp", "combo", "clinical_mode", "feature_selection_mode",
        "top_k_after_sparse", "training_rank_within_tissue_tp",
        "selected_model_type_from_training", "best_model_type",
        "train_oof_r2", "train_mean_valid_r2", "test_r2", "test_mae",
        "train_r2", "best_score_inner_cv_r2", "n_features_after_selection",
        "test_selection_basis", "holdout_test_usage_note",
    ]
    compare_path = SAVE_DIR / f"single_omics_test_for_ef_lf_compare_by_tissue_tp_{TEST_EXPERIMENT_TAG}.csv"
    rank1_df[[c for c in compare_cols if c in rank1_df.columns]].to_csv(compare_path, index=False)
    print("saved EF/LF compare table using training rank1 only:", compare_path)

print("\nHoldout test summary sorted by TEST R² for inspection only.")
print("Do not use this ranking to choose a new final config.")
display_cols = [
    "status", "tissue", "tp", "training_rank_within_tissue_tp", "combo",
    "clinical_mode", "feature_selection_mode", "top_k_after_sparse",
    "selected_model_type_from_training", "best_model_type",
    "train_oof_r2", "train_mean_valid_r2", "test_r2", "test_mae",
    "train_r2", "best_score_inner_cv_r2", "n_features_after_selection",
]
display(summary_df.sort_values("test_r2", ascending=False, na_position="last")[[c for c in display_cols if c in summary_df.columns]].head(120))

if len(ok_df) > 0:
    print("\nLeakage-safe final EF/LF table: training OOF rank-1 per tissue+TP.")
    display(rank1_df[[c for c in display_cols if c in rank1_df.columns]].head(80))

    print("\nTop-N sensitivity summary. Test-best columns are descriptive only.")
    display(sensitivity_df.head(80))

    print("\nDescriptive test-best among inspected top-N candidates. Do not use this as final model selection.")
    display(best_by_test_tissue_tp[[c for c in display_cols if c in best_by_test_tissue_tp.columns]].head(80))

loaded training summary: ../../DifferentCom_data_rebuild/results_single_omics_train_only_single_omics_train_paper_style_v11_rescue_expansion_v9compatible/omics_paper_style_train_summary_single_omics_train_paper_style_v11_rescue_expansion_v9compatible.csv
training summary shape: (148, 39)
training ok rows: 148
selected configs saved: ../../DifferentCom_data_rebuild/testResult/results_single_omics_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible/single_omics_selected_configs_used_for_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible.csv
n_selected_configs: 50
selection mode: top_n_per_tissue_tp
TOP_N_PER_TISSUE_TP: 5
selected coverage saved: ../../DifferentCom_data_rebuild/testResult/results_single_omics_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible/single_omics_selected_config_coverage_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible.csv

,tissue,tp,training_rank_within_tissue_tp,combo,clinical_mode,feature_selection_mode,top_k_after_sparse,selected_model_type_from_training,oof_r2,mean_valid_r2,std_valid_r2,mean_train_r2,oof_mae,test_selection_basis
0,ser,24,1,C,light,f_regression_topk,40,xgboost,0.271758,0.194197,0.176020,0.733303,15.176796,selected_before_holdout_test_using_training_on...
1,csf,24,1,C,light,corr_topk,30,ridge,0.261029,0.240782,0.225431,0.797261,14.235372,selected_before_holdout_test_using_training_on...
2,csf,24,2,C,light,corr_topk,20,ridge,0.253265,0.316194,0.200290,0.674126,13.439060,selected_before_holdout_test_using_training_on...
3,ser,96,1,A,light,corr_topk,120,svr_linear,0.242782,0.306499,0.302850,0.683036,13.388230,selected_before_holdout_test_using_training_on...
4,csf,96,1,A,light,f_regression_topk,30,ridge,0.236085,0.199354,0.296724,0.501134,13.732454,selected_before_holdout_test_using_training_on...
5,ser,96,2,A,light,f_regression_topk,100,svr_linear,0.234564,0.288056,0.272773,0.634685,13.494215,selected_before_holdout_test_using_training_on...
6,ser,96,3,A,light,corr_topk,100,svr_linear,0.231528,0.283952,0.271167,0.636724,13.546047,selected_before_holdout_test_using_training_on...
7,csf,96,2,A,light,corr_topk,30,ridge,0.226360,0.188781,0.303123,0.517226,13.697032,selected_before_holdout_test_using_training_on...
8,ser,96,4,A,light,f_regression_topk,120,svr_linear,0.217384,0.270970,0.290776,0.660641,13.474596,selected_before_holdout_test_using_training_on...
9,csf,48,1,C,light,corr_topk,30,ridge,0.201590,0.186037,0.241039,0.696185,14.601400,selected_before_holdout_test_using_training_on...
10,csf,72,1,A,light,corr_topk,60,gbr,0.195500,0.126244,0.287160,0.562045,14.211108,selected_before_holdout_test_using_training_on...
11,ser,96,5,A,light,corr_topk,140,svr_linear,0.194071,0.258349,0.311671,0.634389,13.616950,selected_before_holdout_test_using_training_on...
12,csf,24,3,C,light,f_regression_topk,30,ridge,0.185944,0.159013,0.305969,0.791110,14.740801,selected_before_holdout_test_using_training_on...
13,ser,48,1,C,light,f_regression_topk,15,ridge,0.183097,0.180746,0.169184,0.367828,15.716588,selected_before_holdout_test_using_training_on...
14,csf,120,1,C,light,corr_topk,30,ridge,0.181183,0.158403,0.162130,0.583065,14.333944,selected_before_holdout_test_using_training_on...
15,ser,48,2,C,light,f_regression_topk,5,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,selected_before_holdout_test_using_training_on...
16,ser,48,3,C,light,f_regression_topk,10,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,selected_before_holdout_test_using_training_on...
17,ser,72,1,C,light,f_regression_topk,5,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,selected_before_holdout_test_using_training_on...
18,ser,72,2,C,light,f_regression_topk,10,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,selected_before_holdout_test_using_training_on...
19,ser,120,1,C,light,f_regression_topk,5,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,selected_before_holdout_test_using_training_on...
20,ser,120,2,C,light,f_regression_topk,10,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,selected_before_holdout_test_using_training_on...
21,ser,72,3,A,light,f_regression_topk,120,svr_linear,0.140991,0.200750,0.245112,0.783185,14.705040,selected_before_holdout_test_using_training_on...
22,csf,24,4,C,light,f_regression_topk,20,ridge,0.138420,0.137486,0.067322,0.691792,14.458335,selected_before_holdout_test_using_training_on...
23,ser,72,4,A,light,corr_topk,120,svr_linear,0.138242,0.197571,0.242775,0.782533,14.762171,selected_before_holdout_test_using_training_on...
24,csf,96,3,A,light,corr_topk,40,ridge,0.138209,0.071006,0.399013,0.511877,14.258980,selected_before_holdout_test_using_training_on...
25,ser,24,2,C,light,corr_topk,30,xgboost,0.137132,0.101614,0.154439,0.707129,15.579252,selected_before_holdout_test_using_training_on...
26,csf,72,2,A,light,corr_topk,80,svr_linear,0.135272,0.073697,0.301794,0.581174,14.488833,selected_before_holdout_test_using_training_on...
27,ser,72,5,A,light,corr_topk,140,svr_linear,0.132800,0.185666,0.220283,0.777597,15.059100,selected_before_holdout_test_using_training_on...
28,ser,24,3,C,light,f_regression_topk,30,xgboost,0.131876,0.093529,0.156923,0.692137,15.509887,selected_before_holdout_test_using_training_on...
29,ser,24,4,C,light,corr_topk,60,xgboost,0.131258,0.098993,0.101168,0.713086,15.624270,selected_before_holdout_test_using_training_on...
30,csf,72,3,A,light,f_regression_topk,40,gbr,0.128291,0.075298,0.254300,0.508171,14.392514,selected_before_holdout_test_using_training_on...
31,csf,72,4,A,light,f_regression_topk,80,svr_linear,0.126126,0.077705,0.261764,0.584231,14.606145,selected_before_holdout_test_using_training_on...
32,ser,24,5,C,light,f_regression_topk,60,xgboost,0.126043,0.084710,0.105510,0.687499,15.539563,selected_before_holdout_test_using_training_on...
33,csf,96,4,A,light,f_regression_topk,40,ridge,0.125457,0.056174,0.411549,0.506595,14.301020,selected_before_holdout_test_using_training_on...
34,ser,120,3,B,light,f_regression_topk,40,ridge,0.125283,0.162649,0.195343,0.545873,15.438100,selected_before_holdout_test_using_training_on...
35,csf,72,5,A,light,f_regression_topk,100,svr_linear,0.121153,0.057753,0.343938,0.636879,14.553661,selected_before_holdout_test_using_training_on...
36,csf,48,2,C,light,f_regression_topk,30,ridge,0.117648,0.060554,0.261978,0.711715,15.028840,selected_before_holdout_test_using_training_on...
37,csf,96,5,A,light,corr_topk,60,ridge,0.111878,0.036657,0.396222,0.507778,14.432340,selected_before_holdout_test_using_training_on...
38,csf,48,3,B,light,f_regression_topk,40,ridge,0.110969,0.023137,0.395376,0.556011,14.898098,selected_before_holdout_test_using_training_on...
39,csf,48,4,C,light,f_regression_topk,20,ridge,0.109897,0.014646,0.235538,0.506182,15.685368,selected_before_holdout_test_using_training_on...
40,ser,48,4,B,light,f_regression_topk,80,ridge,0.101422,0.142470,0.193881,0.771779,15.836199,selected_before_holdout_test_using_training_on...
41,ser,120,4,C,light,f_regression_topk,15,ridge,0.099527,0.093419,0.293497,0.372007,16.345416,selected_before_holdout_test_using_training_on...
42,csf,120,2,C,light,f_regression_topk,20,ridge,0.088311,-0.012170,0.235679,0.597156,15.739595,selected_before_holdout_test_using_training_on...
43,ser,48,5,A,light,corr_topk,40,ridge,0.082142,0.092378,0.232703,0.519129,15.571042,selected_before_holdout_test_using_training_on...
44,csf,120,3,C,light,f_regression_topk,30,ridge,0.078199,-0.075153,0.370923,0.590920,14.797653,selected_before_holdout_test_using_training_on...
45,csf,24,5,A,light,f_regression_topk,120,ridge,0.069795,0.072770,0.230849,0.573675,15.335052,selected_before_holdout_test_using_training_on...
46,csf,48,5,C,light,corr_topk,20,ridge,0.061727,-0.072414,0.249332,0.468013,16.291894,selected_before_holdout_test_using_training_on...
47,csf,120,4,C,light,corr_topk,20,ridge,0.059603,-0.125359,0.404802,0.577506,15.609323,selected_before_holdout_test_using_training_on...
48,ser,120,5,C,light,f_regression_topk,20,ridge,0.045795,0.032286,0.209344,0.409573,16.823466,selected_before_holdout_test_using_training_on...
49,csf,120,5,A,light,f_regression_topk,40,ridge,0.031232,-0.004695,0.154198,0.429323,15.855359,selected_before_holdout_test_using_training_on...

n_jobs_to_run: 50

,feature_mode,clinical_mode,feature_selection_mode,combo,top_k,tissue,tp,selected_model_type_from_training,train_oof_r2,train_mean_valid_r2,train_std_valid_r2,train_mean_train_r2,train_oof_mae,training_rank_global,training_rank_within_tissue_tp,training_rank_within_tissue_combo_tp,test_selection_basis,holdout_test_usage_note
0,omics,light,f_regression_topk,C,40,ser,24,xgboost,0.271758,0.194197,0.176020,0.733303,15.176796,1,1,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
1,omics,light,corr_topk,C,30,csf,24,ridge,0.261029,0.240782,0.225431,0.797261,14.235372,2,1,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
2,omics,light,corr_topk,C,20,csf,24,ridge,0.253265,0.316194,0.200290,0.674126,13.439060,3,2,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
3,omics,light,corr_topk,A,120,ser,96,svr_linear,0.242782,0.306499,0.302850,0.683036,13.388230,4,1,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
4,omics,light,f_regression_topk,A,30,csf,96,ridge,0.236085,0.199354,0.296724,0.501134,13.732454,5,1,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
5,omics,light,f_regression_topk,A,100,ser,96,svr_linear,0.234564,0.288056,0.272773,0.634685,13.494215,6,2,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
6,omics,light,corr_topk,A,100,ser,96,svr_linear,0.231528,0.283952,0.271167,0.636724,13.546047,7,3,3,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
7,omics,light,corr_topk,A,30,csf,96,ridge,0.226360,0.188781,0.303123,0.517226,13.697032,8,2,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
8,omics,light,f_regression_topk,A,120,ser,96,svr_linear,0.217384,0.270970,0.290776,0.660641,13.474596,9,4,4,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
9,omics,light,corr_topk,C,30,csf,48,ridge,0.201590,0.186037,0.241039,0.696185,14.601400,10,1,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
10,omics,light,corr_topk,A,60,csf,72,gbr,0.195500,0.126244,0.287160,0.562045,14.211108,11,1,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
11,omics,light,corr_topk,A,140,ser,96,svr_linear,0.194071,0.258349,0.311671,0.634389,13.616950,12,5,5,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
12,omics,light,f_regression_topk,C,30,csf,24,ridge,0.185944,0.159013,0.305969,0.791110,14.740801,16,3,3,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
13,omics,light,f_regression_topk,C,15,ser,48,ridge,0.183097,0.180746,0.169184,0.367828,15.716588,17,1,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
14,omics,light,corr_topk,C,30,csf,120,ridge,0.181183,0.158403,0.162130,0.583065,14.333944,18,1,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
15,omics,light,f_regression_topk,C,5,ser,48,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,22,2,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
16,omics,light,f_regression_topk,C,10,ser,48,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,23,3,3,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
17,omics,light,f_regression_topk,C,5,ser,72,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,24,1,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
18,omics,light,f_regression_topk,C,10,ser,72,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,25,2,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
19,omics,light,f_regression_topk,C,5,ser,120,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,28,1,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
20,omics,light,f_regression_topk,C,10,ser,120,ridge,0.157075,0.147370,0.222005,0.333103,15.686889,29,2,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
21,omics,light,f_regression_topk,A,120,ser,72,svr_linear,0.140991,0.200750,0.245112,0.783185,14.705040,32,3,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
22,omics,light,f_regression_topk,C,20,csf,24,ridge,0.138420,0.137486,0.067322,0.691792,14.458335,33,4,4,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
23,omics,light,corr_topk,A,120,ser,72,svr_linear,0.138242,0.197571,0.242775,0.782533,14.762171,34,4,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
24,omics,light,corr_topk,A,40,csf,96,ridge,0.138209,0.071006,0.399013,0.511877,14.258980,35,3,3,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
25,omics,light,corr_topk,C,30,ser,24,xgboost,0.137132,0.101614,0.154439,0.707129,15.579252,36,2,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
26,omics,light,corr_topk,A,80,csf,72,svr_linear,0.135272,0.073697,0.301794,0.581174,14.488833,37,2,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
27,omics,light,corr_topk,A,140,ser,72,svr_linear,0.132800,0.185666,0.220283,0.777597,15.059100,38,5,3,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
28,omics,light,f_regression_topk,C,30,ser,24,xgboost,0.131876,0.093529,0.156923,0.692137,15.509887,39,3,3,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
29,omics,light,corr_topk,C,60,ser,24,xgboost,0.131258,0.098993,0.101168,0.713086,15.624270,40,4,4,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
30,omics,light,f_regression_topk,A,40,csf,72,gbr,0.128291,0.075298,0.254300,0.508171,14.392514,41,3,3,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
31,omics,light,f_regression_topk,A,80,csf,72,svr_linear,0.126126,0.077705,0.261764,0.584231,14.606145,42,4,4,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
32,omics,light,f_regression_topk,C,60,ser,24,xgboost,0.126043,0.084710,0.105510,0.687499,15.539563,43,5,5,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
33,omics,light,f_regression_topk,A,40,csf,96,ridge,0.125457,0.056174,0.411549,0.506595,14.301020,44,4,4,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
34,omics,light,f_regression_topk,B,40,ser,120,ridge,0.125283,0.162649,0.195343,0.545873,15.438100,45,3,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
35,omics,light,f_regression_topk,A,100,csf,72,svr_linear,0.121153,0.057753,0.343938,0.636879,14.553661,46,5,5,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
36,omics,light,f_regression_topk,C,30,csf,48,ridge,0.117648,0.060554,0.261978,0.711715,15.028840,48,2,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
37,omics,light,corr_topk,A,60,csf,96,ridge,0.111878,0.036657,0.396222,0.507778,14.432340,54,5,5,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
38,omics,light,f_regression_topk,B,40,csf,48,ridge,0.110969,0.023137,0.395376,0.556011,14.898098,57,3,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
39,omics,light,f_regression_topk,C,20,csf,48,ridge,0.109897,0.014646,0.235538,0.506182,15.685368,58,4,3,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
40,omics,light,f_regression_topk,B,80,ser,48,ridge,0.101422,0.142470,0.193881,0.771779,15.836199,63,4,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
41,omics,light,f_regression_topk,C,15,ser,120,ridge,0.099527,0.093419,0.293497,0.372007,16.345416,65,4,3,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
42,omics,light,f_regression_topk,C,20,csf,120,ridge,0.088311,-0.012170,0.235679,0.597156,15.739595,71,2,2,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
43,omics,light,corr_topk,A,40,ser,48,ridge,0.082142,0.092378,0.232703,0.519129,15.571042,75,5,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
44,omics,light,f_regression_topk,C,30,csf,120,ridge,0.078199,-0.075153,0.370923,0.590920,14.797653,76,3,3,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
45,omics,light,f_regression_topk,A,120,csf,24,ridge,0.069795,0.072770,0.230849,0.573675,15.335052,81,5,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
46,omics,light,corr_topk,C,20,csf,48,ridge,0.061727,-0.072414,0.249332,0.468013,16.291894,85,5,4,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
47,omics,light,corr_topk,C,20,csf,120,ridge,0.059603,-0.125359,0.404802,0.577506,15.609323,86,4,4,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
48,omics,light,f_regression_topk,C,20,ser,120,ridge,0.045795,0.032286,0.209344,0.409573,16.823466,93,5,4,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...
49,omics,light,f_regression_topk,A,40,csf,120,ridge,0.031232,-0.004695,0.154198,0.429323,15.855359,97,5,1,selected_before_holdout_test_using_training_on...,Holdout test is evaluation only. Do not choose...

[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_24.csv

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 24
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.128205128205128
  std : 20.162732019325432
  min : 0.0
  max : 80.0
X shape after clinical mode: (39, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 30
X_train shape: (26, 315)
X_test  shape: (13, 315)
y_train shape: (26,)
y_test  shape: (13,)
train unique ids: 26
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: C | tp: 24
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.128205128205128
  std : 20.162732019325432
  min : 0.0
  max : 80.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv
X shape after clinical mode: (39, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 20
X_train shape: (26, 315)
X_test  shape: (13, 315)
y_train shape: (26,)
y_test  shape: (13,)
train unique ids: 26
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (26, 301)
X_test_f  shape: (13, 301)

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv
n_removed_by_sparse: 14
removed example: ['CSF_RNA_hsa-miR-1273h-3p_TP24', 'CSF_RNA_hsa-miR-18a-5p_TP24', 'CSF_RNA_hsa-miR-20b-5p_TP24', 'CSF_RNA_hsa-miR-2115-3p_TP24', 'CSF_RNA_hsa-miR-224-5p_TP24', 'CSF_RNA_hsa-miR-301b-3p_TP24', 'CSF_RNA_hsa-miR-340-3p_TP24', 'CSF_RNA_hsa-miR-371b-5p_TP24', 'CSF_RNA_hsa-miR-431-5p_TP24', 'CSF_RNA_hsa-miR-4433b-5p_TP24', 'CSF_RNA_hsa-miR-550a-3p_TP24', 'CSF_RNA_hsa-miR-625-5p_TP24', 'CSF_RNA_hsa-miR-6852-5p_TP24', 'CSF_RNA_hsa-miR-96-5p_TP24']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[AFTER CLINICAL ENCODING]
X_train_f shape: (26, 314)
X_test_f  shape: (13, 314)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (26, 314)
X_test_f  shape: (13, 314)
candidate feature examples: ['CSF_RNA_hsa-let-7a-3p_TP24', 'CSF_RNA_hsa-let-7a-5p_TP24', 'CSF_RNA_hsa-let-7b-3p_TP24', 'CSF_RNA_hsa-let-7b-5p_TP24', 'CSF_RNA_hsa-let-7c-5p_TP24', 'CSF_RNA_hsa-let-7d-3p_TP24', 'CSF_RNA_hsa-let-7d-5p_TP24', 'CSF_RNA_hsa-let-7e-5p_TP24', 'CSF_RNA_hsa-let-7f-5p_TP24', 'CSF_RNA_hsa-let-7g-5p_TP24', 'CSF_RNA_hsa-let-7i-3p_TP24', 'CSF_RNA_hsa-let-7i-5p_TP24', 'CSF_RNA_hsa-miR-100-5p_TP24', 'CSF_RNA_hsa-miR-101-3p_TP24', 'CSF_RNA_hsa-miR-103a-3p_TP24', 'CSF_RNA_hsa-miR-106b-3p_TP24', 'CSF_RNA_hsa-miR-106b-5p_TP24', 'CSF_RNA_hsa-miR-107_TP24', 'CSF_RNA_hsa-miR-10a-3p_TP24', 'CSF_RNA_hsa-miR-10a-5p_TP24', 'CSF_RNA_hsa-miR-10b-3p_TP24', 'CSF_RNA_hsa-miR-10b-5p_TP24', 'CSF_RNA_hsa-miR-1180-3p_TP24', 'CSF_RNA_hsa-miR-122-5p_TP24', 'CSF_RNA_hsa-miR-124-3p_TP24', 'CSF_RNA_hsa-miR-1246_TP24', 'CSF_RNA_hsa-miR-1247-5p_TP24', 'CSF_RNA_hsa-miR-125a-3p_TP24', 'CSF_RNA_hsa-miR-125a-5p_TP24', 'CSF_RNA_hsa-miR-125b-1-3p_TP24']

[AFTER SPARSE FILTER]
X_train_f shape: (26, 301)
X_test_f  shape: (13, 301)
n_removed_by_sparse: 14
removed example: ['CSF_RNA_hsa-miR-1273h-3p_TP24', 'CSF_RNA_hsa-miR-18a-5p_TP24', 'CSF_RNA_hsa-miR-20b-5p_TP24', 'CSF_RNA_hsa-miR-2115-3p_TP24', 'CSF_RNA_hsa-miR-224-5p_TP24', 'CSF_RNA_hsa-miR-301b-3p_TP24', 'CSF_RNA_hsa-miR-340-3p_TP24', 'CSF_RNA_hsa-miR-371b-5p_TP24', 'CSF_RNA_hsa-miR-431-5p_TP24', 'CSF_RNA_hsa-miR-4433b-5p_TP24', 'CSF_RNA_hsa-miR-550a-3p_TP24', 'CSF_RNA_hsa-miR-625-5p_TP24', 'CSF_RNA_hsa-miR-6852-5p_TP24', 'CSF_RNA_hsa-miR-96-5p_TP24']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.99074074074074
  std : 20.349973188974218
  min : -6.0
  max : 80.0

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
X shape after clinical mode: (108, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.18421052631579
  std : 20.43031036945642
  min : 0.0
  max : 80.0

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 100
X_train shape: (58, 441)
X_test  shape: (30, 441)
y_train shape: (58,)
y_test  shape: (30,)
train unique ids: 58
test unique ids : 30
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (26, 314)
X_test_f  shape: X shape after clinical mode:(13, 314)
 encoded clinical cols: (38, 315)
['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']delta cols count:
 0n_encoded_clinical_cols:
 clinical cols present:16
['Age', 'Gender', 'Level']
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (26, 314)
X_test_f  shape: (13, 314)
candidate feature examples: ['CSF_RNA_hsa-let-7a-3p_TP24', 'CSF_RNA_hsa-let-7a-5p_TP24', 'CSF_RNA_hsa-let-7b-3p_TP24', 'CSF_RNA_hsa-let-7b-5p_TP24', 'CSF_RNA_hsa-let-7c-5p_TP24', 'CSF_RNA_hsa-let-7d-3p_TP24', 'CSF_RNA_hsa-let-7d-5p_TP24', 'CSF_RNA_hsa-let-7e-5p_TP24', 'CSF_RNA_hsa-let-7f-5p_TP24', 'CSF_RNA_hsa-let-7g-5p_TP24', 'CSF_RNA_hsa-let-7i-3p_TP24', 'CSF_RNA_hsa-let-7i-5p_TP24', 'CSF_RNA_hsa-miR-100-5p_TP24', 'CSF_RNA_hsa-miR-101-3p_TP24', 'CSF_RNA_hsa-miR-103a-3p_TP24', 'CSF_RNA_hsa-miR-106b-3p_TP24', 'CSF_RNA_hsa-miR-106b-5p_TP24', 'CSF_RNA_hsa-miR-107_TP24', 'CSF_RNA_hsa-miR-10a-3p_TP24', 'CSF_RNA_hsa-miR-10a-5p_TP24', 'CSF_RNA_hsa-miR-10b-3p_TP24', 'CSF_RNA_hsa-miR-10b-5p_TP24', 'CSF_RNA_hsa-miR-1180-3p_TP24', 'CSF_RNA_hsa-miR-122-5p_TP24', 'CSF_RNA_hsa-miR-124-3p_TP24', 'CSF_RNA_hsa-miR-1246_TP24', 'CSF_RNA_hsa-miR-1247-5p_TP24', 'CSF_RNA_hsa-miR-125a-3p_TP24', 'CSF_RNA_hsa-miR-125a-5p_TP24', 'CSF_RNA_hsa-miR-125b-1-3p_TP24']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_train shape: (25, 315)
X_test  shape: (13, 315)
y_train shape: (25,)
y_test  shape: (13,)
train unique ids: 25
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.99074074074074
  std : 20.349973188974218
  min : -6.0
  max : 80.0
X shape after clinical mode: (108, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 120
X_train shape: (58, 441)
X_test  shape: (30, 441)
y_train shape: (58,)
y_test  shape: (30,)
train unique ids: 58
test unique ids : 30
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (25, 304)
X_test_f  shape: (13, 304)
n_removed_by_sparse: 11
removed example: ['SERUM_RNA_hsa-miR-124-3p_TP24', 'SERUM_RNA_hsa-miR-129-5p_TP24', 'SERUM_RNA_hsa-miR-1298-3p_TP24', 'SERUM_RNA_hsa-miR-1298-5p_TP24', 'SERUM_RNA_hsa-miR-1299_TP24', 'SERUM_RNA_hsa-miR-1911-5p_TP24', 'SERUM_RNA_hsa-miR-204-3p_TP24', 'SERUM_RNA_hsa-miR-219a-2-3p_TP24', 'SERUM_RNA_hsa-miR-219a-5p_TP24', 'SERUM_RNA_hsa-miR-488-3p_TP24', 'SERUM_RNA_hsa-miR-615-3p_TP24']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (58, 130)
X_test_f  shape: (30, 130)
n_removed_by_sparse: 311
removed example: ['SERUM_PROT_A1BG|GVTFLLR_TP96', 'SERUM_PROT_ACO1|NIEVPFKPAR_TP96', 'SERUM_PROT_ACTA2|SYELPDGQVITIGNER_TP96', 'SERUM_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP96', 'SERUM_PROT_ACY1|LHEAVFLR_TP96', 'SERUM_PROT_ACYP2|LEYSNFSIR_TP96', 'SERUM_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP96', 'SERUM_PROT_ADD1|VDENNPEYLR_TP96', 'SERUM_PROT_ADH1B|FSLDALITHVLPFEK_TP96', 'SERUM_PROT_ADIRF|TTQETIDK_TP96', 'SERUM_PROT_AFM|HFQNLGK_TP96', 'SERUM_PROT_AGA|NAIGVAR_TP96', 'SERUM_PROT_AHCY|VPAINVNDSVTK_TP96', 'SERUM_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP96', 'SERUM_PROT_AK1|IIFVVGGPGSGK_TP96', 'SERUM_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP96', 'SERUM_PROT_AKR1E2|NVIVIPGSITPSHIK_TP96', 'SERUM_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP96', 'SERUM_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP96', 'SERUM_PROT_ALAD|GSAADSEESPAIEAIHLLR_TP96']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.145631067961165
  std : 19.99431672534811
  min : -6.0
  max : 80.0

[AFTER CLINICAL ENCODING]
X_train_f shape: (25, 317)
X_test_f  shape: (13, 317)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (25, 317)
X_test_f  shape: (13, 317)
candidate feature examples: ['SERUM_RNA_hsa-let-7a-3p_TP24', 'SERUM_RNA_hsa-let-7a-5p_TP24', 'SERUM_RNA_hsa-let-7b-3p_TP24', 'SERUM_RNA_hsa-let-7b-5p_TP24', 'SERUM_RNA_hsa-let-7c-5p_TP24', 'SERUM_RNA_hsa-let-7d-3p_TP24', 'SERUM_RNA_hsa-let-7d-5p_TP24', 'SERUM_RNA_hsa-let-7e-5p_TP24', 'SERUM_RNA_hsa-let-7f-5p_TP24', 'SERUM_RNA_hsa-let-7g-5p_TP24', 'SERUM_RNA_hsa-let-7i-3p_TP24', 'SERUM_RNA_hsa-let-7i-5p_TP24', 'SERUM_RNA_hsa-miR-100-5p_TP24', 'SERUM_RNA_hsa-miR-101-3p_TP24', 'SERUM_RNA_hsa-miR-103a-3p_TP24', 'SERUM_RNA_hsa-miR-106b-3p_TP24', 'SERUM_RNA_hsa-miR-106b-5p_TP24', 'SERUM_RNA_hsa-miR-107_TP24', 'SERUM_RNA_hsa-miR-10a-3p_TP24', 'SERUM_RNA_hsa-miR-10a-5p_TP24', 'SERUM_RNA_hsa-miR-10b-3p_TP24', 'SERUM_RNA_hsa-miR-10b-5p_TP24', 'SERUM_RNA_hsa-miR-1180-3p_TP24', 'SERUM_RNA_hsa-miR-122-5p_TP24', 'SERUM_RNA_hsa-miR-1246_TP24', 'SERUM_RNA_hsa-miR-1247-5p_TP24', 'SERUM_RNA_hsa-miR-125a-3p_TP24', 'SERUM_RNA_hsa-miR-125a-5p_TP24', 'SERUM_RNA_hsa-miR-125b-1-3p_TP24', 'SERUM_RNA_hsa-miR-125b-2-3p_TP24']
X shape after clinical mode: (103, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (58, 150)
X_test_f  shape: (30, 150)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (58, 150)
X_test_f  shape: (30, 150)
candidate feature examples: ['SERUM_PROT_A1BG|LETPDFQLFK_TP96', 'SERUM_PROT_A2M|AIGYLNTGYQR_TP96', 'SERUM_PROT_ADGRF5|DVIVHPLPLK_TP96', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'SERUM_PROT_AFM|DADPDTFFAK_TP96', 'SERUM_PROT_AGT|ALQDQLVLVAAK_TP96', 'SERUM_PROT_AHSG|FSVVYAK_TP96', 'SERUM_PROT_ALB|LVNEVTEFAK_TP96', 'SERUM_PROT_AMBP|HHGPTITAK_TP96', 'SERUM_PROT_APCS|IVLGQEQDSYGGK_TP96', 'SERUM_PROT_APMAP|LLEYDTVTR_TP96', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP96', 'SERUM_PROT_APOA2|SPELQAEAK_TP96', 'SERUM_PROT_APOA4|LGEVNTYAGDLQK_TP96', 'SERUM_PROT_APOB|FPEVDVLTK_TP96', 'SERUM_PROT_APOC1|EWFSETFQK_TP96', 'SERUM_PROT_APOC2|TYLPAVDEK_TP96', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP96', 'SERUM_PROT_APOC4|ELLETVVNR_TP96', 'SERUM_PROT_APOD|NILTSNNIDVK_TP96', 'SERUM_PROT_APOE|LGPLVEQGR_TP96', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP96', 'SERUM_PROT_APOH|ATVVYQGER_TP96', 'SERUM_PROT_APOL1|VAQELEEK_TP96', 'SERUM_PROT_APOM|AFLLTPR_TP96', 'SERUM_PROT_ATRN|SVNNVVVR_TP96', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP96', 'SERUM_PROT_B2M|VNHVTLSQPK_TP96', 'SERUM_PROT_BCHE|YLTLNTESTR_TP96', 'SERUM_PROT_BTD|SHLIIAQVAK_TP96']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_train shape: (55, 441)
X_test  shape: (28, 441)
y_train shape: (55,)
y_test  shape: (28,)
train unique ids: 55
test unique ids : 28
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (58, 130)
X_test_f  shape: (30, 130)
n_removed_by_sparse: 311
removed example: ['SERUM_PROT_A1BG|GVTFLLR_TP96', 'SERUM_PROT_ACO1|NIEVPFKPAR_TP96', 'SERUM_PROT_ACTA2|SYELPDGQVITIGNER_TP96', 'SERUM_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP96', 'SERUM_PROT_ACY1|LHEAVFLR_TP96', 'SERUM_PROT_ACYP2|LEYSNFSIR_TP96', 'SERUM_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP96', 'SERUM_PROT_ADD1|VDENNPEYLR_TP96', 'SERUM_PROT_ADH1B|FSLDALITHVLPFEK_TP96', 'SERUM_PROT_ADIRF|TTQETIDK_TP96', 'SERUM_PROT_AFM|HFQNLGK_TP96', 'SERUM_PROT_AGA|NAIGVAR_TP96', 'SERUM_PROT_AHCY|VPAINVNDSVTK_TP96', 'SERUM_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP96', 'SERUM_PROT_AK1|IIFVVGGPGSGK_TP96', 'SERUM_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP96', 'SERUM_PROT_AKR1E2|NVIVIPGSITPSHIK_TP96', 'SERUM_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP96', 'SERUM_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP96', 'SERUM_PROT_ALAD|GSAADSEESPAIEAIHLLR_TP96']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (58, 150)
X_test_f  shape: (30, 150)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (58, 150)
X_test_f  shape: (30, 150)
candidate feature examples: ['SERUM_PROT_A1BG|LETPDFQLFK_TP96', 'SERUM_PROT_A2M|AIGYLNTGYQR_TP96', 'SERUM_PROT_ADGRF5|DVIVHPLPLK_TP96', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'SERUM_PROT_AFM|DADPDTFFAK_TP96', 'SERUM_PROT_AGT|ALQDQLVLVAAK_TP96', 'SERUM_PROT_AHSG|FSVVYAK_TP96', 'SERUM_PROT_ALB|LVNEVTEFAK_TP96', 'SERUM_PROT_AMBP|HHGPTITAK_TP96', 'SERUM_PROT_APCS|IVLGQEQDSYGGK_TP96', 'SERUM_PROT_APMAP|LLEYDTVTR_TP96', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP96', 'SERUM_PROT_APOA2|SPELQAEAK_TP96', 'SERUM_PROT_APOA4|LGEVNTYAGDLQK_TP96', 'SERUM_PROT_APOB|FPEVDVLTK_TP96', 'SERUM_PROT_APOC1|EWFSETFQK_TP96', 'SERUM_PROT_APOC2|TYLPAVDEK_TP96', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP96', 'SERUM_PROT_APOC4|ELLETVVNR_TP96', 'SERUM_PROT_APOD|NILTSNNIDVK_TP96', 'SERUM_PROT_APOE|LGPLVEQGR_TP96', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP96', 'SERUM_PROT_APOH|ATVVYQGER_TP96', 'SERUM_PROT_APOL1|VAQELEEK_TP96', 'SERUM_PROT_APOM|AFLLTPR_TP96', 'SERUM_PROT_ATRN|SVNNVVVR_TP96', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP96', 'SERUM_PROT_B2M|VNHVTLSQPK_TP96', 'SERUM_PROT_BCHE|YLTLNTESTR_TP96', 'SERUM_PROT_BTD|SHLIIAQVAK_TP96']

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[AFTER SPARSE FILTER]
X_train_f shape: (55, 169)
X_test_f  shape: (28, 169)

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv
n_removed_by_sparse: 272
removed example: ['CSF_PROT_A1BG|LETPDFQLFK_TP96', 'CSF_PROT_A2M|AIGYLNTGYQR_TP96', 'CSF_PROT_ACO1|NIEVPFKPAR_TP96', 'CSF_PROT_ACTA2|SYELPDGQVITIGNER_TP96', 'CSF_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP96', 'CSF_PROT_ACY1|LHEAVFLR_TP96', 'CSF_PROT_ACYP2|LEYSNFSIR_TP96', 'CSF_PROT_ADD1|VDENNPEYLR_TP96', 'CSF_PROT_ADGRF5|DVIVHPLPLK_TP96', 'CSF_PROT_ADH1B|FSLDALITHVLPFEK_TP96', 'CSF_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'CSF_PROT_ADIRF|TTQETIDK_TP96', 'CSF_PROT_AFM|DADPDTFFAK_TP96', 'CSF_PROT_AGT|ALQDQLVLVAAK_TP96', 'CSF_PROT_AHCY|VPAINVNDSVTK_TP96', 'CSF_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP96', 'CSF_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP96', 'CSF_PROT_AKR1E2|NVIVIPGSITPSHIK_TP96', 'CSF_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP96', 'CSF_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP96']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (55, 189)
X_test_f  shape: (28, 189)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (55, 189)
X_test_f  shape: (28, 189)

[Parallel(n_jobs=8)]: Done   2 tasks      | elapsed:    8.9s

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 30
selected feature examples: ['CSF_RNA_hsa-let-7g-5p_TP24', 'CSF_RNA_hsa-miR-1285-3p_TP24', 'CSF_RNA_hsa-miR-1294_TP24', 'CSF_RNA_hsa-miR-143-3p_TP24', 'CSF_RNA_hsa-miR-145-3p_TP24', 'CSF_RNA_hsa-miR-181a-2-3p_TP24', 'CSF_RNA_hsa-miR-18a-3p_TP24', 'CSF_RNA_hsa-miR-1910-5p_TP24', 'CSF_RNA_hsa-miR-193b-3p_TP24', 'CSF_RNA_hsa-miR-3158-3p_TP24', 'CSF_RNA_hsa-miR-374a-3p_TP24', 'CSF_RNA_hsa-miR-454-5p_TP24', 'CSF_RNA_hsa-miR-628-3p_TP24', 'CSF_RNA_hsa-miR-877-5p_TP24', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 50.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.1597392370284072
train_r2: 0.8138721168494094
train_mae: 7.274446289233982
test_r2 : -0.3010578524371599
test_mae: 15.969808126309907
pred_train summary:
  mean: 18.96153846153846
  std : 13.803165784312926
  min : 3.4461699343746535
  max : 56.95301566011295
pred_test summary:
  mean: 20.61853591938047
  std : 10.77569202369045
  min : 6.9469799111542905
  max : 47.09823305193056
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.145631067961165
  std : 19.99431672534811
  min : -6.0
  max : 80.0
X shape after clinical mode: (103, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 60
X_train shape: (55, 441)
X_test  shape: (28, 441)
y_train shape: (55,)
y_test  shape: (28,)
train unique ids: 55
test unique ids : 28
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (55, 174)
X_test_f  shape: (28, 174)
n_removed_by_sparse: 267
removed example: ['CSF_PROT_A1BG|LETPDFQLFK_TP72', 'CSF_PROT_A2M|AIGYLNTGYQR_TP72', 'CSF_PROT_ACO1|NIEVPFKPAR_TP72', 'CSF_PROT_ACTA2|SYELPDGQVITIGNER_TP72', 'CSF_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP72', 'CSF_PROT_ACYP2|LEYSNFSIR_TP72', 'CSF_PROT_ADD1|VDENNPEYLR_TP72', 'CSF_PROT_ADGRF5|DVIVHPLPLK_TP72', 'CSF_PROT_ADH1B|FSLDALITHVLPFEK_TP72', 'CSF_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP72', 'CSF_PROT_ADIRF|TTQETIDK_TP72', 'CSF_PROT_AFM|DADPDTFFAK_TP72', 'CSF_PROT_AGT|ALQDQLVLVAAK_TP72', 'CSF_PROT_AHCY|VPAINVNDSVTK_TP72', 'CSF_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP72', 'CSF_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP72', 'CSF_PROT_AKR1E2|NVIVIPGSITPSHIK_TP72', 'CSF_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP72', 'CSF_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP72', 'CSF_PROT_ALAD|GSAADSEESPAIEAIHLLR_TP72']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (55, 194)
X_test_f  shape: (28, 194)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (55, 194)
X_test_f  shape: (28, 194)
candidate feature examples: ['CSF_PROT_A1BG|GVTFLLR_TP72', 'CSF_PROT_ACY1|LHEAVFLR_TP72', 'CSF_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP72', 'CSF_PROT_AFM|HFQNLGK_TP72', 'CSF_PROT_AGA|NAIGVAR_TP72', 'CSF_PROT_AHSG|FSVVYAK_TP72', 'CSF_PROT_AK1|IIFVVGGPGSGK_TP72', 'CSF_PROT_AMBP|ETLLQDFR_TP72', 'CSF_PROT_ANXA2|QDIAFAYQR_TP72', 'CSF_PROT_APCS|VGEYSLYIGR_TP72', 'CSF_PROT_APOA4|SLAPYAQDTQEK_TP72', 'CSF_PROT_APOB|IEGNLIFDPNNYLPK_TP72', 'CSF_PROT_APOC2|ESLSSYWESAK_TP72', 'CSF_PROT_APOE|LGPLVEQGR_TP72', 'CSF_PROT_APOH|ATVVYQGER_TP72', 'CSF_PROT_APOL1|LNILNNNYK_TP72', 'CSF_PROT_APOM|AFLLTPR_TP72', 'CSF_PROT_AZGP1|YSLTYIYTGLSK_TP72', 'CSF_PROT_B2M|VNHVTLSQPK_TP72', 'CSF_PROT_B4GAT1|TALASGGVLDASGDYR_TP72', 'CSF_PROT_BCAN|YPIVTPSQR_TP72', 'CSF_PROT_BCHE|YLTLNTESTR_TP72', 'CSF_PROT_BLVRB|TVAGQDAVIVLLGTR_TP72', 'CSF_PROT_BTD|LSSGLVTAALYGR_TP72', 'CSF_PROT_C16orf89|ATIADLILSALER_TP72', 'CSF_PROT_C1QA|PAFSAIR_TP72', 'CSF_PROT_C1QB|IAFSATR_TP72', 'CSF_PROT_C1R|YTTEIIK_TP72', 'CSF_PROT_C2|ELNELGSK_TP72', 'CSF_PROT_C3|TGLQEVEVK_TP72']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 20
selected feature examples: ['CSF_RNA_hsa-miR-181a-2-3p_TP24', 'CSF_RNA_hsa-miR-18a-3p_TP24', 'CSF_RNA_hsa-miR-1910-5p_TP24', 'CSF_RNA_hsa-miR-877-5p_TP24', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 25.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.2764624824262447
train_r2: 0.7939644147424243
train_mae: 7.512762928334769
test_r2 : -0.0587867078414519
test_mae: 14.899025140167392
pred_train summary:
  mean: 18.96153846153846
  std : 13.993267709425604
  min : 1.0393600751901495
  max : 56.713877249714514
pred_test summary:
  mean: 17.517958898953125
  std : 6.946413196646788
  min : 6.493569018206658
  max : 31.730082191115
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 96
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.99074074074074
  std : 20.349973188974218
  min : -6.0
  max : 80.0
X shape after clinical mode: (108, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 140
X_train shape: (58, 441)
X_test  shape: (30, 441)
y_train shape: (58,)
y_test  shape: (30,)
train unique ids: 58
test unique ids : 30
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (58, 130)
X_test_f  shape: (30, 130)
n_removed_by_sparse: 311
removed example: ['SERUM_PROT_A1BG|GVTFLLR_TP96', 'SERUM_PROT_ACO1|NIEVPFKPAR_TP96', 'SERUM_PROT_ACTA2|SYELPDGQVITIGNER_TP96', 'SERUM_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP96', 'SERUM_PROT_ACY1|LHEAVFLR_TP96', 'SERUM_PROT_ACYP2|LEYSNFSIR_TP96', 'SERUM_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP96', 'SERUM_PROT_ADD1|VDENNPEYLR_TP96', 'SERUM_PROT_ADH1B|FSLDALITHVLPFEK_TP96', 'SERUM_PROT_ADIRF|TTQETIDK_TP96', 'SERUM_PROT_AFM|HFQNLGK_TP96', 'SERUM_PROT_AGA|NAIGVAR_TP96', 'SERUM_PROT_AHCY|VPAINVNDSVTK_TP96', 'SERUM_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP96', 'SERUM_PROT_AK1|IIFVVGGPGSGK_TP96', 'SERUM_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP96', 'SERUM_PROT_AKR1E2|NVIVIPGSITPSHIK_TP96', 'SERUM_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP96', 'SERUM_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP96', 'SERUM_PROT_ALAD|GSAADSEESPAIEAIHLLR_TP96']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (58, 150)
X_test_f  shape: (30, 150)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (58, 150)
X_test_f  shape: (30, 150)
candidate feature examples: ['SERUM_PROT_A1BG|LETPDFQLFK_TP96', 'SERUM_PROT_A2M|AIGYLNTGYQR_TP96', 'SERUM_PROT_ADGRF5|DVIVHPLPLK_TP96', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'SERUM_PROT_AFM|DADPDTFFAK_TP96', 'SERUM_PROT_AGT|ALQDQLVLVAAK_TP96', 'SERUM_PROT_AHSG|FSVVYAK_TP96', 'SERUM_PROT_ALB|LVNEVTEFAK_TP96', 'SERUM_PROT_AMBP|HHGPTITAK_TP96', 'SERUM_PROT_APCS|IVLGQEQDSYGGK_TP96', 'SERUM_PROT_APMAP|LLEYDTVTR_TP96', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP96', 'SERUM_PROT_APOA2|SPELQAEAK_TP96', 'SERUM_PROT_APOA4|LGEVNTYAGDLQK_TP96', 'SERUM_PROT_APOB|FPEVDVLTK_TP96', 'SERUM_PROT_APOC1|EWFSETFQK_TP96', 'SERUM_PROT_APOC2|TYLPAVDEK_TP96', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP96', 'SERUM_PROT_APOC4|ELLETVVNR_TP96', 'SERUM_PROT_APOD|NILTSNNIDVK_TP96', 'SERUM_PROT_APOE|LGPLVEQGR_TP96', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP96', 'SERUM_PROT_APOH|ATVVYQGER_TP96', 'SERUM_PROT_APOL1|VAQELEEK_TP96', 'SERUM_PROT_APOM|AFLLTPR_TP96', 'SERUM_PROT_ATRN|SVNNVVVR_TP96', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP96', 'SERUM_PROT_B2M|VNHVTLSQPK_TP96', 'SERUM_PROT_BCHE|YLTLNTESTR_TP96', 'SERUM_PROT_BTD|SHLIIAQVAK_TP96']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 100
selected feature examples: ['SERUM_PROT_ADGRF5|DVIVHPLPLK_TP96', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'SERUM_PROT_AFM|DADPDTFFAK_TP96', 'SERUM_PROT_AHSG|FSVVYAK_TP96', 'SERUM_PROT_ALB|LVNEVTEFAK_TP96', 'SERUM_PROT_AMBP|HHGPTITAK_TP96', 'SERUM_PROT_APMAP|LLEYDTVTR_TP96', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP96', 'SERUM_PROT_APOA2|SPELQAEAK_TP96', 'SERUM_PROT_APOB|FPEVDVLTK_TP96', 'SERUM_PROT_APOC1|EWFSETFQK_TP96', 'SERUM_PROT_APOC2|TYLPAVDEK_TP96', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP96', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP96', 'SERUM_PROT_APOL1|VAQELEEK_TP96', 'SERUM_PROT_APOM|AFLLTPR_TP96', 'SERUM_PROT_ATRN|SVNNVVVR_TP96', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP96', 'SERUM_PROT_BCHE|YLTLNTESTR_TP96', 'SERUM_PROT_BTD|SHLIIAQVAK_TP96', 'SERUM_PROT_C1R|GLTLHLK_TP96', 'SERUM_PROT_C1RL|VVVHPDYR_TP96', 'SERUM_PROT_C1S|TNFDNDIALVR_TP96', 'SERUM_PROT_C4A|VLSLAQEQVGGSPEK_TP96', 'SERUM_PROT_C5|VFQFLEK_TP96', 'SERUM_PROT_C9|LSPIYNLVPVK_TP96', 'SERUM_PROT_CFB|EELLPAQDIK_TP96', 'SERUM_PROT_CFH|SSQESYAHGTK_TP96', 'SERUM_PROT_CKM|FEEILTR_TP96', 'SERUM_PROT_CLU|ELDESLQVAER_TP96']

[FINAL PREDICTION CHECK]
best_model_type: svr_linear
best_params: {'model__C': 0.1, 'model__epsilon': 0.1, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.1765593745294885
train_r2: 0.5141508146056912
train_mae: 8.291488729536935
test_r2 : -0.04901043122372428
test_mae: 14.769857234439439
pred_train summary:
  mean: 15.029939453374885
  std : 11.949187033922973
  min : -0.10000044741826564
  max : 48.899953438957155
pred_test summary:
  mean: 12.299076558891098
  std : 8.99005913092689
  min : -10.519936323701744
  max : 35.78390027213984
y_test summary:
  mean: 13.1
  std : 19.047922021399955
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 24
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.128205128205128
  std : 20.162732019325432
  min : 0.0
  max : 80.0
X shape after clinical mode: (39, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_train shape: (26, 315)
X_test  shape: (13, 315)
y_train shape: (26,)
y_test  shape: (13,)
train unique ids: 26
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (26, 301)
X_test_f  shape: (13, 301)
n_removed_by_sparse: 14
removed example: ['CSF_RNA_hsa-miR-1273h-3p_TP24', 'CSF_RNA_hsa-miR-18a-5p_TP24', 'CSF_RNA_hsa-miR-20b-5p_TP24', 'CSF_RNA_hsa-miR-2115-3p_TP24', 'CSF_RNA_hsa-miR-224-5p_TP24', 'CSF_RNA_hsa-miR-301b-3p_TP24', 'CSF_RNA_hsa-miR-340-3p_TP24', 'CSF_RNA_hsa-miR-371b-5p_TP24', 'CSF_RNA_hsa-miR-431-5p_TP24', 'CSF_RNA_hsa-miR-4433b-5p_TP24', 'CSF_RNA_hsa-miR-550a-3p_TP24', 'CSF_RNA_hsa-miR-625-5p_TP24', 'CSF_RNA_hsa-miR-6852-5p_TP24', 'CSF_RNA_hsa-miR-96-5p_TP24']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (26, 314)
X_test_f  shape: (13, 314)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (26, 314)
X_test_f  shape: (13, 314)
candidate feature examples: ['CSF_RNA_hsa-let-7a-3p_TP24', 'CSF_RNA_hsa-let-7a-5p_TP24', 'CSF_RNA_hsa-let-7b-3p_TP24', 'CSF_RNA_hsa-let-7b-5p_TP24', 'CSF_RNA_hsa-let-7c-5p_TP24', 'CSF_RNA_hsa-let-7d-3p_TP24', 'CSF_RNA_hsa-let-7d-5p_TP24', 'CSF_RNA_hsa-let-7e-5p_TP24', 'CSF_RNA_hsa-let-7f-5p_TP24', 'CSF_RNA_hsa-let-7g-5p_TP24', 'CSF_RNA_hsa-let-7i-3p_TP24', 'CSF_RNA_hsa-let-7i-5p_TP24', 'CSF_RNA_hsa-miR-100-5p_TP24', 'CSF_RNA_hsa-miR-101-3p_TP24', 'CSF_RNA_hsa-miR-103a-3p_TP24', 'CSF_RNA_hsa-miR-106b-3p_TP24', 'CSF_RNA_hsa-miR-106b-5p_TP24', 'CSF_RNA_hsa-miR-107_TP24', 'CSF_RNA_hsa-miR-10a-3p_TP24', 'CSF_RNA_hsa-miR-10a-5p_TP24', 'CSF_RNA_hsa-miR-10b-3p_TP24', 'CSF_RNA_hsa-miR-10b-5p_TP24', 'CSF_RNA_hsa-miR-1180-3p_TP24', 'CSF_RNA_hsa-miR-122-5p_TP24', 'CSF_RNA_hsa-miR-124-3p_TP24', 'CSF_RNA_hsa-miR-1246_TP24', 'CSF_RNA_hsa-miR-1247-5p_TP24', 'CSF_RNA_hsa-miR-125a-3p_TP24', 'CSF_RNA_hsa-miR-125a-5p_TP24', 'CSF_RNA_hsa-miR-125b-1-3p_TP24']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 120
selected feature examples: ['SERUM_PROT_A1BG|LETPDFQLFK_TP96', 'SERUM_PROT_ADGRF5|DVIVHPLPLK_TP96', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'SERUM_PROT_AFM|DADPDTFFAK_TP96', 'SERUM_PROT_AHSG|FSVVYAK_TP96', 'SERUM_PROT_ALB|LVNEVTEFAK_TP96', 'SERUM_PROT_AMBP|HHGPTITAK_TP96', 'SERUM_PROT_APCS|IVLGQEQDSYGGK_TP96', 'SERUM_PROT_APMAP|LLEYDTVTR_TP96', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP96', 'SERUM_PROT_APOA2|SPELQAEAK_TP96', 'SERUM_PROT_APOB|FPEVDVLTK_TP96', 'SERUM_PROT_APOC1|EWFSETFQK_TP96', 'SERUM_PROT_APOC2|TYLPAVDEK_TP96', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP96', 'SERUM_PROT_APOD|NILTSNNIDVK_TP96', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP96', 'SERUM_PROT_APOH|ATVVYQGER_TP96', 'SERUM_PROT_APOL1|VAQELEEK_TP96', 'SERUM_PROT_APOM|AFLLTPR_TP96', 'SERUM_PROT_ATRN|SVNNVVVR_TP96', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP96', 'SERUM_PROT_BCHE|YLTLNTESTR_TP96', 'SERUM_PROT_BTD|SHLIIAQVAK_TP96', 'SERUM_PROT_C1QC|FQSVFTVTR_TP96', 'SERUM_PROT_C1R|GLTLHLK_TP96', 'SERUM_PROT_C1RL|VVVHPDYR_TP96', 'SERUM_PROT_C1S|TNFDNDIALVR_TP96', 'SERUM_PROT_C3|TGLQEVEVK_TP96', 'SERUM_PROT_C4A|VLSLAQEQVGGSPEK_TP96']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 100
selected feature examples: ['SERUM_PROT_ADGRF5|DVIVHPLPLK_TP96', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'SERUM_PROT_AFM|DADPDTFFAK_TP96', 'SERUM_PROT_AHSG|FSVVYAK_TP96', 'SERUM_PROT_ALB|LVNEVTEFAK_TP96', 'SERUM_PROT_AMBP|HHGPTITAK_TP96', 'SERUM_PROT_APMAP|LLEYDTVTR_TP96', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP96', 'SERUM_PROT_APOA2|SPELQAEAK_TP96', 'SERUM_PROT_APOB|FPEVDVLTK_TP96', 'SERUM_PROT_APOC1|EWFSETFQK_TP96', 'SERUM_PROT_APOC2|TYLPAVDEK_TP96', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP96', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP96', 'SERUM_PROT_APOL1|VAQELEEK_TP96', 'SERUM_PROT_APOM|AFLLTPR_TP96', 'SERUM_PROT_ATRN|SVNNVVVR_TP96', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP96', 'SERUM_PROT_BCHE|YLTLNTESTR_TP96', 'SERUM_PROT_BTD|SHLIIAQVAK_TP96', 'SERUM_PROT_C1R|GLTLHLK_TP96', 'SERUM_PROT_C1RL|VVVHPDYR_TP96', 'SERUM_PROT_C1S|TNFDNDIALVR_TP96', 'SERUM_PROT_C4A|VLSLAQEQVGGSPEK_TP96', 'SERUM_PROT_C5|VFQFLEK_TP96', 'SERUM_PROT_C9|LSPIYNLVPVK_TP96', 'SERUM_PROT_CFB|EELLPAQDIK_TP96', 'SERUM_PROT_CFH|SSQESYAHGTK_TP96', 'SERUM_PROT_CKM|FEEILTR_TP96', 'SERUM_PROT_CLU|ELDESLQVAER_TP96']

[FINAL PREDICTION CHECK]
best_model_type: svr_linear
best_params: {'model__C': 0.1, 'model__epsilon': 0.1, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.16132782583417474
train_r2: 0.5439196316513893
train_mae: 7.745881875521964
test_r2 : -0.0508293107458162
test_mae: 15.040610704965264
pred_train summary:
  mean: 15.279683501301982
  std : 12.592150614685929
  min : -0.1000912461600656
  max : 48.90006023543048
pred_test summary:
  mean: 12.869115974580366
  std : 9.376719828495803
  min : -12.808002434826767
  max : 38.65224272491165
y_test summary:
  mean: 13.1
  std : 19.047922021399955
  min : -2.0
  max : 61.0

[FINAL PREDICTION CHECK]
best_model_type: svr_linear
best_params: {'model__C': 0.1, 'model__epsilon': 0.1, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17892496848525005
train_r2: 0.5141508146056912
train_mae: 8.291488729536935
test_r2 : -0.04901043122372428
test_mae: 14.769857234439439
pred_train summary:
  mean: 15.029939453374885
  std : 11.949187033922973
  min : -0.10000044741826564
  max : 48.899953438957155
pred_test summary:
  mean: 12.299076558891098
  std : 8.99005913092689
  min : -10.519936323701744
  max : 35.78390027213984
y_test summary:
  mean: 13.1
  std : 19.047922021399955
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 48
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.18421052631579
  std : 20.43031036945642
  min : 0.0
  max : 80.0
X shape after clinical mode: (38, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 15
X_train shape: (25, 315)
X_test  shape: (13, 315)
y_train shape: (25,)
y_test  shape: (13,)
train unique ids: 25
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_120.csv

[AFTER SPARSE FILTER]
X_train_f shape: (25, 303)
X_test_f  shape: (13, 303)
n_removed_by_sparse: 12
removed example: ['SERUM_RNA_hsa-miR-124-3p_TP48', 'SERUM_RNA_hsa-miR-129-5p_TP48', 'SERUM_RNA_hsa-miR-1298-3p_TP48', 'SERUM_RNA_hsa-miR-1298-5p_TP48', 'SERUM_RNA_hsa-miR-1299_TP48', 'SERUM_RNA_hsa-miR-184_TP48', 'SERUM_RNA_hsa-miR-1911-5p_TP48', 'SERUM_RNA_hsa-miR-204-3p_TP48', 'SERUM_RNA_hsa-miR-219a-2-3p_TP48', 'SERUM_RNA_hsa-miR-219a-5p_TP48', 'SERUM_RNA_hsa-miR-488-3p_TP48', 'SERUM_RNA_hsa-miR-615-3p_TP48']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (25, 316)
X_test_f  shape: (13, 316)

[Parallel(n_jobs=8)]: Done   9 tasks      | elapsed:   21.0s

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 120
selected feature examples: ['SERUM_PROT_A1BG|LETPDFQLFK_TP96', 'SERUM_PROT_ADGRF5|DVIVHPLPLK_TP96', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'SERUM_PROT_AFM|DADPDTFFAK_TP96', 'SERUM_PROT_AHSG|FSVVYAK_TP96', 'SERUM_PROT_ALB|LVNEVTEFAK_TP96', 'SERUM_PROT_AMBP|HHGPTITAK_TP96', 'SERUM_PROT_APCS|IVLGQEQDSYGGK_TP96', 'SERUM_PROT_APMAP|LLEYDTVTR_TP96', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP96', 'SERUM_PROT_APOA2|SPELQAEAK_TP96', 'SERUM_PROT_APOB|FPEVDVLTK_TP96', 'SERUM_PROT_APOC1|EWFSETFQK_TP96', 'SERUM_PROT_APOC2|TYLPAVDEK_TP96', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP96', 'SERUM_PROT_APOD|NILTSNNIDVK_TP96', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP96', 'SERUM_PROT_APOH|ATVVYQGER_TP96', 'SERUM_PROT_APOL1|VAQELEEK_TP96', 'SERUM_PROT_APOM|AFLLTPR_TP96', 'SERUM_PROT_ATRN|SVNNVVVR_TP96', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP96', 'SERUM_PROT_BCHE|YLTLNTESTR_TP96', 'SERUM_PROT_BTD|SHLIIAQVAK_TP96', 'SERUM_PROT_C1QC|FQSVFTVTR_TP96', 'SERUM_PROT_C1R|GLTLHLK_TP96', 'SERUM_PROT_C1RL|VVVHPDYR_TP96', 'SERUM_PROT_C1S|TNFDNDIALVR_TP96', 'SERUM_PROT_C3|TGLQEVEVK_TP96', 'SERUM_PROT_C4A|VLSLAQEQVGGSPEK_TP96']

[FINAL PREDICTION CHECK]
best_model_type: svr_linear
best_params: {'model__C': 0.1, 'model__epsilon': 0.1, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17077444406446493
train_r2: 0.5439196316513893
train_mae: 7.745881875521964
test_r2 : -0.0508293107458162
test_mae: 15.040610704965264
pred_train summary:
  mean: 15.279683501301982
  std : 12.592150614685929
  min : -0.1000912461600656
  max : 48.90006023543048
pred_test summary:
  mean: 12.869115974580366
  std : 9.376719828495803
  min : -12.808002434826767
  max : 38.65224272491165
y_test summary:
  mean: 13.1
  std : 19.047922021399955
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 72
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.18421052631579
  std : 20.43031036945642
  min : 0.0
  max : 80.0
X shape after clinical mode: (38, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 5
X_train shape: (25, 315)
X_test  shape: (13, 315)
y_train shape: (25,)
y_test  shape: (13,)
train unique ids: 25
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (25, 302)
X_test_f  shape: (13, 302)
n_removed_by_sparse: 13
removed example: ['SERUM_RNA_hsa-miR-124-3p_TP72', 'SERUM_RNA_hsa-miR-129-5p_TP72', 'SERUM_RNA_hsa-miR-1298-3p_TP72', 'SERUM_RNA_hsa-miR-1298-5p_TP72', 'SERUM_RNA_hsa-miR-1299_TP72', 'SERUM_RNA_hsa-miR-184_TP72', 'SERUM_RNA_hsa-miR-1911-5p_TP72', 'SERUM_RNA_hsa-miR-204-3p_TP72', 'SERUM_RNA_hsa-miR-219a-2-3p_TP72', 'SERUM_RNA_hsa-miR-219a-5p_TP72', 'SERUM_RNA_hsa-miR-488-3p_TP72', 'SERUM_RNA_hsa-miR-615-3p_TP72', 'SERUM_RNA_hsa-miR-9-3p_TP72']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (25, 315)
X_test_f  shape: (13, 315)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (25, 315)
X_test_f  shape: (13, 315)
candidate feature examples: ['SERUM_RNA_hsa-let-7a-3p_TP72', 'SERUM_RNA_hsa-let-7a-5p_TP72', 'SERUM_RNA_hsa-let-7b-3p_TP72', 'SERUM_RNA_hsa-let-7b-5p_TP72', 'SERUM_RNA_hsa-let-7c-5p_TP72', 'SERUM_RNA_hsa-let-7d-3p_TP72', 'SERUM_RNA_hsa-let-7d-5p_TP72', 'SERUM_RNA_hsa-let-7e-5p_TP72', 'SERUM_RNA_hsa-let-7f-5p_TP72', 'SERUM_RNA_hsa-let-7g-5p_TP72', 'SERUM_RNA_hsa-let-7i-3p_TP72', 'SERUM_RNA_hsa-let-7i-5p_TP72', 'SERUM_RNA_hsa-miR-100-5p_TP72', 'SERUM_RNA_hsa-miR-101-3p_TP72', 'SERUM_RNA_hsa-miR-103a-3p_TP72', 'SERUM_RNA_hsa-miR-106b-3p_TP72', 'SERUM_RNA_hsa-miR-106b-5p_TP72', 'SERUM_RNA_hsa-miR-107_TP72', 'SERUM_RNA_hsa-miR-10a-3p_TP72', 'SERUM_RNA_hsa-miR-10a-5p_TP72', 'SERUM_RNA_hsa-miR-10b-3p_TP72', 'SERUM_RNA_hsa-miR-10b-5p_TP72', 'SERUM_RNA_hsa-miR-1180-3p_TP72', 'SERUM_RNA_hsa-miR-122-5p_TP72', 'SERUM_RNA_hsa-miR-1246_TP72', 'SERUM_RNA_hsa-miR-1247-5p_TP72', 'SERUM_RNA_hsa-miR-125a-3p_TP72', 'SERUM_RNA_hsa-miR-125a-5p_TP72', 'SERUM_RNA_hsa-miR-125b-1-3p_TP72', 'SERUM_RNA_hsa-miR-125b-2-3p_TP72']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 16
selected feature examples: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 25.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17855299189219467
train_r2: 0.46333961267119894
train_mae: 11.67335476830036
test_r2 : -0.45320330936598285
test_mae: 18.7369753953651
pred_train summary:
  mean: 19.12
  std : 9.538814833454746
  min : 7.13980106681991
  max : 41.2859007811485
pred_test summary:
  mean: 23.345663194262922
  std : 6.34068740942471
  min : 16.02481952008979
  max : 34.454181294323085
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 72
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.18421052631579
  std : 20.43031036945642
  min : 0.0
  max : 80.0
X shape after clinical mode: (38, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 10
X_train shape: (25, 315)
X_test  shape: (13, 315)
y_train shape: (25,)
y_test  shape: (13,)
train unique ids: 25
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (25, 302)
X_test_f  shape: (13, 302)
n_removed_by_sparse: 13
removed example: ['SERUM_RNA_hsa-miR-124-3p_TP72', 'SERUM_RNA_hsa-miR-129-5p_TP72', 'SERUM_RNA_hsa-miR-1298-3p_TP72', 'SERUM_RNA_hsa-miR-1298-5p_TP72', 'SERUM_RNA_hsa-miR-1299_TP72', 'SERUM_RNA_hsa-miR-184_TP72', 'SERUM_RNA_hsa-miR-1911-5p_TP72', 'SERUM_RNA_hsa-miR-204-3p_TP72', 'SERUM_RNA_hsa-miR-219a-2-3p_TP72', 'SERUM_RNA_hsa-miR-219a-5p_TP72', 'SERUM_RNA_hsa-miR-488-3p_TP72', 'SERUM_RNA_hsa-miR-615-3p_TP72', 'SERUM_RNA_hsa-miR-9-3p_TP72']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (25, 315)
X_test_f  shape: (13, 315)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (25, 315)
X_test_f  shape: (13, 315)
candidate feature examples: ['SERUM_RNA_hsa-let-7a-3p_TP72', 'SERUM_RNA_hsa-let-7a-5p_TP72', 'SERUM_RNA_hsa-let-7b-3p_TP72', 'SERUM_RNA_hsa-let-7b-5p_TP72', 'SERUM_RNA_hsa-let-7c-5p_TP72', 'SERUM_RNA_hsa-let-7d-3p_TP72', 'SERUM_RNA_hsa-let-7d-5p_TP72', 'SERUM_RNA_hsa-let-7e-5p_TP72', 'SERUM_RNA_hsa-let-7f-5p_TP72', 'SERUM_RNA_hsa-let-7g-5p_TP72', 'SERUM_RNA_hsa-let-7i-3p_TP72', 'SERUM_RNA_hsa-let-7i-5p_TP72', 'SERUM_RNA_hsa-miR-100-5p_TP72', 'SERUM_RNA_hsa-miR-101-3p_TP72', 'SERUM_RNA_hsa-miR-103a-3p_TP72', 'SERUM_RNA_hsa-miR-106b-3p_TP72', 'SERUM_RNA_hsa-miR-106b-5p_TP72', 'SERUM_RNA_hsa-miR-107_TP72', 'SERUM_RNA_hsa-miR-10a-3p_TP72', 'SERUM_RNA_hsa-miR-10a-5p_TP72', 'SERUM_RNA_hsa-miR-10b-3p_TP72', 'SERUM_RNA_hsa-miR-10b-5p_TP72', 'SERUM_RNA_hsa-miR-1180-3p_TP72', 'SERUM_RNA_hsa-miR-122-5p_TP72', 'SERUM_RNA_hsa-miR-1246_TP72', 'SERUM_RNA_hsa-miR-1247-5p_TP72', 'SERUM_RNA_hsa-miR-125a-3p_TP72', 'SERUM_RNA_hsa-miR-125a-5p_TP72', 'SERUM_RNA_hsa-miR-125b-1-3p_TP72', 'SERUM_RNA_hsa-miR-125b-2-3p_TP72']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 30
selected feature examples: ['CSF_RNA_hsa-let-7g-5p_TP24', 'CSF_RNA_hsa-miR-1294_TP24', 'CSF_RNA_hsa-miR-143-3p_TP24', 'CSF_RNA_hsa-miR-145-3p_TP24', 'CSF_RNA_hsa-miR-181a-2-3p_TP24', 'CSF_RNA_hsa-miR-18a-3p_TP24', 'CSF_RNA_hsa-miR-1910-5p_TP24', 'CSF_RNA_hsa-miR-193b-3p_TP24', 'CSF_RNA_hsa-miR-3605-3p_TP24', 'CSF_RNA_hsa-miR-375_TP24', 'CSF_RNA_hsa-miR-454-5p_TP24', 'CSF_RNA_hsa-miR-628-3p_TP24', 'CSF_RNA_hsa-miR-877-5p_TP24', 'CSF_RNA_hsa-miR-93-5p_TP24', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 100.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: -0.028393097363707792
train_r2: 0.7131875625890539
train_mae: 9.101732125721647
test_r2 : -0.22054696055851863
test_mae: 16.212200903600724
pred_train summary:
  mean: 18.96153846153846
  std : 11.29675356937362
  min : 4.881687374160586
  max : 51.422492561625596
pred_test summary:
  mean: 20.57060738109035
  std : 8.204169520840447
  min : 9.73591100007238
  max : 41.18647588220779
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 120
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.18421052631579
  std : 20.43031036945642
  min : 0.0
  max : 80.0
X shape after clinical mode: (38, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 5
X_train shape: (25, 315)
X_test  shape: (13, 315)
y_train shape: (25,)
y_test  shape: (13,)
train unique ids: 25
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (25, 300)
X_test_f  shape: (13, 300)
n_removed_by_sparse: 15
removed example: ['SERUM_RNA_hsa-miR-124-3p_TP120', 'SERUM_RNA_hsa-miR-129-5p_TP120', 'SERUM_RNA_hsa-miR-1298-3p_TP120', 'SERUM_RNA_hsa-miR-1298-5p_TP120', 'SERUM_RNA_hsa-miR-184_TP120', 'SERUM_RNA_hsa-miR-1911-5p_TP120', 'SERUM_RNA_hsa-miR-204-3p_TP120', 'SERUM_RNA_hsa-miR-219a-2-3p_TP120', 'SERUM_RNA_hsa-miR-219a-5p_TP120', 'SERUM_RNA_hsa-miR-34c-5p_TP120', 'SERUM_RNA_hsa-miR-433-3p_TP120', 'SERUM_RNA_hsa-miR-488-3p_TP120', 'SERUM_RNA_hsa-miR-615-3p_TP120', 'SERUM_RNA_hsa-miR-708-3p_TP120', 'SERUM_RNA_hsa-miR-9-3p_TP120']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (25, 313)
X_test_f  shape: (13, 313)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (25, 313)
X_test_f  shape: (13, 313)
candidate feature examples: ['SERUM_RNA_hsa-let-7a-3p_TP120', 'SERUM_RNA_hsa-let-7a-5p_TP120', 'SERUM_RNA_hsa-let-7b-3p_TP120', 'SERUM_RNA_hsa-let-7b-5p_TP120', 'SERUM_RNA_hsa-let-7c-5p_TP120', 'SERUM_RNA_hsa-let-7d-3p_TP120', 'SERUM_RNA_hsa-let-7d-5p_TP120', 'SERUM_RNA_hsa-let-7e-5p_TP120', 'SERUM_RNA_hsa-let-7f-5p_TP120', 'SERUM_RNA_hsa-let-7g-5p_TP120', 'SERUM_RNA_hsa-let-7i-3p_TP120', 'SERUM_RNA_hsa-let-7i-5p_TP120', 'SERUM_RNA_hsa-miR-100-5p_TP120', 'SERUM_RNA_hsa-miR-101-3p_TP120', 'SERUM_RNA_hsa-miR-103a-3p_TP120', 'SERUM_RNA_hsa-miR-106b-3p_TP120', 'SERUM_RNA_hsa-miR-106b-5p_TP120', 'SERUM_RNA_hsa-miR-107_TP120', 'SERUM_RNA_hsa-miR-10a-3p_TP120', 'SERUM_RNA_hsa-miR-10a-5p_TP120', 'SERUM_RNA_hsa-miR-10b-3p_TP120', 'SERUM_RNA_hsa-miR-10b-5p_TP120', 'SERUM_RNA_hsa-miR-1180-3p_TP120', 'SERUM_RNA_hsa-miR-122-5p_TP120', 'SERUM_RNA_hsa-miR-1246_TP120', 'SERUM_RNA_hsa-miR-1247-5p_TP120', 'SERUM_RNA_hsa-miR-125a-3p_TP120', 'SERUM_RNA_hsa-miR-125a-5p_TP120', 'SERUM_RNA_hsa-miR-125b-1-3p_TP120', 'SERUM_RNA_hsa-miR-125b-2-3p_TP120']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 60
selected feature examples: ['CSF_PROT_AGA|NAIGVAR_TP72', 'CSF_PROT_AHSG|FSVVYAK_TP72', 'CSF_PROT_AMBP|ETLLQDFR_TP72', 'CSF_PROT_APOB|IEGNLIFDPNNYLPK_TP72', 'CSF_PROT_APOM|AFLLTPR_TP72', 'CSF_PROT_C4BPB|ALLAFQESK_TP72', 'CSF_PROT_C5|TLLPVSKPEIR_TP72', 'CSF_PROT_C6|ALQEYAAK_TP72', 'CSF_PROT_C9|TSNFNAAISLK_TP72', 'CSF_PROT_CD5L|LEVLHK_TP72', 'CSF_PROT_CNTN2|GPPGPPGGVVVR_TP72', 'CSF_PROT_CP|GAYPLSIEPIGVR_TP72', 'CSF_PROT_CPB2|EAFAAVSK_TP72', 'CSF_PROT_CRYAB|VLGDVIEVHGK_TP72', 'CSF_PROT_CTSD|YYTVFDR_TP72', 'CSF_PROT_ENO1|YISPDQLADLYK_TP72', 'CSF_PROT_GAPDH|VIPELNGK_TP72', 'CSF_PROT_GC|VLEPTLK_TP72', 'CSF_PROT_GFAP|LADVYQAELR_TP72', 'CSF_PROT_HIST1H4A|DNIQGITKPAIR_TP72', 'CSF_PROT_HSP90AA1|TLVSVTK_TP72', 'CSF_PROT_IGD|NQFSLNLR_TP72', 'CSF_PROT_IGFALS|DLHFLEELQLGHNR_TP72', 'CSF_PROT_IGFALS|LAELPADALGPLQR_TP72', 'CSF_PROT_ITIH1|GFSLDEATNLNGGLLR_TP72', 'CSF_PROT_ITIH2|VQFELHYQEVK_TP72', 'CSF_PROT_ITIH3|DYIFGNYIER_TP72', 'CSF_PROT_ITIH4|NVVFVIDK_TP72', 'CSF_PROT_ITIH4|SPEQQETVLDGNLIIR_TP72', 'CSF_PROT_KNG1|DIPTNSPELEETLTHTITK_TP72']

[FINAL PREDICTION CHECK]
best_model_type: gbr
best_params: {'model__learning_rate': 0.03, 'model__max_depth': 1, 'model__min_samples_leaf': 3, 'model__n_estimators': 30, 'model__subsample': 0.8, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.11399209119008497
train_r2: 0.4114097071547338
train_mae: 12.77159594076615
test_r2 : 0.28391752787244606
test_mae: 14.039792075340165
pred_train summary:
  mean: 16.83665973138248
  std : 6.6432724774134355
  min : 13.412123505161729
  max : 41.357359113612866
pred_test summary:
  mean: 16.52324309450626
  std : 5.271009583156146
  min : 13.412123505161729
  max : 35.7137301521121
y_test summary:
  mean: 13.857142857142858
  std : 19.496729186701852
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 120
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.18421052631579
  std : 20.43031036945642
  min : 0.0
  max : 80.0
X shape after clinical mode: (38, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 10
X_train shape: (25, 315)
X_test  shape: (13, 315)
y_train shape: (25,)
y_test  shape: (13,)
train unique ids: 25
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (25, 300)
X_test_f  shape: (13, 300)
n_removed_by_sparse: 15
removed example: ['SERUM_RNA_hsa-miR-124-3p_TP120', 'SERUM_RNA_hsa-miR-129-5p_TP120', 'SERUM_RNA_hsa-miR-1298-3p_TP120', 'SERUM_RNA_hsa-miR-1298-5p_TP120', 'SERUM_RNA_hsa-miR-184_TP120', 'SERUM_RNA_hsa-miR-1911-5p_TP120', 'SERUM_RNA_hsa-miR-204-3p_TP120', 'SERUM_RNA_hsa-miR-219a-2-3p_TP120', 'SERUM_RNA_hsa-miR-219a-5p_TP120', 'SERUM_RNA_hsa-miR-34c-5p_TP120', 'SERUM_RNA_hsa-miR-433-3p_TP120', 'SERUM_RNA_hsa-miR-488-3p_TP120', 'SERUM_RNA_hsa-miR-615-3p_TP120', 'SERUM_RNA_hsa-miR-708-3p_TP120', 'SERUM_RNA_hsa-miR-9-3p_TP120']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (25, 313)
X_test_f  shape: (13, 313)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (25, 313)
X_test_f  shape: (13, 313)
candidate feature examples: ['SERUM_RNA_hsa-let-7a-3p_TP120', 'SERUM_RNA_hsa-let-7a-5p_TP120', 'SERUM_RNA_hsa-let-7b-3p_TP120', 'SERUM_RNA_hsa-let-7b-5p_TP120', 'SERUM_RNA_hsa-let-7c-5p_TP120', 'SERUM_RNA_hsa-let-7d-3p_TP120', 'SERUM_RNA_hsa-let-7d-5p_TP120', 'SERUM_RNA_hsa-let-7e-5p_TP120', 'SERUM_RNA_hsa-let-7f-5p_TP120', 'SERUM_RNA_hsa-let-7g-5p_TP120', 'SERUM_RNA_hsa-let-7i-3p_TP120', 'SERUM_RNA_hsa-let-7i-5p_TP120', 'SERUM_RNA_hsa-miR-100-5p_TP120', 'SERUM_RNA_hsa-miR-101-3p_TP120', 'SERUM_RNA_hsa-miR-103a-3p_TP120', 'SERUM_RNA_hsa-miR-106b-3p_TP120', 'SERUM_RNA_hsa-miR-106b-5p_TP120', 'SERUM_RNA_hsa-miR-107_TP120', 'SERUM_RNA_hsa-miR-10a-3p_TP120', 'SERUM_RNA_hsa-miR-10a-5p_TP120', 'SERUM_RNA_hsa-miR-10b-3p_TP120', 'SERUM_RNA_hsa-miR-10b-5p_TP120', 'SERUM_RNA_hsa-miR-1180-3p_TP120', 'SERUM_RNA_hsa-miR-122-5p_TP120', 'SERUM_RNA_hsa-miR-1246_TP120', 'SERUM_RNA_hsa-miR-1247-5p_TP120', 'SERUM_RNA_hsa-miR-125a-3p_TP120', 'SERUM_RNA_hsa-miR-125a-5p_TP120', 'SERUM_RNA_hsa-miR-125b-1-3p_TP120', 'SERUM_RNA_hsa-miR-125b-2-3p_TP120']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 140
selected feature examples: ['SERUM_PROT_A1BG|LETPDFQLFK_TP96', 'SERUM_PROT_A2M|AIGYLNTGYQR_TP96', 'SERUM_PROT_ADGRF5|DVIVHPLPLK_TP96', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'SERUM_PROT_AFM|DADPDTFFAK_TP96', 'SERUM_PROT_AGT|ALQDQLVLVAAK_TP96', 'SERUM_PROT_AHSG|FSVVYAK_TP96', 'SERUM_PROT_ALB|LVNEVTEFAK_TP96', 'SERUM_PROT_AMBP|HHGPTITAK_TP96', 'SERUM_PROT_APCS|IVLGQEQDSYGGK_TP96', 'SERUM_PROT_APMAP|LLEYDTVTR_TP96', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP96', 'SERUM_PROT_APOA2|SPELQAEAK_TP96', 'SERUM_PROT_APOA4|LGEVNTYAGDLQK_TP96', 'SERUM_PROT_APOB|FPEVDVLTK_TP96', 'SERUM_PROT_APOC1|EWFSETFQK_TP96', 'SERUM_PROT_APOC2|TYLPAVDEK_TP96', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP96', 'SERUM_PROT_APOC4|ELLETVVNR_TP96', 'SERUM_PROT_APOD|NILTSNNIDVK_TP96', 'SERUM_PROT_APOE|LGPLVEQGR_TP96', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP96', 'SERUM_PROT_APOH|ATVVYQGER_TP96', 'SERUM_PROT_APOL1|VAQELEEK_TP96', 'SERUM_PROT_APOM|AFLLTPR_TP96', 'SERUM_PROT_ATRN|SVNNVVVR_TP96', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP96', 'SERUM_PROT_B2M|VNHVTLSQPK_TP96', 'SERUM_PROT_BCHE|YLTLNTESTR_TP96', 'SERUM_PROT_BTD|SHLIIAQVAK_TP96']

[FINAL PREDICTION CHECK]
best_model_type: svr_linear

[Parallel(n_jobs=8)]: Done  16 tasks      | elapsed:   31.5s

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 16
selected feature examples: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 25.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17855299189219467
train_r2: 0.46333961267119894
train_mae: 11.67335476830036
test_r2 : -0.45320330936598285
test_mae: 18.7369753953651
pred_train summary:
  mean: 19.12
  std : 9.538814833454746
  min : 7.13980106681991
  max : 41.2859007811485
pred_test summary:
  mean: 23.345663194262922
  std : 6.34068740942471
  min : 16.02481952008979
  max : 34.454181294323085
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.145631067961165
  std : 19.99431672534811
  min : -6.0
  max : 80.0
X shape after clinical mode: (103, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_train shape: (55, 441)
X_test  shape: (28, 441)
y_train shape: (55,)
y_test  shape: (28,)
train unique ids: 55
test unique ids : 28
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (55, 169)
X_test_f  shape: (28, 169)
n_removed_by_sparse: 272
removed example: ['CSF_PROT_A1BG|LETPDFQLFK_TP96', 'CSF_PROT_A2M|AIGYLNTGYQR_TP96', 'CSF_PROT_ACO1|NIEVPFKPAR_TP96', 'CSF_PROT_ACTA2|SYELPDGQVITIGNER_TP96', 'CSF_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP96', 'CSF_PROT_ACY1|LHEAVFLR_TP96', 'CSF_PROT_ACYP2|LEYSNFSIR_TP96', 'CSF_PROT_ADD1|VDENNPEYLR_TP96', 'CSF_PROT_ADGRF5|DVIVHPLPLK_TP96', 'CSF_PROT_ADH1B|FSLDALITHVLPFEK_TP96', 'CSF_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'CSF_PROT_ADIRF|TTQETIDK_TP96', 'CSF_PROT_AFM|DADPDTFFAK_TP96', 'CSF_PROT_AGT|ALQDQLVLVAAK_TP96', 'CSF_PROT_AHCY|VPAINVNDSVTK_TP96', 'CSF_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP96', 'CSF_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP96', 'CSF_PROT_AKR1E2|NVIVIPGSITPSHIK_TP96', 'CSF_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP96', 'CSF_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP96']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (55, 189)
X_test_f  shape: (28, 189)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (55, 189)
X_test_f  shape: (28, 189)
candidate feature examples: ['CSF_PROT_A1BG|GVTFLLR_TP96', 'CSF_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP96', 'CSF_PROT_AFM|HFQNLGK_TP96', 'CSF_PROT_AGA|NAIGVAR_TP96', 'CSF_PROT_AHSG|FSVVYAK_TP96', 'CSF_PROT_AK1|IIFVVGGPGSGK_TP96', 'CSF_PROT_AMBP|ETLLQDFR_TP96', 'CSF_PROT_ANXA2|QDIAFAYQR_TP96', 'CSF_PROT_APCS|VGEYSLYIGR_TP96', 'CSF_PROT_APOA4|SLAPYAQDTQEK_TP96', 'CSF_PROT_APOB|IEGNLIFDPNNYLPK_TP96', 'CSF_PROT_APOC2|ESLSSYWESAK_TP96', 'CSF_PROT_APOE|LGPLVEQGR_TP96', 'CSF_PROT_APOH|ATVVYQGER_TP96', 'CSF_PROT_APOL1|LNILNNNYK_TP96', 'CSF_PROT_APOM|AFLLTPR_TP96', 'CSF_PROT_AZGP1|YSLTYIYTGLSK_TP96', 'CSF_PROT_B2M|VNHVTLSQPK_TP96', 'CSF_PROT_B4GAT1|TALASGGVLDASGDYR_TP96', 'CSF_PROT_BCAN|YPIVTPSQR_TP96', 'CSF_PROT_BCHE|YLTLNTESTR_TP96', 'CSF_PROT_BLVRB|TVAGQDAVIVLLGTR_TP96', 'CSF_PROT_BTD|LSSGLVTAALYGR_TP96', 'CSF_PROT_C16orf89|ATIADLILSALER_TP96', 'CSF_PROT_C1QA|PAFSAIR_TP96', 'CSF_PROT_C1QB|IAFSATR_TP96', 'CSF_PROT_C1R|YTTEIIK_TP96', 'CSF_PROT_C2|ELNELGSK_TP96', 'CSF_PROT_C3|TGLQEVEVK_TP96', 'CSF_PROT_C4A|DHAVDLIQK_TP96']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 16
selected feature examples: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 25.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17855299189219467
train_r2: 0.46333961267119894
train_mae: 11.67335476830036
test_r2 : -0.45320330936598285
test_mae: 18.7369753953651
pred_train summary:
  mean: 19.12
  std : 9.538814833454746
  min : 7.13980106681991
  max : 41.2859007811485
pred_test summary:
  mean: 23.345663194262922
  std : 6.34068740942471
  min : 16.02481952008979
  max : 34.454181294323085
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.18421052631579
  std : 20.43031036945642
  min : 0.0
  max : 80.0
X shape after clinical mode: (38, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 30
X_train shape: (25, 315)
X_test  shape: (13, 315)
y_train shape: (25,)
y_test  shape: (13,)
train unique ids: 25
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (25, 304)
X_test_f  shape: (13, 304)
n_removed_by_sparse: 11
removed example: ['SERUM_RNA_hsa-miR-124-3p_TP24', 'SERUM_RNA_hsa-miR-129-5p_TP24', 'SERUM_RNA_hsa-miR-1298-3p_TP24', 'SERUM_RNA_hsa-miR-1298-5p_TP24', 'SERUM_RNA_hsa-miR-1299_TP24', 'SERUM_RNA_hsa-miR-1911-5p_TP24', 'SERUM_RNA_hsa-miR-204-3p_TP24', 'SERUM_RNA_hsa-miR-219a-2-3p_TP24', 'SERUM_RNA_hsa-miR-219a-5p_TP24', 'SERUM_RNA_hsa-miR-488-3p_TP24', 'SERUM_RNA_hsa-miR-615-3p_TP24']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (25, 317)
X_test_f  shape: (13, 317)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (25, 317)
X_test_f  shape: (13, 317)
candidate feature examples: ['SERUM_RNA_hsa-let-7a-3p_TP24', 'SERUM_RNA_hsa-let-7a-5p_TP24', 'SERUM_RNA_hsa-let-7b-3p_TP24', 'SERUM_RNA_hsa-let-7b-5p_TP24', 'SERUM_RNA_hsa-let-7c-5p_TP24', 'SERUM_RNA_hsa-let-7d-3p_TP24', 'SERUM_RNA_hsa-let-7d-5p_TP24', 'SERUM_RNA_hsa-let-7e-5p_TP24', 'SERUM_RNA_hsa-let-7f-5p_TP24', 'SERUM_RNA_hsa-let-7g-5p_TP24', 'SERUM_RNA_hsa-let-7i-3p_TP24', 'SERUM_RNA_hsa-let-7i-5p_TP24', 'SERUM_RNA_hsa-miR-100-5p_TP24', 'SERUM_RNA_hsa-miR-101-3p_TP24', 'SERUM_RNA_hsa-miR-103a-3p_TP24', 'SERUM_RNA_hsa-miR-106b-3p_TP24', 'SERUM_RNA_hsa-miR-106b-5p_TP24', 'SERUM_RNA_hsa-miR-107_TP24', 'SERUM_RNA_hsa-miR-10a-3p_TP24', 'SERUM_RNA_hsa-miR-10a-5p_TP24', 'SERUM_RNA_hsa-miR-10b-3p_TP24', 'SERUM_RNA_hsa-miR-10b-5p_TP24', 'SERUM_RNA_hsa-miR-1180-3p_TP24', 'SERUM_RNA_hsa-miR-122-5p_TP24', 'SERUM_RNA_hsa-miR-1246_TP24', 'SERUM_RNA_hsa-miR-1247-5p_TP24', 'SERUM_RNA_hsa-miR-125a-3p_TP24', 'SERUM_RNA_hsa-miR-125a-5p_TP24', 'SERUM_RNA_hsa-miR-125b-1-3p_TP24', 'SERUM_RNA_hsa-miR-125b-2-3p_TP24']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 16
selected feature examples: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 25.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17855299189219467
train_r2: 0.46333961267119894
train_mae: 11.67335476830036
test_r2 : -0.45320330936598285
test_mae: 18.7369753953651
pred_train summary:
  mean: 19.12
  std : 9.538814833454746
  min : 7.13980106681991
  max : 41.2859007811485
pred_test summary:
  mean: 23.345663194262922
  std : 6.34068740942471
  min : 16.02481952008979
  max : 34.454181294323085
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.145631067961165
  std : 19.99431672534811
  min : -6.0
  max : 80.0
X shape after clinical mode: (103, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 80
X_train shape: (55, 441)
X_test  shape: (28, 441)
y_train shape: (55,)
y_test  shape: (28,)
train unique ids: 55
test unique ids : 28
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (55, 174)
X_test_f  shape: (28, 174)
n_removed_by_sparse: 267
removed example: ['CSF_PROT_A1BG|LETPDFQLFK_TP72', 'CSF_PROT_A2M|AIGYLNTGYQR_TP72', 'CSF_PROT_ACO1|NIEVPFKPAR_TP72', 'CSF_PROT_ACTA2|SYELPDGQVITIGNER_TP72', 'CSF_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP72', 'CSF_PROT_ACYP2|LEYSNFSIR_TP72', 'CSF_PROT_ADD1|VDENNPEYLR_TP72', 'CSF_PROT_ADGRF5|DVIVHPLPLK_TP72', 'CSF_PROT_ADH1B|FSLDALITHVLPFEK_TP72', 'CSF_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP72', 'CSF_PROT_ADIRF|TTQETIDK_TP72', 'CSF_PROT_AFM|DADPDTFFAK_TP72', 'CSF_PROT_AGT|ALQDQLVLVAAK_TP72', 'CSF_PROT_AHCY|VPAINVNDSVTK_TP72', 'CSF_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP72', 'CSF_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP72', 'CSF_PROT_AKR1E2|NVIVIPGSITPSHIK_TP72', 'CSF_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP72', 'CSF_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP72', 'CSF_PROT_ALAD|GSAADSEESPAIEAIHLLR_TP72']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (55, 194)
X_test_f  shape: (28, 194)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (55, 194)
X_test_f  shape: (28, 194)
candidate feature examples: ['CSF_PROT_A1BG|GVTFLLR_TP72', 'CSF_PROT_ACY1|LHEAVFLR_TP72', 'CSF_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP72', 'CSF_PROT_AFM|HFQNLGK_TP72', 'CSF_PROT_AGA|NAIGVAR_TP72', 'CSF_PROT_AHSG|FSVVYAK_TP72', 'CSF_PROT_AK1|IIFVVGGPGSGK_TP72', 'CSF_PROT_AMBP|ETLLQDFR_TP72', 'CSF_PROT_ANXA2|QDIAFAYQR_TP72', 'CSF_PROT_APCS|VGEYSLYIGR_TP72', 'CSF_PROT_APOA4|SLAPYAQDTQEK_TP72', 'CSF_PROT_APOB|IEGNLIFDPNNYLPK_TP72', 'CSF_PROT_APOC2|ESLSSYWESAK_TP72', 'CSF_PROT_APOE|LGPLVEQGR_TP72', 'CSF_PROT_APOH|ATVVYQGER_TP72', 'CSF_PROT_APOL1|LNILNNNYK_TP72', 'CSF_PROT_APOM|AFLLTPR_TP72', 'CSF_PROT_AZGP1|YSLTYIYTGLSK_TP72', 'CSF_PROT_B2M|VNHVTLSQPK_TP72', 'CSF_PROT_B4GAT1|TALASGGVLDASGDYR_TP72', 'CSF_PROT_BCAN|YPIVTPSQR_TP72', 'CSF_PROT_BCHE|YLTLNTESTR_TP72', 'CSF_PROT_BLVRB|TVAGQDAVIVLLGTR_TP72', 'CSF_PROT_BTD|LSSGLVTAALYGR_TP72', 'CSF_PROT_C16orf89|ATIADLILSALER_TP72', 'CSF_PROT_C1QA|PAFSAIR_TP72', 'CSF_PROT_C1QB|IAFSATR_TP72', 'CSF_PROT_C1R|YTTEIIK_TP72', 'CSF_PROT_C2|ELNELGSK_TP72', 'CSF_PROT_C3|TGLQEVEVK_TP72']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 16
selected feature examples: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 25.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17855299189219467
train_r2: 0.46333961267119894
train_mae: 11.67335476830036
test_r2 : -0.45320330936598285
test_mae: 18.7369753953651
pred_train summary:
  mean: 19.12
  std : 9.538814833454746
  min : 7.13980106681991
  max : 41.2859007811485
pred_test summary:
  mean: 23.345663194262922
  std : 6.34068740942471
  min : 16.02481952008979
  max : 34.454181294323085
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 72
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.99074074074074
  std : 20.349973188974218
  min : -6.0
  max : 80.0
X shape after clinical mode: (108, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 140
X_train shape: (58, 441)
X_test  shape: (30, 441)
y_train shape: (58,)
y_test  shape: (30,)
train unique ids: 58
test unique ids : 30
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (58, 131)
X_test_f  shape: (30, 131)
n_removed_by_sparse: 310
removed example: ['SERUM_PROT_A1BG|GVTFLLR_TP72', 'SERUM_PROT_ACO1|NIEVPFKPAR_TP72', 'SERUM_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP72', 'SERUM_PROT_ACY1|LHEAVFLR_TP72', 'SERUM_PROT_ACYP2|LEYSNFSIR_TP72', 'SERUM_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP72', 'SERUM_PROT_ADD1|VDENNPEYLR_TP72', 'SERUM_PROT_ADH1B|FSLDALITHVLPFEK_TP72', 'SERUM_PROT_ADIRF|TTQETIDK_TP72', 'SERUM_PROT_AFM|HFQNLGK_TP72', 'SERUM_PROT_AGA|NAIGVAR_TP72', 'SERUM_PROT_AHCY|VPAINVNDSVTK_TP72', 'SERUM_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP72', 'SERUM_PROT_AK1|IIFVVGGPGSGK_TP72', 'SERUM_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP72', 'SERUM_PROT_AKR1E2|NVIVIPGSITPSHIK_TP72', 'SERUM_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP72', 'SERUM_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP72', 'SERUM_PROT_ALAD|GSAADSEESPAIEAIHLLR_TP72', 'SERUM_PROT_ALDH9A1|ANDTTFGLAAGVFTR_TP72']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (58, 151)
X_test_f  shape: (30, 151)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (58, 151)
X_test_f  shape: (30, 151)
candidate feature examples: ['SERUM_PROT_A1BG|LETPDFQLFK_TP72', 'SERUM_PROT_A2M|AIGYLNTGYQR_TP72', 'SERUM_PROT_ACTA2|SYELPDGQVITIGNER_TP72', 'SERUM_PROT_ADGRF5|DVIVHPLPLK_TP72', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP72', 'SERUM_PROT_AFM|DADPDTFFAK_TP72', 'SERUM_PROT_AGT|ALQDQLVLVAAK_TP72', 'SERUM_PROT_AHSG|FSVVYAK_TP72', 'SERUM_PROT_ALB|LVNEVTEFAK_TP72', 'SERUM_PROT_AMBP|HHGPTITAK_TP72', 'SERUM_PROT_APCS|IVLGQEQDSYGGK_TP72', 'SERUM_PROT_APMAP|LLEYDTVTR_TP72', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP72', 'SERUM_PROT_APOA2|SPELQAEAK_TP72', 'SERUM_PROT_APOA4|LGEVNTYAGDLQK_TP72', 'SERUM_PROT_APOB|FPEVDVLTK_TP72', 'SERUM_PROT_APOC1|EWFSETFQK_TP72', 'SERUM_PROT_APOC2|TYLPAVDEK_TP72', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP72', 'SERUM_PROT_APOC4|ELLETVVNR_TP72', 'SERUM_PROT_APOD|NILTSNNIDVK_TP72', 'SERUM_PROT_APOE|LGPLVEQGR_TP72', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP72', 'SERUM_PROT_APOH|ATVVYQGER_TP72', 'SERUM_PROT_APOL1|VAQELEEK_TP72', 'SERUM_PROT_APOM|AFLLTPR_TP72', 'SERUM_PROT_ATRN|SVNNVVVR_TP72', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP72', 'SERUM_PROT_B2M|VNHVTLSQPK_TP72', 'SERUM_PROT_BCHE|YLTLNTESTR_TP72']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 40
selected feature examples: ['CSF_PROT_A1BG|GVTFLLR_TP96', 'CSF_PROT_AHSG|FSVVYAK_TP96', 'CSF_PROT_C9|TSNFNAAISLK_TP96', 'CSF_PROT_FCGBP|GNPAVSYVR_TP96', 'CSF_PROT_GC|VLEPTLK_TP96', 'CSF_PROT_GFAP|LADVYQAELR_TP96', 'CSF_PROT_HSP90AA1|TLVSVTK_TP96', 'CSF_PROT_ITIH3|DYIFGNYIER_TP96', 'CSF_PROT_ITIH4|NVVFVIDK_TP96', 'CSF_PROT_ITIH4|SPEQQETVLDGNLIIR_TP96', 'CSF_PROT_LRG1|ALGHLDLSGNR_TP96', 'CSF_PROT_LRRC4B|LTTVPTQAFEYLSK_TP96', 'CSF_PROT_LYZ|AWVAWR_TP96', 'CSF_PROT_S100A8|ALNSIIDVYHK_TP96', 'CSF_PROT_SERPINF2|LGNQEPGGQTALK_TP96', 'CSF_PROT_TIMP1|GFQALGDAADIR_TP96', 'CSF_PROT_YWHAH|LAEQAER_TP96', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 100.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.11529190519920551
train_r2: 0.5132497591623268
train_mae: 11.068789504041959
test_r2 : 0.21317740300746568
test_mae: 14.580309907640004
pred_train summary:
  mean: 16.727272727272727
  std : 10.743449323236339
  min : -5.161821797512285
  max : 44.62396632588147
pred_test summary:
  mean: 17.358089298147764
  std : 11.62006492117891
  min : -11.017641793338967
  max : 42.166687427413706
y_test summary:
  mean: 13.857142857142858
  std : 19.496729186701852
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=C, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_C_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: C | tp: 24
X shape before clinical: (38, 312)
y shape: (38,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.18421052631579
  std : 20.43031036945642
  min : 0.0
  max : 80.0
X shape after clinical mode: (38, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_train shape: (25, 315)
X_test  shape: (13, 315)
y_train shape: (25,)
y_test  shape: (13,)
train unique ids: 25
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (25, 304)
X_test_f  shape: (13, 304)
n_removed_by_sparse: 11

[Parallel(n_jobs=8)]: Done  25 tasks      | elapsed:   49.9s

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 140
selected feature examples: ['SERUM_PROT_A1BG|LETPDFQLFK_TP72', 'SERUM_PROT_A2M|AIGYLNTGYQR_TP72', 'SERUM_PROT_ACTA2|SYELPDGQVITIGNER_TP72', 'SERUM_PROT_ADGRF5|DVIVHPLPLK_TP72', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP72', 'SERUM_PROT_AFM|DADPDTFFAK_TP72', 'SERUM_PROT_AGT|ALQDQLVLVAAK_TP72', 'SERUM_PROT_AHSG|FSVVYAK_TP72', 'SERUM_PROT_ALB|LVNEVTEFAK_TP72', 'SERUM_PROT_AMBP|HHGPTITAK_TP72', 'SERUM_PROT_APCS|IVLGQEQDSYGGK_TP72', 'SERUM_PROT_APMAP|LLEYDTVTR_TP72', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP72', 'SERUM_PROT_APOA2|SPELQAEAK_TP72', 'SERUM_PROT_APOA4|LGEVNTYAGDLQK_TP72', 'SERUM_PROT_APOB|FPEVDVLTK_TP72', 'SERUM_PROT_APOC1|EWFSETFQK_TP72', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP72', 'SERUM_PROT_APOC4|ELLETVVNR_TP72', 'SERUM_PROT_APOE|LGPLVEQGR_TP72', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP72', 'SERUM_PROT_APOH|ATVVYQGER_TP72', 'SERUM_PROT_APOL1|VAQELEEK_TP72', 'SERUM_PROT_APOM|AFLLTPR_TP72', 'SERUM_PROT_ATRN|SVNNVVVR_TP72', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP72', 'SERUM_PROT_B2M|VNHVTLSQPK_TP72', 'SERUM_PROT_BCHE|YLTLNTESTR_TP72', 'SERUM_PROT_BTD|SHLIIAQVAK_TP72', 'SERUM_PROT_C1QC|FQSVFTVTR_TP72']

[FINAL PREDICTION CHECK]
best_model_type: svr_linear
best_params: {'model__C': 0.1, 'model__epsilon': 0.1, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.11725069097102837
train_r2: 0.5965588730744935
train_mae: 6.921798421657526
test_r2 : 0.19668381459884043
test_mae: 13.083296349025982
pred_train summary:
  mean: 13.99655775628774
  std : 12.465624450236538
  min : 0.09965384145715461
  max : 48.900374497513894
pred_test summary:
  mean: 13.388434840498237
  std : 8.68259812442267
  min : -2.1568387733247754
  max : 31.457581612123025
y_test summary:
  mean: 13.1
  std : 19.047922021399955
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=96
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_96.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 96
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.145631067961165
  std : 19.99431672534811
  min : -6.0
  max : 80.0
X shape after clinical mode: (103, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_train shape: (55, 441)
X_test  shape: (28, 441)
y_train shape: (55,)
y_test  shape: (28,)
train unique ids: 55
test unique ids : 28
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (55, 169)
X_test_f  shape: (28, 169)
n_removed_by_sparse: 272
removed example: ['CSF_PROT_A1BG|LETPDFQLFK_TP96', 'CSF_PROT_A2M|AIGYLNTGYQR_TP96', 'CSF_PROT_ACO1|NIEVPFKPAR_TP96', 'CSF_PROT_ACTA2|SYELPDGQVITIGNER_TP96', 'CSF_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP96', 'CSF_PROT_ACY1|LHEAVFLR_TP96', 'CSF_PROT_ACYP2|LEYSNFSIR_TP96', 'CSF_PROT_ADD1|VDENNPEYLR_TP96', 'CSF_PROT_ADGRF5|DVIVHPLPLK_TP96', 'CSF_PROT_ADH1B|FSLDALITHVLPFEK_TP96', 'CSF_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP96', 'CSF_PROT_ADIRF|TTQETIDK_TP96', 'CSF_PROT_AFM|DADPDTFFAK_TP96', 'CSF_PROT_AGT|ALQDQLVLVAAK_TP96', 'CSF_PROT_AHCY|VPAINVNDSVTK_TP96', 'CSF_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP96', 'CSF_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP96', 'CSF_PROT_AKR1E2|NVIVIPGSITPSHIK_TP96', 'CSF_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP96', 'CSF_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP96']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (55, 189)
X_test_f  shape: (28, 189)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (55, 189)
X_test_f  shape: (28, 189)
candidate feature examples: ['CSF_PROT_A1BG|GVTFLLR_TP96', 'CSF_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP96', 'CSF_PROT_AFM|HFQNLGK_TP96', 'CSF_PROT_AGA|NAIGVAR_TP96', 'CSF_PROT_AHSG|FSVVYAK_TP96', 'CSF_PROT_AK1|IIFVVGGPGSGK_TP96', 'CSF_PROT_AMBP|ETLLQDFR_TP96', 'CSF_PROT_ANXA2|QDIAFAYQR_TP96', 'CSF_PROT_APCS|VGEYSLYIGR_TP96', 'CSF_PROT_APOA4|SLAPYAQDTQEK_TP96', 'CSF_PROT_APOB|IEGNLIFDPNNYLPK_TP96', 'CSF_PROT_APOC2|ESLSSYWESAK_TP96', 'CSF_PROT_APOE|LGPLVEQGR_TP96', 'CSF_PROT_APOH|ATVVYQGER_TP96', 'CSF_PROT_APOL1|LNILNNNYK_TP96', 'CSF_PROT_APOM|AFLLTPR_TP96', 'CSF_PROT_AZGP1|YSLTYIYTGLSK_TP96', 'CSF_PROT_B2M|VNHVTLSQPK_TP96', 'CSF_PROT_B4GAT1|TALASGGVLDASGDYR_TP96', 'CSF_PROT_BCAN|YPIVTPSQR_TP96', 'CSF_PROT_BCHE|YLTLNTESTR_TP96', 'CSF_PROT_BLVRB|TVAGQDAVIVLLGTR_TP96', 'CSF_PROT_BTD|LSSGLVTAALYGR_TP96', 'CSF_PROT_C16orf89|ATIADLILSALER_TP96', 'CSF_PROT_C1QA|PAFSAIR_TP96', 'CSF_PROT_C1QB|IAFSATR_TP96', 'CSF_PROT_C1R|YTTEIIK_TP96', 'CSF_PROT_C2|ELNELGSK_TP96', 'CSF_PROT_C3|TGLQEVEVK_TP96', 'CSF_PROT_C4A|DHAVDLIQK_TP96']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 40
selected feature examples: ['CSF_PROT_AHSG|FSVVYAK_TP72', 'CSF_PROT_APOB|IEGNLIFDPNNYLPK_TP72', 'CSF_PROT_APOM|AFLLTPR_TP72', 'CSF_PROT_C5|TLLPVSKPEIR_TP72', 'CSF_PROT_C9|TSNFNAAISLK_TP72', 'CSF_PROT_CRYAB|VLGDVIEVHGK_TP72', 'CSF_PROT_GC|VLEPTLK_TP72', 'CSF_PROT_GFAP|LADVYQAELR_TP72', 'CSF_PROT_HSP90AA1|TLVSVTK_TP72', 'CSF_PROT_IGD|NQFSLNLR_TP72', 'CSF_PROT_IGFALS|LAELPADALGPLQR_TP72', 'CSF_PROT_ITIH4|NVVFVIDK_TP72', 'CSF_PROT_ITIH4|SPEQQETVLDGNLIIR_TP72', 'CSF_PROT_KNG1|DIPTNSPELEETLTHTITK_TP72', 'CSF_PROT_LRG1|ALGHLDLSGNR_TP72', 'CSF_PROT_S100A6|LQDAEIAR_TP72', 'CSF_PROT_TIMP1|GFQALGDAADIR_TP72', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02']

[FINAL PREDICTION CHECK]
best_model_type: gbr
best_params: {'model__learning_rate': 0.05, 'model__max_depth': 1, 'model__min_samples_leaf': 3, 'model__n_estimators': 30, 'model__subsample': 0.8, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.14983309760061944
train_r2: 0.5253426602546446
train_mae: 11.226831690809044
test_r2 : 0.3697298549485978
test_mae: 12.881784950899482
pred_train summary:
  mean: 16.932324533976026
  std : 9.50188169069191
  min : 11.342312642553207
  max : 51.36070631883615
pred_test summary:
  mean: 16.669571513805263
  std : 7.724996303372415
  min : 11.342312642553207
  max : 42.84263059457014
y_test summary:
  mean: 13.857142857142858
  std : 19.496729186701852
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=ser, combo=B, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_B_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: ser | combo: B | tp: 120
X shape before clinical: (108, 749)
y shape: (108,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.99074074074074
  std : 20.349973188974218
  min : -6.0
  max : 80.0
X shape after clinical mode: (108, 752)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_train shape: (58, 752)
X_test  shape: (30, 752)
y_train shape: (58,)
y_test  shape: (30,)
train unique ids: 58
test unique ids : 30
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (58, 252)
X_test_f  shape: (30, 252)
n_removed_by_sparse: 500
removed example: ['SERUM_MET_CSF-Amine-21_TP120', 'SERUM_MET_CSF-Amine-24_TP120', 'SERUM_MET_CSF-Amine-33_TP120', 'SERUM_MET_CSF-Amine-34_TP120', 'SERUM_MET_CSF-Amine-35_TP120', 'SERUM_MET_CSF-Amine-37_TP120', 'SERUM_MET_CSF-Amine-42_TP120', 'SERUM_MET_CSF-Amine-43_TP120', 'SERUM_MET_CSF-Amine-45_TP120', 'SERUM_MET_CSF-Amine-48_TP120', 'SERUM_MET_CSF-Amine-52_TP120', 'SERUM_MET_CSF-Amine-53_TP120', 'SERUM_MET_CSF-Amine-55_TP120', 'SERUM_MET_CSF-Amine-56_TP120', 'SERUM_MET_CSF-Amine-59_TP120', 'SERUM_MET_CSF-Amine-64_TP120', 'SERUM_MET_CSF-Amine-67_TP120', 'SERUM_MET_CSF-Amine-76_TP120', 'SERUM_MET_CSF-Amine-79_TP120', 'SERUM_MET_CSF-Amine-82_TP120']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (58, 272)
X_test_f  shape: (30, 272)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (58, 272)
X_test_f  shape: (30, 272)
candidate feature examples: ['SERUM_MET_Serum-Amine-6_TP120', 'SERUM_MET_Serum-Amine-7_TP120', 'SERUM_MET_Serum-Amine-12_TP120', 'SERUM_MET_Serum-Amine-14_TP120', 'SERUM_MET_Serum-Amine-15_TP120', 'SERUM_MET_Serum-Amine-16_TP120', 'SERUM_MET_Serum-Amine-18_TP120', 'SERUM_MET_Serum-Amine-19_TP120', 'SERUM_MET_Serum-Amine-25_TP120', 'SERUM_MET_Serum-Amine-26_TP120', 'SERUM_MET_Serum-Amine-30_TP120', 'SERUM_MET_Serum-Amine-33_TP120', 'SERUM_MET_Serum-Amine-37_TP120', 'SERUM_MET_Serum-Amine-39_TP120', 'SERUM_MET_Serum-Amine-47_TP120', 'SERUM_MET_Serum-Amine-48_TP120', 'SERUM_MET_Serum-Amine-54_TP120', 'SERUM_MET_Serum-Amine-58_TP120', 'SERUM_MET_Serum-Amine-62_TP120', 'SERUM_MET_Serum-Amine-64_TP120', 'SERUM_MET_Serum-Amine-66_TP120', 'SERUM_MET_Serum-Amine-75_TP120', 'SERUM_MET_Serum-Amine-83_TP120', 'SERUM_MET_Serum-Amine-86_TP120', 'SERUM_MET_Serum-Amine-87_TP120', 'SERUM_MET_Serum-Amine-94_TP120', 'SERUM_MET_Serum-Amine-99_TP120', 'SERUM_MET_Serum-Amine-111_TP120', 'SERUM_MET_Serum-Amine-114_TP120', 'SERUM_MET_Serum-Amine-115_TP120']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 80
selected feature examples: ['CSF_PROT_A1BG|GVTFLLR_TP72', 'CSF_PROT_AGA|NAIGVAR_TP72', 'CSF_PROT_AHSG|FSVVYAK_TP72', 'CSF_PROT_AMBP|ETLLQDFR_TP72', 'CSF_PROT_APCS|VGEYSLYIGR_TP72', 'CSF_PROT_APOB|IEGNLIFDPNNYLPK_TP72', 'CSF_PROT_APOM|AFLLTPR_TP72', 'CSF_PROT_C3|TGLQEVEVK_TP72', 'CSF_PROT_C4BPB|ALLAFQESK_TP72', 'CSF_PROT_C5|TLLPVSKPEIR_TP72', 'CSF_PROT_C6|ALQEYAAK_TP72', 'CSF_PROT_C8G|AGQLSVK_TP72', 'CSF_PROT_C9|TSNFNAAISLK_TP72', 'CSF_PROT_CD5L|LEVLHK_TP72', 'CSF_PROT_CFH|SSNLIILEEHLK_TP72', 'CSF_PROT_CFI|VFSLQWGEVK_TP72', 'CSF_PROT_CNTN2|GPPGPPGGVVVR_TP72', 'CSF_PROT_CP|GAYPLSIEPIGVR_TP72', 'CSF_PROT_CPB2|EAFAAVSK_TP72', 'CSF_PROT_CPE|SNAQGIDLNR_TP72', 'CSF_PROT_CRYAB|VLGDVIEVHGK_TP72', 'CSF_PROT_CTSD|YYTVFDR_TP72', 'CSF_PROT_ENO1|YISPDQLADLYK_TP72', 'CSF_PROT_F12|VVGGLVALR_TP72', 'CSF_PROT_FABP5|ELGVGIALR_TP72', 'CSF_PROT_GAPDH|VIPELNGK_TP72', 'CSF_PROT_GC|VLEPTLK_TP72', 'CSF_PROT_GFAP|LADVYQAELR_TP72', 'CSF_PROT_HBA1|VDPVNFK_TP72', 'CSF_PROT_HIST1H4A|DNIQGITKPAIR_TP72']

[FINAL PREDICTION CHECK]
best_model_type: svr_linear
best_params: {'model__C': 0.1, 'model__epsilon': 0.2, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.1408451691301576
train_r2: 0.4291762361125664
train_mae: 9.177374627201935
test_r2 : 0.04999736298509505
test_mae: 14.115347391107322
pred_train summary:
  mean: 12.030489807569825
  std : 9.645992968093962
  min : -0.20011140878317768
  max : 36.80033899047095
pred_test summary:
  mean: 13.292374575673168
  std : 10.389752205497437
  min : -4.1748075686767745
  max : 41.85120297025792
y_test summary:
  mean: 13.857142857142858
  std : 19.496729186701852
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=72
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_72.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 72
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.145631067961165
  std : 19.99431672534811
  min : -6.0
  max : 80.0
X shape after clinical mode: (103, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 100
X_train shape: (55, 441)
X_test  shape: (28, 441)
y_train shape: (55,)
y_test  shape: (28,)
train unique ids: 55
test unique ids : 28
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (55, 174)
X_test_f  shape: (28, 174)
n_removed_by_sparse: 267
removed example: ['CSF_PROT_A1BG|LETPDFQLFK_TP72', 'CSF_PROT_A2M|AIGYLNTGYQR_TP72', 'CSF_PROT_ACO1|NIEVPFKPAR_TP72', 'CSF_PROT_ACTA2|SYELPDGQVITIGNER_TP72', 'CSF_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP72', 'CSF_PROT_ACYP2|LEYSNFSIR_TP72', 'CSF_PROT_ADD1|VDENNPEYLR_TP72', 'CSF_PROT_ADGRF5|DVIVHPLPLK_TP72', 'CSF_PROT_ADH1B|FSLDALITHVLPFEK_TP72', 'CSF_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP72', 'CSF_PROT_ADIRF|TTQETIDK_TP72', 'CSF_PROT_AFM|DADPDTFFAK_TP72', 'CSF_PROT_AGT|ALQDQLVLVAAK_TP72', 'CSF_PROT_AHCY|VPAINVNDSVTK_TP72', 'CSF_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP72', 'CSF_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP72', 'CSF_PROT_AKR1E2|NVIVIPGSITPSHIK_TP72', 'CSF_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP72', 'CSF_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP72', 'CSF_PROT_ALAD|GSAADSEESPAIEAIHLLR_TP72']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (55, 194)
X_test_f  shape: (28, 194)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (55, 194)
X_test_f  shape: (28, 194)
candidate feature examples: ['CSF_PROT_A1BG|GVTFLLR_TP72', 'CSF_PROT_ACY1|LHEAVFLR_TP72', 'CSF_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP72', 'CSF_PROT_AFM|HFQNLGK_TP72', 'CSF_PROT_AGA|NAIGVAR_TP72', 'CSF_PROT_AHSG|FSVVYAK_TP72', 'CSF_PROT_AK1|IIFVVGGPGSGK_TP72', 'CSF_PROT_AMBP|ETLLQDFR_TP72', 'CSF_PROT_ANXA2|QDIAFAYQR_TP72', 'CSF_PROT_APCS|VGEYSLYIGR_TP72', 'CSF_PROT_APOA4|SLAPYAQDTQEK_TP72', 'CSF_PROT_APOB|IEGNLIFDPNNYLPK_TP72', 'CSF_PROT_APOC2|ESLSSYWESAK_TP72', 'CSF_PROT_APOE|LGPLVEQGR_TP72', 'CSF_PROT_APOH|ATVVYQGER_TP72', 'CSF_PROT_APOL1|LNILNNNYK_TP72', 'CSF_PROT_APOM|AFLLTPR_TP72', 'CSF_PROT_AZGP1|YSLTYIYTGLSK_TP72', 'CSF_PROT_B2M|VNHVTLSQPK_TP72', 'CSF_PROT_B4GAT1|TALASGGVLDASGDYR_TP72', 'CSF_PROT_BCAN|YPIVTPSQR_TP72', 'CSF_PROT_BCHE|YLTLNTESTR_TP72', 'CSF_PROT_BLVRB|TVAGQDAVIVLLGTR_TP72', 'CSF_PROT_BTD|LSSGLVTAALYGR_TP72', 'CSF_PROT_C16orf89|ATIADLILSALER_TP72', 'CSF_PROT_C1QA|PAFSAIR_TP72', 'CSF_PROT_C1QB|IAFSATR_TP72', 'CSF_PROT_C1R|YTTEIIK_TP72', 'CSF_PROT_C2|ELNELGSK_TP72', 'CSF_PROT_C3|TGLQEVEVK_TP72']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 40
selected feature examples: ['CSF_PROT_A1BG|GVTFLLR_TP96', 'CSF_PROT_AHSG|FSVVYAK_TP96', 'CSF_PROT_C5|TLLPVSKPEIR_TP96', 'CSF_PROT_C9|TSNFNAAISLK_TP96', 'CSF_PROT_FCGBP|GNPAVSYVR_TP96', 'CSF_PROT_GC|VLEPTLK_TP96', 'CSF_PROT_GFAP|LADVYQAELR_TP96', 'CSF_PROT_HSP90AA1|TLVSVTK_TP96', 'CSF_PROT_ITIH3|DYIFGNYIER_TP96', 'CSF_PROT_ITIH4|NVVFVIDK_TP96', 'CSF_PROT_ITIH4|SPEQQETVLDGNLIIR_TP96', 'CSF_PROT_LRG1|ALGHLDLSGNR_TP96', 'CSF_PROT_LYZ|AWVAWR_TP96', 'CSF_PROT_S100A8|ALNSIIDVYHK_TP96', 'CSF_PROT_SERPINF2|LGNQEPGGQTALK_TP96', 'CSF_PROT_TIMP1|GFQALGDAADIR_TP96', 'CSF_PROT_YWHAH|LAEQAER_TP96', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 100.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.11193810643473627
train_r2: 0.49062692621472115
train_mae: 11.209416704326825
test_r2 : 0.212523450379559
test_mae: 14.524528256326633
pred_train summary:
  mean: 16.727272727272727
  std : 10.605968426349863
  min : -3.4558935835390336
  max : 44.032556739838014
pred_test summary:
  mean: 17.247862466031414
  std : 11.10325712823486
  min : -10.07904250022904
  max : 41.215983657934345
y_test summary:
  mean: 13.857142857142858
  std : 19.496729186701852
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 48
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.128205128205128
  std : 20.162732019325432
  min : 0.0
  max : 80.0
X shape after clinical mode: (39, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_train shape: (26, 315)
X_test  shape: (13, 315)
y_train shape: (26,)
y_test  shape: (13,)
train unique ids: 26
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (26, 239)
X_test_f  shape: (13, 239)
n_removed_by_sparse: 76
removed example: ['CSF_RNA_hsa-let-7a-3p_TP48', 'CSF_RNA_hsa-miR-1273h-3p_TP48', 'CSF_RNA_hsa-miR-1285-3p_TP48', 'CSF_RNA_hsa-miR-1294_TP48', 'CSF_RNA_hsa-miR-1301-3p_TP48', 'CSF_RNA_hsa-miR-130b-5p_TP48', 'CSF_RNA_hsa-miR-139-5p_TP48', 'CSF_RNA_hsa-miR-140-5p_TP48', 'CSF_RNA_hsa-miR-141-3p_TP48', 'CSF_RNA_hsa-miR-148b-5p_TP48', 'CSF_RNA_hsa-miR-155-5p_TP48', 'CSF_RNA_hsa-miR-15b-3p_TP48', 'CSF_RNA_hsa-miR-185-3p_TP48', 'CSF_RNA_hsa-miR-18a-3p_TP48', 'CSF_RNA_hsa-miR-18a-5p_TP48', 'CSF_RNA_hsa-miR-193b-3p_TP48', 'CSF_RNA_hsa-miR-194-5p_TP48', 'CSF_RNA_hsa-miR-195-3p_TP48', 'CSF_RNA_hsa-miR-196a-5p_TP48', 'CSF_RNA_hsa-miR-196b-5p_TP48']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (26, 252)
X_test_f  shape: (13, 252)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (26, 252)
X_test_f  shape: (13, 252)

[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:  1.3min

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 40
selected feature examples: ['CSF_MET_CSF-Amine-52_TP48', 'CSF_MET_CSF-Amine-106_TP48', 'CSF_MET_CSF-Amine-323_TP48', 'CSF_MET_CSF-Amine-420_TP48', 'CSF_MET_CSF-Amine-429_TP48', 'CSF_MET_CSF-Amine-537_TP48', 'CSF_MET_CSF-Amine-701_TP48', 'CSF_MET_CSF-Amine-1018_TP48', 'CSF_MET_CSF-Amine-1250_TP48', 'CSF_MET_CSF-Amine-1370_TP48', 'CSF_MET_CSF-Amine-1386_TP48', 'CSF_MET_CSF-Amine-1424_TP48', 'CSF_MET_CSF-Amine-1616_TP48', 'CSF_MET_CSF-Amine-1738_TP48', 'CSF_MET_CSF-Carboxyl-2527_TP48', 'CSF_MET_CSF-Carboxyl-3864_TP48', 'CSF_MET_CSF-Hydroxyl-5247_TP48', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 100.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.06279178066401556
train_r2: 0.5011973333202928
train_mae: 11.11641395335121
test_r2 : -0.039430276891751825
test_mae: 16.399851423774866
pred_train summary:
  mean: 16.727272727272727
  std : 10.521823435749813
  min : -4.571467910085911
  max : 47.22176214105956
pred_test summary:
  mean: 19.720314833575053
  std : 12.41434367316097
  min : -3.8807790563188753
  max : 49.33805559519225
y_test summary:
  mean: 13.857142857142858
  std : 19.496729186701852
  min : -2.0
  max : 61.0

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 80
selected feature examples: ['SERUM_MET_Serum-Amine-7_TP48', 'SERUM_MET_Serum-Amine-25_TP48', 'SERUM_MET_Serum-Amine-37_TP48', 'SERUM_MET_Serum-Amine-39_TP48', 'SERUM_MET_Serum-Amine-46_TP48', 'SERUM_MET_Serum-Amine-47_TP48', 'SERUM_MET_Serum-Amine-58_TP48', 'SERUM_MET_Serum-Amine-62_TP48', 'SERUM_MET_Serum-Amine-66_TP48', 'SERUM_MET_Serum-Amine-73_TP48', 'SERUM_MET_Serum-Amine-83_TP48', 'SERUM_MET_Serum-Amine-116_TP48', 'SERUM_MET_Serum-Amine-118_TP48', 'SERUM_MET_Serum-Amine-139_TP48', 'SERUM_MET_Serum-Amine-205_TP48', 'SERUM_MET_Serum-Amine-212_TP48', 'SERUM_MET_Serum-Amine-217_TP48', 'SERUM_MET_Serum-Amine-256_TP48', 'SERUM_MET_Serum-Amine-298_TP48', 'SERUM_MET_Serum-Amine-320_TP48', 'SERUM_MET_Serum-Amine-323_TP48', 'SERUM_MET_Serum-Amine-333_TP48', 'SERUM_MET_Serum-Amine-357_TP48', 'SERUM_MET_Serum-Amine-405_TP48', 'SERUM_MET_Serum-Amine-530_TP48', 'SERUM_MET_Serum-Amine-538_TP48', 'SERUM_MET_Serum-Amine-565_TP48', 'SERUM_MET_Serum-Amine-642_TP48', 'SERUM_MET_Serum-Amine-751_TP48', 'SERUM_MET_Serum-Amine-854_TP48']

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 120
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.128205128205128
  std : 20.162732019325432
  min : 0.0
  max : 80.0
X shape after clinical mode: (39, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 20
X_train shape: (26, 315)
X_test  shape: (13, 315)
y_train shape: (26,)
y_test  shape: (13,)
train unique ids: 26
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 50.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.009948190908576342
train_r2: 0.79006835289919
train_mae: 7.111005765813694
test_r2 : -0.7330882170267496
test_mae: 20.95644896556265
pred_train summary:
  mean: 18.655172413793103
  std : 14.578985393343288
  min : -0.661411594500116
  max : 53.80973775827748
pred_test summary:
  mean: 22.336461963032438
  std : 11.146119265015821
  min : 1.2894280841048378
  max : 49.48624426341087
y_test summary:
  mean: 13.1
  std : 19.047922021399955
  min : -2.0
  max : 61.0

[AFTER SPARSE FILTER]
X_train_f shape: (26, 165)
X_test_f  shape: (13, 165)
n_removed_by_sparse: 150
removed example: ['CSF_RNA_hsa-let-7a-3p_TP120', 'CSF_RNA_hsa-let-7b-3p_TP120', 'CSF_RNA_hsa-let-7i-3p_TP120', 'CSF_RNA_hsa-miR-10a-3p_TP120', 'CSF_RNA_hsa-miR-10b-3p_TP120', 'CSF_RNA_hsa-miR-1180-3p_TP120', 'CSF_RNA_hsa-miR-124-3p_TP120', 'CSF_RNA_hsa-miR-125a-3p_TP120', 'CSF_RNA_hsa-miR-1260a_TP120', 'CSF_RNA_hsa-miR-1260b_TP120', 'CSF_RNA_hsa-miR-1273h-3p_TP120', 'CSF_RNA_hsa-miR-1285-3p_TP120', 'CSF_RNA_hsa-miR-1294_TP120', 'CSF_RNA_hsa-miR-1298-3p_TP120', 'CSF_RNA_hsa-miR-1299_TP120', 'CSF_RNA_hsa-miR-1301-3p_TP120', 'CSF_RNA_hsa-miR-1304-3p_TP120', 'CSF_RNA_hsa-miR-130b-5p_TP120', 'CSF_RNA_hsa-miR-132-3p_TP120', 'CSF_RNA_hsa-miR-136-5p_TP120']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (26, 178)
X_test_f  shape: (13, 178)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (26, 178)
X_test_f  shape: (13, 178)
candidate feature examples: ['CSF_RNA_hsa-let-7a-5p_TP120', 'CSF_RNA_hsa-let-7b-5p_TP120', 'CSF_RNA_hsa-let-7c-5p_TP120', 'CSF_RNA_hsa-let-7d-3p_TP120', 'CSF_RNA_hsa-let-7d-5p_TP120', 'CSF_RNA_hsa-let-7e-5p_TP120', 'CSF_RNA_hsa-let-7f-5p_TP120', 'CSF_RNA_hsa-let-7g-5p_TP120', 'CSF_RNA_hsa-let-7i-5p_TP120', 'CSF_RNA_hsa-miR-100-5p_TP120', 'CSF_RNA_hsa-miR-101-3p_TP120', 'CSF_RNA_hsa-miR-103a-3p_TP120', 'CSF_RNA_hsa-miR-106b-3p_TP120', 'CSF_RNA_hsa-miR-106b-5p_TP120', 'CSF_RNA_hsa-miR-107_TP120', 'CSF_RNA_hsa-miR-10a-5p_TP120', 'CSF_RNA_hsa-miR-10b-5p_TP120', 'CSF_RNA_hsa-miR-122-5p_TP120', 'CSF_RNA_hsa-miR-1246_TP120', 'CSF_RNA_hsa-miR-1247-5p_TP120', 'CSF_RNA_hsa-miR-125a-5p_TP120', 'CSF_RNA_hsa-miR-125b-1-3p_TP120', 'CSF_RNA_hsa-miR-125b-2-3p_TP120', 'CSF_RNA_hsa-miR-125b-5p_TP120', 'CSF_RNA_hsa-miR-126-3p_TP120', 'CSF_RNA_hsa-miR-126-5p_TP120', 'CSF_RNA_hsa-miR-127-3p_TP120', 'CSF_RNA_hsa-miR-128-3p_TP120', 'CSF_RNA_hsa-miR-129-5p_TP120', 'CSF_RNA_hsa-miR-1298-5p_TP120']

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=corr_topk, tissue=ser, combo=A, tp=48
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_ser_A_48.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: corr_topk
tissue: ser | combo: A | tp: 48
X shape before clinical: (108, 438)
y shape: (108,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.99074074074074
  std : 20.349973188974218
  min : -6.0
  max : 80.0
X shape after clinical mode: (108, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: corr_topk
top_k_after_sparse: 40
X_train shape: (58, 441)
X_test  shape: (30, 441)
y_train shape: (58,)
y_test  shape: (30,)
train unique ids: 58
test unique ids : 30
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (58, 129)
X_test_f  shape: (30, 129)
n_removed_by_sparse: 312
removed example: ['SERUM_PROT_A1BG|GVTFLLR_TP48', 'SERUM_PROT_ACO1|NIEVPFKPAR_TP48', 'SERUM_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP48', 'SERUM_PROT_ACY1|LHEAVFLR_TP48', 'SERUM_PROT_ACYP2|LEYSNFSIR_TP48', 'SERUM_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP48', 'SERUM_PROT_ADD1|VDENNPEYLR_TP48', 'SERUM_PROT_ADH1B|FSLDALITHVLPFEK_TP48', 'SERUM_PROT_ADIRF|TTQETIDK_TP48', 'SERUM_PROT_AFM|HFQNLGK_TP48', 'SERUM_PROT_AGA|NAIGVAR_TP48', 'SERUM_PROT_AHCY|VPAINVNDSVTK_TP48', 'SERUM_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP48', 'SERUM_PROT_AK1|IIFVVGGPGSGK_TP48', 'SERUM_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP48', 'SERUM_PROT_AKR1E2|NVIVIPGSITPSHIK_TP48', 'SERUM_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP48', 'SERUM_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP48', 'SERUM_PROT_ALAD|GSAADSEESPAIEAIHLLR_TP48', 'SERUM_PROT_ALDH9A1|ANDTTFGLAAGVFTR_TP48']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (58, 149)
X_test_f  shape: (30, 149)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (58, 149)
X_test_f  shape: (30, 149)
candidate feature examples: ['SERUM_PROT_A1BG|LETPDFQLFK_TP48', 'SERUM_PROT_A2M|AIGYLNTGYQR_TP48', 'SERUM_PROT_ACTA2|SYELPDGQVITIGNER_TP48', 'SERUM_PROT_ADGRF5|DVIVHPLPLK_TP48', 'SERUM_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP48', 'SERUM_PROT_AFM|DADPDTFFAK_TP48', 'SERUM_PROT_AGT|ALQDQLVLVAAK_TP48', 'SERUM_PROT_AHSG|FSVVYAK_TP48', 'SERUM_PROT_ALB|LVNEVTEFAK_TP48', 'SERUM_PROT_AMBP|HHGPTITAK_TP48', 'SERUM_PROT_APCS|IVLGQEQDSYGGK_TP48', 'SERUM_PROT_APMAP|LLEYDTVTR_TP48', 'SERUM_PROT_APOA1|ATEHLSTLSEK_TP48', 'SERUM_PROT_APOA2|SPELQAEAK_TP48', 'SERUM_PROT_APOA4|LGEVNTYAGDLQK_TP48', 'SERUM_PROT_APOB|FPEVDVLTK_TP48', 'SERUM_PROT_APOC1|EWFSETFQK_TP48', 'SERUM_PROT_APOC2|TYLPAVDEK_TP48', 'SERUM_PROT_APOC3|GWVTDGFSSLK_TP48', 'SERUM_PROT_APOC4|ELLETVVNR_TP48', 'SERUM_PROT_APOD|NILTSNNIDVK_TP48', 'SERUM_PROT_APOE|LGPLVEQGR_TP48', 'SERUM_PROT_APOF|SGVQQLIQYYQDQK_TP48', 'SERUM_PROT_APOH|ATVVYQGER_TP48', 'SERUM_PROT_APOL1|VAQELEEK_TP48', 'SERUM_PROT_APOM|AFLLTPR_TP48', 'SERUM_PROT_ATRN|SVNNVVVR_TP48', 'SERUM_PROT_AZGP1|EIPAWVPFDPAAQITK_TP48', 'SERUM_PROT_B2M|VNHVTLSQPK_TP48', 'SERUM_PROT_BCHE|YLTLNTESTR_TP48']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 16
selected feature examples: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 25.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17855299189219467
train_r2: 0.46333961267119894
train_mae: 11.67335476830036
test_r2 : -0.45320330936598285
test_mae: 18.7369753953651
pred_train summary:
  mean: 19.12
  std : 9.538814833454746
  min : 7.13980106681991
  max : 41.2859007811485
pred_test summary:
  mean: 23.345663194262922
  std : 6.34068740942471
  min : 16.02481952008979
  max : 34.454181294323085
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=C, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_C_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: C | tp: 120
X shape before clinical: (39, 312)
y shape: (39,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 17.128205128205128
  std : 20.162732019325432
  min : 0.0
  max : 80.0
X shape after clinical mode: (39, 315)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 30
X_train shape: (26, 315)
X_test  shape: (13, 315)
y_train shape: (26,)
y_test  shape: (13,)
train unique ids: 26
test unique ids : 13
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (26, 165)
X_test_f  shape: (13, 165)
n_removed_by_sparse: 150
removed example: ['CSF_RNA_hsa-let-7a-3p_TP120', 'CSF_RNA_hsa-let-7b-3p_TP120', 'CSF_RNA_hsa-let-7i-3p_TP120', 'CSF_RNA_hsa-miR-10a-3p_TP120', 'CSF_RNA_hsa-miR-10b-3p_TP120', 'CSF_RNA_hsa-miR-1180-3p_TP120', 'CSF_RNA_hsa-miR-124-3p_TP120', 'CSF_RNA_hsa-miR-125a-3p_TP120', 'CSF_RNA_hsa-miR-1260a_TP120', 'CSF_RNA_hsa-miR-1260b_TP120', 'CSF_RNA_hsa-miR-1273h-3p_TP120', 'CSF_RNA_hsa-miR-1285-3p_TP120', 'CSF_RNA_hsa-miR-1294_TP120', 'CSF_RNA_hsa-miR-1298-3p_TP120', 'CSF_RNA_hsa-miR-1299_TP120', 'CSF_RNA_hsa-miR-1301-3p_TP120', 'CSF_RNA_hsa-miR-1304-3p_TP120', 'CSF_RNA_hsa-miR-130b-5p_TP120', 'CSF_RNA_hsa-miR-132-3p_TP120', 'CSF_RNA_hsa-miR-136-5p_TP120']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (26, 178)
X_test_f  shape: (13, 178)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']
n_encoded_clinical_cols: 16
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (26, 178)
X_test_f  shape: (13, 178)
candidate feature examples: ['CSF_RNA_hsa-let-7a-5p_TP120', 'CSF_RNA_hsa-let-7b-5p_TP120', 'CSF_RNA_hsa-let-7c-5p_TP120', 'CSF_RNA_hsa-let-7d-3p_TP120', 'CSF_RNA_hsa-let-7d-5p_TP120', 'CSF_RNA_hsa-let-7e-5p_TP120', 'CSF_RNA_hsa-let-7f-5p_TP120', 'CSF_RNA_hsa-let-7g-5p_TP120', 'CSF_RNA_hsa-let-7i-5p_TP120', 'CSF_RNA_hsa-miR-100-5p_TP120', 'CSF_RNA_hsa-miR-101-3p_TP120', 'CSF_RNA_hsa-miR-103a-3p_TP120', 'CSF_RNA_hsa-miR-106b-3p_TP120', 'CSF_RNA_hsa-miR-106b-5p_TP120', 'CSF_RNA_hsa-miR-107_TP120', 'CSF_RNA_hsa-miR-10a-5p_TP120', 'CSF_RNA_hsa-miR-10b-5p_TP120', 'CSF_RNA_hsa-miR-122-5p_TP120', 'CSF_RNA_hsa-miR-1246_TP120', 'CSF_RNA_hsa-miR-1247-5p_TP120', 'CSF_RNA_hsa-miR-125a-5p_TP120', 'CSF_RNA_hsa-miR-125b-1-3p_TP120', 'CSF_RNA_hsa-miR-125b-2-3p_TP120', 'CSF_RNA_hsa-miR-125b-5p_TP120', 'CSF_RNA_hsa-miR-126-3p_TP120', 'CSF_RNA_hsa-miR-126-5p_TP120', 'CSF_RNA_hsa-miR-127-3p_TP120', 'CSF_RNA_hsa-miR-128-3p_TP120', 'CSF_RNA_hsa-miR-129-5p_TP120', 'CSF_RNA_hsa-miR-1298-5p_TP120']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 40
selected feature examples: ['SERUM_PROT_AFM|DADPDTFFAK_TP48', 'SERUM_PROT_APCS|IVLGQEQDSYGGK_TP48', 'SERUM_PROT_APMAP|LLEYDTVTR_TP48', 'SERUM_PROT_BTD|SHLIIAQVAK_TP48', 'SERUM_PROT_C1RL|VVVHPDYR_TP48', 'SERUM_PROT_C5|VFQFLEK_TP48', 'SERUM_PROT_C6|DLHLSDVFLK_TP48', 'SERUM_PROT_CLU|ELDESLQVAER_TP48', 'SERUM_PROT_CRP|AFVFPK_TP48', 'SERUM_PROT_ECM1|NVALVSGDTENAK_TP48', 'SERUM_PROT_F11|TSESGLPSTR_TP48', 'SERUM_PROT_ITIH1|GSLVQASEANLQAAQDFVR_TP48', 'SERUM_PROT_ITIH2|SLAPTAAAK_TP48', 'SERUM_PROT_PGLYRP2|AGLLRPDYALLGHR_TP48', 'SERUM_PROT_PLG|EAQLPVIENK_TP48', 'SERUM_PROT_PROC|LGEYDLR_TP48', 'SERUM_PROT_SERPINC1|DDLYVSDAFHK_TP48', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 100.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.045956922765557434
train_r2: 0.4779220239776778
train_mae: 11.687074251595856
test_r2 : 0.07822251139718206
test_mae: 15.196407605102115
pred_train summary:
  mean: 18.6551724137931
  std : 10.320394855526024
  min : 1.492805778780454
  max : 44.22679629799574
pred_test summary:
  mean: 17.71984959542291
  std : 9.332202143120094
  min : -3.883356600609364
  max : 37.84070028644932
y_test summary:
  mean: 13.1
  std : 19.047922021399955
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=24
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_24.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 24
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.145631067961165
  std : 19.99431672534811
  min : -6.0
  max : 80.0
X shape after clinical mode: (103, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 120
X_train shape: (55, 441)
X_test  shape: (28, 441)
y_train shape: (55,)
y_test  shape: (28,)
train unique ids: 55
test unique ids : 28
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (55, 205)
X_test_f  shape: (28, 205)
n_removed_by_sparse: 236
removed example: ['CSF_PROT_A1BG|LETPDFQLFK_TP24', 'CSF_PROT_A2M|AIGYLNTGYQR_TP24', 'CSF_PROT_ACO1|NIEVPFKPAR_TP24', 'CSF_PROT_ACTA2|SYELPDGQVITIGNER_TP24', 'CSF_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP24', 'CSF_PROT_ACYP2|LEYSNFSIR_TP24', 'CSF_PROT_ADD1|VDENNPEYLR_TP24', 'CSF_PROT_ADGRF5|DVIVHPLPLK_TP24', 'CSF_PROT_ADH1B|FSLDALITHVLPFEK_TP24', 'CSF_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP24', 'CSF_PROT_AFM|DADPDTFFAK_TP24', 'CSF_PROT_AGT|ALQDQLVLVAAK_TP24', 'CSF_PROT_AHCY|VPAINVNDSVTK_TP24', 'CSF_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP24', 'CSF_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP24', 'CSF_PROT_AKR1E2|NVIVIPGSITPSHIK_TP24', 'CSF_PROT_AKT1S1|EAEDTQVFGDLPRPR_TP24', 'CSF_PROT_ALB|LVNEVTEFAK_TP24', 'CSF_PROT_ALDOB|ALQASALAAWGGK_TP24', 'CSF_PROT_AMBP|HHGPTITAK_TP24']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (55, 225)
X_test_f  shape: (28, 225)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (55, 225)
X_test_f  shape: (28, 225)
candidate feature examples: ['CSF_PROT_A1BG|GVTFLLR_TP24', 'CSF_PROT_ACY1|LHEAVFLR_TP24', 'CSF_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP24', 'CSF_PROT_ADIRF|TTQETIDK_TP24', 'CSF_PROT_AFM|HFQNLGK_TP24', 'CSF_PROT_AGA|NAIGVAR_TP24', 'CSF_PROT_AHSG|FSVVYAK_TP24', 'CSF_PROT_AK1|IIFVVGGPGSGK_TP24', 'CSF_PROT_AKR7A2|ALQAAYGASAPSVTSAALR_TP24', 'CSF_PROT_ALAD|GSAADSEESPAIEAIHLLR_TP24', 'CSF_PROT_ALDH9A1|ANDTTFGLAAGVFTR_TP24', 'CSF_PROT_ALDOC|DNAGAATEEFIK_TP24', 'CSF_PROT_AMBP|ETLLQDFR_TP24', 'CSF_PROT_ANXA2|QDIAFAYQR_TP24', 'CSF_PROT_APCS|VGEYSLYIGR_TP24', 'CSF_PROT_APOA4|SLAPYAQDTQEK_TP24', 'CSF_PROT_APOB|IEGNLIFDPNNYLPK_TP24', 'CSF_PROT_APOC2|ESLSSYWESAK_TP24', 'CSF_PROT_APOC4|AWFLESK_TP24', 'CSF_PROT_APOE|LGPLVEQGR_TP24', 'CSF_PROT_APOH|ATVVYQGER_TP24', 'CSF_PROT_APOL1|LNILNNNYK_TP24', 'CSF_PROT_APOM|AFLLTPR_TP24', 'CSF_PROT_AZGP1|YSLTYIYTGLSK_TP24', 'CSF_PROT_B2M|VNHVTLSQPK_TP24', 'CSF_PROT_B4GAT1|TALASGGVLDASGDYR_TP24', 'CSF_PROT_BCAN|YPIVTPSQR_TP24', 'CSF_PROT_BCHE|YLTLNTESTR_TP24', 'CSF_PROT_BLVRB|TVAGQDAVIVLLGTR_TP24', 'CSF_PROT_BTD|LSSGLVTAALYGR_TP24']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 20
selected feature examples: ['CSF_RNA_hsa-miR-145-3p_TP120', 'CSF_RNA_hsa-miR-146b-5p_TP120', 'CSF_RNA_hsa-miR-342-3p_TP120', 'CSF_RNA_hsa-miR-363-3p_TP120', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 100.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.052364294712201206
train_r2: 0.44031445199199426
train_mae: 11.557376573469408

[Parallel(n_jobs=8)]: Done  41 out of  50 | elapsed:  1.7min remaining:   22.2s

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 120
selected feature examples: ['CSF_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP24', 'CSF_PROT_AGA|NAIGVAR_TP24', 'CSF_PROT_AK1|IIFVVGGPGSGK_TP24', 'CSF_PROT_ALAD|GSAADSEESPAIEAIHLLR_TP24', 'CSF_PROT_ALDH9A1|ANDTTFGLAAGVFTR_TP24', 'CSF_PROT_ALDOC|DNAGAATEEFIK_TP24', 'CSF_PROT_ANXA2|QDIAFAYQR_TP24', 'CSF_PROT_APOA4|SLAPYAQDTQEK_TP24', 'CSF_PROT_APOC2|ESLSSYWESAK_TP24', 'CSF_PROT_B2M|VNHVTLSQPK_TP24', 'CSF_PROT_B4GAT1|TALASGGVLDASGDYR_TP24', 'CSF_PROT_BCAN|YPIVTPSQR_TP24', 'CSF_PROT_BLVRB|TVAGQDAVIVLLGTR_TP24', 'CSF_PROT_BTD|LSSGLVTAALYGR_TP24', 'CSF_PROT_C16orf89|ATIADLILSALER_TP24', 'CSF_PROT_C1QA|PAFSAIR_TP24', 'CSF_PROT_C1QB|IAFSATR_TP24', 'CSF_PROT_C1R|YTTEIIK_TP24', 'CSF_PROT_C2|ELNELGSK_TP24', 'CSF_PROT_C4A|DHAVDLIQK_TP24', 'CSF_PROT_C9|TSNFNAAISLK_TP24', 'CSF_PROT_CA2|VVDVLDSIK_TP24', 'CSF_PROT_CADM4|LHQYDGSIVVIQNPAR_TP24', 'CSF_PROT_CD5L|LEVLHK_TP24', 'CSF_PROT_CHL1|TAVTANLDIR_TP24', 'CSF_PROT_CKB|LAVEALSSLDGDLAGR_TP24', 'CSF_PROT_CNTN2|GPPGPPGGVVVR_TP24', 'CSF_PROT_COL15A1|AFLSSHLQDLSTIVR_TP24', 'CSF_PROT_CP|GAYPLSIEPIGVR_TP24', 'CSF_PROT_CPE|SNAQGIDLNR_TP24']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 100.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.006059964731072089
train_r2: 0.559359972961097
train_mae: 9.698650596164118
test_r2 : 0.17550938827865692
test_mae: 14.173173569546707
pred_train summary:
  mean: 16.72727272727273
  std : 10.892833318211983
  min : -0.5789639854122584
  max : 43.90054021583767
pred_test summary:
  mean: 15.552423256543666
  std : 9.053075354139345
  min : -11.321602301679413
  max : 34.762837467300514
y_test summary:
  mean: 13.857142857142858
  std : 19.496729186701852
  min : -2.0
  max : 61.0

[RUN-FINAL-TEST] feature_mode=omics, clinical_mode=light, selection=f_regression_topk, tissue=csf, combo=A, tp=120
feature_path: ../../DifferentCom_data_rebuild/tp_views/x_omics_csf_A_120.csv

[EXPERIMENT START]
feature_mode: omics
clinical_mode: light
feature_selection_mode: f_regression_topk
tissue: csf | combo: A | tp: 120
X shape before clinical: (103, 438)
y shape: (103,)
n_delta_features: 0
delta examples: []
y summary:
  mean: 15.145631067961165
  std : 19.99431672534811
  min : -6.0
  max : 80.0
X shape after clinical mode: (103, 441)
delta cols count: 0
clinical cols present: ['Age', 'Gender', 'Level']

[TRAIN / TEST SPLIT CHECK]
clinical_mode: light
feature_selection_mode: f_regression_topk
top_k_after_sparse: 40
X_train shape: (55, 441)
X_test  shape: (28, 441)
y_train shape: (55,)
y_test  shape: (28,)
train unique ids: 55
test unique ids : 28
overlap ids count: 0
overlap ids example: []
  delta cols count: 0
  delta examples: []
  clinical cols present: ['Age', 'Gender', 'Level']

[AFTER SPARSE FILTER]
X_train_f shape: (55, 127)
X_test_f  shape: (28, 127)
n_removed_by_sparse: 314
removed example: ['CSF_PROT_A1BG|LETPDFQLFK_TP120', 'CSF_PROT_A2M|AIGYLNTGYQR_TP120', 'CSF_PROT_ACO1|NIEVPFKPAR_TP120', 'CSF_PROT_ACTA2|SYELPDGQVITIGNER_TP120', 'CSF_PROT_ACTN4|LSGSNPYTTVTPQIINSK_TP120', 'CSF_PROT_ACY1|LHEAVFLR_TP120', 'CSF_PROT_ACYP2|LEYSNFSIR_TP120', 'CSF_PROT_ADD1|VDENNPEYLR_TP120', 'CSF_PROT_ADGRF5|DVIVHPLPLK_TP120', 'CSF_PROT_ADH1B|FSLDALITHVLPFEK_TP120', 'CSF_PROT_ADIPOQ|IFYNQQNHYDGSTGK_TP120', 'CSF_PROT_ADIRF|TTQETIDK_TP120', 'CSF_PROT_AFM|DADPDTFFAK_TP120', 'CSF_PROT_AFM|HFQNLGK_TP120', 'CSF_PROT_AGA|NAIGVAR_TP120', 'CSF_PROT_AGT|ALQDQLVLVAAK_TP120', 'CSF_PROT_AHCY|VPAINVNDSVTK_TP120', 'CSF_PROT_AHNAK|VDINAPDVDVQGPDWHLK_TP120', 'CSF_PROT_AK1|IIFVVGGPGSGK_TP120', 'CSF_PROT_AKR1A1|GLEVTAYSPLGSSDR_TP120']
clinical remaining after sparse: ['Age', 'Gender', 'Level']

[AFTER CLINICAL ENCODING]
X_train_f shape: (55, 147)
X_test_f  shape: (28, 147)
encoded clinical cols: ['Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02', 'Level_T03', 'Level_T04', 'Level_T05', 'Level_T06', 'Level_T07', 'Level_T09', 'Level_T10']
n_encoded_clinical_cols: 23
non_numeric_cols_after_encoding: []
n_non_numeric_after_encoding: 0

[BEFORE FOLD-SAFE SELECTION]
X_train_f shape: (55, 147)
X_test_f  shape: (28, 147)
candidate feature examples: ['CSF_PROT_A1BG|GVTFLLR_TP120', 'CSF_PROT_ADAMTS1|GAFYLLGEAYFIQPLPAASER_TP120', 'CSF_PROT_AHSG|FSVVYAK_TP120', 'CSF_PROT_AMBP|ETLLQDFR_TP120', 'CSF_PROT_APOA4|SLAPYAQDTQEK_TP120', 'CSF_PROT_APOB|IEGNLIFDPNNYLPK_TP120', 'CSF_PROT_APOE|LGPLVEQGR_TP120', 'CSF_PROT_APOH|ATVVYQGER_TP120', 'CSF_PROT_APOM|AFLLTPR_TP120', 'CSF_PROT_AZGP1|YSLTYIYTGLSK_TP120', 'CSF_PROT_B2M|VNHVTLSQPK_TP120', 'CSF_PROT_B4GAT1|TALASGGVLDASGDYR_TP120', 'CSF_PROT_BCAN|YPIVTPSQR_TP120', 'CSF_PROT_BTD|LSSGLVTAALYGR_TP120', 'CSF_PROT_C16orf89|ATIADLILSALER_TP120', 'CSF_PROT_C1QA|PAFSAIR_TP120', 'CSF_PROT_C1QB|IAFSATR_TP120', 'CSF_PROT_C1R|YTTEIIK_TP120', 'CSF_PROT_C2|ELNELGSK_TP120', 'CSF_PROT_C3|TGLQEVEVK_TP120', 'CSF_PROT_C4A|DHAVDLIQK_TP120', 'CSF_PROT_C4A|GLEEELQFSLGSK_TP120', 'CSF_PROT_C4BPB|ALLAFQESK_TP120', 'CSF_PROT_C5|TLLPVSKPEIR_TP120', 'CSF_PROT_C6|ALQEYAAK_TP120', 'CSF_PROT_C7|LSGNVLSYTFQVK_TP120', 'CSF_PROT_C8G|AGQLSVK_TP120', 'CSF_PROT_C9|TSNFNAAISLK_TP120', 'CSF_PROT_CA1|GGPFSDSYR_TP120', 'CSF_PROT_CADM4|LHQYDGSIVVIQNPAR_TP120']

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 20
selected feature examples: ['CSF_RNA_hsa-miR-145-3p_TP120', 'CSF_RNA_hsa-miR-342-3p_TP120', 'CSF_RNA_hsa-miR-363-3p_TP120', 'CSF_RNA_hsa-miR-4732-3p_TP120', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 50.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.08644319762556592
train_r2: 0.5457243318206813
train_mae: 9.647349308725861
test_r2 : 0.06289032289301033
test_mae: 15.131957328562503
pred_train summary:
  mean: 18.96153846153846
  std : 9.82546211100621
  min : 5.82750959141223
  max : 47.19809324051499
pred_test summary:
  mean: 20.384657531846333
  std : 6.509539128831919
  min : 9.062059240001412
  max : 31.888129981336547
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 40
selected feature examples: ['CSF_PROT_AZGP1|YSLTYIYTGLSK_TP120', 'CSF_PROT_C16orf89|ATIADLILSALER_TP120', 'CSF_PROT_C9|TSNFNAAISLK_TP120', 'CSF_PROT_CALR|GQTLVVQFTVK_TP120', 'CSF_PROT_CNTN2|GPPGPPGGVVVR_TP120', 'CSF_PROT_CTSL|VFQEPLFYEAPR_TP120', 'CSF_PROT_GC|VLEPTLK_TP120', 'CSF_PROT_GFAP|LADVYQAELR_TP120', 'CSF_PROT_LRG1|ALGHLDLSGNR_TP120', 'CSF_PROT_NEO1|LTHQIQELTLDTPYYFK_TP120', 'CSF_PROT_NRXN3|LFQGQLSGLYYDGLK_TP120', 'CSF_PROT_NUTF2|LSSLPFQK_TP120', 'CSF_PROT_OMG|TLDISNNR_TP120', 'CSF_PROT_SERPINF2|LGNQEPGGQTALK_TP120', 'CSF_PROT_SPOCK1|SLLGAFIPR_TP120', 'CSF_PROT_TIMP1|GFQALGDAADIR_TP120', 'CSF_PROT_YWHAH|LAEQAER_TP120', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C06', 'Level_C07', 'Level_L01', 'Level_T01', 'Level_T02']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 100.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.0636653104724936
train_r2: 0.3842185846150883
train_mae: 12.00995808672461
test_r2 : 0.07407034776548782
test_mae: 16.215884550002006
pred_train summary:
  mean: 16.727272727272727
  std : 8.352250061938095
  min : -3.1009545356327344
  max : 39.518175067332606
pred_test summary:
  mean: 19.330563813246794
  std : 9.322389520036412
  min : -2.62204492932338
  max : 39.30610325468661
y_test summary:
  mean: 13.857142857142858
  std : 19.496729186701852
  min : -2.0
  max : 61.0

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 20
selected feature examples: ['SERUM_RNA_hsa-miR-10b-5p_TP120', 'SERUM_RNA_hsa-miR-133a-3p_TP120', 'SERUM_RNA_hsa-miR-204-5p_TP120', 'SERUM_RNA_hsa-miR-92b-3p_TP120', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: ridge
best_params: {'model__alpha': 50.0, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.13745884552393237
train_r2: 0.5202814463491174
train_mae: 10.146278952100905
test_r2 : -0.2862065183348006
test_mae: 17.214072846691078
pred_train summary:
  mean: 19.12
  std : 9.560193953697938
  min : 5.997348342183537
  max : 44.26947677756132
pred_test summary:
  mean: 23.185846722186206
  std : 6.214295266978866
  min : 10.452428410190247
  max : 33.36933874931313
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 40
selected feature examples: ['SERUM_RNA_hsa-let-7c-5p_TP24', 'SERUM_RNA_hsa-let-7e-5p_TP24', 'SERUM_RNA_hsa-miR-101-3p_TP24', 'SERUM_RNA_hsa-miR-106b-5p_TP24', 'SERUM_RNA_hsa-miR-125b-1-3p_TP24', 'SERUM_RNA_hsa-miR-126-5p_TP24', 'SERUM_RNA_hsa-miR-128-3p_TP24', 'SERUM_RNA_hsa-miR-145-3p_TP24', 'SERUM_RNA_hsa-miR-18a-5p_TP24', 'SERUM_RNA_hsa-miR-193b-5p_TP24', 'SERUM_RNA_hsa-miR-199a-3p_TP24', 'SERUM_RNA_hsa-miR-199b-3p_TP24', 'SERUM_RNA_hsa-miR-19a-3p_TP24', 'SERUM_RNA_hsa-miR-19b-3p_TP24', 'SERUM_RNA_hsa-miR-20b-5p_TP24', 'SERUM_RNA_hsa-miR-22-5p_TP24', 'SERUM_RNA_hsa-miR-222-3p_TP24', 'SERUM_RNA_hsa-miR-223-5p_TP24', 'SERUM_RNA_hsa-miR-30e-5p_TP24', 'SERUM_RNA_hsa-miR-342-5p_TP24', 'SERUM_RNA_hsa-miR-486-5p_TP24', 'SERUM_RNA_hsa-miR-542-3p_TP24', 'SERUM_RNA_hsa-miR-550a-3p_TP24', 'SERUM_RNA_hsa-miR-873-3p_TP24', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03']

[FINAL PREDICTION CHECK]
best_model_type: xgboost
best_params: {'model__colsample_bytree': 0.9, 'model__learning_rate': 0.03, 'model__max_depth': 1, 'model__min_child_weight': 4, 'model__n_estimators': 80, 'model__reg_alpha': 1.0, 'model__reg_lambda': 10.0, 'model__subsample': 0.8, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17639298346013613
train_r2: 0.5902329737139832
train_mae: 9.695563163757324
test_r2 : -0.5980313356302036
test_mae: 17.9727725982666
pred_train summary:
  mean: 17.648548126220703
  std : 9.114392280578613
  min : 8.78207015991211
  max : 35.0890998840332
pred_test summary:
  mean: 23.029369354248047
  std : 7.368628025054932
  min : 10.22933292388916
  max : 32.552284240722656
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 30
selected feature examples: ['SERUM_RNA_hsa-let-7c-5p_TP24', 'SERUM_RNA_hsa-let-7e-5p_TP24', 'SERUM_RNA_hsa-miR-101-3p_TP24', 'SERUM_RNA_hsa-miR-126-5p_TP24', 'SERUM_RNA_hsa-miR-128-3p_TP24', 'SERUM_RNA_hsa-miR-193b-5p_TP24', 'SERUM_RNA_hsa-miR-19b-3p_TP24', 'SERUM_RNA_hsa-miR-20b-5p_TP24', 'SERUM_RNA_hsa-miR-22-5p_TP24', 'SERUM_RNA_hsa-miR-222-3p_TP24', 'SERUM_RNA_hsa-miR-223-5p_TP24', 'SERUM_RNA_hsa-miR-4446-3p_TP24', 'SERUM_RNA_hsa-miR-486-5p_TP24', 'SERUM_RNA_hsa-miR-873-3p_TP24', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: xgboost
best_params: {'model__colsample_bytree': 0.9, 'model__learning_rate': 0.03, 'model__max_depth': 2, 'model__min_child_weight': 4, 'model__n_estimators': 80, 'model__reg_alpha': 0.5, 'model__reg_lambda': 10.0, 'model__subsample': 0.8, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17767535452482563
train_r2: 0.608157792118275
train_mae: 9.377769317626953
test_r2 : -0.7936368739371369
test_mae: 19.318777377788837
pred_train summary:
  mean: 17.473730087280273
  std : 9.338380813598633
  min : 8.078414916992188
  max : 35.635746002197266
pred_test summary:
  mean: 23.918962478637695
  std : 7.641472816467285
  min : 10.302102088928223
  max : 34.55656814575195
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[Parallel(n_jobs=8)]: Done  47 out of  50 | elapsed:  2.7min remaining:   10.3s

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 30
selected feature examples: ['SERUM_RNA_hsa-let-7c-5p_TP24', 'SERUM_RNA_hsa-let-7e-5p_TP24', 'SERUM_RNA_hsa-miR-101-3p_TP24', 'SERUM_RNA_hsa-miR-125b-1-3p_TP24', 'SERUM_RNA_hsa-miR-126-5p_TP24', 'SERUM_RNA_hsa-miR-128-3p_TP24', 'SERUM_RNA_hsa-miR-193b-5p_TP24', 'SERUM_RNA_hsa-miR-19a-3p_TP24', 'SERUM_RNA_hsa-miR-19b-3p_TP24', 'SERUM_RNA_hsa-miR-22-5p_TP24', 'SERUM_RNA_hsa-miR-222-3p_TP24', 'SERUM_RNA_hsa-miR-223-5p_TP24', 'SERUM_RNA_hsa-miR-486-5p_TP24', 'SERUM_RNA_hsa-miR-550a-3p_TP24', 'Age', 'Gender_F', 'Gender_M', 'Gender_nan', 'Level_C01', 'Level_C03', 'Level_C04', 'Level_C05', 'Level_C07', 'Level_L01', 'Level_T03', 'Level_T04', 'Level_T07', 'Level_T09', 'Level_T12', 'Level_nan']

[FINAL PREDICTION CHECK]
best_model_type: xgboost
best_params: {'model__colsample_bytree': 0.9, 'model__learning_rate': 0.03, 'model__max_depth': 2, 'model__min_child_weight': 2, 'model__n_estimators': 80, 'model__reg_alpha': 0.5, 'model__reg_lambda': 5.0, 'model__subsample': 0.8, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.17412304348639424
train_r2: 0.779827405170733
train_mae: 6.897051582336426
test_r2 : -0.874355228283255
test_mae: 18.757509818443886
pred_train summary:
  mean: 17.69778060913086
  std : 12.444511413574219
  min : 6.363276958465576
  max : 43.575462341308594
pred_test summary:
  mean: 24.822298049926758
  std : 9.910558700561523
  min : 10.443801879882812
  max : 40.76919174194336
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 60
selected feature examples: ['SERUM_RNA_hsa-let-7b-5p_TP24', 'SERUM_RNA_hsa-let-7c-5p_TP24', 'SERUM_RNA_hsa-let-7e-5p_TP24', 'SERUM_RNA_hsa-miR-101-3p_TP24', 'SERUM_RNA_hsa-miR-103a-3p_TP24', 'SERUM_RNA_hsa-miR-106b-5p_TP24', 'SERUM_RNA_hsa-miR-10b-3p_TP24', 'SERUM_RNA_hsa-miR-125b-1-3p_TP24', 'SERUM_RNA_hsa-miR-126-3p_TP24', 'SERUM_RNA_hsa-miR-126-5p_TP24', 'SERUM_RNA_hsa-miR-128-3p_TP24', 'SERUM_RNA_hsa-miR-142-5p_TP24', 'SERUM_RNA_hsa-miR-145-3p_TP24', 'SERUM_RNA_hsa-miR-146a-5p_TP24', 'SERUM_RNA_hsa-miR-146b-3p_TP24', 'SERUM_RNA_hsa-miR-182-5p_TP24', 'SERUM_RNA_hsa-miR-183-5p_TP24', 'SERUM_RNA_hsa-miR-18a-5p_TP24', 'SERUM_RNA_hsa-miR-193a-5p_TP24', 'SERUM_RNA_hsa-miR-193b-5p_TP24', 'SERUM_RNA_hsa-miR-199a-3p_TP24', 'SERUM_RNA_hsa-miR-199b-3p_TP24', 'SERUM_RNA_hsa-miR-199b-5p_TP24', 'SERUM_RNA_hsa-miR-19a-3p_TP24', 'SERUM_RNA_hsa-miR-19b-3p_TP24', 'SERUM_RNA_hsa-miR-20b-5p_TP24', 'SERUM_RNA_hsa-miR-210-3p_TP24', 'SERUM_RNA_hsa-miR-22-5p_TP24', 'SERUM_RNA_hsa-miR-222-3p_TP24', 'SERUM_RNA_hsa-miR-223-5p_TP24']

[FINAL PREDICTION CHECK]
best_model_type: xgboost
best_params: {'model__colsample_bytree': 0.9, 'model__learning_rate': 0.03, 'model__max_depth': 2, 'model__min_child_weight': 2, 'model__n_estimators': 80, 'model__reg_alpha': 1.0, 'model__reg_lambda': 5.0, 'model__subsample': 0.8, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.20178378996631854
train_r2: 0.7894025932894658
train_mae: 6.272169227600098
test_r2 : -0.64763062114981
test_mae: 17.014823106619026
pred_train summary:
  mean: 17.602853775024414
  std : 12.468167304992676
  min : 6.130918502807617
  max : 43.31892395019531
pred_test summary:
  mean: 21.63661003112793
  std : 9.173872947692871
  min : 7.973078727722168
  max : 35.56854248046875
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0

[AFTER FINAL TRAIN-ONLY FEATURE SELECTION]
selected n_features: 60
selected feature examples: ['SERUM_RNA_hsa-let-7b-5p_TP24', 'SERUM_RNA_hsa-let-7c-5p_TP24', 'SERUM_RNA_hsa-let-7e-5p_TP24', 'SERUM_RNA_hsa-miR-101-3p_TP24', 'SERUM_RNA_hsa-miR-103a-3p_TP24', 'SERUM_RNA_hsa-miR-106b-5p_TP24', 'SERUM_RNA_hsa-miR-125b-1-3p_TP24', 'SERUM_RNA_hsa-miR-126-3p_TP24', 'SERUM_RNA_hsa-miR-126-5p_TP24', 'SERUM_RNA_hsa-miR-128-3p_TP24', 'SERUM_RNA_hsa-miR-1307-3p_TP24', 'SERUM_RNA_hsa-miR-142-5p_TP24', 'SERUM_RNA_hsa-miR-144-5p_TP24', 'SERUM_RNA_hsa-miR-145-3p_TP24', 'SERUM_RNA_hsa-miR-146a-5p_TP24', 'SERUM_RNA_hsa-miR-146b-3p_TP24', 'SERUM_RNA_hsa-miR-182-5p_TP24', 'SERUM_RNA_hsa-miR-183-5p_TP24', 'SERUM_RNA_hsa-miR-18a-5p_TP24', 'SERUM_RNA_hsa-miR-193b-5p_TP24', 'SERUM_RNA_hsa-miR-199a-3p_TP24', 'SERUM_RNA_hsa-miR-199b-3p_TP24', 'SERUM_RNA_hsa-miR-199b-5p_TP24', 'SERUM_RNA_hsa-miR-19a-3p_TP24', 'SERUM_RNA_hsa-miR-19b-3p_TP24', 'SERUM_RNA_hsa-miR-20b-5p_TP24', 'SERUM_RNA_hsa-miR-210-3p_TP24', 'SERUM_RNA_hsa-miR-22-5p_TP24', 'SERUM_RNA_hsa-miR-222-3p_TP24', 'SERUM_RNA_hsa-miR-223-5p_TP24']

[FINAL PREDICTION CHECK]
best_model_type: xgboost
best_params: {'model__colsample_bytree': 0.9, 'model__learning_rate': 0.03, 'model__max_depth': 2, 'model__min_child_weight': 2, 'model__n_estimators': 80, 'model__reg_alpha': 1.0, 'model__reg_lambda': 5.0, 'model__subsample': 0.8, 'preprocess__num__imputer': SimpleImputer(strategy='median')}
best_score_inner_oof_r2: 0.18198312052820267
train_r2: 0.7889505074251352
train_mae: 6.2996084594726565
test_r2 : -0.6860223740391711
test_mae: 17.04496354323167
pred_train summary:
  mean: 17.67011070251465
  std : 12.448509216308594
  min : 6.13966703414917
  max : 43.30098342895508
pred_test summary:
  mean: 21.64307403564453
  std : 9.57930850982666
  min : 7.96223258972168
  max : 36.36474609375
y_test summary:
  mean: 13.461538461538462
  std : 17.442721138344762
  min : 0.0
  max : 59.0
saved: ../../DifferentCom_data_rebuild/testResult/results_single_omics_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible/omics_holdout_test_summary_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible.csv
saved leakage-safe rank1 final compare table: ../../DifferentCom_data_rebuild/testResult/results_single_omics_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible/single_omics_test_training_rank1_by_tissue_tp_for_ef_lf_compare_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible.csv
saved descriptive test-best table: ../../DifferentCom_data_rebuild/testResult/results_single_omics_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible/single_omics_test_descriptive_best_by_test_r2_within_topN_tissue_tp_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible.csv
saved descriptive test-best combo table: ../../DifferentCom_data_rebuild/testResult/results_single_omics_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible/single_omics_test_descriptive_best_by_test_r2_within_topN_tissue_combo_tp_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible.csv
saved top-N sensitivity summary: ../../DifferentCom_data_rebuild/testResult/results_single_omics_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible/single_omics_test_topN_sensitivity_by_tissue_tp_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible.csv
saved EF/LF compare table using training rank1 only: ../../DifferentCom_data_rebuild/testResult/results_single_omics_test_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible/single_omics_test_for_ef_lf_compare_by_tissue_tp_single_omics_final_test_top5_sensitivity_from_v11_rescue_expansion_v9compatible.csv

Holdout test summary sorted by TEST R² for inspection only.
Do not use this ranking to choose a new final config.

[Parallel(n_jobs=8)]: Done  50 out of  50 | elapsed:  3.2min finished

,status,tissue,tp,training_rank_within_tissue_tp,combo,clinical_mode,feature_selection_mode,top_k_after_sparse,selected_model_type_from_training,best_model_type,train_oof_r2,train_mean_valid_r2,test_r2,test_mae,train_r2,best_score_inner_cv_r2,n_features_after_selection
5,ok,csf,48,1,C,light,corr_topk,30,ridge,ridge,0.201590,0.186037,0.461189,9.556048,0.778636,0.167297,30
6,ok,csf,48,2,C,light,f_regression_topk,30,ridge,ridge,0.117648,0.060554,0.383918,12.321457,0.629481,0.161967,30
12,ok,csf,72,3,A,light,f_regression_topk,40,gbr,gbr,0.128291,0.075298,0.369730,12.881785,0.525343,0.149833,40
10,ok,csf,72,1,A,light,corr_topk,60,gbr,gbr,0.195500,0.126244,0.283918,14.039792,0.411410,0.113992,60
38,ok,ser,72,4,A,light,corr_topk,120,svr_linear,svr_linear,0.138242,0.197571,0.228788,12.988432,0.577262,0.103099,120
37,ok,ser,72,3,A,light,f_regression_topk,120,svr_linear,svr_linear,0.140991,0.200750,0.224871,12.998874,0.580169,0.109696,120
17,ok,csf,96,3,A,light,corr_topk,40,ridge,ridge,0.138209,0.071006,0.213177,14.580310,0.513250,0.115292,40
18,ok,csf,96,4,A,light,f_regression_topk,40,ridge,ridge,0.125457,0.056174,0.212523,14.524528,0.490627,0.111938,40
39,ok,ser,72,5,A,light,corr_topk,140,svr_linear,svr_linear,0.132800,0.185666,0.196684,13.083296,0.596559,0.117251,140
4,ok,csf,24,5,A,light,f_regression_topk,120,ridge,ridge,0.069795,0.072770,0.175509,14.173174,0.559360,0.006060,120
15,ok,csf,96,1,A,light,f_regression_topk,30,ridge,ridge,0.236085,0.199354,0.169784,14.855100,0.491992,0.212344,30
19,ok,csf,96,5,A,light,corr_topk,60,ridge,ridge,0.111878,0.036657,0.167698,14.853356,0.537332,0.063998,60
16,ok,csf,96,2,A,light,corr_topk,30,ridge,ridge,0.226360,0.188781,0.162452,14.882377,0.492237,0.203671,30
8,ok,csf,48,4,C,light,f_regression_topk,20,ridge,ridge,0.109897,0.014646,0.161742,14.465476,0.484287,0.066898,20
22,ok,csf,120,3,C,light,f_regression_topk,30,ridge,ridge,0.078199,-0.075153,0.152879,13.229077,0.597189,0.125848,30
20,ok,csf,120,1,C,light,corr_topk,30,ridge,ridge,0.181183,0.158403,0.131909,13.633584,0.590275,0.096037,30
21,ok,csf,120,2,C,light,f_regression_topk,20,ridge,ridge,0.088311,-0.012170,0.126571,14.712094,0.440314,0.052364,20
9,ok,csf,48,5,C,light,corr_topk,20,ridge,ridge,0.061727,-0.072414,0.111765,13.409807,0.571697,0.170615,20
34,ok,ser,48,5,A,light,corr_topk,40,ridge,ridge,0.082142,0.092378,0.078223,15.196408,0.477922,0.045957,40
24,ok,csf,120,5,A,light,f_regression_topk,40,ridge,ridge,0.031232,-0.004695,0.074070,16.215885,0.384219,0.063665,40
23,ok,csf,120,4,C,light,corr_topk,20,ridge,ridge,0.059603,-0.125359,0.062890,15.131957,0.545724,0.086443,20
13,ok,csf,72,4,A,light,f_regression_topk,80,svr_linear,svr_linear,0.126126,0.077705,0.049997,14.115347,0.429176,0.140845,80
14,ok,csf,72,5,A,light,f_regression_topk,100,svr_linear,svr_linear,0.121153,0.057753,0.024968,14.275165,0.424991,0.116763,100
7,ok,csf,48,3,B,light,f_regression_topk,40,ridge,ridge,0.110969,0.023137,-0.039430,16.399851,0.501197,0.062792,40
42,ok,ser,96,3,A,light,corr_topk,100,svr_linear,svr_linear,0.231528,0.283952,-0.049010,14.769857,0.514151,0.178925,100
41,ok,ser,96,2,A,light,f_regression_topk,100,svr_linear,svr_linear,0.234564,0.288056,-0.049010,14.769857,0.514151,0.176559,100
40,ok,ser,96,1,A,light,corr_topk,120,svr_linear,svr_linear,0.242782,0.306499,-0.050829,15.040611,0.543920,0.161328,120
43,ok,ser,96,4,A,light,f_regression_topk,120,svr_linear,svr_linear,0.217384,0.270970,-0.050829,15.040611,0.543920,0.170774,120
1,ok,csf,24,2,C,light,corr_topk,20,ridge,ridge,0.253265,0.316194,-0.058787,14.899025,0.793964,0.276462,20
3,ok,csf,24,4,C,light,f_regression_topk,20,ridge,ridge,0.138420,0.137486,-0.063995,15.637493,0.680573,0.161887,20
44,ok,ser,96,5,A,light,corr_topk,140,svr_linear,svr_linear,0.194071,0.258349,-0.076678,15.102834,0.557259,0.155597,140
11,ok,csf,72,2,A,light,corr_topk,80,svr_linear,svr_linear,0.135272,0.073697,-0.151727,15.197353,0.630917,0.140581,80
2,ok,csf,24,3,C,light,f_regression_topk,30,ridge,ridge,0.185944,0.159013,-0.220547,16.212201,0.713188,-0.028393,30
49,ok,ser,120,5,C,light,f_regression_topk,20,ridge,ridge,0.045795,0.032286,-0.286207,17.214073,0.520281,0.137459,20
0,ok,csf,24,1,C,light,corr_topk,30,ridge,ridge,0.261029,0.240782,-0.301058,15.969808,0.813872,0.159739,30
47,ok,ser,120,3,B,light,f_regression_topk,40,ridge,ridge,0.125283,0.162649,-0.427399,19.249639,0.544043,0.103158,40
31,ok,ser,48,2,C,light,f_regression_topk,5,ridge,ridge,0.157075,0.147370,-0.453203,18.736975,0.463340,0.178553,16
36,ok,ser,72,2,C,light,f_regression_topk,10,ridge,ridge,0.157075,0.147370,-0.453203,18.736975,0.463340,0.178553,16
35,ok,ser,72,1,C,light,f_regression_topk,5,ridge,ridge,0.157075,0.147370,-0.453203,18.736975,0.463340,0.178553,16
45,ok,ser,120,1,C,light,f_regression_topk,5,ridge,ridge,0.157075,0.147370,-0.453203,18.736975,0.463340,0.178553,16
32,ok,ser,48,3,C,light,f_regression_topk,10,ridge,ridge,0.157075,0.147370,-0.453203,18.736975,0.463340,0.178553,16
30,ok,ser,48,1,C,light,f_regression_topk,15,ridge,ridge,0.183097,0.180746,-0.453203,18.736975,0.463340,0.178553,16
46,ok,ser,120,2,C,light,f_regression_topk,10,ridge,ridge,0.157075,0.147370,-0.453203,18.736975,0.463340,0.178553,16
48,ok,ser,120,4,C,light,f_regression_topk,15,ridge,ridge,0.099527,0.093419,-0.453203,18.736975,0.463340,0.178553,16
25,ok,ser,24,1,C,light,f_regression_topk,40,xgboost,xgboost,0.271758,0.194197,-0.598031,17.972773,0.590233,0.176393,40
28,ok,ser,24,4,C,light,corr_topk,60,xgboost,xgboost,0.131258,0.098993,-0.647631,17.014823,0.789403,0.201784,60
29,ok,ser,24,5,C,light,f_regression_topk,60,xgboost,xgboost,0.126043,0.084710,-0.686022,17.044964,0.788951,0.181983,60
33,ok,ser,48,4,B,light,f_regression_topk,80,ridge,ridge,0.101422,0.142470,-0.733088,20.956449,0.790068,0.009948,80
26,ok,ser,24,2,C,light,corr_topk,30,xgboost,xgboost,0.137132,0.101614,-0.793637,19.318777,0.608158,0.177675,30
27,ok,ser,24,3,C,light,f_regression_topk,30,xgboost,xgboost,0.131876,0.093529,-0.874355,18.757510,0.779827,0.174123,30

Leakage-safe final EF/LF table: training OOF rank-1 per tissue+TP.

,status,tissue,tp,training_rank_within_tissue_tp,combo,clinical_mode,feature_selection_mode,top_k_after_sparse,selected_model_type_from_training,best_model_type,train_oof_r2,train_mean_valid_r2,test_r2,test_mae,train_r2,best_score_inner_cv_r2,n_features_after_selection
0,ok,csf,24,1,C,light,corr_topk,30,ridge,ridge,0.261029,0.240782,-0.301058,15.969808,0.813872,0.159739,30
1,ok,csf,48,1,C,light,corr_topk,30,ridge,ridge,0.201590,0.186037,0.461189,9.556048,0.778636,0.167297,30
2,ok,csf,72,1,A,light,corr_topk,60,gbr,gbr,0.195500,0.126244,0.283918,14.039792,0.411410,0.113992,60
3,ok,csf,96,1,A,light,f_regression_topk,30,ridge,ridge,0.236085,0.199354,0.169784,14.855100,0.491992,0.212344,30
4,ok,csf,120,1,C,light,corr_topk,30,ridge,ridge,0.181183,0.158403,0.131909,13.633584,0.590275,0.096037,30
5,ok,ser,24,1,C,light,f_regression_topk,40,xgboost,xgboost,0.271758,0.194197,-0.598031,17.972773,0.590233,0.176393,40
6,ok,ser,48,1,C,light,f_regression_topk,15,ridge,ridge,0.183097,0.180746,-0.453203,18.736975,0.463340,0.178553,16
7,ok,ser,72,1,C,light,f_regression_topk,5,ridge,ridge,0.157075,0.147370,-0.453203,18.736975,0.463340,0.178553,16
8,ok,ser,96,1,A,light,corr_topk,120,svr_linear,svr_linear,0.242782,0.306499,-0.050829,15.040611,0.543920,0.161328,120
9,ok,ser,120,1,C,light,f_regression_topk,5,ridge,ridge,0.157075,0.147370,-0.453203,18.736975,0.463340,0.178553,16

Top-N sensitivity summary. Test-best columns are descriptive only.

,tissue,tp,n_tested_topN_candidates,train_rank1_combo,train_rank1_model,train_rank1_fs,train_rank1_top_k,train_rank1_oof_r2,train_rank1_test_r2,descriptive_test_best_combo,...,descriptive_test_best_top_k,descriptive_test_best_training_rank,descriptive_test_best_train_oof_r2,descriptive_test_best_test_r2,test_r2_median_among_topN,test_r2_mean_among_topN,test_r2_std_among_topN,n_positive_test_r2_among_topN,n_negative_test_r2_among_topN,note
0,csf,24,5,C,ridge,corr_topk,30,0.261029,-0.301058,A,...,120,5,0.069795,0.175509,-0.063995,-0.093775,0.182799,1,4,test_best columns are descriptive only; final ...
1,csf,48,5,C,ridge,corr_topk,30,0.201590,0.461189,C,...,30,1,0.201590,0.461189,0.161742,0.215837,0.204553,4,1,test_best columns are descriptive only; final ...
2,csf,72,5,A,gbr,corr_topk,60,0.195500,0.283918,A,...,40,3,0.128291,0.369730,0.049997,0.115377,0.210294,4,1,test_best columns are descriptive only; final ...
3,csf,96,5,A,ridge,f_regression_topk,30,0.236085,0.169784,A,...,40,3,0.138209,0.213177,0.169784,0.185127,0.025450,5,0,test_best columns are descriptive only; final ...
4,csf,120,5,C,ridge,corr_topk,30,0.181183,0.131909,C,...,30,3,0.078199,0.152879,0.126571,0.109664,0.039061,5,0,test_best columns are descriptive only; final ...
5,ser,24,5,C,xgboost,f_regression_topk,40,0.271758,-0.598031,C,...,40,1,0.271758,-0.598031,-0.686022,-0.719935,0.112379,0,5,test_best columns are descriptive only; final ...
6,ser,48,5,C,ridge,f_regression_topk,15,0.183097,-0.453203,A,...,40,5,0.082142,0.078223,-0.453203,-0.402895,0.294998,1,4,test_best columns are descriptive only; final ...
7,ser,72,5,C,ridge,f_regression_topk,5,0.157075,-0.453203,A,...,120,4,0.138242,0.228788,0.196684,-0.051213,0.367175,3,2,test_best columns are descriptive only; final ...
8,ser,96,5,A,svr_linear,corr_topk,120,0.242782,-0.050829,A,...,100,2,0.234564,-0.049010,-0.050829,-0.055271,0.012001,0,5,test_best columns are descriptive only; final ...
9,ser,120,5,C,ridge,f_regression_topk,5,0.157075,-0.453203,C,...,20,5,0.045795,-0.286207,-0.453203,-0.414643,0.072662,0,5,test_best columns are descriptive only; final ...

Descriptive test-best among inspected top-N candidates. Do not use this as final model selection.

,status,tissue,tp,training_rank_within_tissue_tp,combo,clinical_mode,feature_selection_mode,top_k_after_sparse,selected_model_type_from_training,best_model_type,train_oof_r2,train_mean_valid_r2,test_r2,test_mae,train_r2,best_score_inner_cv_r2,n_features_after_selection
0,ok,csf,24,5,A,light,f_regression_topk,120,ridge,ridge,0.069795,0.072770,0.175509,14.173174,0.559360,0.006060,120
1,ok,csf,48,1,C,light,corr_topk,30,ridge,ridge,0.201590,0.186037,0.461189,9.556048,0.778636,0.167297,30
2,ok,csf,72,3,A,light,f_regression_topk,40,gbr,gbr,0.128291,0.075298,0.369730,12.881785,0.525343,0.149833,40
3,ok,csf,96,3,A,light,corr_topk,40,ridge,ridge,0.138209,0.071006,0.213177,14.580310,0.513250,0.115292,40
4,ok,csf,120,3,C,light,f_regression_topk,30,ridge,ridge,0.078199,-0.075153,0.152879,13.229077,0.597189,0.125848,30
5,ok,ser,24,1,C,light,f_regression_topk,40,xgboost,xgboost,0.271758,0.194197,-0.598031,17.972773,0.590233,0.176393,40
6,ok,ser,48,5,A,light,corr_topk,40,ridge,ridge,0.082142,0.092378,0.078223,15.196408,0.477922,0.045957,40
7,ok,ser,72,4,A,light,corr_topk,120,svr_linear,svr_linear,0.138242,0.197571,0.228788,12.988432,0.577262,0.103099,120
8,ok,ser,96,3,A,light,corr_topk,100,svr_linear,svr_linear,0.231528,0.283952,-0.049010,14.769857,0.514151,0.178925,100
9,ok,ser,120,5,C,light,f_regression_topk,20,ridge,ridge,0.045795,0.032286,-0.286207,17.214073,0.520281,0.137459,20